#!/usr/bin/env python3
"""nqp_prec.py -- extract Raku's operator-precedence table from Grammar.nqp and emit a Pratt parser.

RUNG 4 of the port, and the one that actually decides it. Rungs 1-3 translated the SHAPE of the
grammar; `EXPR`/`O` is the part that cannot be translated as shape, because it is not a fixed table:

  ⛔ RAKU'S OPERATOR TABLE IS EXTENDED AT PARSE TIME. `sub infix:<foo> {...}` installs a new operator
  WHILE the file is being parsed, and `sub infix:<foo> is tighter(&infix:<+>)` places it between two
  existing levels. This single property is why the language is not LALR and why a bison table can
  never be finished -- and why the emitted table below MUST be a runtime-mutable structure, never a
  static const array.

⭐ PRECEDENCE IS A STRING, COMPARED LEXICOGRAPHICALLY -- 'u=' (multiplicative) binds tighter than 't='
(additive). That is not an encoding detail to normalise away into integers: it is what makes
`is tighter`/`is looser` implementable at all, because a new level can always be minted BETWEEN two
existing ones by extending the string ('t=' < 'tA=' < 'u='). Integers have no room between 20 and 21;
strings always have room. Any port that "cleans this up" into an int loses user-defined operators.
"""
import sys, re, os, collections
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from nqp_read import scan_decls, lex_body

LEVEL = re.compile(r"^\s*my %(?P<name>\w+)\s*:=\s*nqp::hash\((?P<args>.*)\);\s*$")
OPDECL = re.compile(r"^(?P<kind>infix|prefix|postfix|circumfix|postcircumfix|term|trait_mod|quote|prefix_circumfix_meta_operator|infix_circumfix_meta_operator|infix_prefix_meta_operator|postfix_prefix_meta_operator)$")

def parse_levels(src):
    lv = {}
    for line in src.split('\n'):
        m = LEVEL.match(line)
        if not m: continue
        parts = re.findall(r"'([^']*)'", m.group('args'))
        d = dict(zip(parts[0::2], parts[1::2]))
        if 'prec' in d: lv[m.group('name')] = d
    return lv

def parse_ops(decls):
    """Map each operator token to the precedence level it flattens via <O(|%level)>."""
    ops, unlevelled = [], []
    for d in decls:
        if d['sym'] is None: continue
        m = OPDECL.match(d['name'])
        if not m: continue
        lm = re.search(r'<O\(\s*\|%(\w+)', d['body'])
        if not lm:
            lm2 = re.search(r"<O\(([^)]*)\)>", d['body'])
            unlevelled.append((d['name'], d['sym'], (lm2.group(1)[:40] if lm2 else None)))
            continue
        ops.append(dict(kind=d['name'], sym=d['sym'], level=lm.group(1), line=d['line']))
    return ops, unlevelled

def main(path='/home/resources/rakudo-main/src/Perl6/Grammar.nqp'):
    src = open(path, encoding='utf-8', errors='replace').read()
    levels = parse_levels(src)
    decls = [d for d in scan_decls(src) if not d.get('overrun')]
    ops, unlev = parse_ops(decls)
    bykind = collections.Counter(o['kind'] for o in ops)
    bylevel = collections.Counter(o['level'] for o in ops)
    print(f"precedence levels : {len(levels)}")
    print(f"operators mapped  : {len(ops)}")
    print(f"operator tokens with an <O(...)> we could NOT resolve to a named level : {len(unlev)}")
    print()
    print("LEVELS, tightest first (prec string desc -- lexicographic IS the ordering):")
    for name, d in sorted(levels.items(), key=lambda kv: kv[1]['prec'], reverse=True):
        print(f"  {d['prec']:<4} {d.get('assoc','?'):<7} {name:<20} ops={bylevel.get(name,0):<3} {d.get('dba','')}")
    print()
    print("OPERATOR KINDS:")
    for k, v in bykind.most_common(): print(f"  {k:<14} {v}")
    if unlev:
        print()
        print("UNRESOLVED <O(...)> -- these carry an inline hash rather than a named level:")
        for n, s, a in unlev[:10]: print(f"  {n}:sym<{s}>  O({a})")
    return levels, ops

C_HEAD = """/* GENERATED by tools/rakugram/nqp_prec.py from Rakudo src/Perl6/Grammar.nqp -- DO NOT EDIT.
 *
 * Raku's operator-precedence (Pratt) parser, rung 4 of the Grammar.nqp -> recursive-descent port.
 *
 * \u26d4 THE TABLE IS MUTABLE ON PURPOSE AND MUST STAY THAT WAY. `sub infix:<foo> {...}` installs a new
 * operator WHILE the enclosing file is being parsed, and `is tighter(&infix:<+>)` places it BETWEEN two
 * existing levels. That is why Raku is not LALR: a bison table is frozen at build time. Emitting these
 * rows as a `static const` array would compile, pass every test built from this file, and silently
 * refuse every user-defined operator -- so the array is heap-backed and rk_op_install() is public.
 *
 * \u2b50 PRECEDENCE IS A STRING COMPARED WITH strcmp, NOT AN INTEGER, and that is load-bearing rather
 * than a quirk to normalise away: a new level can always be minted BETWEEN two existing ones by
 * extending the string ("t=" < "tA=" < "u="). Integers have no room between 20 and 21; strings always
 * have room. Converting this to an int rank is the one \"cleanup\" that would break `is tighter`.
 */
#include <string.h>
#include <stdlib.h>

typedef enum { RK_INFIX, RK_PREFIX, RK_POSTFIX, RK_CIRCUMFIX, RK_POSTCIRCUMFIX, RK_TERM, RK_META } RkOpKind;
typedef enum { RK_LEFT, RK_RIGHT, RK_NONASSOC, RK_LIST, RK_UNARY, RK_CHAIN } RkAssoc;

typedef struct { const char *sym; RkOpKind kind; const char *prec; RkAssoc assoc; const char *dba; } RkOp;

static RkOp  *g_rk_ops;                 /* heap, NOT const -- see the banner above */
static int    g_rk_nops, g_rk_opcap;

static void rk_op_reserve(int n) {
    if (n <= g_rk_opcap) return;
    int c = g_rk_opcap ? g_rk_opcap : 256;
    while (c < n) c *= 2;
    g_rk_ops = (RkOp *)realloc(g_rk_ops, (size_t)c * sizeof *g_rk_ops);
    g_rk_opcap = c;
}
/* Install an operator at parse time. This is the entry point `sub infix:<foo>` compiles to; a port
   that omits it parses only the operators that existed when the port was generated. */
int rk_op_install(const char *sym, RkOpKind kind, const char *prec, RkAssoc assoc, const char *dba) {
    rk_op_reserve(g_rk_nops + 1);
    g_rk_ops[g_rk_nops].sym = sym; g_rk_ops[g_rk_nops].kind = kind;
    g_rk_ops[g_rk_nops].prec = prec; g_rk_ops[g_rk_nops].assoc = assoc;
    g_rk_ops[g_rk_nops].dba = dba;
    return g_rk_nops++;
}
/* \u26d4 LONGEST MATCH, not first match. \"<=\" must never be read as \"<\" followed by \"=\"; the table is
   not sorted by length, so every candidate is scanned and the longest kept. */
static const RkOp *rk_op_lookup(const char *s, int len, RkOpKind kind) {
    const RkOp *best = 0; int blen = 0;
    for (int i = 0; i < g_rk_nops; i++) {
        if (g_rk_ops[i].kind != kind) continue;
        int n = (int)strlen(g_rk_ops[i].sym);
        if (n <= blen || n > len) continue;
        if (!memcmp(s, g_rk_ops[i].sym, (size_t)n)) { best = &g_rk_ops[i]; blen = n; }
    }
    return best;
}
static int rk_prec_cmp(const char *a, const char *b) { return strcmp(a, b); }
"""

def emit_c(levels, ops, out):
    ASSOC = {'left':'RK_LEFT','right':'RK_RIGHT','non':'RK_NONASSOC','list':'RK_LIST',
             'unary':'RK_UNARY','chain':'RK_CHAIN'}
    KIND = {'infix':'RK_INFIX','prefix':'RK_PREFIX','postfix':'RK_POSTFIX',
            'circumfix':'RK_CIRCUMFIX','postcircumfix':'RK_POSTCIRCUMFIX','term':'RK_TERM'}
    with open(out, 'w') as f:
        f.write(C_HEAD)
        f.write("\n/* ---- the table Rakudo ships with; rk_op_install() may add to it at parse time ---- */\n")
        f.write("void rk_ops_init_builtin(void) {\n    if (g_rk_nops) return;\n")
        n = 0
        for o in ops:
            lv = levels.get(o['level'])
            if not lv: continue
            k = KIND.get(o['kind'], 'RK_META')
            a = ASSOC.get(lv.get('assoc','left'), 'RK_LEFT')
            sym = o['sym'].replace('\\', '\\\\').replace('"', '\\"')
            dba = lv.get('dba','').replace('"','\\"')
            f.write(f'    rk_op_install("{sym}", {k}, "{lv["prec"]}", {a}, "{dba}");\n')
            n += 1
        f.write("}\n")
        f.write(PRATT)
    return n

PRATT = """
/* ---- the Pratt loop ------------------------------------------------------------------------- */
/* EXPR in NQP's HLL::Grammar. Climbs while the next infix binds at least as tightly as `min_prec`;
   for a LEFT/LIST operator the right operand is parsed one notch tighter, for RIGHT at the same
   level, which is what makes `2**3**2` right-associate and `1-2-3` left-associate. */
typedef struct RkNode RkNode;
extern RkNode *rk_parse_term(RkCur *c);                 /* supplied by the generated grammar */
extern RkNode *rk_mk_binop(const RkOp *, RkNode *, RkNode *);
extern RkNode *rk_mk_unop(const RkOp *, RkNode *);
extern void    rk_skip_ws(RkCur *c);

static RkNode *rk_EXPR(RkCur *c, const char *min_prec) {
    rk_skip_ws(c);
    const RkOp *pre = rk_op_lookup(c->src + c->pos, c->len - c->pos, RK_PREFIX);
    RkNode *lhs;
    if (pre) { c->pos += (int)strlen(pre->sym); lhs = rk_mk_unop(pre, rk_EXPR(c, pre->prec)); }
    else     { lhs = rk_parse_term(c); }
    if (!lhs) return 0;
    for (;;) {
        rk_skip_ws(c);
        const RkOp *op = rk_op_lookup(c->src + c->pos, c->len - c->pos, RK_INFIX);
        if (!op) break;
        if (rk_prec_cmp(op->prec, min_prec) < 0) break;
        c->pos += (int)strlen(op->sym);
        /* LEFT and LIST consume a strictly tighter right operand so they fold leftward; RIGHT
           re-enters at its own level so it folds rightward. Getting this backwards still parses
           every expression -- it just associates them wrongly, which no syntax test would catch. */
        const char *next = op->prec;
        static char bump[16];
        if (op->assoc == RK_LEFT || op->assoc == RK_LIST || op->assoc == RK_NONASSOC) {
            size_t n = strlen(op->prec);
            if (n + 1 < sizeof bump) { memcpy(bump, op->prec, n); bump[n] = '\1'; bump[n+1] = 0; next = bump; }
        }
        RkNode *rhs = rk_EXPR(c, next);
        if (!rhs) return 0;
        lhs = rk_mk_binop(op, lhs, rhs);
    }
    return lhs;
}
"""

if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    levels, ops = main(*args[:1])
    if '--emit' in sys.argv:
        out = args[1] if len(args) > 1 else '/tmp/claude-1000/-home-claude-C/bf92a46a-6680-4a47-b7db-57e12b40e2b1/scratchpad/rk_prec_gen.c'
        n = emit_c(levels, ops, out)
        print()
        print(f"emitted {n} operator install call(s) + the Pratt loop -> {out}")
