#include <string>
#include <algorithm>
#include <stdint.h>
#include "emit.h"
#include "bb_templates.h"
extern "C" {
#include "bb_template_common.h"
extern struct gv_s g_call_args;
#include "descr.h"
#include <string.h>
extern DESCR_t rt_call_value(DESCR_t callee, DESCR_t *argv, int n);
extern DESCR_t rt_call_value_gen_h(DESCR_t callee, DESCR_t *argv, int n, void **hslot);
extern DESCR_t rt_call_apply_gen_h(DESCR_t callee, DESCR_t lv, void **hslot);
extern DESCR_t rt_call_value_resume_h(void **hslot, int n);
extern void rt_proc_drop_frame_h(void **hslot);
extern CVSPINE_t rt_call_value_spine_prep(DESCR_t callee, DESCR_t *argv, int n);
extern CVSPINE_t rt_call_apply_spine_prep(DESCR_t callee, DESCR_t lv);
extern CVSPINE_t rt_call_value_spine_prep_blk(DESCR_t callee, DESCR_t *argv, int n, void **hslot);
extern CVSPINE_t rt_call_apply_spine_prep_blk(DESCR_t callee, DESCR_t lv, void **hslot);
extern CVSPINE_t rt_pl_goal_resolve(DESCR_t goal, int n);
extern int * const rt_k_level_p;
extern "C++" std::string icn_landing_line_restore(void);
DESCR_t rt_proc_call_epilogue_γ(DESCR_t frame0);
DESCR_t rt_proc_call_epilogue_ω(void);
DESCR_t rt_gen_spine_pass_γ(DESCR_t v);
DESCR_t rt_gen_spine_pass_ω(void);
void rt_gen_spine_resume_enter(void);
}
#include "rt/rt_pl_trail.h"
#include "x86_asm.h"
#include "bb_pl_cell.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
#define cv_is_apply() (_.op_sval && strcmp(_.op_sval, "apply") == 0 && _.op_arg_slot_n == 1)
#define cv_is_goal() (_.op_sval && strcmp(_.op_sval, "goal") == 0)
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
#define cv_pl_proto() (cv_is_goal() && x86_fb_pinned())
#define cv_icn() (!cv_is_goal() && g_emit_cfg && g_emit_cfg->icn_cells_graph)
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
#define cv_lvl_add(d) (x86("mov", "rax", std::string("[rip@got + __]"), (uint64_t)(uintptr_t)(void *)&rt_k_level_p, "rt_k_level_p") \
           + x86("mov", "rax", RDQ("rax", 0)) \
           + x86("add", RDD("rax", 0), (d)))
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
#define cv_sync_out() (cv_is_goal() ? x86_scan_sync_out() : x86_scan_sync_out_force())
#define cv_sync_in() (cv_is_goal() ? x86_scan_sync_in_rr() : x86_scan_sync_in_rr_force())
#define CV_N() (_.op_arg_slot_n)
#define CV_H() (_.op_off + 16 + _.op_arg_slot_n * 16)
#define CV_UNFILLED() (std::count_if(_.op_arg_slot, _.op_arg_slot + _.op_arg_slot_n, [](int s) { return s < 0; }) > 0)
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_call_value() {
    x86_begin();
    return IF(_.op_off < 0 || _.op_sa < 0, x86_alpha()
        + x86_bomb("bb_call_value: needs own slot + callee operand slot"))
        + IF(!(_.op_off < 0 || _.op_sa < 0) && CV_UNFILLED(), x86_alpha()
        + x86_bomb("bb_call_value: argument slot unfilled"))
        + IF(!(_.op_off < 0 || _.op_sa < 0) && !CV_UNFILLED(),
        x86_alpha()
       + FOR(0, CV_N(), [&](int i) {
           return x86("mov", "rax", FRQ(_.op_arg_slot[i]))
                + x86("mov", FRQ(_.op_off + 16 + i * 16), "rax")
                + x86("mov", "rax", FRQ(_.op_arg_slot[i] + 8))
                + x86("mov", FRQ(_.op_off + 16 + i * 16 + 8), "rax"); })
       + cv_sync_out()
       + x86_anchor_enter()
         + (cv_pl_proto()
            ?  x86("note", "the retained token (ARCH-PROLOG-C-OUT-OF-THE-BOX 1.5): a spine-road token carries its beta at [H+8] and is cleared here; "
                           "a coroutine-road token ([H+8] = 0) is handed to the C road that owns it, through the slot")
              + x86("mov", "rcx", FRQ(CV_H() + 8))
              + x86("test", "rcx", "rcx")
              + x86("je", L(22))
              + x86("mov", FRQ(CV_H()), 0L)
              + x86("mov", FRQ(CV_H() + 8), 0L)
              + x86("def", L(22))
            :  cv_icn() ? x86("note", "the retained token: the block preps and the coroutine road each drop the slot's generator at their head, "
                                       "so the box calls no rt_proc_drop_frame_h")
            :  x86("mov",   "rax", FRQ(CV_H()))
              + x86("test",  "rax", "rax")
              + x86("je",    L(22))
              + x86("lea",   "rdi", FRQ(CV_H()))
              + x86("call", "rt_proc_drop_frame_h", (uint64_t)(uintptr_t)(void *)rt_proc_drop_frame_h)
              + x86("def",   L(22)))
       + x86("mov",   "rdi", FRQ(_.op_sa))
       + x86("mov",   "rsi", FRQ(_.op_sa + 8))
       + (cv_is_apply()
            ? x86("mov",   "rdx", FRQ(_.op_off + 16))
            + x86("mov",   "rcx", FRQ(_.op_off + 24))
            + (cv_icn() ? x86("lea", "r8", FRQ(CV_H()))
                        + x86("call", "rt_call_apply_spine_prep_blk", TEMPLATE_FN_ADDR(rt_call_apply_spine_prep_blk))
                        : x86("call",  "rt_call_apply_spine_prep", TEMPLATE_FN_ADDR(rt_call_apply_spine_prep)))
            : x86("lea",   "rdx", FRQ(_.op_off + 16))
            + x86("mov32", "ecx", (long)CV_N())
            + (cv_pl_proto() ? x86("mov32", "edx", (long)CV_N())
                             + x86("call", "rt_pl_goal_resolve", TEMPLATE_FN_ADDR(rt_pl_goal_resolve))
               : cv_is_goal() ? x86_bomb("bb_call_value: a Prolog goal box in a frame that is not pinned has no road (every Prolog graph is pinned)")
               : cv_icn() ? x86("lea", "r8", FRQ(CV_H()))
                          + x86("call", "rt_call_value_spine_prep_blk", TEMPLATE_FN_ADDR(rt_call_value_spine_prep_blk))
               : x86("call", "rt_call_value_spine_prep", TEMPLATE_FN_ADDR(rt_call_value_spine_prep))))
       + x86_rt_gc_poll()
       + x86("test",  "rax", "rax")
       + x86("je",    L(7))
       + IF(!cv_is_goal(),  IF(cv_icn(), x86("mov", "rsi", "rdx")
                                       + x86("shr", "rsi", 8L)
                                       + x86("and", "edx", 255L))
                          + x86("mov", FRQ(CV_H()), "rdx"))
       + IF(cv_pl_proto(),  x86("note", "ARCH-PROLOG-C-OUT-OF-THE-BOX 4.2: rax = the callee's fn, rdx = the goal's own arity; "
                                        "the goal is dereferenced AGAIN after the poll (the compound may have moved) and its cells are copied onto this spine as the block, "
                                        "the n extra arguments after them; the level bumps inline; the wires and the jump")
                          + x86("mov", "r10", "rax")
                          + x86("mov", "r11", "rdx")
                          + x86("lea", "rdi", FRQ(_.op_sa))
                          + PL_DEREF(40, 41, 42, 43)
                          + x86("cmp", "al", (long)DT_PLREF)
                          + x86("jne", L(44))
                          + x86("mov", "r8", RDQ("rdi", 8))
                          + x86("jmp", L(45))
                          + x86("def", L(44))
                          + x86("xor", "r8d", "r8d")
                          + x86("def", L(45))
                          + x86("lea", "rcx", RDQ("r11", (int)CV_N()))
                          + x86("shl", "rcx", 4L)
                          + x86("sub", "rsp", "rcx")
                          + x86("mov", "rdi", "rsp")
                          + x86("mov", "rsi", "r8")
                          + x86("mov", "rcx", "r11")
                          + x86("add", "rcx", "rcx")
                          + x86("rep_movsq")
                          + FOR(0, CV_N(), [&](int i) {
                              return x86("mov", "rax", FRQ(_.op_off + 16 + i * 16))
                                   + x86("mov", RDQ("rdi", 0), "rax")
                                   + x86("mov", "rax", FRQ(_.op_off + 16 + i * 16 + 8))
                                   + x86("mov", RDQ("rdi", 8), "rax")
                                   + x86("add", "rdi", 16L); })
                          + cv_lvl_add(1L)
                          + x86("mov", "rax", "r10")
                          + bb_glue_pass_wires(3, 4))
       + IF(!cv_pl_proto() && !cv_icn(), bb_glue_pass_wires_blob_regs(3, 4))
       + IF(cv_icn(), x86("note", "the block protocol: the prep answered the callee's block cell count in rdx>>8 (rsi here); the wires go first, "
                                  "then the n cells copied from the staged medium at the callee's entry rsp")
                    + x86_lea_id("rcx", 4)
                    + x86("push", "rcx")
                    + x86_lea_id("rcx", 3)
                    + x86("push", "rcx")
                    + x86("mov", "rcx", "rsi")
                    + x86("shl", "rcx", 4L)
                    + x86("sub", "rsp", "rcx")
                    + x86("mov", "rcx", "rsi")
                    + x86("add", "rcx", "rcx")
                    + x86("mov", "rsi", "[rip + __]", (uint64_t)(uintptr_t)&g_call_args, "g_call_args")
                    + x86("mov", "rsi", RDQ("rsi", 0))
                    + x86("mov", "rdi", "rsp")
                    + x86("rep_movsq")
                    + x86_lea_id("rcx", 3)
                    + x86_lea_id("rdx", 4)
                    + x86_jmp_reg("rax"))
       + x86("def", L(3))
       + IF(cv_icn(), icn_landing_line_restore())
       + (cv_pl_proto()
            ?  x86("mov",  FRQ(CV_H()), "rax")
              + x86("mov",  FRQ(CV_H() + 8), "rdx")
              + cv_lvl_add(-1L)
              + x86("mov", "rax", "rdi")
              + x86("mov", "rdx", "rsi")
              + x86("jmp",  L(2))
            : bb_glue_wire_land()
              + x86("mov",  FRQ(CV_H() + 8), "rsp")
              + x86("mov",  "rax", FRQ(CV_H()))
         + x86("cmp",  "rax", 2L)
              + x86("je",   L(23))
              + x86("test", "rax", "rax")
              + x86("jne",  L(5))
              + x86("mov",  FRQ(CV_H()), 1L)
              + x86("def",  L(23))
              + x86("call", "rt_proc_call_epilogue_γ", TEMPLATE_FN_ADDR(rt_proc_call_epilogue_γ))
              + x86("jmp",  L(2))
              + x86("def", L(5))
              + x86("call", "rt_gen_spine_pass_γ", TEMPLATE_FN_ADDR(rt_gen_spine_pass_γ))
              + x86("jmp",  L(2)))
       + x86("def", L(4))
       + IF(cv_icn(), icn_landing_line_restore())
       + (cv_pl_proto()
            ?  x86("mov",  FRQ(CV_H()), 0L)
              + x86("mov",  FRQ(CV_H() + 8), 0L)
              + cv_lvl_add(-1L)
              + x86("mov32", "eax", (long)DT_FAIL)
              + x86("xor", "edx", "edx")
              + x86("jmp",  L(2))
            : bb_glue_wire_land()
              + x86("mov",  FRQ(CV_H() + 8), "rsp")
              + x86("mov",  "rax", FRQ(CV_H()))
              + x86("cmp",  "rax", 2L)
              + x86("je",   L(24))
              + x86("test", "rax", "rax")
              + x86("jne",  L(6))
              + x86("mov",  FRQ(CV_H()), 1L)
              + x86("def",  L(24))
              + x86("call", "rt_proc_call_epilogue_ω", TEMPLATE_FN_ADDR(rt_proc_call_epilogue_ω))
              + x86("jmp",  L(2))
              + x86("def", L(6))
              + x86("call", "rt_gen_spine_pass_ω", TEMPLATE_FN_ADDR(rt_gen_spine_pass_ω))
              + x86("jmp",  L(2)))
       + x86("def", L(7))
       + x86("mov",   "rdi", FRQ(_.op_sa))
       + x86("mov",   "rsi", FRQ(_.op_sa + 8))
       + (cv_is_apply()
            ? x86("mov",   "rdx", FRQ(_.op_off + 16))
            + x86("mov",   "rcx", FRQ(_.op_off + 24))
            + x86("lea",   "r8",  FRQ(CV_H()))
            + x86("call",  "rt_call_apply_gen_h", (uint64_t)(uintptr_t)(void *)rt_call_apply_gen_h)
            : x86("lea",   "rdx", FRQ(_.op_off + 16))
            + x86("mov32", "ecx", (long)CV_N())
            + x86("lea",   "r8",  FRQ(CV_H()))
            + (cv_is_goal()
                 ? x86("mov32", "eax", (long)DT_FAIL)
                 + x86("xor", "edx", "edx")
                 : x86("call", "rt_call_value_gen_h", (uint64_t)(uintptr_t)(void *)rt_call_value_gen_h)))
       + x86("def", L(2))
       + x86_anchor_leave()
       + cv_sync_in()
       + x86("mov",   FRQ(_.op_off),     "rax")
       + x86("mov",   FRQ(_.op_off + 8), "rdx")
       + x86("cmp",   "al", (long)DT_FAIL)
       + x86_omega("je")
       + x86_rt_gc_poll()
       + x86_gamma()
       + x86_beta()
       + (cv_pl_proto()
            ?  x86("test", "r15", "r15")
              + x86("jne",  L(12))
              + x86("mov",  "rax", FRQ(CV_H()))
              + x86("test", "rax", "rax")
              + x86("je",   L(12))
              + x86("mov",  "rcx", FRQ(CV_H() + 8))
              + x86("test", "rcx", "rcx")
              + x86("je",   L(12))
              + x86("mov",  x86_fb(), "rax")
              + cv_lvl_add(1L)
              + x86_jmp_reg("rcx")
              + x86("def",  L(12))
              + x86_omega()
            : x86("mov",  "rax", FRQ(CV_H()))
         + x86("cmp",  "rax", 2L)
              + x86_omega("je")
              + x86("cmp",  "rax", 1L)
              + x86("jne",  L(8))
              + x86_scan_sync_out()
              + x86("call", "rt_gen_spine_resume_enter", TEMPLATE_FN_ADDR(rt_gen_spine_resume_enter))
              + x86("mov",  "rsp", FRQ(CV_H() + 8))
              + x86_jmp_mem("rsp", 0))
       + IF(!cv_pl_proto(),
               x86("def", L(8))
             + cv_sync_out()
             + x86("lea",   "rdi", FRQ(CV_H()))
             + x86("mov32", "esi", cv_is_apply() ? -1L : (long)CV_N())
             + x86("call",  "rt_call_value_resume_h", (uint64_t)(uintptr_t)(void *)rt_call_value_resume_h)
             + cv_sync_in()
             + x86("cmp",   "al", (long)DT_FAIL)
             + x86_omega("je")
             + x86("mov",   FRQ(_.op_off),     "rax")
             + x86("mov",   FRQ(_.op_off + 8), "rdx")
             + x86_rt_gc_poll()
             + x86_gamma())
       + x86_omega());
}
