#include <string>
#include <stdint.h>
#include "emit.h"
extern "C" {
#include "bb_template_common.h"
#include "descr.h"
extern int g_scan_regs_live;
struct DESCR_t rt_keyword_subject(void);
struct DESCR_t rt_keyword_pos(void);
DESCR_t rt_keyword_read(const char *sval);
DESCR_t rt_keyword_gen(const char *sval, long idx);
DESCR_t rt_keyword_var(const char *name);
}
#include "x86_asm.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
#define KI_BOMB() (!(_.op_off >= 0) && !_.op_zres)
#define KI_VARFORM() (_.op_var_form && _.op_sval && _.op_sval[0] == '&')
std::string bb_keyword_icon() {
    return IF(KI_BOMB(), x86_alpha() + x86_bomb("bb_keyword: no slot"))
         + IF(!KI_BOMB() && KI_VARFORM(),
               x86_alpha()
             + x86("mov",     "rdi", ROQ(0))
             + x86("call",    "rt_keyword_var", (uint64_t)(uintptr_t)(void *)rt_keyword_var)
             + x86("mov",     FRQ(_.op_off),     "rax")
             + x86("mov",     FRQ(_.op_off + 8), "rdx")
             + x86_rt_gc_poll()
             + x86_gamma() + x86_beta() + x86_omega()
             + x86("def",     L(0))
             + x86(".quad",   LS(0), _.op_sval)
             + x86("label",   LS(0))
             + x86(".string", _.op_sval))
         + IF(!KI_BOMB() && !KI_VARFORM(),
               _.op_zres
         ? (!strcmp(_.op_name2, "subject")
            ? (g_scan_regs_live
               ?  x86_alpha()
               + x86("mov", ZRESD(0), (long)DT_S)
               + x86("mov", ZRESD(4), "r15d")
               + x86("note", ZRESN())
               + x86("mov",  ZRES(8), "r13")
               + x86_gamma() + x86_beta_trampoline()
               : x86("comment", "KEYWORD_subject_call->ZRES (ZK-2)")
               + x86_alpha()
               + x86("call", "rt_keyword_subject", (uint64_t)(uintptr_t)(void *)rt_keyword_subject)
               + x86("note", ZRESN())
               + x86("mov",  ZRES(0), "rax")
               + x86("note", ZRESN())
               + x86("mov",  ZRES(8), "rdx")
               + x86_gamma() + x86_beta_trampoline())
          : !strcmp(_.op_name2, "pos")
            ? x86("comment", "KEYWORD_pos->ZRES (ZK-2) [r14+1: scan-reg truth]")
            + x86_alpha()
            + x86("mov", ZRES(0), (long)DT_I)
            + x86("mov", "rax", "r14")
            + x86("add", "rax", (long)1)
            + x86("note", ZRESN())
            + x86("mov",  ZRES(8), "rax")
            + x86_gamma() + x86_beta_trampoline()
          : !strcmp(_.op_name2, "null")
            ? x86("comment", "KEYWORD_null->ZRES (ZK-2)")
            + x86_alpha()
            + x86("mov", ZRES(0), (long)DT_SNUL)
            + x86("mov", ZRES(8), (long)0)
            + x86_gamma() + x86_beta_trampoline()
          : x86_alpha() + x86_bomb("bb_keyword_icon: unhandled keyword in ZD arm"))
         : (!strcmp(_.op_name2, "subject")
            ? (g_scan_regs_live
               ? x86("comment", "KEYWORD_subject_reg: same word0 packing fix as the ZRES arm above -- v/slen share one qword, so this needs a dword pair, not a single clobbering qword store of the bare tag.")
               + x86_alpha()
               + x86("mov", FR(_.op_off),      (long)DT_S)
               + x86("mov", FR(_.op_off + 4),  "r15d")
               + x86("mov", FRQ(_.op_off + 8), "r13")
               + x86_gamma() + x86_beta() + x86_omega()
               : x86("comment", "KEYWORD_subject_call")
               + x86_alpha()
               + x86("call", "rt_keyword_subject", (uint64_t)(uintptr_t)(void *)rt_keyword_subject)
               + x86("mov", FRQ(_.op_off),     "rax")
               + x86("mov", FRQ(_.op_off + 8), "rdx")
               + x86_gamma() + x86_beta() + x86_omega())
          : !strcmp(_.op_name2, "pos")
            ? x86("comment", "KEYWORD_pos_reg [always r14+1: register cursor is the source of truth, incl. ?-less scanning callees]")
            + x86_alpha()
            + x86("mov", FRQ(_.op_off), (long)DT_I)
            + x86("mov", "rax", "r14")
            + x86("add", "rax", (long)1)
            + x86("mov", FRQ(_.op_off + 8), "rax")
            + x86_gamma() + x86_beta() + x86_omega()
          : !strcmp(_.op_name2, "null")
            ? x86("comment", "KEYWORD_null")
            + x86_alpha()
            + x86("mov", FRQ(_.op_off),     (long)DT_SNUL)
            + x86("mov", FRQ(_.op_off + 8), (long)0)
            + x86_gamma() + x86_beta() + x86_omega()
          : !strcmp(_.op_name2, "fail")
            ? x86("comment", "KEYWORD_fail")
            + x86_alpha()
            + x86_omega()
            + x86_beta()
            + x86_omega()
          : (!strcmp(_.op_name2, "features") || !strcmp(_.op_name2, "regions") || !strcmp(_.op_name2, "storage") || !strcmp(_.op_name2, "collections") || !strcmp(_.op_name2, "allocated"))
            ? x86("comment", "KEYWORD_gen")
            + x86_alpha()
            + x86("mov",     FRQ(_.op_off + 16), (long)0)
            + x86("def",     L(1))
            + x86("mov",     "rdi", ROQ(0))
            + x86("mov",     "rsi", FRQ(_.op_off + 16))
            + x86("call",    "rt_keyword_gen", (uint64_t)(uintptr_t)(void *)rt_keyword_gen)
            + x86("cmp",     "al", (long)DT_FAIL)
            + x86_omega("je")
            + x86("mov",     FRQ(_.op_off),     "rax")
            + x86("mov",     FRQ(_.op_off + 8), "rdx")
            + x86("mov",     "rax", FRQ(_.op_off + 16))
            + x86("add",     "rax", (long)1)
            + x86("mov",     FRQ(_.op_off + 16), "rax")
            + x86_gamma()
            + x86_beta()
            + x86("jmp",     L(1))
            + x86("def",     L(0))
            + x86(".quad",   LS(0), _.op_sval)
            + x86("label",   LS(0))
            + x86(".string", _.op_sval)
          : x86("comment", "KEYWORD_read")
            + x86_alpha()
            + x86("mov",     "rdi", ROQ(0))
            + x86("call",    "rt_keyword_read", (uint64_t)(uintptr_t)(void *)rt_keyword_read)
            + x86("cmp",     "al", (long)DT_FAIL)
            + x86_omega("je")
            + x86("mov",     FRQ(_.op_off),     "rax")
            + x86("mov",     FRQ(_.op_off + 8), "rdx")
            + x86_rt_gc_poll()
            + x86_gamma() + x86_beta() + x86_omega()
            + x86("def",     L(0))
            + x86(".quad",   LS(0), _.op_sval)
            + x86("label",   LS(0))
            + x86(".string", _.op_sval)));
}
