#include <string>
#include <string.h>
#include "emit.h"
extern "C" {
#include "bb_template_common.h"
#include "descr.h"
void rt_icn_cset_register(const char *ptr, int len);
int prolog_atom_intern(const char *name);
const char * bb_ab_sym_name(const char * nm);
#include "dtp.h"
}
#include "x86_asm.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static uint64_t blsc_bits(double d, uint64_t b = 0) { memcpy(&b, &d, 8); return b; }
#define lit_tag_imm(base_tag) (!sn4_descr_stamp() ? (base_tag) : ((base_tag) \
     | (((_.nid <= 0 || _.nid > (long)DESCR_SRC_NODE_OVERFLOW - 1) ? (long)DESCR_SRC_NODE_OVERFLOW : (long)_.nid) << 8)))
#define ls_rq(w) (_.op_zres ? ZRES(w) : FRQ(_.op_off + (w)))
#define ls_rd(w) (_.op_zres ? ZRESD(w) : FR(_.op_off + (w)))
static std::string blsc_thk_label(const char * n) { return std::string(".Lthk_") + bb_ab_sym_name(n ? n : ""); }
static const char * blsc_thk_rec(const char * n) { void * r = bb_thunk_rec_addr(n); return r ? (const char *)r : ""; }
extern "C" void * bb_dstar_rec_addr(const char * star);
static std::string blsc_dstar_label(const char * n) { return std::string(".Ldstar_") + bb_ab_sym_name((std::string("*") + (n ? n : "")).c_str()); }
static const char * blsc_dstar_rec(const char * n) { void * r = bb_dstar_rec_addr((std::string("*") + (n ? n : "")).c_str()); return r ? (const char *)r : ""; }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_lit_scalar() {
    return _.op_node_kind == (int)IR_LIT_INTEGER && (_.op_off >= 0 || _.op_zres)
         ? x86("comment", "IR_LIT_INTEGER")
             + x86_alpha()
             + x86("note", ZRESN())
             + x86("mov", ls_rq(0), lit_tag_imm((long)DT_I))
             + x86("mov", "rax", ROQ(0))
             + x86("note", ZRESN())
             + x86("mov", ls_rq(8), "rax")
             + x86_gamma()
             + x86_beta_trampoline()
             + x86("def", L(0))
             + x86(".quad", (uint64_t)_.op_ival)
         : _.op_node_kind == (int)IR_LIT_STRING && _.node && _.node->seal == IR_SEAL_DSTAR_REF && (_.op_off >= 0 || _.op_zres)
         ? x86("comment", "IR_LIT_STRING DSTAR-REF: the unevaluated expression's star record, its address baked -- no name at run time")
             + x86_alpha()
             + x86("note", ZRESN())
             + x86("mov", ls_rq(0), lit_tag_imm((long)DT_I))
             + x86("mov", "rax", ROQ(0))
             + x86("note", ZRESN())
             + x86("mov", ls_rq(8), "rax")
             + x86_gamma()
             + x86_beta_trampoline()
             + x86("def", L(0))
             + x86(".quad", blsc_dstar_label(_.op_sval).c_str(), blsc_dstar_rec(_.op_sval))
         : _.op_node_kind == (int)IR_LIT_STRING && _.node && _.node->seal == IR_SEAL_THUNK_REF && (_.op_off >= 0 || _.op_zres)
         ? x86("comment", "IR_LIT_STRING THUNK-REF: the compiled pattern's record, its address baked -- no name at run time")
             + x86_alpha()
             + x86("note", ZRESN())
             + x86("mov", ls_rq(0), lit_tag_imm((long)DT_I))
             + x86("mov", "rax", ROQ(0))
             + x86("note", ZRESN())
             + x86("mov", ls_rq(8), "rax")
             + x86_gamma()
             + x86_beta_trampoline()
             + x86("def", L(0))
             + x86(".quad", blsc_thk_label(_.op_sval).c_str(), blsc_thk_rec(_.op_sval))
         : _.op_node_kind == (int)IR_LIT_STRING && (_.op_off >= 0 || _.op_zres)
         ? x86("comment", "IR_LIT_STRING")
             + x86_alpha()
             + x86("note", ZRESN())
             + x86("mov", ls_rq(0), lit_tag_imm((long)DT_S))
             + x86("note", ZRESN())
             + (_.op_a_node_kind >= 0
                 ? x86("mov", ls_rd(4), (long)_.op_a_ival_sg)
                 : x86("mov", ls_rd(4), (long)(_.op_sval ? strlen(_.op_sval) : 0)))
             + x86("mov", "rax", ROQ(0))
             + x86("note", ZRESN())
             + x86("mov", ls_rq(8), "rax")
             + x86_gamma()
             + x86_beta_trampoline()
             + x86("def", L(0))
             + x86(".quad", LS(0), _.op_sval ? _.op_sval : "")
             + x86("label", LS(0))
             + (_.op_a_node_kind >= 0
                 ? x86(".string", _.op_sval ? _.op_sval : "", (unsigned long)_.op_a_ival_sg)
                 : x86(".string", _.op_sval ? _.op_sval : ""))
         : _.op_node_kind == (int)IR_LIT_ATOM && (_.op_off >= 0 || _.op_zres)
         ? x86("comment", "IR_LIT_ATOM: the atom's compile-time id from the one interner (ARCH-PROLOG-BB-REWRITE.md section 3, R1)")
             + x86_alpha()
             + x86("note", ZRESN())
             + x86("mov", ls_rq(0), lit_tag_imm((long)DT_PLATOM))
             + x86("mov", "rax", ROQ(0))
             + x86("note", ZRESN())
             + x86("mov", ls_rq(8), "rax")
             + x86_gamma()
             + x86_beta_trampoline()
             + x86("def", L(0))
             + x86(".quad", (uint64_t)(unsigned)prolog_atom_intern(_.op_sval ? _.op_sval : ""))
         : _.op_node_kind == (int)IR_LIT_NAME && (_.op_off >= 0 || _.op_zres)
         ? x86("comment", "IR_LIT_NAME")
             + x86_alpha()
             + x86("note", ZRESN())
             + x86("mov", ls_rq(0), lit_tag_imm((long)DT_N))
             + x86("note", ZRESN())
             + x86("mov", ls_rd(4), (long)0)
             + x86("mov", "rax", ROQ(0))
             + x86("note", ZRESN())
             + x86("mov", ls_rq(8), "rax")
             + x86_gamma()
             + x86_beta_trampoline()
             + x86("def", L(0))
             + x86(".quad", LS(0), _.op_sval ? _.op_sval : "")
             + x86("label", LS(0))
             + x86(".string", _.op_sval ? _.op_sval : "")
         : _.op_node_kind == (int)IR_LIT_CHARSET && (_.op_off >= 0 || _.op_zres)
         ? x86("comment", "IR_LIT_CHARSET")
             + x86_alpha()
             + x86("note", ZRESN())
             + x86("mov", ls_rq(0), lit_tag_imm((long)DT_S))
             + x86("note", ZRESN())
             + x86("mov", ls_rd(4), (long)-1)
             + x86("mov", "rax", ROQ(0))
             + x86("note", ZRESN())
             + x86("mov", ls_rq(8), "rax")
             + (_.op_a_node_kind >= 0
                 ? x86("push", "rax")
                       + x86("push", "rdx")
                       + x86("mov", "rdi", ROQ(0))
                       + x86("mov", "rsi", (long)_.op_a_ival_sg)
                       + x86("call", "rt_icn_cset_register", (uint64_t)(uintptr_t)(void *)(void (*)(const char *, int))rt_icn_cset_register)
                       + x86("pop", "rdx")
                       + x86("pop", "rax")
                       + x86_rt_gc_poll()
                 : std::string())
             + x86_gamma()
             + x86_beta_trampoline()
             + x86("def", L(0))
             + x86(".quad", LS(0), _.op_sval ? _.op_sval : "")
             + x86("label", LS(0))
             + (_.op_a_node_kind >= 0
                 ? x86(".string", _.op_sval ? _.op_sval : "", (unsigned long)_.op_a_ival_sg)
                 : x86(".string", _.op_sval ? _.op_sval : ""))
         : _.op_node_kind == (int)IR_LIT_REAL && (_.op_off >= 0 || _.op_zres)
         ? x86("comment", "IR_LIT_REAL")
             + x86_alpha()
             + x86("note", ZRESN())
             + x86("mov", ls_rq(0), lit_tag_imm((long)DT_R))
             + x86("mov", "rax", ROQ(0))
             + x86("note", ZRESN())
             + x86("mov", ls_rq(8), "rax")
             + x86_gamma()
             + x86_beta_trampoline()
             + x86("def", L(0))
             + x86(".quad", blsc_bits(_.op_dval))
         : x86("comment", "IR_LIT_scalar")
             + x86_alpha()
             + x86_gamma()
             + x86_beta_trampoline();
}
