#include <string>
#include <cstdint>
#include "emit.h"
extern "C" {
#include "bb_template_common.h"
#include "bb_templates.h"
}
extern "C" void * rt_zcol_push(void ** ptr_cell, int * cap_cell, int i, long elem_sz);
extern "C" int sn4_defer_resume(void);
extern "C" int sn4_arbno_seal_omega(void);
extern "C" int sn4_arbno_tailbeta(void);
#include "x86_asm.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static inline const char * zv() { return "rsp"; }
static std::string arbno_zero_window(long op_sb) { std::string r; for (long k = 24; k < op_sb; k += 8) r += x86("mov", RSP((int)k), "rax"); return r; }
static int arbno_nofill(void) { static int v = -1; if (v < 0) { const char * e = getenv("SCRIP_ARBNO_NOFILL"); v = e ? (atoi(e) != 0) : 1; } return v; }
static int arbno_poison(void) { static int v = -1; if (v < 0) { const char * e = getenv("SCRIP_ZLS_POISON"); v = e ? (atoi(e) != 0) : 0; } return v; }
static std::string arbno_fill_cells(void) { std::string r; for (int i = 0; i < _.op_arbno_nzq; i++) { int w = _.op_arbno_zq[i] - _.op_sa + 24; r += x86("mov", RSP(w), "rax"); } return r; }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static std::string arbno_fill_window(long op_sb) {
    return (!arbno_nofill() || _.op_arbno_nzq > 8)
             ? x86("mov", "eax", 0L) + arbno_zero_window(op_sb)
         : arbno_poison()
             ? x86("movabs", "rax", (uint64_t)0xA5A5A5A5A5A5A5A5ULL) + arbno_zero_window(op_sb) + (_.op_arbno_nzq > 0 ? x86("mov", "eax", 0L) + arbno_fill_cells() : std::string())
         : _.op_arbno_nzq > 0
             ? x86("mov", "eax", 0L) + arbno_fill_cells()
             : std::string();
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static inline const char * trd(int off) { static char b[8][40]; static int i; i = (i + 1) & 7; snprintf(b[i], 40, "dword ptr [rsp + %d]", off); return b[i]; }
static inline const char * trq(int off) { static char b[8][40]; static int i; i = (i + 1) & 7; snprintf(b[i], 40, "qword ptr [rsp + %d]", off); return b[i]; }
static std::string tail_zero(int lo, int hi, const char * zr64) { std::string r; for (int k = lo; k < hi; k += 8) r += x86("mov", trq(k), zr64); return r; }
static std::string tail_cap_zero8(int base, int n, const char * zr64) { std::string r; for (int j = 0; j < n; j++) r += x86("mov", trq(base + 16 * j + 8), zr64); return r; }
static std::string tail_cap_copy(int dst, int src, int n) { std::string r; for (int j = 0; j < n; j++) r += x86("mov", "rax", trq(src + 16 * j)) + x86("mov", trq(dst + 16 * j), "rax"); return r; }
static int arbno_lon(void) { static int v = -1; if (v < 0) { const char * e = getenv("SCRIP_ARBNO_FRAMELESS"); v = e ? (atoi(e) != 0) : 1; } return v; }
static int arbno_rootspine(void) { static int v = -1; if (v < 0) { const char * e = getenv("SCRIP_ARBNO_ROOTSPINE"); v = e ? (atoi(e) != 0) : 0; } return v; }
static int arbno_fprpop(void) { static int v = -1; if (v < 0) { const char * e = getenv("SCRIP_ARBNO_FPRPOP"); v = e ? (atoi(e) != 0) : 0; } return v; }
static inline int kkN(void) { return _.op_arbno_body_kk; }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static std::string bb_match_arbno_frameless_k() {
    return x86("comment", "IR_MATCH_ARBNO_FRAMELESS_K (ARB-LON-K16: re-homed cell, one-level static offsets)")
         + x86_alpha()
         + x86("sub", "rsp", 16L)
         + x86("mov", RDD("rsp", 0), "r14d")
         + x86("mov", RDD("rsp", 4), "r14d")
         + x86_gamma()
         + x86_beta()
         + x86("jmp", PAIR(0))
         + x86("def", PAIR(2))
         + x86("mov", "eax", RDD("rsp", kkN() + 4))
         + x86("cmp", "r14d", "eax")
         + x86("je",  PAIR(1))
         + x86("mov", "eax", RDD("rsp", kkN()))
         + x86("sub", "rsp", 16L)
         + x86("mov", RDD("rsp", 0), "eax")
         + x86("mov", RDD("rsp", 4), "r14d")
         + x86_gamma()
         + x86("def", PAIR(3))
         + x86("mov", "eax", RDD("rsp", 0))
         + x86("cmp", "r14d", "eax")
         + x86("jne", L(3))
         + x86("add", "rsp", 16L)
         + x86_omega()
         + x86("def", L(3))
         + x86("add", "rsp", 16L)
         + x86("jmp", PAIR(1));
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static std::string bb_match_arbno_frameless() {
    return x86("comment", "IR_MATCH_ARBNO_FRAMELESS (ARBNO-LON: one cell, two compares, no chain)")
         + x86_alpha()
         + x86("sub", "rsp", 16L)
         + x86("mov", RDD("rsp", 0), "r14d")
         + x86("mov", RDD("rsp", 4), "r14d")
         + x86_gamma()
         + x86_beta()
         + x86("jmp", PAIR(0))
         + x86("def", PAIR(2))
         + x86("mov", "eax", RDD("rsp", 4))
         + x86("cmp", "r14d", "eax")
         + x86("je",  PAIR(1))
         + x86("mov", RDD("rsp", 4), "r14d")
         + x86_gamma()
         + x86("def", PAIR(3))
         + x86("mov", "eax", RDD("rsp", 0))
         + x86("cmp", "r14d", "eax")
         + IF(!(_.op_tail_seal && sn4_arbno_seal_omega()), x86("jne", PAIR(1)))
         + x86("add", "rsp", 16L)
         + x86_omega();
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static std::string bb_match_arbno_frame() {
    int off = _.op_arbno_frame_off;
    return x86("comment", "IR_MATCH_ARBNO_FRAME (ARBNO-FRAME SLOT: frameless-arm cell, rbp-relative -- immune to a DEFER body member's frontier movement)")
         + x86_alpha()
         + x86("mov", AFC(0), "r14d")
         + x86("mov", AFC(4), "r14d")
         + x86("comment", "PEND-MARK a: bank the r12 pend cursor in this node's own slot (frame_slot_off strides 16B per index; the arm uses only [0..7], so [8..15] is ours).  An instance ATTEMPT that is later abandoned must not leave its deferred-capture entries behind for rt_dcap_pump to replay")
         + x86("mov", AFCQ(8), "r12")
         + x86_gamma()
         + x86_beta()
         + x86("comment", "PEND-MARK b: roll the pend cursor back to the last COMMITTED instance before retrying the body -- this is the cure for the double-fire")
         + x86("mov", "r12", AFCQ(8))
         + x86("jmp", PAIR(0))
         + x86("def", PAIR(2))
         + x86("mov", "eax", AFC(4))
         + x86("cmp", "r14d", "eax")
         + x86("je",  PAIR(1))
         + x86("mov", AFC(4), "r14d")
         + x86("comment", "PEND-MARK c: this instance made progress and is COMMITTED -- advance the mark so its entries SURVIVE the next retry (rolling back to the alpha mark would wipe legitimately-completed instances)")
         + x86("mov", AFCQ(8), "r12")
         + x86_gamma()
         + x86("def", PAIR(3))
         + x86("mov", "eax", AFC(0))
         + x86("cmp", "r14d", "eax")
         + IF(!sn4_defer_resume() || !_.op_arbno_body_actframe, x86("jne", sn4_arbno_tailbeta() ? PAIR(4) : PAIR(1)))
         + x86_omega();
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static std::string bb_match_arbno_tail() {
    int HDRB = _.op_sa, FPB = _.op_tail_fpb, FPL = _.op_tail_fpl, SEAL = _.op_tail_seal, NCAP = _.op_tail_ncap;
    int KA = (int)_.op_sb + FPB, HDRA = FPB + HDRB;
    int FB5_HDR = -(FPL + KA - HDRA);
    int FPR_RSP = _.op_tail_fpr_rsp;
    return x86("comment", "IR_MATCH_ARBNO_TAIL (R12-EXIT-1 carry-the-tail rsp elements)")
         + x86_alpha()
         + x86("sub", "rsp", (long)KA)
         + x86("mov", "eax", 0L)
         + tail_zero(_.op_tail_dfr ? 0 : FPB, FPB + HDRB, "rax")
         + tail_cap_zero8(HDRA + 32, NCAP, "rax")
         + x86("mov", trd(HDRA + 0), "r14d")
         + x86("mov", trd(HDRA + 4), "r14d")
         + x86("stk32", (long)(HDRA + 8), 1L)
         + x86("mov", "rax", trq(KA + FPL + 8))
         + x86("mov", trq(HDRA + 16), "rax")
         + x86("mov", "rax", trq(KA + FPL + 16))
         + x86("mov", trq(HDRA + 24), "rax")
         + tail_cap_copy(HDRA + 32, KA, NCAP)
         + x86_gamma()
         + x86_beta()
         + IF(FPR_RSP > 0 && arbno_fprpop(), x86("add", "rsp", (long)FPR_RSP))
         + x86("mov", "r14d", trd(HDRA + 4))
         + x86("mov", "rax", trq(HDRA + 16))
         + x86("mov", "rcx", trq(HDRA + 24))
         + x86("sub", "rsp", (long)_.op_sb)
         + x86("mov", "edx", 0L)
         + tail_zero(0, HDRB, "rdx")
         + x86("mov", trd(HDRB + 0), "r14d")
         + x86("mov", trd(HDRB + 4), "r14d")
         + x86("stk32", (long)(HDRB + 8), 0L)
         + x86("mov", trq(HDRB + 16), "rax")
         + x86("mov", trq(HDRB + 24), "rcx")
         + tail_cap_zero8(HDRB + 32, NCAP, "rdx")
         + tail_cap_copy(HDRB + 32, (int)_.op_sb + HDRA + 32, NCAP)
         + x86("jmp", PAIR(0))
         + x86("def", PAIR(2))
         + x86("mov", "eax", trd(HDRA + 0))
         + x86("cmp", "r14d", "eax")
         + x86("je",  SEAL ? L(3) : PAIR(1))
         + x86("mov", trd(HDRA + 4), "r14d")
         + x86_gamma()
         + IF(SEAL, x86("def", L(3)) + IF(FPB > 0, x86("add", "rsp", (long)FPB)))
         + x86("def", PAIR(3))
         + x86("mov", "eax", trd(HDRB + 8))
         + x86("test", "eax", "eax")
         + x86("jnz", L(2))
         + x86("add", "rsp", (long)_.op_sb)
         + x86("jmp", SEAL ? L(3) : PAIR(1))
         + x86("def", L(2))
         + x86("mov", "r14d", trd(HDRB + 0))
         + x86("add", "rsp", (long)_.op_sb)
         + IF(_.flat_deep_arrival, x86("note", "old_base") + std::string(""))
         + x86_omega();
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static std::string bb_match_arbno_rbp() {
    return x86("comment", "IR_MATCH_ARBNO_RBP (Lon 2026-08-14: rbp frame, RESULT@[rbp+0..15], count@[rbp+16], negative=>exhaust)")
         + x86_alpha()
         + x86("push", "rbp")
         + x86("sub", "rsp", 24L)
         + x86("mov", "rbp", "rsp")
         + x86("mov", RDD("rbp", 0), "r14d")
         + x86("mov", RDD("rbp", 4), "r14d")
         + x86("mov", RDD("rbp", 16), 0L)
         + x86_gamma()
         + x86_beta()
         + x86("jmp", PAIR(0))
         + x86("def", PAIR(2))
         + x86("mov", "eax", RDD("rbp", 4))
         + x86("cmp", "r14d", "eax")
         + x86("je",  PAIR(1))
         + x86("mov", RDD("rbp", 4), "r14d")
         + x86("add", RDD("rbp", 16), 1L)
         + x86_gamma()
         + x86("def", PAIR(3))
         + x86("mov", "eax", RDD("rbp", 16))
         + x86("sub", "eax", 1L)
         + x86("js",  L(2))
         + x86("mov", RDD("rbp", 16), "eax")
         + x86("jmp", PAIR(1))
         + x86("def", L(2))
         + x86("mov", "r14d", RDD("rbp", 0))
         + x86("lea", "rsp", RDQ("rbp", 24))
         + x86("pop", "rbp")
         + x86_omega();
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static void arbno_arm_diag(const char * arm) { static int d = -1; if (d < 0) { const char * e = getenv("SCRIP_ARBNO_DIAG"); d = (e && *e == '1') ? 1 : 0; } if (d) fprintf(stderr, "[ARBNO-ARM] %s\n", arm); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_match_arbno() {
    x86_begin();
    arbno_arm_diag(_.op_arbno_body_kk > 0 ? "FRAMELESS_K" : _.op_off < 0 ? "bomb-slot" : (_.op_sa < 0 || _.op_sb <= 0) ? "bomb-geom" : (_.op_arbno_body_defer_unsafe || !_.op_arbno_body_k0) ? (_.op_arbno_frame_off == -1 ? "bomb-defer-unframed" : "ARBNO-FRAME") : "FRAMELESS");
    return _.op_arbno_body_kk > 0
             ? bb_match_arbno_frameless_k()
         : _.op_off < 0
             ? x86_alpha() + x86_bomb("IR_MATCH_ARBNO: slot not granted (zls)")
         : (_.op_sa < 0 || _.op_sb <= 0)
             ? x86_alpha() + x86_bomb("IR_MATCH_ARBNO: COLLECTION geometry not staged (zls_arbno_geom)")
         : (_.op_arbno_body_defer_unsafe || !_.op_arbno_body_k0) && _.op_arbno_frame_off != -1
             ? bb_match_arbno_frame()
         : (_.op_arbno_body_defer_unsafe || !_.op_arbno_body_k0)
             ? x86_alpha() + x86_bomb("IR_MATCH_ARBNO: body contains a DEFER unsafe for the plain-frameless arm, and emit_match_rbp() is off -- ARBNO-FRAME slot unavailable (SCRIP_MATCH_RBP=0)")
                            + x86_beta() + x86_bomb("IR_MATCH_ARBNO: unreachable beta (defer-unsafe refuse)")
                            + x86("def", PAIR(2)) + x86("def", PAIR(3))
             : bb_match_arbno_frameless();
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static std::string bb_match_arbno_DELETED_ARMS() {
    return _.op_tail
             ? bb_match_arbno_tail()
         : (_.op_arbno_dt && _.op_arbno_dt_susp == 0)
             ? x86("comment", "IR_MATCH_ARBNO_DT (PS-3 s155 record-carry: susp-free, recursion-safe)")
             + x86_alpha()
             + x86("mov", FR(_.op_off), "r14d")
             + x86("mov", FR(_.op_off + 4), "r14d")
             + x86("mov", FR(_.op_off + 8), 0L)
             + x86("mov", FRQ(_.op_off + 24), "rsp")
             + x86_gamma()
             + x86_beta()
             + x86("mov", "r14d", FR(_.op_off + 4))
             + x86("jmp", PAIR(0))
             + x86("def", PAIR(2))
             + x86("mov", "eax", FR(_.op_off + 4))
             + x86("cmp", "r14d", "eax")
             + x86("je",  PAIR(1))
             + x86("mov", "rcx", "rax")
             + x86_lea_id("rax", 4)
             + x86("sub", "rsp", 16L)
             + x86("mov", trq(0), "rax")
             + x86("mov", trq(8), "rcx")
             + x86("mov", "eax", FR(_.op_off + 8))
             + x86("add", "eax", 1L)
             + x86("mov", FR(_.op_off + 8), "eax")
             + x86("mov", FR(_.op_off + 4), "r14d")
             + x86_gamma()
             + x86("def", L(4))
             + x86("mov", "rax", trq(8))
             + x86("mov", FR(_.op_off + 4), "eax")
             + x86("add", "rsp", 16L)
             + x86_jmp_mem("rsp", 0)
             + x86("def", PAIR(3))
             + x86("mov", "ecx", FR(_.op_off + 8))
             + x86("test", "ecx", "ecx")
             + x86("jz",  L(2))
             + x86("sub", "ecx", 1L)
             + x86("mov", FR(_.op_off + 8), "ecx")
             + x86("jmp", PAIR(1))
             + x86("def", L(2))
             + x86("mov", "r14d", FR(_.op_off))
             + x86("mov", "rsp", FRQ(_.op_off + 24))
             + x86_omega()
         : _.op_arbno_dt
             ? x86("comment", "IR_MATCH_ARBNO_DT (PS-3 defer-tail: blob-owned frames, zero linkage)")
             + x86_alpha()
             + x86("mov", FR(_.op_off), "r14d")
             + x86("mov", FR(_.op_off + 4), "r14d")
             + x86("mov", FR(_.op_off + 8), 0L)
             + x86("mov", FRQ(_.op_off + 24), "rsp")
             + x86_gamma()
             + x86_beta()
             + x86("mov", "r14d", FR(_.op_off + 4))
             + x86("sub", "rsp", 16L)
             + x86("mov", trq(0), "r14")
             + x86("mov", trq(8), 0L)
             + x86("jmp", PAIR(0))
             + x86("def", PAIR(2))
             + x86("mov", "eax", trd(_.op_arbno_dt_susp))
             + x86("cmp", "r14d", "eax")
             + x86("je",  PAIR(1))
             + x86("mov", "eax", FR(_.op_off + 8))
             + x86("add", "eax", 1L)
             + x86("mov", FR(_.op_off + 8), "eax")
             + x86("mov", FR(_.op_off + 4), "r14d")
             + x86_gamma()
             + x86("def", PAIR(3))
             + x86("add", "rsp", 16L)
             + x86("mov", "ecx", FR(_.op_off + 8))
             + x86("test", "ecx", "ecx")
             + x86("jz",  L(2))
             + x86("sub", "ecx", 1L)
             + x86("mov", FR(_.op_off + 8), "ecx")
             + x86("jmp", PAIR(1))
             + x86("def", L(2))
             + x86("mov", "r14d", FR(_.op_off))
             + x86("mov", "rsp", FRQ(_.op_off + 24))
             + x86_omega()
         : _.op_arbno_body_kk > 0
             ? bb_match_arbno_frameless_k()
         : _.op_off < 0
             ? x86_alpha() + x86_bomb("IR_MATCH_ARBNO: slot not granted (zls)")
         : (_.op_sa < 0 || _.op_sb <= 0)
             ? x86_alpha() + x86_bomb("IR_MATCH_ARBNO: COLLECTION geometry not staged (zls_arbno_geom)")
         : (_.op_arbno_body_k0 && arbno_lon())
             ? bb_match_arbno_frameless()
         : _.op_arbno_chain
             ? x86("comment", "IR_MATCH_ARBNO_NARY (ZB-FC-4 rsp linked-frame-chain)")
             + x86_alpha()
             + IF(arbno_rootspine(),
                   x86("sub", "rsp", 48L)
                 + x86("mov", trq(32), "rsp")
                 + x86("mov", zv(), "rsp")
                 + x86("add", zv(), (long)(-_.op_off))
                 + x86("lea", "rax", RDQ("rsp", 48)))
             + x86("mov", FR(_.op_off), "r14d")
             + x86("mov", FR(_.op_off + 4), "r14d")
             + x86("mov", FR(_.op_off + 8), 0L)
             + IF(arbno_rootspine(),  x86("mov", FRQ(_.op_off + 24), "rax"))
             + IF(!arbno_rootspine(), x86("mov", FRQ(_.op_off + 24), "rsp"))
             + IF(!arbno_rootspine(), x86("mov", FRQ(_.op_off + 32), "rsp"))
             + x86("mov", FRQ(_.op_off + 16), 0L)
             + x86_gamma()
             + x86_beta()
             + x86("mov", "r14d", FR(_.op_off + 4))
             + x86("mov", "rax", FRQ(_.op_off + 16))
             + x86("sub", "rsp", (long)_.op_sb)
             + x86("mov", RSP(0), zv())
             + x86("mov", RSP(8), "r14")
             + x86("mov", RSP(16), "rax")
             + arbno_fill_window((long)_.op_sb)
             + x86("mov", FRQ(_.op_off + 16), "rsp")
             + x86("mov", zv(), "rsp")
             + x86("add", zv(), (long)(24 - _.op_sa))
             + x86("jmp", PAIR(0))
             + x86("def", PAIR(2))
             + x86("mov", "eax", FR(_.op_sa - 16))
             + x86("cmp", "r14d", "eax")
             + x86("je",  PAIR(1))
             + x86("mov", zv(), FRQ(_.op_sa - 24))
             + x86("mov", "eax", FR(_.op_off + 8))
             + x86("add", "eax", 1L)
             + x86("mov", FR(_.op_off + 8), "eax")
             + x86("mov", FR(_.op_off + 4), "r14d")
             + x86_gamma()
             + x86("def", PAIR(3))
             + x86("mov", "rax", FRQ(_.op_sa - 8))
             + x86("mov", "rdx", FRQ(_.op_sa - 24))
             + x86("lea", "rsp", RDQ(zv(), (int)(_.op_sa - 24 + _.op_sb)))
             + x86("mov", zv(), "rdx")
             + x86("mov", "ecx", FR(_.op_off + 8))
             + x86("test", "ecx", "ecx")
             + x86("jz",  L(2))
             + x86("sub", "ecx", 1L)
             + x86("mov", FR(_.op_off + 8), "ecx")
             + x86("mov", FRQ(_.op_off + 16), "rax")
             + x86("lea", zv(), RDQ("rax", 24 - _.op_sa))
             + x86("jmp", PAIR(1))
             + x86("def", L(2))
             + x86("mov", "r14d", FR(_.op_off))
             + std::string("")
             + x86("mov", "rsp", FRQ(_.op_off + 24))
             + x86_omega()
         : x86("comment", "IR_MATCH_ARBNO_NARY")
             + x86_alpha()
             + x86("mov", FR(_.op_off), "r14d")
             + x86("mov", FR(_.op_off + 4), "r14d")
             + x86("mov", FR(_.op_off + 8), 0L)
             + x86_gamma()
             + x86_beta()
             + x86("mov", "r14d", FR(_.op_off + 4))
             + x86("lea", "rdi", FR(_.op_off + 16))
             + x86("lea", "rsi", FR(_.op_off + 12))
             + x86("mov", "edx", FR(_.op_off + 8))
             + x86("mov", "rcx", (long)_.op_sb)
             + x86_align_enter()
             + x86("call", "rt_zcol_push", (uint64_t)(uintptr_t)(void *)(void * (*)(void **, int *, int, long))rt_zcol_push)
             + x86_align_leave()
             + x86("mov", RDQ("rax", 0), x86_zr())
             + x86("mov", "ecx", "r14d")
             + x86("mov", RDQ("rax", 8), "rcx")
             + x86("lea", x86_zr(), RDQ("rax", 16 - _.op_sa))
             + x86("jmp", PAIR(0))
             + x86("def", PAIR(2))
             + x86("mov", "rax", FRQ(_.op_off + 16))
             + x86("mov", "ecx", FR(_.op_off + 8))
             + x86("mov", "rdx", (long)_.op_sb)
             + x86("imul", "rcx", "rdx")
             + x86("add", "rax", "rcx")
             + x86("lea", x86_zr(), RDQ("rax", 16 - _.op_sa))
             + x86("mov", "eax", FR(_.op_sa - 8))
             + x86("cmp", "r14d", "eax")
             + x86("je",  PAIR(1))
             + x86("mov", x86_zr(), FRQ(_.op_sa - 16))
             + x86("mov", "eax", FR(_.op_off + 8))
             + x86("add", "eax", 1L)
             + x86("mov", FR(_.op_off + 8), "eax")
             + x86("mov", FR(_.op_off + 4), "r14d")
             + x86_gamma()
             + x86("def", PAIR(3))
             + x86("mov", x86_zr(), FRQ(_.op_sa - 16))
             + x86("mov", "eax", FR(_.op_off + 8))
             + x86("test", "eax", "eax")
             + x86("jz",  L(2))
             + x86("sub", "eax", 1L)
             + x86("mov", FR(_.op_off + 8), "eax")
             + x86("mov", "rax", FRQ(_.op_off + 16))
             + x86("mov", "ecx", FR(_.op_off + 8))
             + x86("mov", "rdx", (long)_.op_sb)
             + x86("imul", "rcx", "rdx")
             + x86("add", "rax", "rcx")
             + x86("lea", x86_zr(), RDQ("rax", 16 - _.op_sa))
             + x86("jmp", PAIR(1))
             + x86("def", L(2))
             + x86("mov", "r14d", FR(_.op_off))
             + x86_omega();
}
