#include <string>
#include <stdint.h>
#include "emit.h"
extern "C" {
#include "bb_template_common.h"
#include "bb_templates.h"
typedef struct { uint64_t ptr; uint64_t len; } ScanSubjRegs;
ScanSubjRegs rt_match_enter(uint64_t lo, uint64_t hi);
void rt_match_ctx_restore(uint64_t sig, uint64_t len, uint64_t capgen);
void * rt_zls_mark(void);
void   rt_zls_release_to(void *mark);
extern "C" long *rt_anchor_ptr(void);
}
#include "x86_asm.h"
#define hfc() (x86_port_mode() == ZC_PORT_FORTH && _.op_fc_wbytes > 0)
#define subjc() (_.op_subj_cell)
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int hpin(void) { static int v = -1; if (v < 0) { const char * e = getenv("SCRIP_HEAD_PIN"); v = (e && *e == '0') ? 0 : 1; } return v; }
static int jepin(void) { static int v = -1; if (v < 0) { const char * e = getenv("SCRIP_JEPIN"); v = (e && *e == '0') ? 0 : 1; } return v && _.flat_jmp_entry && _.flat_deep_arrival; }
static int rpin(void) { return hpin() && ((_.flat_layout_unknown && (subjc() || _.op_zres || !_.flat_jmp_entry)) || jepin());     }
static int oscap_l(void) { static int v = -1; if (v < 0) { const char * e = getenv("SCRIP_OS_CAP"); v = (e && *e == '0') ? 0 : 1; } return v; }
static int has_replace_l(void) { if (!g_emit_cfg) return 0; for (int _i = 0; _i < g_emit_cfg->n; _i++) { IR_t * _nd = g_emit_cfg->all[_i]; if (_nd && (_nd->op == IR_MATCH_REPLACE || _nd->op == IR_MATCH_FENCE0 || _nd->op == IR_MATCH_FENCE1 || _nd->op == IR_MATCH_ABORT || _nd->op == IR_MATCH_ARBNO)) return 1; } return 0; }
#define stfh() (_.flat_stmt_frame || (oscap_l() && _.flat_deep_arrival && !_.flat_jmp_entry && !_.flat_lcl_proc && !_.zframe_graph && !_.flat_pat && !_.flat_gen && !has_replace_l()))
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static const char * HKQ(int k) { static char b[8][40]; static int i; i = (i + 1) & 7; snprintf(b[i], 40, "qword ptr [rsp# + %d]", 16 + 8 * k); return b[i]; }
static const char * HKM() { return "qword ptr [rsp# + 8]"; }
static const char * HKD() { return "dword ptr [rsp# + 0]"; }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_match_begin() {
    x86_begin();
    if (emit_match_rbp()) {
        return x86("comment", "IR_MATCH_BEGIN")
             + x86_alpha()
             + IF(_.op_zres, x86("note", ZOPN(0))
                           + x86("mov", "rdi", x86_zref(_.op_zread[0] + 0, 1))
                           + x86("note", ZOPN(0))
                           + x86("mov", "rsi", x86_zref(_.op_zread[0] + 8, 1)))
             + IF(!_.op_zres && subjc(), x86("mov", "rdi", "qword ptr [rsp + 0]")
                         + x86("mov", "rsi", "qword ptr [rsp + 8]")
                         + x86_zrelease(16))
             + IF(!_.op_zres && !subjc(), x86("mov", "rdi", FRQ(_.op_sa))
                          + x86("mov", "rsi", FRQ(_.op_sa + 8)))
             + x86("push", "rbp")
             + x86("mov",  "rbp", "rsp")
             + x86("note", "cas_mark")
             + x86("push", "r12")
             + x86("note", HKN(1))
             + x86("push", "r13")
             + x86("note", HKN(2))
             + x86("push", "r14")
             + x86("note", HKN(3))
             + x86("push", "r15")
             + x86("sub",  "rsp", (long)(24 + _.op_frame_extra))
             + x86("rtcc_wb")
             + x86("call_bare", "rt_match_enter", (uint64_t)(uintptr_t)(void *)rt_match_enter)
             + x86("mov", "r13", "rax")
             + x86("mov", "r15", "rdx")
             + x86("rtcc_rl")
             + x86("note", "start_δ")
             + x86("mov", RDD("rbp", -40), (long)0)
             + x86("def", L(0))
             + x86("note", "start_δ")
             + x86("mov", "r14d", RDD("rbp", -40))
             + IF(({ static int _bg = -1; if (_bg < 0) { const char * e = getenv("SCRIP_DEFER_BETA_GUARD"); _bg = (e && *e == '0') ? 0 : 1; } _bg; }),
                   x86("note", "match_beta_cont")
                 + x86("mov", "rcx", "[rip@got + __]", (uint64_t)(uintptr_t)(const void *)&rtccb[0], "rtccb")
                 + x86("mov", "rax", RDQ("rcx", 248))
                 + x86("mov", RDQ("rbp", -48), "rax")
                 + x86_lea_id("rax", 13)
                 + x86("mov", RDQ("rcx", 248), "rax"))
             + x86_gamma()
             + x86_beta()
             + IF(({ static int _bg2 = -1; if (_bg2 < 0) { const char * e = getenv("SCRIP_DEFER_BETA_GUARD"); _bg2 = (e && *e == '0') ? 0 : 1; } _bg2; }), x86("def", L(13)))
             + x86("note", "retry_whack")
             + x86("lea", "rsp", RDQ("rbp", -56 - _.op_frame_extra))
             + x86("note", "start_δ")
             + x86("add", RDD("rbp", -40), (long)1)
             + x86("note", "start_δ")
             + x86("mov", "eax", RDD("rbp", -40))
             + x86("cmp", "eax", "r15d")
             + x86("jg",  L(1))
             + x86("mov", "rcx", "[rip@got + __]", (uint64_t)(uintptr_t)(const void *)rt_anchor_ptr(), "rt_anchor_g")
             + x86("mov", "rax", "[rcx]")
             + x86("cmp64", "rax", (long)0)
             + x86("jne", L(1))
             + x86("jmp", L(0))
             + x86("def", L(1))
             + IF(g_emit.xa_bb_emit_pair_n >= 4 && g_emit.xa_bb_emit_pair_define[3] != NULL, x86("def", PAIR(3)))
             + IF(({ static int _bg3 = -1; if (_bg3 < 0) { const char * e = getenv("SCRIP_DEFER_BETA_GUARD"); _bg3 = (e && *e == '0') ? 0 : 1; } _bg3; }),
                   x86("note", "mbc_restore")
                 + x86("mov", "rcx", "[rip@got + __]", (uint64_t)(uintptr_t)(const void *)&rtccb[0], "rtccb")
                 + x86("mov", "rax", RDQ("rbp", -48))
                 + x86("mov", RDQ("rcx", 248), "rax"))
             + x86("note", "cas_mark")
             + x86("mov", "r12", RDQ("rbp", -8))
             + x86("note", HKN(1))
             + x86("mov", "r13", RDQ("rbp", -16))
             + x86("note", HKN(2))
             + x86("mov", "r14", RDQ("rbp", -24))
             + x86("note", HKN(3))
             + x86("mov", "r15", RDQ("rbp", -32))
             + x86("mov", "rdi", "r13")
             + x86("mov", "rsi", "r15")
             + x86("call", "rt_match_ctx_restore", (uint64_t)(uintptr_t)(void *)rt_match_ctx_restore)
             + x86("mov", "rsp", "rbp")
             + x86("pop", "rbp")
             + x86_omega();
    }
    return ((_.op_sa < 0 && !subjc() && !_.op_zres) || _.op_off < 0)
         ? x86_bomb("IR_MATCH_BEGIN: subject/start slot not promoted (emit_drive)")
         : x86("comment", "IR_MATCH_BEGIN")
         + x86_alpha()
         + IF(_.op_zres, x86("note", ZOPN(0))
                       + x86("mov", "rdi", x86_zref(_.op_zread[0] + 0, 1))
                       + x86("note", ZOPN(0))
                       + x86("mov", "rsi", x86_zref(_.op_zread[0] + 8, 1)))
         + IF(!_.op_zres && subjc(), x86("mov", "rdi", "qword ptr [rsp + 0]")
                     + x86("mov", "rsi", "qword ptr [rsp + 8]")
                     + x86_zrelease(16))
         + IF(rpin(),
               x86("note", HKN(0))
             + x86("mov", RDQ("rsp", _.op_off + 40), "rsp")
             + x86("note", "stmt_base") + std::string(""))
         + IF(emit_match_begin_stfh_k() > 0, x86_zclaim(emit_match_begin_stfh_k()))
         + x86("note", HKN(1))
         + x86("mov", stfh() ? HKQ(1) : FRQ(_.op_off + 48), "r13")
         + x86("note", HKN(2))
         + x86("mov", stfh() ? HKQ(2) : FRQ(_.op_off + 56), "r14")
         + x86("note", HKN(3))
         + x86("mov", stfh() ? HKQ(3) : FRQ(_.op_off + 64), "r15")
         + IF(_.flat_deep_arrival && !rpin(), x86("note", HKN(0))
                                            + x86("mov", stfh() ? HKQ(0) : FRQ(_.op_off + 40), "rsp"))
         + IF(!_.op_zres && !subjc(), rpin()
                      ? x86("mov", "rdi", RDQ("rsp", _.op_sa))
                      + x86("mov", "rsi", RDQ("rsp", _.op_sa + 8))
                      : x86("mov", "rdi", FRQ(_.op_sa))
                      + x86("mov", "rsi", FRQ(_.op_sa + 8)))
         + x86("rtcc_wb")
         + x86("call_bare", "rt_match_enter", (uint64_t)(uintptr_t)(void *)rt_match_enter)
         + x86("mov", "r13", "rax")
         + x86("mov", "r15", "rdx")
         + x86("rtcc_rl")
         + x86("note", "cas_top")
         + x86("mov", RDQ("r12", 0), (long)0)
         + x86("note", "cas_rsp_mark")
         + x86("mov", RDQ("r12", 8), "rsp")
         + x86("note", "cas_top")
         + x86("add", "r12", (long)24)
         + IF(x86_zc_frame() == ZC_FRAME_RSP, (hfc() ? x86("mov", "rax", "rsp")
                                                + x86_zclaim(32)
                                                + x86("note", "rsp_mark")
                                                + x86("mov", stfh() ? HKM() : FRQ(_.op_off + 16), "rax")
                                                : x86_zls2_mark_save(stfh() ? HKM() : FRQ(_.op_off + 16))))
         + x86("note", "start_δ")
         + x86("mov", stfh() ? HKD() : FR(_.op_off), (long)0)
         + x86("def", L(0))
         + x86("note", "start_δ")
         + x86("mov", "r14d", stfh() ? HKD() : FR(_.op_off))
         + x86_gamma()
         + x86_beta()
         + IF(hfc() && x86_zc_frame() == ZC_FRAME_RSP, x86("note", "rsp_restore")
                                                      + x86("mov", "rsp", RDQ("r12", -16))
                                                      + x86("sub", "rsp", (long)32))
         + x86("note", "start_δ")
         + x86("add", stfh() ? HKD() : FR(_.op_off), (long)1)
         + x86("note", "start_δ")
         + x86("mov", "eax", stfh() ? HKD() : FR(_.op_off))
         + x86("cmp", "eax", "r15d")
         + x86("jg",  L(1))
         + x86("mov", "rcx", "[rip@got + __]", (uint64_t)(uintptr_t)(const void *)rt_anchor_ptr(), "rt_anchor_g")
         + x86("mov", "rax", "[rcx]")
         + x86("cmp64", "rax", (long)0)
         + x86("jne", L(1))
         + x86("jmp", L(0))
         + x86("def", L(1))
         + IF(g_emit.xa_bb_emit_pair_n >= 4 && g_emit.xa_bb_emit_pair_define[3] != NULL, x86("def", PAIR(3)))
         + (hfc() && x86_zc_frame() == ZC_FRAME_RSP
             ? x86("note", "cas_mark")
             + x86("sub", "r12", (long)24)
             + IF(emit_arbno_rbp_unwind(), x86_arbno_rbp_unwind("r12", 8, 11, 12))
             + x86("note", "cas_rsp_mark")
             + x86("mov", "rsp", RDQ("r12", 8))
             : IF(x86_zc_frame() != ZC_FRAME_RSP, x86("note", "cas_mark")
                                                 + x86("sub", "r12", (long)24))
             + (x86_zc_frame() == ZC_FRAME_RSP
                 ? x86("note", "cas_mark")
                 + x86("def", L(2))
                 + x86("sub", "r12", (long)24)
                 + x86("mov", "rax", RDQ("r12", 0))
                 + x86("test", "rax", "rax")
                 + x86("jne", L(2))
                 + IF(emit_arbno_rbp_unwind(), x86_arbno_rbp_unwind("r12", 8, 11, 12))
                 + x86("note", "cas_rsp_mark")
                 + x86("mov", "rsp", RDQ("r12", 8))
                 : ( x86_align_enter()
                   + x86("call", "rt_zls_release_to", (uint64_t)(uintptr_t)(void *)rt_zls_release_to)
                   + x86_zls2_release_to_call(stfh() ? HKM() : FRQ(_.op_off + 16))
                   + x86_align_leave())))
         + x86("note", HKN(1))
         + x86("mov", "r13", stfh() ? HKQ(1) : FRQ(_.op_off + 48))
         + x86("note", HKN(2))
         + x86("mov", "r14", stfh() ? HKQ(2) : FRQ(_.op_off + 56))
         + x86("note", HKN(3))
         + x86("mov", "r15", stfh() ? HKQ(3) : FRQ(_.op_off + 64))
         + x86("mov", "rdi", "r13")
         + x86("mov", "rsi", "r15")
         + x86("call", "rt_match_ctx_restore", (uint64_t)(uintptr_t)(void *)rt_match_ctx_restore)
         + IF(_.flat_deep_arrival, x86("note", HKN(0)) + std::string(""))
         + x86_omega();
}
