#include <string>
#include <stdint.h>
#include "emit.h"
extern "C" {
#include "bb_template_common.h"
#include "bb_templates.h"
typedef struct { uint64_t ptr; uint64_t len; } ScanSubjRegs;
ScanSubjRegs rt_match_enter(uint64_t lo, uint64_t hi);
uint64_t rt_match_ctx_restore(uint64_t sig, uint64_t len, uint64_t cell);
extern "C" long *rt_anchor_ptr(void);
}
#include "x86_asm.h"
#define subjc() (_.op_subj_cell)
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_match_begin() {
    x86_begin();
    return x86("comment", "IR_MATCH_BEGIN")
         + x86_alpha()
         + IF(_.op_zres, x86("note", ZOPN(0))
                       + x86("mov", "rdi", x86_zref(_.op_zread[0] + 0, 1))
                       + x86("note", ZOPN(0))
                       + x86("mov", "rsi", x86_zref(_.op_zread[0] + 8, 1)))
         + IF(!_.op_zres && subjc(), x86("mov", "rdi", "qword ptr [rsp + 0]")
                     + x86("mov", "rsi", "qword ptr [rsp + 8]")
                     + x86_zrelease(16))
         + IF(!_.op_zres && !subjc(), x86("mov", "rdi", FRQ(_.op_sa))
                      + x86("mov", "rsi", FRQ(_.op_sa + 8)))
         + x86_gc_site(X86_SITE_MATCH_ENTER)
         + x86("push", "rbp")
         + x86("mov",  "rbp", "rsp")
         + x86("note", "cas_mark")
         + x86("push", "r12")
         + x86("note", HKN(1))
         + x86("push", "r13")
         + x86("note", HKN(2))
         + x86("push", "r14")
         + x86("note", HKN(3))
         + x86("push", "r15")
         + x86("sub",  "rsp", (long)(24 + _.op_frame_extra))
         + x86("mov", "rax", std::string("[rip@got + __]"), TEMPLATE_ADDR_SIGMA, "Σ")
         + x86("mov", "rax", "[rax]")
         + x86("mov", "rcx", std::string("[rip@got + __]"), TEMPLATE_ADDR_SIGLEN, "Σlen")
         + x86("mov", "ecx", RDD("rcx", 0))
         + x86("mov", RDD("rbp", MATCH_CTX_CELL_OFF(_.op_frame_extra)), (long)DT_S)
         + x86("mov", RDD("rbp", MATCH_CTX_CELL_OFF(_.op_frame_extra) + 4), "ecx")
         + x86("mov", RDQ("rbp", MATCH_CTX_CELL_OFF(_.op_frame_extra) + 8), "rax")
         + x86("neg", "rax")
         + x86("mov", RDQ("rbp", MATCH_CTX_CELL_OFF(_.op_frame_extra) + 16), "rax")
         + x86("call", "rt_match_enter", (uint64_t)(uintptr_t)(void *)rt_match_enter)
         + x86_rt_gc_poll_rec_subject_new()
         + x86("mov", "r13", "rax")
         + x86("mov", "r15", "rdx")
         + x86("comment",
             "CAS begin marker (FLUSH, Lon 2026-09-27): one null entry above the saved mark; rt_dcap_pump skips it, bb_match_flush scans down r12 to it from any frame, the exits pop it with the mark")
         + x86("note", "cas_mark")
         + x86("mov", RDQ("r12", 0), 0L)
         + x86("mov", RDQ("r12", 8), 0L)
         + x86("mov", RDQ("r12", 16), 0L)
         + x86("add", "r12", (long)24)
         + x86("note", "start_δ")
         + x86("mov", RDD("rbp", -40), (long)0)
         + x86("def", L(0))
         + x86("note", "start_δ")
         + x86("mov", "r14d", RDD("rbp", -40))
         + IF(sn4_defer_beta_guard(),
               x86("note", "match_beta_cont")
             + x86("mov", "rcx", "[rip@got + __]", (uint64_t)(uintptr_t)(const void *)&rtccb[0], "rtccb")
             + x86("mov", "rax", RDQ("rcx", 248))
             + x86("mov", RDQ("rbp", -48), "rax")
             + x86_lea_id("rax", 13)
             + x86("mov", RDQ("rcx", 248), "rax"))
         + x86_gamma()
         + x86_beta()
         + IF(sn4_defer_beta_guard(), x86("def", L(13)))
         + x86("note", "retry_whack")
         + x86("lea", "rsp", RDQ("rbp", -56 - _.op_frame_extra))
         + x86("mov", "rcx", "[rip@got + __]", (uint64_t)(uintptr_t)(const void *)&rtccb[0], "rtccb")
         + x86("mov", "rcx", RDQ("rcx", 200))
         + x86("test", "rcx", "rcx")
         + x86("jne", L(1))
         + x86("note", "start_δ")
         + x86("add", RDD("rbp", -40), (long)1)
         + x86("note", "start_δ")
         + x86("mov", "eax", RDD("rbp", -40))
         + x86("cmp", "eax", "r15d")
         + x86("jg",  L(1))
         + x86("mov", "rcx", "[rip@got + __]", (uint64_t)(uintptr_t)(const void *)rt_anchor_ptr(), "rt_anchor_g")
         + x86("mov", "rax", "[rcx]")
         + x86("cmp64", "rax", (long)0)
         + x86("jne", L(1))
         + x86("jmp", L(0))
         + x86("def", L(1))
         + IF(g_emit.xa_bb_emit_pair_n >= 4 && XA_PAIR(3).define != NULL, x86("def", PAIR(3)))
         + IF(g_emit.xa_bb_emit_pair_n >= 5 && XA_PAIR(4).define != NULL, x86("def", PAIR(4)))
         + IF(sn4_defer_beta_guard(),
               x86("note", "mbc_restore")
             + x86("mov", "rcx", "[rip@got + __]", (uint64_t)(uintptr_t)(const void *)&rtccb[0], "rtccb")
             + x86("mov", "rax", RDQ("rbp", -48))
             + x86("mov", RDQ("rcx", 248), "rax"))
         + x86("note", "cas_mark")
         + x86("mov", "r12", RDQ("rbp", -8))
         + x86("note", HKN(1))
         + x86("mov", "r13", RDQ("rbp", -16))
         + x86("note", HKN(2))
         + x86("mov", "r14", RDQ("rbp", -24))
         + x86("note", HKN(3))
         + x86("mov", "r15", RDQ("rbp", -32))
         + x86("mov", "rdi", "r13")
         + x86("mov", "rsi", "r15")
         + x86("lea", "rdx", RDQ("rbp", MATCH_CTX_CELL_OFF(_.op_frame_extra)))
         + x86("call", "rt_match_ctx_restore", (uint64_t)(uintptr_t)(void *)rt_match_ctx_restore)
         + x86("note", HKN(1))
         + x86("mov", RDQ("rbp", -16), "rax")
         + x86("note", HKN(1))
         + x86("mov", "r13", RDQ("rbp", -16))
         + x86("mov", "rsp", "rbp")
         + x86("pop", "rbp")
         + x86_omega();
}
