/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
#pragma once
#ifdef __cplusplus
#include <string>
#include "IR.h"
extern "C" { void bb_pattern_stub(const char * which); }
extern "C++" {
std::string bb_match_any();
std::string bb_match_notany();
std::string bb_match_span();
std::string bb_match_break();
std::string bb_match_breakx();
std::string bb_match_rtab();
std::string bb_match_lambda();
std::string bb_match_pos();
std::string bb_match_rpos();
std::string bb_match_tab();
std::string bb_coerce_string();
std::string bb_coerce_numeric();
std::string bb_cmp_test();
std::string bb_ident();
std::string bb_differ();
std::string bb_coerce_integer();
std::string bb_coerce_real();
std::string bb_match_atp();
std::string bb_match_len();
std::string bb_match_rem();
std::string bb_match_arb();
std::string bb_match_bal();
std::string bb_match_arbno();
std::string bb_match_abort();
std::string bb_match_fence0();
std::string bb_match_fence1();
std::string bb_match_alternate();
std::string bb_scan_sequence();
std::string bb_scan_alternate();
std::string bb_match_begin();
std::string bb_match_end();
std::string bb_match_replace();
std::string bb_match_capture();
std::string bb_conjunction();
std::string bb_subscript();
std::string bb_subscript2();
std::string bb_deref();
std::string bb_random();
std::string bb_var_ref();
std::string bb_var_ref_frame();
std::string bb_assign_var();
std::string bb_assign_var_sub();
std::string bb_rev_assign_var();
std::string bb_goto();
std::string bb_bound();
std::string bb_statement();
std::string bb_stmt_mark(long stno, long line);
std::string bb_line_mark(long line, const char * file);
std::string bb_glue_flat_enter();
std::string bb_glue_flat_leave();
std::string bb_glue_framed_enter();
std::string bb_glue_framed_leave();
std::string bb_glue_outer_γ();
std::string bb_glue_outer_ω();
std::string bb_main_entry_bridge();
std::string bb_main_β();
std::string bb_main_floater(int kind);
std::string bb_glue_wire_exit(int is_gamma);
std::string bb_glue_wire_γ();
std::string bb_glue_wire_ω();
std::string bb_glue_pass_wires(int gid, int wid);
std::string bb_glue_wire_land(void);
std::string bb_glue_pass_wires_blob(int gid, int wid);
std::string bb_glue_pass_wires_blob_regs(int gid, int wid);
std::string bb_glue_enter_c2bb(int base, int lg, int lw);
std::string bb_glue_prim_int(int base);
std::string bb_glue_prim_str(int base, int ptr_d, int ptr_sd, int len_d, int len_sd);
std::string bb_glue_prim_str_rsp(int base, int ptr_off, int len_off);
std::string bb_disjunction();
std::string bb_cut();
std::string bb_fail();
std::string bb_call(IR_t * pBB);
std::string bb_iterate();
std::string bb_binop_relop();
std::string bb_binop_relop_val();
std::string bb_binop_arith();
std::string bb_binop_concat_slot();
std::string bb_binop_xrep_slot();
std::string bb_lit_scalar();
std::string bb_var();
std::string bb_var_global();
std::string bb_return();
std::string bb_unop();
std::string bb_succeed();
std::string bb_match_defer();
std::string bb_match_value();
std::string bb_keyword_icon();
std::string bb_keyword_snobol4();
std::string bb_keyword_assign();
std::string bb_keyword_assign_snobol4();
std::string bb_goto_deferred();
std::string bb_define();
std::string bb_nreturn_mark();
extern "C" void * bb_ab_fn_cell_ptr(const char * fname);
std::string bb_gen_scan();
std::string bb_assign_local();
std::string bb_assign_global();
std::string bb_field_get();
std::string bb_section();
std::string bb_swap();
std::string bb_swap_var();
std::string bb_proc_value();
std::string bb_call_value();
std::string bb_rev_assign();
std::string bb_rev_assign_global();
std::string bb_rev_swap();
std::string bb_assign_frame();
std::string bb_var_frame();
std::string bb_to();
std::string bb_match_len();
std::string bb_match_lit();
std::string bb_to_by();
std::string bb_make_list();
std::string bb_limit();
std::string bb_suspend();
std::string bb_enter_init();
std::string bb_activate();
std::string bb_create();
std::string bb_coret();
std::string bb_cofail();
std::string bb_gate_arm();
std::string bb_gate();
std::string xa_coexpr_body_lea(const char * dst);
std::string bb_limit_init();
std::string bb_limit_gate();
std::string bb_repalt_clear();
std::string bb_repalt_yield();
std::string bb_repalt_test();
std::string bb_scan_pos();
std::string bb_scan_any();
std::string bb_scan_match();
std::string bb_glit();
std::string bb_gcc();
std::string bb_galt();
std::string bb_scan_many();
std::string bb_scan_tab();
std::string bb_scan_move();
std::string bb_scan_upto();
std::string bb_scan_find();
std::string bb_scan_bal();
}
#endif
