#ifndef RK_TREE_H
#define RK_TREE_H
#include "ast.h"
typedef struct RkB RkB;
typedef struct RkItems RkItems;
typedef struct RkDecl RkDecl;
enum { RKI_TREE = 0, RKI_VAR, RKI_NAME, RKI_QUOTE, RKI_WORDS, RKI_CP, RKI_FAT, RKI_STAR, RKI_PAREN, RKI_BLOCK, RKI_DECL, RKI_BSTMT, RKI_DOTTY, RKI_EMPTY, RKI_CALL };
enum { BK_MAIN = 0, BK_BLOCK, BK_SUB, BK_METHOD, BK_CLASS, BK_GRAMMAR, BK_MODULE, BK_GIVEN, BK_CATCH, BK_ITEMS };
typedef struct RkItem {
    tree_t *t;
    int kind, cls;
    int from, to, core_to;
    int npost, npre, cpre;
    const char **pre;
    const char *name;
    int ck;
    tree_t *val;
    RkItems *inner;
    int cnt;
    RkDecl *decl;
} RkItem;
struct RkItems { RkItem *t; const char **ot; tree_t **om; int nt, ct, no, co; };
typedef struct { const char *word; const char *name; } RkTrait;
struct RkDecl {
    int scope, sigil;
    const char *name, *type, *init_op;
    RkItems *init;
    tree_t *sig;
    RkTrait *tr; int ntr;
};
typedef struct { int k; int from, to; const char *txt; int form, mod; RkItems *inner; RkItems *args; } RkPf;
typedef struct { int pos; RkItems *items; int cnt; } RkClosure;
RkB     *rkb_new(const char *src, int len);
RkItems *rkb_items_new(void);
void     rkb_items_term(RkItems *xs, RkItem *it);
void     rkb_items_op(RkItems *xs, const char *op, int oplen, tree_t *mid);
void     rkb_adverb(RkB *b, RkItems *xs, const char *key, int ck, tree_t *val);
tree_t  *rkb_expr(RkB *b, RkItems *xs);
tree_t  *rkb_paren(RkB *b, RkItems *xs, int nstmts);
tree_t  *rkb_bracket(RkB *b, RkItems *xs);
void     rkb_var(RkB *b, RkItem *it, int from, int to, const char *named_capture, int nclen);
void     rkb_number(RkB *b, RkItem *it, int from, int to);
void     rkb_quote(RkB *b, RkItem *it, int from, int to, RkClosure *cl, int ncl);
void     rkb_words(RkB *b, RkItem *it, int from, int to, int inner_from, int inner_to);
void     rkb_name(RkB *b, RkItem *it, int from, int to, int namelen);
void     rkb_call(RkB *b, RkItem *it, int from, int to, int namelen, RkItems *args, int form);
void     rkb_colonpair(RkB *b, RkItem *it, int from, int to, int ck, int kfrom, int kto, tree_t *val, int vfrom, int vto, int vkind);
void     rkb_fatarrow(RkB *b, RkItem *it, int from, int to, int kfrom, int kto, RkItems *val);
void     rkb_postfix(RkB *b, RkItem *it, RkPf *pf);
void     rkb_prefix(RkItem *it, const char *s, int n);
void     rkb_reduce(RkB *b, RkItem *it, int from, int to, int ofrom, int oto, RkItems *args);
void     rkb_method_term(RkB *b, RkItem *it, RkPf *pf);
tree_t  *rkb_param(RkB *b, int prefix, const char *var, int varlen, int *tf, int *tt, int ntypes, RkItems *dflt, int suffix, int named);
tree_t  *rkb_block_seq(RkB *b, tree_t *list, int bk, int yada);
void     rkb_block_term(RkB *b, RkItem *it, int from, int to, tree_t *seq, tree_t *sig, int sub, RkItems *last, int nstmts);
void     rkb_statement(RkB *b, tree_t *list, int bk, int from, int to, RkItems *xs, int nmods, const char **modk, RkItems **modx, int semi, int last);
void     rkb_control(RkB *b, tree_t *list, int bk, int from, tree_t *t, int ns, int semi, int last);
void     rkb_empty(RkB *b, tree_t *list, int bk);
tree_t  *rkb_routine(RkB *b, int kind, int multi, const char *name, int namelen, int prefix, tree_t *sig, int has_parens, tree_t *body, RkTrait *tr, int ntr);
tree_t  *rkb_package(RkB *b, const char *kind, const char *name, int namelen, RkTrait *tr, int ntr, tree_t *body);
tree_t  *rkb_regex_decl(RkB *b, int kind, const char *name, int namelen, int brace);
void     rkb_decl(RkB *b, RkItem *it, int from, int to, RkDecl *d);
tree_t  *rkb_enum(RkB *b, const char *text, int n);
tree_t  *rkb_constant(RkB *b, const char *name, int namelen, RkItems *init);
tree_t  *rkb_use(RkB *b, const char *name, int namelen, RkItems *args);
tree_t  *rkb_if(RkB *b, int n, const char **kw, RkItems **cond, tree_t **blk, tree_t *els);
tree_t  *rkb_unless(RkB *b, RkItems *cond, tree_t *blk);
tree_t  *rkb_while(RkB *b, int until, RkItems *cond, tree_t *blk);
tree_t  *rkb_repeat(RkB *b, int until, tree_t *blk, RkItems *cond);
tree_t  *rkb_loop(RkB *b, RkItems *e1, RkItems *e2, RkItems *e3, int parens, tree_t *blk);
tree_t  *rkb_for(RkB *b, RkItems *list, tree_t *sig, tree_t *blk);
tree_t  *rkb_given(RkB *b, RkItems *topic, tree_t *whens);
tree_t  *rkb_catch(RkB *b, tree_t *body, int whens);
void     rkb_when(RkB *b, tree_t *list, int bk, RkItems *cond, tree_t *blk);
int      rkb_swap_nonwhen(RkB *b, int v);
void     rkb_default(RkB *b, tree_t *list, tree_t *blk);
void     rkb_sprefix_term(RkB *b, RkItem *it, int from, int to, const char *word, int wlen, tree_t *blk, tree_t *stmt);
void     rkb_set_after_line(RkB *b, int pos);
tree_t  *rkb_program(RkB *b, tree_t *list);
#endif
