#ifndef RK_TREE_H
#define RK_TREE_H
#include "ast.h"
typedef struct RkB RkB;
typedef struct RkList RkList;
typedef struct RkDecl RkDecl;
enum { TK_TREE = 0, TK_VAR, TK_NAME, TK_QUOTE, TK_WORDS, TK_CP, TK_FAT, TK_STAR, TK_PAREN, TK_BLOCK, TK_DECL, TK_BSTMT, TK_DOTTY, TK_EMPTY, TK_CALL };
enum { BK_MAIN = 0, BK_BLOCK, BK_SUB, BK_METHOD, BK_CLASS, BK_GRAMMAR, BK_MODULE, BK_GIVEN, BK_CATCH, BK_ITEMS };
enum { LV_MUL = 0, LV_ADDSUB, LV_REPL, LV_CAT, LV_RANGE1, LV_RANGE2, LV_DOR, LV_JCT, LV_DIVIS, LV_CMP, LV_AND, LV_OR, LV_POW, LV_TERN, LV_PAIR, LV_COMPOUND };
typedef struct {
    tree_t *t;
    int kind, cls;
    int from, to, core_to;
    int npost, npre, cpre;
    const char **pre;
    const char *name;
    int ck, cnt;
    tree_t *val, *lop;
    RkList *in;
    RkDecl *decl;
} RkTerm;
typedef struct { tree_t *ph; RkDecl *d; } RkPend;
typedef struct { tree_t *t; int nitem; RkTerm t0; const char *op1; tree_t *rest; RkPend *pd; int npd, cpd; } RkEl;
struct RkList {
    RkEl *v; int n, cap;
    int trailing, nitem, subst;
    RkTerm t1;
    const char *op1;
    tree_t *rg_lo, *rg_hi; const char *rg_op; int rg_nitem;
};
typedef struct { const char *word; const char *name; } RkTrait;
struct RkDecl {
    int scope, sigil;
    const char *name, *type, *init_op;
    RkList *init;
    tree_t *sig;
    RkTrait *tr; int ntr;
};
typedef struct { int k; int from, to; const char *txt; int form, mod, hyper; RkList *inner; RkList *args; } RkPf;
typedef struct { int pos; RkList *last; int cnt; } RkClosure;
RkB     *rkb_new(const char *src, int len);
RkList  *rkb_list_new(void);
RkEl    *rkb_list_el(RkList *L);
void     rkb_list_end(RkList *L);
void     rkb_pend(RkEl *e, tree_t *ph, RkDecl *d);
int      rkb_op_index(int lv, const char *op);
tree_t  *rkb_binop(RkB *b, int lv, int k, tree_t *l, tree_t *r);
tree_t  *rkb_ternary(RkB *b, tree_t *l, tree_t *mid, tree_t *r);
tree_t  *rkb_assign(RkB *b, int cls, const char *name, int k, tree_t *r);
tree_t  *rkb_prefix_apply(RkB *b, const char *op, tree_t *x);
tree_t  *rkb_incdec(RkB *b, const char *var, int add);
tree_t  *rkb_smartmatch_term(RkB *b, tree_t *l, RkTerm *x);
tree_t  *rkb_smartmatch(RkB *b, tree_t *l, tree_t *r);
int      rkb_listop_substitutes(const char *name, int namelen);
tree_t  *rkb_listop_call(RkB *b, const char *name, int namelen, RkTerm *paren);
const char *rkb_reduce_name(RkB *b, int ofrom, int oto);
void     rkb_adverb(RkB *b, tree_t *t, const char *key);
tree_t  *rkb_expr(RkB *b, RkList *L);
void     rkb_cross(RkB *b, const char *op, RkList *L, RkList **rs, int nr);
int      rkb_compound_base(const char *op, int *lv, int *k);
tree_t  *rkb_assign_op(RkB *b, const char *name, const char *op, tree_t *r);
tree_t  *rkb_elem_incdec(RkB *b, tree_t *g, int add, int post);
tree_t  *rkb_paren(RkB *b, RkList *L, int nstmts);
void     rkb_contextualize(RkB *b, RkTerm *it, const char *meth);
void     rkb_codevar(RkB *b, const char *name);
tree_t  *rkb_bracket(RkB *b, RkList *L);
void     rkb_var(RkB *b, RkTerm *it, int from, int to, const char *named_capture, int nclen);
void     rkb_number(RkB *b, RkTerm *it, int from, int to);
void     rkb_quote(RkB *b, RkTerm *it, int from, int to, RkClosure *cl, int ncl);
void     rkb_words(RkB *b, RkTerm *it, int from, int to, int inner_from, int inner_to);
void     rkb_name(RkB *b, RkTerm *it, int from, int to, int namelen);
void     rkb_call(RkB *b, RkTerm *it, int from, int to, int namelen, RkList *args, int form);
void     rkb_colonpair(RkB *b, RkTerm *it, int from, int to, int ck, int kfrom, int kto, tree_t *val, int vfrom, int vto, int vkind);
void     rkb_fatarrow(RkB *b, RkTerm *it, int from, int to, int kfrom, int kto, RkList *val);
void     rkb_postfix(RkB *b, RkTerm *it, RkPf *pf);
void     rkb_prefix(RkTerm *it, const char *s, int n);
void     rkb_reduce(RkB *b, RkTerm *it, int from, int to, const char *rop, RkList *args);
void     rkb_method_term(RkB *b, RkTerm *it, RkPf *pf);
tree_t  *rkb_param(RkB *b, int prefix, const char *var, int varlen, int *tf, int *tt, int ntypes, RkList *dflt, int suffix, int named);
tree_t  *rkb_block_seq(RkB *b, tree_t *list, int bk, int yada);
void     rkb_block_term(RkB *b, RkTerm *it, int from, int to, tree_t *seq, tree_t *sig, int sub, RkList *last, int nstmts);
void     rkb_statement(RkB *b, tree_t *list, int bk, int from, int to, RkList *L, int nmods, const char **modk, RkList **modx, int semi, int last);
void     rkb_control(RkB *b, tree_t *list, int bk, int from, tree_t *t, int ns, int semi, int last);
void     rkb_empty(RkB *b, tree_t *list, int bk);
tree_t  *rkb_routine(RkB *b, int kind, int multi, const char *name, int namelen, int prefix, tree_t *sig, int has_parens, tree_t *body, RkTrait *tr, int ntr);
tree_t  *rkb_package(RkB *b, const char *kind, const char *name, int namelen, RkTrait *tr, int ntr, tree_t *body);
tree_t  *rkb_regex_decl(RkB *b, int kind, const char *name, int namelen, int brace);
void     rkb_decl(RkB *b, RkTerm *it, int from, int to, RkDecl *d);
tree_t  *rkb_enum(RkB *b, const char *text, int n);
tree_t  *rkb_constant(RkB *b, const char *name, int namelen, RkList *init);
tree_t  *rkb_use(RkB *b, const char *name, int namelen, RkList *args);
tree_t  *rkb_if(RkB *b, int n, const char **kw, RkList **cond, tree_t **blk, tree_t *els);
tree_t  *rkb_unless(RkB *b, RkList *cond, tree_t *blk);
tree_t  *rkb_while(RkB *b, int until, RkList *cond, tree_t *blk);
tree_t  *rkb_repeat(RkB *b, int until, tree_t *blk, RkList *cond);
tree_t  *rkb_loop(RkB *b, RkList *e1, RkList *e2, RkList *e3, int parens, tree_t *blk);
tree_t  *rkb_for(RkB *b, RkList *list, tree_t *sig, tree_t *blk);
tree_t  *rkb_given(RkB *b, RkList *topic, tree_t *whens);
tree_t  *rkb_catch(RkB *b, tree_t *body, int whens);
void     rkb_when(RkB *b, tree_t *list, int bk, RkList *cond, tree_t *blk);
int      rkb_swap_nonwhen(RkB *b, int v);
void     rkb_default(RkB *b, tree_t *list, tree_t *blk);
void     rkb_sprefix_term(RkB *b, RkTerm *it, int from, int to, const char *word, int wlen, tree_t *blk, tree_t *stmt);
void     rkb_set_after_line(RkB *b, int pos);
tree_t  *rkb_program(RkB *b, tree_t *list);
#endif
