#include <string>
#include <stdint.h>
#include "emit.h"
extern "C" {
#include "bb_template_common.h"
#include "SM.h"
#include "ast.h"
#include "descr.h"
#include "../runtime/builtins/gen.h"
int rt_jct_relop(DESCR_t lhs, DESCR_t rhs, int op);
int rt_relop_overload(DESCR_t a, DESCR_t b, int op, DESCR_t *out);
int rt_binop_overload(DESCR_t a, DESCR_t b, int op, DESCR_t *out);
DESCR_t rt_str_coerce(DESCR_t d);
}
#include "x86_asm.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_binop_relop() {
    if (PLATFORM_X86) {
        return (!_.op_num_real && _.op_off >= 0 && _.op_ival >= BINOP_LT && _.op_ival <= BINOP_NE && _.op_sa >= 0 && _.op_sb >= 0)
                 ? x86_alpha()
                 + x86("comment", "IR_BINOP_TEST")
                 + x86("mov", "eax", FR(_.op_sa))
                 + x86("cmp", "eax", (long)DT_DATA)
                 + x86("je", L(0))
                 + x86("mov", "eax", FR(_.op_sb))
                 + x86("cmp", "eax", (long)DT_DATA)
                 + x86("je", L(0))
                 + x86("mov", "eax", FR(_.op_sa))
                 + x86("cmp", "eax", (long)DT_I)
                 + x86("jne", L(2))
                 + x86("mov", "eax", FR(_.op_sb))
                 + x86("cmp", "eax", (long)DT_I)
                 + x86("jne", L(2))
                 + x86("def", L(1))
                 + x86("mov", "rax", FRQ(_.op_sa + 8))
                 + x86("mov", "rcx", FRQ(_.op_sb + 8))
                 + x86("cmp", "rax", "rcx")
                 + x86_omega(_.op_ival == BINOP_LT ? "jge" : _.op_ival == BINOP_LE ? "jg" : _.op_ival == BINOP_GT ? "jle" : _.op_ival == BINOP_GE ? "jl" : _.op_ival == BINOP_EQ ? "jne" : "je")
                 + x86("mov", "rcx", FRQ(_.op_sb))
                 + x86("mov", FRQ(_.op_off), "rcx")
                 + x86("mov", "rcx", FRQ(_.op_sb + 8))
                 + x86("mov", FRQ(_.op_off + 8), "rcx")
                 + x86_gamma()
                 + x86("def", L(0))
                 + x86("mov", "rdi", FRQ(_.op_sa))
                 + x86("mov", "rsi", FRQ(_.op_sa + 8))
                 + x86("mov", "rdx", FRQ(_.op_sb))
                 + x86("mov", "rcx", FRQ(_.op_sb + 8))
                 + x86("mov", "r8d", (long)_.op_ival)
                 + x86("lea", "r9", FRQ(_.op_off))
                 + x86("call", "rt_relop_overload", (uint64_t)(uintptr_t)(void*)rt_relop_overload)
                 + x86("test", "eax", "eax")
                 + x86("je", L(1))
                 + x86("cmp", "eax", (long)1)
                 + x86_omega("je")
                 + x86_gamma()
                 + x86("def", L(2))
                 + x86("mov", "rdi", FRQ(_.op_sa))
                 + x86("mov", "rsi", FRQ(_.op_sa + 8))
                 + x86("mov", "rdx", FRQ(_.op_sb))
                 + x86("mov", "rcx", FRQ(_.op_sb + 8))
                 + x86("mov", "r8d", (long)_.op_ival)
                 + x86("call", "rt_jct_relop", (uint64_t)(uintptr_t)(void*)rt_jct_relop)
                 + x86("test", "eax", "eax")
                 + x86_omega("jz")
                 + x86("mov", "rax", FRQ(_.op_sb))
                 + x86("mov", FRQ(_.op_off), "rax")
                 + x86("mov", "rax", FRQ(_.op_sb + 8))
                 + x86("mov", FRQ(_.op_off + 8), "rax")
                 + x86_gamma()
                 + x86_beta_trampoline()
             : (_.op_off >= 0 && _.op_sa >= 0 && _.op_sb >= 0
                && ((_.op_num_real && _.op_ival >= BINOP_LT && _.op_ival <= BINOP_NE) || (_.op_ival >= BINOP_SLT && _.op_ival <= BINOP_SNE) || _.op_ival == BINOP_EQV || _.op_ival == BINOP_NEQV))
                 ? x86_alpha()
                 + x86("comment", "IR_BINOP_TEST")
                 + x86("mov", "rdi", FRQ(_.op_sa))
                 + x86("mov", "rsi", FRQ(_.op_sa + 8))
                 + x86("mov", "rdx", FRQ(_.op_sb))
                 + x86("mov", "rcx", FRQ(_.op_sb + 8))
                 + x86("mov", "r8d", (long)_.op_ival)
                 + x86("call", "rt_jct_relop", (uint64_t)(uintptr_t)(void*)rt_jct_relop)
                 + x86("test", "eax", "eax")
                 + x86_omega("jz")
                 + (_.op_ival >= BINOP_SLT && _.op_ival <= BINOP_SNE
                     ? x86("mov", "rdi", FRQ(_.op_sb))
                     + x86("mov", "rsi", FRQ(_.op_sb + 8))
                     + x86("call_rt", "rt_str_coerce", (long)_.op_off, (uint64_t)(uintptr_t)(void*)rt_str_coerce)
                     : x86("mov", "rax", FRQ(_.op_sb))
                     + x86("mov", FRQ(_.op_off), "rax")
                     + x86("mov", "rax", FRQ(_.op_sb + 8))
                     + x86("mov", FRQ(_.op_off + 8), "rax"))
                 + x86_gamma()
                 + x86_beta_trampoline()
             : x86_bomb("bb_binop_relop: shape mismatch");
    }
    return std::string();
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_binop_relop_val() {
    if (PLATFORM_X86 && _.op_zres && !_.op_num_real && _.op_ival >= BINOP_LT && _.op_ival <= BINOP_NE)   /* ⭐ ZK-2 (s226): op_sa/op_sb guards REMOVED from ZD arm -- ZOPQ(k,0/8) reads _.op_zread[k], staged by zd_plan from g_zd_read[]; op_sa/op_sb are flat-frame slots set by emit_binop_opnd_slot which returns -1 for ZD-armed operand nodes (no flat slot allocated on the cells arm).  Only op_zres is needed to select the ZD arm; op_num_real and BINOP_LT..NE are preserved. */
        return x86_alpha()
             + x86("comment", "IR_BINOP_TEST zd")
             + x86("mov", "eax", ZOPD(0, 0))
             + x86("cmp", "eax", (long)DT_I)
             + x86("jne", L(2))
             + x86("mov", "eax", ZOPD(1, 0))
             + x86("cmp", "eax", (long)DT_I)
             + x86("jne", L(2))
             + x86("def", L(1))
             + x86("mov", "rax", ZOPQ(0, 8))
             + x86("mov", "rcx", ZOPQ(1, 8))
             + x86("cmp", "rax", "rcx")
             + x86_omega(_.op_ival == BINOP_LT ? "jge" : _.op_ival == BINOP_LE ? "jg" : _.op_ival == BINOP_GT ? "jle" : _.op_ival == BINOP_GE ? "jl" : _.op_ival == BINOP_EQ ? "jne" : "je")
             + x86("mov", "rcx", ZOPQ(1, 0))
             + x86("mov", ZRES(0), "rcx")
             + x86("mov", "rcx", ZOPQ(1, 8))
             + x86("mov", ZRES(8), "rcx")
             + x86_gamma()
             + x86("def", L(2))
             + x86("mov", "rdi", ZOPQ(0, 0))
             + x86("mov", "rsi", ZOPQ(0, 8))
             + x86("mov", "rdx", ZOPQ(1, 0))
             + x86("mov", "rcx", ZOPQ(1, 8))
             + x86("mov", "r8d", (long)_.op_ival)
             + x86("call", "rt_jct_relop", (uint64_t)(uintptr_t)(void*)rt_jct_relop)
             + x86("test", "eax", "eax")
             + x86_omega("jz")
             + x86("mov", "rcx", ZOPQ(1, 0))
             + x86("mov", ZRES(0), "rcx")
             + x86("mov", "rcx", ZOPQ(1, 8))
             + x86("mov", ZRES(8), "rcx")
             + x86_gamma()
             + x86_beta_trampoline();   /* ⭐ ZK-2 ZD ARM SEMANTICS (s226): IR_BINOP_TEST is a {γ=pass, ω=fail} Icon generator -- γ yields the rhs value (ZOPQ(1) → ZRES), ω fails.  The prior ZD arm wrote {DT_I,0/1} boolean and fired x86_gamma() on BOTH paths -- the {0,1} encoding from IR_BINOP_RELOP_VAL bleeding into the wrong kind.  With both paths going to γ, the `until` loop (whose body runs on ω) could never terminate: the condition always succeeded from the loop's perspective.  Corrected shape: fast DT_I path uses x86_omega() on the failing jcc (invert from the non-ZD bb_binop_relop arm: that arm tests with the SAME jcc sense as a branch-to-fail, so we use it directly as x86_omega); overload fallback checks rt_jct_relop==0 → x86_omega("jz").  ZOPQ(0,0/8) = lhs (op_zread[0] = depth diff to operand[0]); ZOPQ(1,0/8) = rhs (op_zread[1] = depth diff to operand[1]).  SN4 watermark: IR_BINOP_TEST not emitted by SN4; byte-identical by construction.  ONE AUTHORITY: dispatch (emit.cpp:919) and this ZD arm are the two halves; zd_wl_kind + zd_nops are the planner halves.  NO BETA: the relop has no resume port -- each call to α either produces one result or fails, exactly like a SNOBOL4 comparison.  beta_trampoline emits the β stub pointing to ω per the standard non-resumable shape. */
    if (PLATFORM_X86) {
        return (!_.op_num_real && _.op_off >= 0 && _.op_ival >= BINOP_LT && _.op_ival <= BINOP_NE && _.op_sa >= 0 && _.op_sb >= 0)
                 ? x86_alpha()
                 + x86("comment", "IR_BINOP_RELOP_VAL")
                 + x86("mov", "eax", FR(_.op_sa))
                 + x86("cmp", "eax", (long)DT_DATA)
                 + x86("je", L(0))
                 + x86("mov", "eax", FR(_.op_sb))
                 + x86("cmp", "eax", (long)DT_DATA)
                 + x86("je", L(0))
                 + x86("mov", "eax", FR(_.op_sa))
                 + x86("cmp", "eax", (long)DT_I)
                 + x86("jne", L(2))
                 + x86("mov", "eax", FR(_.op_sb))
                 + x86("cmp", "eax", (long)DT_I)
                 + x86("jne", L(2))
                 + x86("def", L(1))
                 + x86("mov", "rax", FRQ(_.op_sa + 8))
                 + x86("mov", "rcx", FRQ(_.op_sb + 8))
                 + x86("cmp", "rax", "rcx")
                 + x86(_.op_ival == BINOP_LT ? "jge" : _.op_ival == BINOP_LE ? "jg" : _.op_ival == BINOP_GT ? "jle" : _.op_ival == BINOP_GE ? "jl" : _.op_ival == BINOP_EQ ? "jne" : "je", L(4))
                 + x86("def", L(3))
                 + x86("mov", "rcx", (long)DT_I)
                 + x86("mov", FRQ(_.op_off), "rcx")
                 + x86("mov", "rcx", (long)1)
                 + x86("mov", FRQ(_.op_off + 8), "rcx")
                 + x86_gamma()
                 + x86("def", L(4))
                 + x86("mov", "rcx", (long)DT_I)
                 + x86("mov", FRQ(_.op_off), "rcx")
                 + x86("mov", "rcx", (long)0)
                 + x86("mov", FRQ(_.op_off + 8), "rcx")
                 + x86_gamma()
                 + x86("def", L(0))
                 + x86("mov", "rdi", FRQ(_.op_sa))
                 + x86("mov", "rsi", FRQ(_.op_sa + 8))
                 + x86("mov", "rdx", FRQ(_.op_sb))
                 + x86("mov", "rcx", FRQ(_.op_sb + 8))
                 + x86("mov", "r8d", (long)_.op_ival)
                 + x86("lea", "r9", FRQ(_.op_off))
                 + x86("call", "rt_binop_overload", (uint64_t)(uintptr_t)(void*)rt_binop_overload)
                 + x86("test", "eax", "eax")
                 + x86("je", L(1))
                 + x86_gamma()
                 + x86("def", L(2))
                 + x86("mov", "rdi", FRQ(_.op_sa))
                 + x86("mov", "rsi", FRQ(_.op_sa + 8))
                 + x86("mov", "rdx", FRQ(_.op_sb))
                 + x86("mov", "rcx", FRQ(_.op_sb + 8))
                 + x86("mov", "r8d", (long)_.op_ival)
                 + x86("call", "rt_jct_relop", (uint64_t)(uintptr_t)(void*)rt_jct_relop)
                 + x86("test", "eax", "eax")
                 + x86("jne", L(3))
                 + x86("jmp", L(4))
                 + x86_beta_trampoline()
             : (_.op_off >= 0 && _.op_sa >= 0 && _.op_sb >= 0
                && ((_.op_num_real && _.op_ival >= BINOP_LT && _.op_ival <= BINOP_NE) || (_.op_ival >= BINOP_SLT && _.op_ival <= BINOP_SNE) || _.op_ival == BINOP_EQV || _.op_ival == BINOP_NEQV))
                 ? x86_alpha()
                 + x86("comment", "IR_BINOP_RELOP_VAL")
                 + x86("mov", "rdi", FRQ(_.op_sa))
                 + x86("mov", "rsi", FRQ(_.op_sa + 8))
                 + x86("mov", "rdx", FRQ(_.op_sb))
                 + x86("mov", "rcx", FRQ(_.op_sb + 8))
                 + x86("mov", "r8d", (long)_.op_ival)
                 + x86("call", "rt_jct_relop", (uint64_t)(uintptr_t)(void*)rt_jct_relop)
                 + x86("test", "eax", "eax")
                 + x86("je", L(4))
                 + x86("def", L(3))
                 + x86("mov", "rcx", (long)DT_I)
                 + x86("mov", FRQ(_.op_off), "rcx")
                 + x86("mov", "rcx", (long)1)
                 + x86("mov", FRQ(_.op_off + 8), "rcx")
                 + x86_gamma()
                 + x86("def", L(4))
                 + x86("mov", "rcx", (long)DT_I)
                 + x86("mov", FRQ(_.op_off), "rcx")
                 + x86("mov", "rcx", (long)0)
                 + x86("mov", FRQ(_.op_off + 8), "rcx")
                 + x86_gamma()
                 + x86_beta_trampoline()
             : x86_bomb("bb_binop_relop_val: shape mismatch");
    }
    return std::string();
}
