#include <string>
#include "emit.h"
#include "x86_asm.h"
extern "C" {
#include "xa_template_common.h"
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static std::string xa_prologue_str(void) {
    if (PLATFORM_JVM) {
        return x86("comment", "; JVM Jasmin output \xe2\x80\x94 generated by scrip --native codegen-emit --target=jvm")
             + x86("directive", ".class public Prog")
             + x86("directive", ".super java/lang/Object")
             + x86("directive", ".method public static main([Ljava/lang/String;)V")
             + x86("directive", ".limit stack 4")
             + x86("directive", ".limit locals 2")
             + x86("comment", "invokestatic rt/SnoRt/init()V")
             + x86("comment", "invokestatic Prog/core_body()V")
             + x86("comment", "invokestatic rt/SnoRt/finalize_rt()I")
             + x86("pop")
             + x86("return")
             + x86("directive", ".end method");
    }
    if (PLATFORM_JS) {
        return std::string("'use strict';\n")
             + "const rt = require('/home/claude/SCRIP/src/backends/runtime/js/core_runtime.js');\n"
             "rt._init();\n"
             "let _pc = 0;\n"
             "loop: while (true) { switch (_pc) {\n";
    }
    if (PLATFORM_NET) {
        return x86("comment", "// .NET MSIL output -- generated by scrip --sm-emit --target=net")
             + x86("comment", ".assembly extern mscorlib {}")
             + x86("comment", ".assembly extern boxes {}")
             + x86("comment", ".assembly Prog {}")
             + x86("comment", ".module Prog.exe")
             + x86("directive", ".class public auto ansi beforefieldinit Prog extends [mscorlib]System.Object")
             + x86("{")
             + x86("directive", ".method public static void Main() cil managed")
             + x86("{")
             + x86(".entrypoint")
             + x86("comment", ".maxstack 8")
             + x86("comment", "call void SnoRt::_init()");
    }
    if (PLATFORM_WASM) {
        return std::string("(module\n")
             + "  ;; imports from core_runtime\n"
             "  (import \"sno\" \"memory\"         (memory 64))\n"
             "  (import \"sno\" \"core_init\"        (func $core_init))\n"
             "  (import \"sno\" \"core_finalize\"    (func $core_finalize))\n"
             "  (import \"sno\" \"core_push_int\"    (func $core_push_int    (param i32)))\n"
             "  (import \"sno\" \"core_push_real\"   (func $core_push_real   (param f64)))\n"
             "  (import \"sno\" \"core_push_str\"    (func $core_push_str    (param i32 i32)))\n"
             "  (import \"sno\" \"core_push_null\"   (func $core_push_null))\n"
             "  (import \"sno\" \"core_push_var\"    (func $core_push_var    (param i32 i32)))\n"
             "  (import \"sno\" \"core_store_var\"   (func $core_store_var   (param i32 i32)))\n"
             "  (import \"sno\" \"core_pop_void\"    (func $core_pop_void))\n"
             "  (import \"sno\" \"core_concat\"      (func $core_concat))\n"
             "  (import \"sno\" \"core_neg\"         (func $core_neg))\n"
             "  (import \"sno\" \"core_coerce_num\"  (func $core_coerce_num))\n"
             "  (import \"sno\" \"core_exp_op\"      (func $core_exp_op))\n"
             "  (import \"sno\" \"core_arith\"       (func $core_arith       (param i32)))\n"
             "  (import \"sno\" \"core_lcomp\"       (func $core_lcomp       (param i32)))\n"
             "  (import \"sno\" \"core_acomp\"       (func $core_acomp       (param i32)))\n"
             "  (import \"sno\" \"core_last_ok\"     (func $core_last_ok     (result i32)))\n"
             "  (import \"sno\" \"core_set_stno\"    (func $core_set_stno    (param i32)))\n"
             "  (import \"sno\" \"core_halt_tos\"    (func $core_halt_tos))\n"
             "  (import \"sno\" \"core_call\"        (func $core_call        (param i32 i32 i32)))\n"
             "  (import \"sno\" \"core_fn_return\"   (func $core_fn_return   (param i32 i32) (result i32)))\n"
             "  (import \"sno\" \"core_call_frame_push\" (func $core_call_frame_push (param i32 i32 i32) (result i32)))\n"
             "  (import \"sno\" \"core_call_frame_close\" (func $core_call_frame_close))\n"
             "  (import \"sno\" \"core_save_var\"    (func $core_save_var    (param i32 i32 i32)))\n"
             "  (import \"sno\" \"core_clear_var\"   (func $core_clear_var   (param i32 i32)))\n"
             "  (import \"sno\" \"core_set_var_from_tos\" (func $core_set_var_from_tos (param i32 i32)))\n"
             "  (import \"sno\" \"core_pop_to_null\" (func $core_pop_to_null))\n"
             "  ;; Pattern matching functions\n"
             "  (import \"sno\" \"core_pat_lit\"     (func $core_pat_lit     (param i32 i32)))\n"
             "  (import \"sno\" \"core_pat_any\"     (func $core_pat_any))\n"
             "  (import \"sno\" \"core_pat_notany\"  (func $core_pat_notany))\n"
             "  (import \"sno\" \"core_pat_span\"    (func $core_pat_span))\n"
             "  (import \"sno\" \"core_pat_break\"   (func $core_pat_break))\n"
             "  (import \"sno\" \"core_pat_len\"     (func $core_pat_len))\n"
             "  (import \"sno\" \"core_pat_pos\"     (func $core_pat_pos))\n"
             "  (import \"sno\" \"core_pat_rpos\"    (func $core_pat_rpos))\n"
             "  (import \"sno\" \"core_pat_tab\"     (func $core_pat_tab))\n"
             "  (import \"sno\" \"core_pat_rtab\"    (func $core_pat_rtab))\n"
             "  (import \"sno\" \"core_pat_rem\"     (func $core_pat_rem))\n"
             "  (import \"sno\" \"core_pat_arb\"     (func $core_pat_arb))\n"
             "  (import \"sno\" \"core_pat_arbno\"   (func $core_pat_arbno))\n"
             "  (import \"sno\" \"core_pat_bal\"     (func $core_pat_bal))\n"
             "  (import \"sno\" \"core_pat_fail\"    (func $core_pat_fail))\n"
             "  (import \"sno\" \"core_pat_succeed\" (func $core_pat_succeed))\n"
             "  (import \"sno\" \"core_pat_abort\"   (func $core_pat_abort))\n"
             "  (import \"sno\" \"core_pat_fence\"   (func $core_pat_fence))\n"
             "  (import \"sno\" \"core_pat_eps\"     (func $core_pat_eps))\n"
             "  (import \"sno\" \"core_pat_cat\"     (func $core_pat_cat))\n"
             "  (import \"sno\" \"core_pat_alt\"     (func $core_pat_alt))\n"
             "  (import \"sno\" \"core_pat_deref\"   (func $core_pat_deref))\n"
             "  (import \"sno\" \"core_pat_refname\" (func $core_pat_refname (param i32 i32)))\n"
             "  (import \"sno\" \"core_pat_capture\" (func $core_pat_capture (param i32 i32 i32)))\n"
             "  (import \"sno\" \"core_exec_stmt\"   (func $core_exec_stmt   (param i32 i32 i32)))\n";
    }
    return std::string();
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
extern "C" void xa_prologue(void) { auto s = xa_prologue_str(); if (!s.empty()) emit_text_n(s.data(), s.size()); }
