#include "bb_common.h"
extern std::string emit_build_compound_term(const IR_t *nd);
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_atom_string() {
    if (PLATFORM_X86) return
          IF(_.op_sval && !strcmp(_.op_sval,"copy_term") && _.op_parts_n >= 2 && (_.op_parts_tag[0] == (int)IR_STRUCT || _.op_parts_tag[0] == (int)IR_ARITH),
              x86("label", _.lbl_α)
            + x86("sub", "rsp", 16L)
            + IF(_.op_parts_tag[1] == (int)IR_STRUCT || _.op_parts_tag[1] == (int)IR_ARITH,
                  emit_build_compound_term((const IR_t *)(intptr_t)_.op_parts_ival[8])
                + x86("mov", RSP(0), "rax")
                + emit_build_compound_term((const IR_t *)(intptr_t)_.op_parts_ival[9])
                + x86("mov", "rsi", "rax")
                + x86("mov", "rdi", RSP(0))
                + x86("call", "rt_copy_term_terms", (unsigned long long)(uintptr_t)(void*)rt_copy_term_terms))
            + IF(!(_.op_parts_tag[1] == (int)IR_STRUCT || _.op_parts_tag[1] == (int)IR_ARITH),
                  emit_build_compound_term((const IR_t *)(intptr_t)_.op_parts_ival[8])
                + x86("mov", "rdi", "rax")
                + x86("mov32", "esi", (long)_.op_parts_tag[1])
                + x86("movabs", "rdx", (unsigned long long)(uint64_t)_.op_parts_ival[1])
                + IF(_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_str[1], x86("lea", "rcx", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1]))
                + IF(!(_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_str[1]), x86("xor", "ecx", "ecx"))
                + x86("call", "rt_copy_term_term", (unsigned long long)(uintptr_t)(void*)rt_copy_term_term))
            + x86("add", "rsp", 16L)
            + x86("test", "eax", "eax")
            + x86("je", "ω")
            + x86("jmp", "γ")
            + x86("label", _.lbl_β)
            + x86("jmp", "ω"))
        + IF(_.op_sval && (!strcmp(_.op_sval,"atom_length")   || !strcmp(_.op_sval,"upcase_atom")    || !strcmp(_.op_sval,"downcase_atom")
           || !strcmp(_.op_sval,"string_length") || !strcmp(_.op_sval,"string_upper")   || !strcmp(_.op_sval,"string_lower")
           || !strcmp(_.op_sval,"atom_string")   || !strcmp(_.op_sval,"string_to_atom") || !strcmp(_.op_sval,"copy_term"))
           && _.op_parts_n >= 2 && !(!strcmp(_.op_sval,"copy_term") && (_.op_parts_tag[0] == (int)IR_STRUCT || _.op_parts_tag[0] == (int)IR_ARITH)),
              x86("label", _.lbl_α)
            + x86("mov32", "edi", (long)_.op_parts_tag[0])
            + x86("movabs", "rsi", (unsigned long long)(uint64_t)_.op_parts_ival[0])
            + IF(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0], x86("lea", "rdx", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0]))
            + IF(!(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0]), x86("xor", "edx", "edx"))
            + x86("mov32", "ecx", (long)_.op_parts_tag[1])
            + x86("movabs", "r8", (unsigned long long)(uint64_t)_.op_parts_ival[1])
            + IF(_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_str[1], x86("lea", "r9", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1]))
            + IF(!(_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_str[1]), x86("xor", "r9d", "r9d"))
            + x86("call", _.op_call_sym, (unsigned long long)(uintptr_t)_.op_call_fp)
            + x86("test", "eax", "eax")
            + x86("je", "ω")
            + x86("jmp", "γ")
            + x86("label", _.lbl_β)
            + x86("jmp", "ω"))
        + IF(_.op_sval && (!strcmp(_.op_sval,"number_string") || !strcmp(_.op_sval,"atom_number")) && _.op_parts_n >= 2,
              x86("label", _.lbl_α)
            + x86("sub", "rsp", 16L)
            + x86("mov32", "edi", (long)(!strcmp(_.op_sval,"number_string") ? 1 : 0))
            + x86("mov32", "esi", (long)_.op_parts_tag[0])
            + x86("movabs", "rdx", (unsigned long long)(uint64_t)_.op_parts_ival[0])
            + IF(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0], x86("lea", "rcx", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0]))
            + IF(!(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0]), x86("xor", "ecx", "ecx"))
            + x86("mov32", "r8d", (long)_.op_parts_tag[1])
            + x86("movabs", "r9", (unsigned long long)(uint64_t)_.op_parts_ival[1])
            + IF(_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_str[1], x86("lea", "rax", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1]))
            + IF(!(_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_str[1]), x86("xor", "eax", "eax"))
            + x86("mov", RSP(0), "rax")
            + x86("call", "rt_number_string_pair", (unsigned long long)(uintptr_t)(void*)rt_number_string_pair)
            + x86("add", "rsp", 16L)
            + x86("test", "eax", "eax")
            + x86("je", "ω")
            + x86("jmp", "γ")
            + x86("label", _.lbl_β)
            + x86("jmp", "ω"))
        + IF(_.op_sval && (!strcmp(_.op_sval,"atom_concat") || !strcmp(_.op_sval,"string_concat")) && _.op_parts_n >= 3,
              x86("label", _.lbl_α)
            + x86("sub", "rsp", 32L)
            + x86("mov32", "edi", (long)_.op_parts_tag[0])
            + x86("movabs", "rsi", (unsigned long long)(uint64_t)_.op_parts_ival[0])
            + IF(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0], x86("lea", "rdx", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0]))
            + IF(!(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0]), x86("xor", "edx", "edx"))
            + x86("mov32", "ecx", (long)_.op_parts_tag[1])
            + x86("movabs", "r8", (unsigned long long)(uint64_t)_.op_parts_ival[1])
            + IF(_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_str[1], x86("lea", "r9", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1]))
            + IF(!(_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_str[1]), x86("xor", "r9d", "r9d"))
            + x86("stk32", 0L, (long)_.op_parts_tag[2])
            + x86("movabs", "rax", (unsigned long long)(uint64_t)_.op_parts_ival[2])
            + x86("mov", RSP(8), "rax")
            + IF(_.op_parts_tag[2] == (int)IR_ATOM && _.op_parts_str[2], x86("lea", "rax", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[2], _.op_parts_lbl[2]))
            + IF(!(_.op_parts_tag[2] == (int)IR_ATOM && _.op_parts_str[2]), x86("xor", "eax", "eax"))
            + x86("mov", RSP(16), "rax")
            + x86("call", "rt_atom_concat", (unsigned long long)(uintptr_t)(void*)rt_atom_concat)
            + x86("add", "rsp", 32L)
            + x86("test", "eax", "eax")
            + x86("je", "ω")
            + x86("jmp", "γ")
            + x86("label", _.lbl_β)
            + x86("jmp", "ω"))
        + IF(_.op_sval && (!strcmp(_.op_sval,"atom_chars") || !strcmp(_.op_sval,"atom_codes") || !strcmp(_.op_sval,"string_chars") || !strcmp(_.op_sval,"string_codes")) && _.op_parts_n >= 2,
              x86("label", _.lbl_α)
            + x86("sub", "rsp", 16L)
            + IF(_.op_parts_tag[1] == (int)IR_STRUCT,
                  emit_build_compound_term((const IR_t *)(intptr_t)_.op_parts_ival[9])
                + x86("mov", "r8", "rax")
                + x86("mov32", "edi", (long)(!strcmp(_.op_sval,"atom_codes") || !strcmp(_.op_sval,"string_codes") ? 1 : 0))
                + x86("mov32", "esi", (long)_.op_parts_tag[0])
                + x86("movabs", "rdx", (unsigned long long)(uint64_t)_.op_parts_ival[0])
                + IF(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0], x86("lea", "rcx", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0]))
                + IF(!(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0]), x86("xor", "ecx", "ecx"))
                + x86("call", "rt_atom_chars_codes_term", (unsigned long long)(uintptr_t)(void*)rt_atom_chars_codes_term))
            + IF(_.op_parts_tag[1] != (int)IR_STRUCT,
                  x86("mov32", "edi", (long)(!strcmp(_.op_sval,"atom_codes") || !strcmp(_.op_sval,"string_codes") ? 1 : 0))
                + x86("mov32", "esi", (long)_.op_parts_tag[0])
                + x86("movabs", "rdx", (unsigned long long)(uint64_t)_.op_parts_ival[0])
                + IF(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0], x86("lea", "rcx", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0]))
                + IF(!(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0]), x86("xor", "ecx", "ecx"))
                + x86("mov32", "r8d", (long)_.op_parts_tag[1])
                + x86("movabs", "r9", (unsigned long long)(uint64_t)_.op_parts_ival[1])
                + IF(_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_str[1], x86("lea", "rax", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1]))
                + IF(!(_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_str[1]), x86("xor", "eax", "eax"))
                + x86("mov", RSP(0), "rax")
                + x86("call", "rt_atom_chars_codes", (unsigned long long)(uintptr_t)(void*)rt_atom_chars_codes))
            + x86("add", "rsp", 16L)
            + x86("test", "eax", "eax")
            + x86("je", "ω")
            + x86("jmp", "γ")
            + x86("label", _.lbl_β)
            + x86("jmp", "ω"))
        + IF(_.op_sval && !strcmp(_.op_sval,"char_type") && _.op_ival == 2 && _.op_parts_n >= 2,
              x86("label", _.lbl_α)
            + x86("sub", "rsp", 16L)
            + x86("mov32", "edi", (long)_.op_parts_tag[0])
            + x86("movabs", "rsi", (unsigned long long)(uint64_t)_.op_parts_ival[0])
            + IF(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0], x86("lea", "rdx", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0]))
            + IF(!(_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_str[0]), x86("xor", "edx", "edx"))
            + IF(_.op_parts_str[1], x86("lea", "rcx", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1]))
            + IF(!_.op_parts_str[1], x86("xor", "ecx", "ecx"))
            + x86("mov32", "r8d", (long)(((_.op_parts_tag[1] == (int)IR_STRUCT || _.op_parts_tag[1] == (int)IR_ARITH) && _.op_parts_str[1]) ? 1 : 0))
            + x86("mov32", "r9d", (long)_.op_parts_tag[3])
            + x86("movabs", "rax", (unsigned long long)(uint64_t)_.op_parts_ival[3])
            + x86("mov", RSP(0), "rax")
            + IF(_.op_parts_tag[3] == (int)IR_ATOM && _.op_parts_str[3], x86("lea", "rax", "[rip + __]", (unsigned long long)(uintptr_t)_.op_parts_str[3], _.op_parts_lbl[3]))
            + IF(!(_.op_parts_tag[3] == (int)IR_ATOM && _.op_parts_str[3]), x86("xor", "eax", "eax"))
            + x86("mov", RSP(8), "rax")
            + x86("call", "rt_char_type", (unsigned long long)(uintptr_t)(void*)rt_char_type)
            + x86("add", "rsp", 16L)
            + x86("test", "eax", "eax")
            + x86("je", "ω")
            + x86("jmp", "γ")
            + x86("label", _.lbl_β)
            + x86("jmp", "ω"));
    return std::string();
}
