#include "bb_common.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_list() {
    if (!(_.op_sval &&
          (((strcmp(_.op_sval, "atomic_list_concat") == 0 || strcmp(_.op_sval, "concat_atom") == 0) && (_.op_ival == 2 || _.op_ival == 3) && _.op_parts_n >= _.op_ival)
        || ((strcmp(_.op_sval, "sort") == 0 || strcmp(_.op_sval, "msort") == 0) && _.op_parts_n >= 2))))
        return std::string();
    return (strcmp(_.op_sval, "atomic_list_concat") == 0 || strcmp(_.op_sval, "concat_atom") == 0)
         ? x86("label", _.lbl_α)
             + x86("sub", "rsp", (long)16)
             + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[8])
             + x86("mov", "rdi", "rax")
             + x86("mov", "esi", (long)_.op_ival)
             + x86("mov", "edx", (long)(_.op_ival == 3 ? _.op_parts_tag[1] : 0))
             + x86("mov", "rcx", (long)(_.op_ival == 3 ? _.op_parts_ival[1] : 0))
             + (_.op_ival == 3 && _.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_lbl[1]
                  ? x86("lea", "r8", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                  : x86("xor", "r8d", "r8d"))
             + x86("mov", "r9d", (long)_.op_parts_tag[_.op_ival == 3 ? 2 : 1])
             + x86("mov", "rax", (long)_.op_parts_ival[_.op_ival == 3 ? 2 : 1])
             + x86("mov", "[rsp + 0]", "rax")
             + (_.op_parts_tag[_.op_ival == 3 ? 2 : 1] == (int)IR_ATOM && _.op_parts_lbl[_.op_ival == 3 ? 2 : 1]
                  ? x86("lea", "rax", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[_.op_ival == 3 ? 2 : 1], _.op_parts_lbl[_.op_ival == 3 ? 2 : 1])
                      + x86("mov", "[rsp + 8]", "rax")
                  : x86("mov", "qword ptr [rsp + 8]", "0"))
             + x86("call", "rt_atomic_list_concat_term", (uint64_t)(uintptr_t)(void*)rt_atomic_list_concat_term)
             + x86("add", "rsp", (long)16)
             + x86("test", "eax", "eax")
             + x86("je", "ω")
             + x86("jmp", "γ")
             + x86("def", "β")
             + x86("jmp", "ω")
         : (_.op_parts_tag[0] == (int)IR_STRUCT)
         ? x86("label", _.lbl_α)
             + x86("sub", "rsp", (long)16)
             + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[8])
             + x86("mov", "rsi", "rax")
             + x86("mov", "edi", (long)(strcmp(_.op_sval, "msort") == 0 ? 1 : 0))
             + x86("mov", "edx", (long)_.op_parts_tag[1])
             + x86("mov", "rcx", (long)_.op_parts_ival[1])
             + (_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_lbl[1]
                  ? x86("lea", "r8", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                  : x86("xor", "r8d", "r8d"))
             + x86("call", "rt_sort_msort_term", (uint64_t)(uintptr_t)(void*)rt_sort_msort_term)
             + x86("add", "rsp", (long)16)
             + x86("test", "eax", "eax")
             + x86("je", "ω")
             + x86("jmp", "γ")
             + x86("def", "β")
             + x86("jmp", "ω")
         : x86("label", _.lbl_α)
             + x86("sub", "rsp", (long)16)
             + x86("mov", "edi", (long)(strcmp(_.op_sval, "msort") == 0 ? 1 : 0))
             + x86("mov", "esi", (long)_.op_parts_tag[0])
             + x86("mov", "rdx", (long)_.op_parts_ival[0])
             + (_.op_parts_tag[0] == (int)IR_ATOM && _.op_parts_lbl[0]
                  ? x86("lea", "rcx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0])
                  : x86("xor", "ecx", "ecx"))
             + x86("mov", "r8d", (long)_.op_parts_tag[1])
             + x86("mov", "r9", (long)_.op_parts_ival[1])
             + (_.op_parts_tag[1] == (int)IR_ATOM && _.op_parts_lbl[1]
                  ? x86("lea", "rax", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                  : x86("xor", "eax", "eax"))
             + x86("mov", "qword ptr [rsp + 0]", "rax")
             + x86("call", "rt_sort_msort", (uint64_t)(uintptr_t)(void*)rt_sort_msort)
             + x86("add", "rsp", (long)16)
             + x86("test", "eax", "eax")
             + x86("je", "ω")
             + x86("jmp", "γ")
             + x86("def", "β")
             + x86("jmp", "ω");
}
