/* bb_pat_rem.cpp — BB template for REM. x86() self-encoding (template-revamp, 2026-06-01, Opus 4.8).
   REM matches the REST of the subject (SPITBOL Manual ch.18: RTAB(0) ≡ REM): δ ← Δ then succeed; β has no
   alternative → jmp ω. REG-2 registers: cursor δ=R14d, length Δ=R15d (established by BB_MATCH α per REG-0).
   x86 arm: ONE return, pure x86() concat, NO template locals, NO bb_bin_t — the medium (BINARY byte stream
   vs GAS text) is invisible; the byte map is regenerated by the x86_asm.h encoders from this one description. */
#include <string>
#include "emit_str.h"
extern "C" {
#include "bb_template_common.h"
#include "emit.h"
}
#include "x86_asm.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static std::string bb_pat_rem_str() {
    int nid = _.nid; (void)nid;
    if (PLATFORM_X86)
        return IF(MEDIUM_TEXT,
                   s_1asm(std::string(_.lbl_α) + ":")
                 + s_comment("# BOX REM()  [REG-2 δ=r14 Δ=r15, x86() self-encoding]"))
             + x86("mov", "r14d", "r15d")
             + x86("jmp", PORT_GAMMA)
             + x86("def", PORT_BETA)
             + x86("jmp", PORT_OMEGA);
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
    if (PLATFORM_JVM) {
        int sid = 0;
        return jvm_class_hdr_str("rem")
             + jvm_init_ms_only_str("rem")
             + s_directive(".method public \316\261()Lbb/bb_box$Spec;")
             + s_directive(".limit stack 6")
             + s_directive(".limit locals 2")
             + s_1asm("aload_0")
             + s_2asm("getfield", "bb/bb_rem/ms Lbb/bb_box$MatchState;")
             + s_2asm("getfield", "bb/bb_box$MatchState/delta I")
             + s_1asm("istore_1")
             + s_1asm("aload_0")
             + s_2asm("getfield", "bb/bb_rem/ms Lbb/bb_box$MatchState;")
             + s_1asm("dup")
             + s_2asm("getfield", "bb/bb_box$MatchState/\317\211 I")
             + s_2asm("putfield", "bb/bb_box$MatchState/delta I")
             + s_2asm("new", "bb/bb_box$Spec")
             + s_1asm("dup")
             + s_1asm("iload_1")
             + s_1asm("aload_0")
             + s_2asm("getfield", "bb/bb_rem/ms Lbb/bb_box$MatchState;")
             + s_2asm("getfield", "bb/bb_box$MatchState/delta I")
             + s_1asm("iload_1")
             + s_1asm("isub")
             + s_2asm("invokespecial", "bb/bb_box$Spec/<init>(II)V")
             + s_1asm("areturn")
             + s_directive(".end method")
             + s_directive(".method public \316\262()Lbb/bb_box$Spec;")
             + s_directive(".limit stack 1")
             + s_directive(".limit locals 1")
             + s_1asm("aconst_null")
             + s_1asm("areturn")
             + s_directive(".end method");
    }
    if (PLATFORM_JS) {
        return emit_fmt("function make_pat_%d_%d(ms) { let self = { succ: null, fail: null,\n", _.op_ival, nid)
             + "\316\261() { const r = ms.sigma.slice(ms.delta, ms.omega); ms.delta = ms.omega; self.succ.\316\261(); return r; },\n"
             "\316\262() { self.fail.\316\261(); }\n}; return self; }\n";
    }
    if (PLATFORM_NET) {
        int sid = 0;
        return net_class_hdr_str(sid, nid)
             + net_ctor_none_str(sid, nid)
             + net_α_hdr_str()
             + s_2asm(".maxstack", "3")
             + s_2asm(".locals", "init (valuetype [boxes]Snobol4.Runtime.Boxes.Spec V_r)")
             + net_cursor_load_str()
             + s_1asm("ldarg.1")
             + net_ms_length_str()
             + net_spec_of_str()
             + s_1asm("stloc.0")
             + s_1asm("ldarg.1")
             + s_1asm("ldarg.1")
             + net_ms_length_str()
             + s_2asm("stfld", "int32 [boxes]Snobol4.Runtime.Boxes.MatchState::Cursor")
             + s_1asm("ldloc.0")
             + s_1asm("ret")
             + s_1asm("}")
             + net_β_hdr_str()
             + s_2asm(".maxstack", "1")
             + net_fail_ret_str()
             + s_1asm("}")
             + s_1asm("}")
             + s_1asm(emit_fmt("    newobj     instance void pat_%d_%d::.ctor()", sid, nid));
    }
    if (PLATFORM_WASM) { return std::string("          (call $bb_rem_new)\n"); }
    return std::string();
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
extern "C" void bb_pat_rem(void) { bb_emit_x86(bb_pat_rem_str()); }
