#include "bb_common.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_succ_plus() {
    if (strcmp(_.op_sval ? _.op_sval : "", "succ") == 0 && _.op_ival == 2 && _.op_parts_n >= 2)
        return x86("label", _.lbl_α)
             + x86("mov", "edi", (long)_.op_parts_tag[0])
             + x86("mov", "rsi", (long)_.op_parts_ival[0])
             + (_.op_parts_lbl[0] ? x86("lea", "rdx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0])
                                  : x86("xor", "edx", "edx"))
             + x86("mov", "ecx", (long)_.op_parts_tag[1])
             + x86("mov", "r8", (long)_.op_parts_ival[1])
             + (_.op_parts_lbl[1] ? x86("lea", "r9", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                                  : x86("xor", "r9d", "r9d"))
             + x86("call", "rt_succ", (uint64_t)(uintptr_t)(void*)rt_succ)
             + x86("test", "eax", "eax")
             + x86("je", "ω")
             + x86("jmp", "γ")
             + x86("def", "β")
             + x86("jmp", "ω");
    return (strcmp(_.op_sval ? _.op_sval : "", "plus") == 0 && _.op_ival == 3 && _.op_parts_n >= 3)
         ? x86("label", _.lbl_α)
             + x86("sub", "rsp", (long)32)
             + x86("mov", "edi", (long)_.op_parts_tag[0])
             + x86("mov", "rsi", (long)_.op_parts_ival[0])
             + (_.op_parts_lbl[0] ? x86("lea", "rdx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0])
                                  : x86("xor", "edx", "edx"))
             + x86("mov", "ecx", (long)_.op_parts_tag[1])
             + x86("mov", "r8", (long)_.op_parts_ival[1])
             + (_.op_parts_lbl[1] ? x86("lea", "r9", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                                  : x86("xor", "r9d", "r9d"))
             + x86("mov", RSP(0), (long)_.op_parts_tag[2])
             + x86("mov", "rax", (long)_.op_parts_ival[2])
             + x86("mov", RSP(8), "rax")
             + (_.op_parts_lbl[2] ? x86("lea", "rax", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[2], _.op_parts_lbl[2])
                                  + x86("mov", RSP(16), "rax")
                                  : x86("mov", RSP(16), (long)0))
             + x86("call", "rt_plus", (uint64_t)(uintptr_t)(void*)rt_plus)
             + x86("add", "rsp", (long)32)
             + x86("test", "eax", "eax")
             + x86("je", "ω")
             + x86("jmp", "γ")
             + x86("def", "β")
             + x86("jmp", "ω")
         : std::string();
}
