#pragma once
#include "emit_core.h"
#include "emit_globals.h"
#include "emit_ir.h"
#include <stdio.h>
void bb_pat_any    (void);
void bb_pat_notany (void);
void bb_pat_span   (void);
void bb_pat_break  (void);
void bb_pat_pos    (void);
void bb_pat_tab    (void);
void bb_pat_atp    (void);
void bb_pat_len    (void);
void bb_pat_rem    (void);
void bb_pat_arb    (void);
void bb_pat_abort  (void);
void bb_pat_fence  (void);
void bb_pat_alt    (void);
void bb_pat_cat    (void);
void bb_capture    (IR_t * pBB, int imm);
void bb_clause         (IR_t * pBB);
void bb_builtin (IR_t * pBB);
void bb_logicvar     (IR_t * pBB);
void bb_atom    (IR_t * pBB);
void bb_unify   (IR_t * pBB);
void bb_arith   (void);
void bb_conj     (void);
void bb_goal    (IR_t * pBB);
void bb_choice  (IR_t * pBB);
void bb_disj     (void);
void bb_ite     (void);
void bb_catch   (void);
void bb_cut     (void);
void bb_to         (IR_t * pBB);
void bb_every      (IR_t * pBB);
void bb_call       (IR_t * pBB);
void bb_program    (IR_t * pBB);
void bb_proc       (IR_t * pBB);
void bb_to_by      (IR_t * pBB);
void bb_binop_gen  (IR_t * pBB);
void bb_binop      (IR_t * pBB);
void bb_if         (IR_t * pBB);
void bb_initial    (IR_t * pBB);
void bb_case_store (IR_t * pBB);
void bb_case_gate  (IR_t * pBB);
void bb_stub       (IR_t * pBB);
void bb_lit        (void);
void bb_lit_scalar (IR_t * pBB);
void bb_var        (IR_t * pBB);
void bb_assign     (IR_t * pBB);
void bb_swap       (IR_t * pBB);
void bb_return     (IR_t * pBB);
void bb_unop       (void);
void bb_field_get  (IR_t * pBB);
void bb_field_set  (IR_t * pBB);
void bb_list_bang  (IR_t * pBB);
void bb_idx        (IR_t * pBB);
void bb_idx_set    (IR_t * pBB);
void bb_fail       (IR_t * pBB);
void bb_succeed    (void);
void bb_cset       (IR_t * pBB);
void bb_eps        (IR_t * pBB);
void bb_nfa_eps      (IR_t * pBB);
void bb_nfa_cap_open (IR_t * pBB);
void bb_nfa_cap_close(IR_t * pBB);
void bb_nfa_char     (IR_t * pBB);
void bb_nfa_accept   (IR_t * pBB);
void bb_nfa_any      (IR_t * pBB);
void bb_nfa_bol      (IR_t * pBB);
void bb_nfa_eol      (IR_t * pBB);
void bb_nfa_class    (IR_t * pBB);
void bb_arbno      (IR_t * pBB);
void bb_pat_defer  (void);
void bb_proc_gen (IR_t * pBB);
void bb_upto     (IR_t * pBB);
void bb_suspend  (IR_t * pBB);
void bb_seq      (IR_t * pBB);
void bb_gen_alt  (IR_t * pBB);
void bb_limit    (IR_t * pBB);
void bb_limit_begin (IR_t * pBB);
void bb_limit_inc   (IR_t * pBB);
void bb_limit_more  (IR_t * pBB);
void bb_alt      (IR_t * pBB);
void bb_iterate  (IR_t * pBB);
void bb_gen_scan (IR_t * pBB);
void bb_keyword  (IR_t * pBB);
