#include "bb_common.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_term_inspect() {
    if (!_.op_sval) return std::string();
    return (strcmp(_.op_sval, "functor") == 0 && _.op_ival == 3 && _.op_parts_n >= 3)
         ? (_.op_parts_tag[0] == (int)IR_STRUCT
                ? x86("label", _.lbl_α)
                    + x86("sub", "rsp", (long)16)
                    + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[8])
                    + x86("mov", "rdi", "rax")
                    + x86("mov", "esi", (long)_.op_parts_tag[1])
                    + x86("mov", "rdx", (long)_.op_parts_ival[1])
                    + (_.op_parts_lbl[1] ? x86("lea", "rcx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                                         : x86("xor", "ecx", "ecx"))
                    + x86("mov", "r8d", (long)_.op_parts_tag[2])
                    + x86("mov", "r9", (long)_.op_parts_ival[2])
                    + (_.op_parts_lbl[2] ? x86("lea", "rax", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[2], _.op_parts_lbl[2])
                                         : x86("xor", "eax", "eax"))
                    + x86("mov", "qword ptr [rsp + 0]", "rax")
                    + x86("call", "rt_functor_term", (uint64_t)(uintptr_t)(void*)rt_functor_term)
                    + x86("add", "rsp", (long)16)
                    + x86("test", "eax", "eax")
                    + x86("je", "ω")
                    + x86("jmp", "γ")
                    + x86("def", "β")
                    + x86("jmp", "ω")
                : x86("label", _.lbl_α)
                    + x86("sub", "rsp", (long)32)
                    + x86("mov", "edi", (long)_.op_parts_tag[0])
                    + x86("mov", "rsi", (long)_.op_parts_ival[0])
                    + (_.op_parts_lbl[0] ? x86("lea", "rdx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0])
                                         : x86("xor", "edx", "edx"))
                    + x86("mov", "ecx", (long)_.op_parts_tag[1])
                    + x86("mov", "r8", (long)_.op_parts_ival[1])
                    + (_.op_parts_lbl[1] ? x86("lea", "r9", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                                         : x86("xor", "r9d", "r9d"))
                    + x86("mov", RSP(0), (long)_.op_parts_tag[2])
                    + x86("mov", "rax", (long)_.op_parts_ival[2])
                    + x86("mov", "qword ptr [rsp + 8]", "rax")
                    + (_.op_parts_lbl[2] ? x86("lea", "rax", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[2], _.op_parts_lbl[2])
                                         : x86("xor", "eax", "eax"))
                    + x86("mov", "qword ptr [rsp + 16]", "rax")
                    + x86("call", "rt_functor", (uint64_t)(uintptr_t)(void*)rt_functor)
                    + x86("add", "rsp", (long)32)
                    + x86("test", "eax", "eax")
                    + x86("je", "ω")
                    + x86("jmp", "γ")
                    + x86("def", "β")
                    + x86("jmp", "ω"))
         : (strcmp(_.op_sval, "arg") == 0 && _.op_ival == 3 && _.op_parts_n >= 3)
         ? (_.op_parts_tag[1] == (int)IR_STRUCT
                ? x86("label", _.lbl_α)
                    + x86("sub", "rsp", (long)16)
                    + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[9])
                    + x86("mov", "rcx", "rax")
                    + x86("mov", "edi", (long)_.op_parts_tag[0])
                    + x86("mov", "rsi", (long)_.op_parts_ival[0])
                    + (_.op_parts_lbl[0] ? x86("lea", "rdx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0])
                                         : x86("xor", "edx", "edx"))
                    + x86("mov", "r8d", (long)_.op_parts_tag[2])
                    + x86("mov", "r9", (long)_.op_parts_ival[2])
                    + (_.op_parts_lbl[2] ? x86("lea", "rax", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[2], _.op_parts_lbl[2])
                                         : x86("xor", "eax", "eax"))
                    + x86("mov", "qword ptr [rsp + 0]", "rax")
                    + x86("call", "rt_arg_term", (uint64_t)(uintptr_t)(void*)rt_arg_term)
                    + x86("add", "rsp", (long)16)
                    + x86("test", "eax", "eax")
                    + x86("je", "ω")
                    + x86("jmp", "γ")
                    + x86("def", "β")
                    + x86("jmp", "ω")
                : x86("label", _.lbl_α)
                    + x86("sub", "rsp", (long)32)
                    + x86("mov", "edi", (long)_.op_parts_tag[0])
                    + x86("mov", "rsi", (long)_.op_parts_ival[0])
                    + (_.op_parts_lbl[0] ? x86("lea", "rdx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0])
                                         : x86("xor", "edx", "edx"))
                    + x86("mov", "ecx", (long)_.op_parts_tag[1])
                    + x86("mov", "r8", (long)_.op_parts_ival[1])
                    + (_.op_parts_lbl[1] ? x86("lea", "r9", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                                         : x86("xor", "r9d", "r9d"))
                    + x86("mov", RSP(0), (long)_.op_parts_tag[2])
                    + x86("mov", "rax", (long)_.op_parts_ival[2])
                    + x86("mov", "qword ptr [rsp + 8]", "rax")
                    + (_.op_parts_lbl[2] ? x86("lea", "rax", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[2], _.op_parts_lbl[2])
                                         : x86("xor", "eax", "eax"))
                    + x86("mov", "qword ptr [rsp + 16]", "rax")
                    + x86("call", "rt_arg", (uint64_t)(uintptr_t)(void*)rt_arg)
                    + x86("add", "rsp", (long)32)
                    + x86("test", "eax", "eax")
                    + x86("je", "ω")
                    + x86("jmp", "γ")
                    + x86("def", "β")
                    + x86("jmp", "ω"))
         : (strcmp(_.op_sval, "=..") == 0 && _.op_ival == 2 && _.op_parts_n >= 2)
         ? ((_.op_parts_tag[0] == (int)IR_STRUCT && _.op_parts_tag[1] == (int)IR_STRUCT)
                ? x86("label", _.lbl_α)
                    + x86("sub", "rsp", (long)16)
                    + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[8])
                    + x86("mov", "qword ptr [rsp + 0]", "rax")
                    + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[9])
                    + x86("mov", "rsi", "rax")
                    + x86("mov", "rdi", "qword ptr [rsp + 0]")
                    + x86("call", "rt_univ_term_term", (uint64_t)(uintptr_t)(void*)rt_univ_term_term)
                    + x86("add", "rsp", (long)16)
                    + x86("test", "eax", "eax")
                    + x86("je", "ω")
                    + x86("jmp", "γ")
                    + x86("def", "β")
                    + x86("jmp", "ω")
                : _.op_parts_tag[0] == (int)IR_STRUCT
                ? x86("label", _.lbl_α)
                    + x86("sub", "rsp", (long)8)
                    + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[8])
                    + x86("mov", "rdi", "rax")
                    + x86("mov", "esi", (long)_.op_parts_tag[1])
                    + x86("mov", "rdx", (long)_.op_parts_ival[1])
                    + (_.op_parts_lbl[1] ? x86("lea", "rcx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                                         : x86("xor", "ecx", "ecx"))
                    + x86("call", "rt_univ_term", (uint64_t)(uintptr_t)(void*)rt_univ_term)
                    + x86("add", "rsp", (long)8)
                    + x86("test", "eax", "eax")
                    + x86("je", "ω")
                    + x86("jmp", "γ")
                    + x86("def", "β")
                    + x86("jmp", "ω")
                : _.op_parts_tag[1] == (int)IR_STRUCT
                ? x86("label", _.lbl_α)
                    + x86("sub", "rsp", (long)8)
                    + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[9])
                    + x86("mov", "rcx", "rax")
                    + x86("mov", "edi", (long)_.op_parts_tag[0])
                    + x86("mov", "rsi", (long)_.op_parts_ival[0])
                    + (_.op_parts_lbl[0] ? x86("lea", "rdx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0])
                                         : x86("xor", "edx", "edx"))
                    + x86("call", "rt_univ_term_list", (uint64_t)(uintptr_t)(void*)rt_univ_term_list)
                    + x86("add", "rsp", (long)8)
                    + x86("test", "eax", "eax")
                    + x86("je", "ω")
                    + x86("jmp", "γ")
                    + x86("def", "β")
                    + x86("jmp", "ω")
                : x86("label", _.lbl_α)
                    + x86("sub", "rsp", (long)8)
                    + x86("mov", "edi", (long)_.op_parts_tag[0])
                    + x86("mov", "rsi", (long)_.op_parts_ival[0])
                    + (_.op_parts_lbl[0] ? x86("lea", "rdx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0])
                                         : x86("xor", "edx", "edx"))
                    + x86("mov", "ecx", (long)_.op_parts_tag[1])
                    + x86("mov", "r8", (long)_.op_parts_ival[1])
                    + (_.op_parts_lbl[1] ? x86("lea", "r9", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                                         : x86("xor", "r9d", "r9d"))
                    + x86("call", "rt_univ", (uint64_t)(uintptr_t)(void*)rt_univ)
                    + x86("add", "rsp", (long)8)
                    + x86("test", "eax", "eax")
                    + x86("je", "ω")
                    + x86("jmp", "γ")
                    + x86("def", "β")
                    + x86("jmp", "ω"))
         : std::string();
}
