#include "bb_common.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
std::string bb_term_io() {
    if (!(_.op_sval &&
          ((strcmp(_.op_sval, "numbervars") == 0 && _.op_ival == 3 && _.op_parts_n >= 3)
        || ((strcmp(_.op_sval, "term_to_atom") == 0 || strcmp(_.op_sval, "term_string") == 0) && _.op_parts_n >= 2)
        || (strcmp(_.op_sval, "format") == 0 && _.op_parts_n >= 1 && (_.op_ival == 1 || _.op_ival == 2)))))
        return std::string();
    return (strcmp(_.op_sval, "numbervars") == 0)
         ? x86("label", _.lbl_α)
             + x86("sub", "rsp", (long)8)
             + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[8])
             + x86("mov", "rdi", "rax")
             + x86("mov", "rsi", (long)_.op_parts_ival[1])
             + x86("mov", "edx", (long)_.op_parts_tag[2])
             + x86("mov", "rcx", (long)_.op_parts_ival[2])
             + (_.op_parts_lbl[2] ? x86("lea", "r8", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[2], _.op_parts_lbl[2])
                                  : x86("xor", "r8d", "r8d"))
             + x86("call", "rt_numbervars_term", (uint64_t)(uintptr_t)(void*)rt_numbervars_term)
             + x86("add", "rsp", (long)8)
             + x86("test", "eax", "eax")
             + x86("je", "ω")
             + x86("jmp", "γ")
             + x86("def", "β")
             + x86("jmp", "ω")
         : (strcmp(_.op_sval, "term_to_atom") == 0 || strcmp(_.op_sval, "term_string") == 0)
         ? x86("label", _.lbl_α)
             + x86("sub", "rsp", (long)16)
             + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[8])
             + x86("mov", "rdi", "rax")
             + x86("mov", "esi", (long)_.op_parts_tag[1])
             + x86("mov", "rdx", (long)_.op_parts_ival[1])
             + (_.op_parts_lbl[1] ? x86("lea", "rcx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                                  : x86("xor", "ecx", "ecx"))
             + x86("call", "rt_term_to_atom_term", (uint64_t)(uintptr_t)(void*)rt_term_to_atom_term)
             + x86("add", "rsp", (long)16)
             + x86("test", "eax", "eax")
             + x86("je", "ω")
             + x86("jmp", "γ")
             + x86("def", "β")
             + x86("jmp", "ω")
         : (_.op_parts_n >= 2 && _.op_parts_tag[1] == (int)IR_STRUCT)
         ? x86("label", _.lbl_α)
             + x86("sub", "rsp", (long)16)
             + emit_build_compound_term((IR_t *)(intptr_t)_.op_parts_ival[9])
             + x86("mov", "r8", "rax")
             + x86("mov", "edi", (long)_.op_ival)
             + x86("mov", "esi", (long)_.op_parts_tag[0])
             + x86("mov", "rdx", (long)_.op_parts_ival[0])
             + (_.op_parts_lbl[0] ? x86("lea", "rcx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0])
                                  : x86("xor", "ecx", "ecx"))
             + x86("call", "rt_format_term", (uint64_t)(uintptr_t)(void*)rt_format_term)
             + x86("add", "rsp", (long)16)
             + x86("test", "eax", "eax")
             + x86("je", "ω")
             + x86("jmp", "γ")
             + x86("def", "β")
             + x86("jmp", "ω")
         : x86("label", _.lbl_α)
             + x86("sub", "rsp", (long)16)
             + x86("mov", "edi", (long)_.op_ival)
             + x86("mov", "esi", (long)_.op_parts_tag[0])
             + x86("mov", "rdx", (long)_.op_parts_ival[0])
             + (_.op_parts_lbl[0] ? x86("lea", "rcx", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[0], _.op_parts_lbl[0])
                                  : x86("xor", "ecx", "ecx"))
             + x86("mov", "r8d", (long)(_.op_parts_n >= 2 ? _.op_parts_tag[1] : 0))
             + x86("mov", "r9", (long)(_.op_parts_n >= 2 ? _.op_parts_ival[1] : 0))
             + ((_.op_parts_n >= 2 && _.op_parts_lbl[1])
                  ? x86("lea", "rax", "[rip + __]", (uint64_t)(uintptr_t)_.op_parts_str[1], _.op_parts_lbl[1])
                      + x86("mov", "[rsp + 0]", "rax")
                  : x86("mov", "qword ptr [rsp + 0]", "0"))
             + x86("call", "rt_format", (uint64_t)(uintptr_t)(void*)rt_format)
             + x86("add", "rsp", (long)16)
             + x86("test", "eax", "eax")
             + x86("je", "ω")
             + x86("jmp", "γ")
             + x86("def", "β")
             + x86("jmp", "ω");
}
