#ifndef G_LOWER_H
#define G_LOWER_H
#include "ct_vec.h"
#include "lower.h"
typedef struct { const char * name; IR_t * landing; } bb_label_entry_t;
typedef struct { cv_t v, ix; } gname_set_t;
typedef struct { const IR_t ** nd; const char ** src; int * line; int n; int max; } lc_bb_src_t;
typedef struct { const IR_t * k; int v; } bb_src_slot_t;
typedef struct { bb_src_slot_t * s; int cap; int n; long runs; } lc_bb_src_ix_t;
typedef struct { const char * name; int k1; } gva_hx_t;
typedef struct {
    cv_t bb_cv;
    const char ** decl_dyn_name;
    int * decl_dyn_arity;
    int decl_dyn_n;
    int decl_dyn_cap;
    const char ** decl_other_name;
    int * decl_other_arity;
    int decl_other_n;
    int decl_other_cap;
    int fresh_next;
    long trace_stmtno;
    int seed_var_base;
    int fence_on;
    char * var_name_cache[1024];
    cv_t param_name_cache;
} g_lower_pl_t;
typedef struct {
    lc_vec bb_labels;
    gname_set_t gnames;
    gname_set_t icn_gnames;
    gname_set_t rbi_names;
    const char ** global_names;
    int global_count;
    lc_bb_src_t bb_src;
    lc_bb_src_ix_t bb_src_ix;
    int bb_src_of_sd;
    int bb_src_reset_sr;
} g_lower_lc_t;
typedef struct {
    int sno_sub_val_on_v;
    int sno_scan_tmp_scv_n;
    int sx_binop_scl_n;
    int sx_call_named_c2bb;
    int sno_ident_inline_on_on;
    int sno_goto_special_chain_sp;
    int sno_goto_computed_target_igt_n;
    int sno_goto_computed_target_bn;
    int sno_goto_direct_target_dgt_n;
    int sno_const_feature_cs;
    int sno_const_t1_on_t;
    int sno_t4_on_v;
    int fc_tail_walk_dtl;
    int sno_cap_name_strict_v;
    int sno_rtseq_resume_v;
    int sno_defer_resume_v;
    int sno_seq_tail_v;
    int sno_kw_nest_ok_nn;
    int sno_pat_inline_ok_ia;
    int sno_pat_node_cn;
    int sno_pat_node_ci;
    int sno_pat_node_ck;
    int sno_pat_node_ec;
    int sno_is_pattern_rhs_kdepth;
    int sno_mkpat_here_on;
    int sno_patsalt_on_v;
    int sno_patname_salt_on_v;
    int sno_lower_match_preord;
    int sno_lower_match_snapctr;
    int sno_expr_thunks_build_xd;
    cv_t exprs;
    int expr_salt;
    cv_t pats;
    int uses_stmtkw;
    int traces_a_label;
    int uses_code;
    int calls_code;
    cv_t predef;
    cv_t tdef;
    cv_t multiproto;
    cv_t proto_fn;
    cv_t proto_enc;
    int in_patproc;
    int pat_match_ctx;
    int seal_enabled;
    cv_t seal;
    cv_t pro;
    cv_t t4;
    int t4_unsafe;
    int in_arbno;
    cv_t scd;
    const tree_t * prescan_top;
    int expr_define_seen;
} g_lower_sno_t;
typedef struct {
    lc_vec fill_pnames_ps;
    const tree_t * icn_progname_as_global_done_prog;
    int icn_progname_as_global_used;
    lc_vec lower_icon_proc_pnv;
    lc_vec lower_icon_proc_lnv;
    lc_vec lower_icon_proc_gnv;
    lc_vec lower_icon_stage2_excl;
    lc_vec lower_icon_stage2_impl;
    lc_vec synth_excl;
    lc_vec reassigned;
    const tree_t * reassigned_prog;
    lc_vec breassigned;
    const tree_t * breassigned_prog;
    const char * icn_record_names[512];
    int icn_record_name_count;
} g_lower_icn_t;
typedef struct { int pas_vptmp_var_vptmp_n; int pas_vpref_var_vpref_n; lc_vec proc_list; lc_vec proc_parent; int has_nesting; } g_lower_pas_t;
typedef struct {
    int bc_mon_m;
    int dg_mon_m;
    int cf_spine_on_s;
    const char ** gva_names;
    int gva_n;
    int gva_max;
    gva_hx_t * gva_hx;
    uint32_t gva_hx_cap;
    const char ** gva_io_refused;
    int gva_io_refused_n;
    int gva_io_refused_max;
    const char ** gva_kw_refused;
    int gva_kw_refused_n;
    int gva_kw_refused_max;
    int gva_kw_seeded;
    int gva_sn4_family;
    int gva_trace_demote;
    const char ** proc_slot_names;
    int proc_slot_n;
    int proc_slot_max;
    int scc_taint;
    int scc_taint_inherited;
} g_lower_opt_t;
typedef struct { g_lower_pl_t pl; g_lower_lc_t lc; g_lower_sno_t sno; g_lower_icn_t icn; g_lower_pas_t pas; g_lower_opt_t opt; } g_lower_t;
extern g_lower_t g_lower;
#endif
