#ifndef LOWER_PASCAL_TREE_H
#define LOWER_PASCAL_TREE_H
typedef struct PNodeList { tree_t **items; int count; int cap; } PNodeList;
#define PAS_CA_NOSTR 2
#define PAS_FIELD_IDX_MARK 0x46494458
#define PAS_FIELD_MAX 128
#define PAS_LOCAL_MAX 64
#define PAS_NEST_MAX 16
#define PAS_NEST_MAX_PV 16
#define PAS_REC_MAX 512
#define PAS_SEM_PATH_MAX 64
#define PAS_WITH_MAX 8
struct pas_pend_frame;
typedef union { tree_t *node; PNodeList *list; char *str; long long ival; double dval; } pval;
typedef struct { const char *name; const char *sig; const char *owner; const char *alias; int depth, rid, formal, uid, fld; } PasDef;
typedef struct { const char *name; PNodeList *params; const char *sig; } PasFwd;
struct pas_vt { int state; char *name; tree_t *node; tree_t *tagexpr; long long mask; int tagslot; int tagfi; long long fmask[PAS_FIELD_MAX]; unsigned char fhas[PAS_FIELD_MAX]; };
struct pas_pend_frame {
    char *fields[PAS_FIELD_MAX];
    char *fldptrto[PAS_FIELD_MAX];
    char *fldenum[PAS_FIELD_MAX];
    char *fldrec[PAS_FIELD_MAX];
    char *fldtypename[PAS_FIELD_MAX];
    int fldca[PAS_FIELD_MAX];
    long long fldca_lo[PAS_FIELD_MAX];
    long long fldca_hi[PAS_FIELD_MAX];
    int fldchar[PAS_FIELD_MAX];
    int fldfile[PAS_FIELD_MAX];
    int fldna[PAS_FIELD_MAX];
    long long fldna_lo[PAS_FIELD_MAX];
    long long fldna_hi[PAS_FIELD_MAX];
    long long fldov[PAS_FIELD_MAX];
    int nf;
};
typedef struct { const tree_t *n; int i; } pas_sem_step_t;
typedef struct {
    PNodeList pascal_procs;
    int pas_recbody_depth;
    struct {
        PasDef *defs;
        int n, cap;
        int *marks;
        int depth, mcap;
        PasFwd *fwd;
        int nfwd, fcap;
        PasDef *pend;
        int npend, cpend;
        PasDef *fsig;
        int nfsig, cfsig;
        PasDef *cand;
        int ncand, ccand;
        int nrid, npf, nuid;
        PasDef *lab;
        int nlab, clab;
        PasDef *apl;
        int napl, capl;
        struct pas_pend_frame *pnest;
        int npnest, cpnest;
        int anonseq;
    } pas_scope;
    int pas_iso_errors;
    int pas_seen_mode_directive;
    int pas_mode_iso;
    int pas_min_enum_size;
    int pas_pack_set_size;
    int pas_range_check_on;
    int pas_align_mac68k;
    int pas_pack_records;
    int pas_zerobased_strings;
    int pas_codepage;
    long long pas_pend_sub_low;
    long long pas_pend_esz;
    struct { char *name; long long bytes; } *pas_tsz;
    int pas_ntsz;
    int pas_tszcap;
    struct pas_vt **pas_vt;
    int pas_nvt;
    int pas_vtcap;
    int pas_pend_isbool;
    int pas_pend_istfile;
    struct { const char *name; int nvp; int vp[16]; int nrp; int rp[16]; int nsp; int sp[16]; } pas_funcs[256];
    int pas_nfunc;
    struct { const char *name; int nvp; int vp[16]; int nrp; int rp[16]; int nsp; int sp[16]; } pas_procs[256];
    int pas_nproc;
    struct { char *name; unsigned long long camask; long long lo[64]; } pas_caparm[256];
    int pas_ncaparm;
    struct { char *name; long long val; int isenum; int uid; } pas_consts[256];
    int pas_nconst;
    struct { char *name; double val; } pas_rconsts[64];
    int pas_nrconst;
    struct { char *name; char *val; } pas_sconsts[64];
    int pas_nsconst;
    int pas_level;
    struct { char *name; long long high; long long ncols; int is_param; int is_local; long long low; int isbool; } pas_arrays[256];
    int pas_narray;
    long long pas_pend_arr_ncols;
    struct { char *name; } pas_assigned[512];
    int pas_nassigned;
    struct { char *name; long long high; int ndim2; long long ncols; int ischar; long long lo; int isbool; } pas_arrtypes[64];
    int pas_narrtype;
    int pas_pend_arr_ischar;
    int pas_pend_arr_wrap;
    struct { char *name; long long high; long long min_size; } pas_enumtypes[64];
    int pas_nenum;
    long long pas_pend_enum_max;
    long long pas_pend_set_hi;
    struct { char *tname; char *names; } pas_enumnames[64];
    int pas_nenumname;
    char pas_pend_enum_names[512];
    struct { char *aname; char *etype; } pas_enumarrs[128];
    int pas_nenumarr;
    struct { char *name; long long low; long long high; int isenum; } pas_subtypes[64];
    int pas_nsubtype;
    long long pas_pend_sub_high;
    int pas_last_const_enum;
    struct { char *name; long long low; long long high; int uid; } pas_subvars[256];
    int pas_nsubvar;
    struct { char *name; char *target; } pas_typealias[64];
    int pas_ntypealias;
    int pas_ldepth;
    struct { char *vname; char *tname; int is_global; int uid; } pas_scalarvartype[512];
    int pas_nscalarvartype;
    struct { char *name; long long low; long long high; int ischar; } pas_tfcomp[128];
    int pas_ntfcomp;
    long long pas_pend_frng_lo;
    long long pas_pend_frng_hi;
    int pas_pend_frng_ischar;
    struct {
        char *tname;
        char *fields[PAS_FIELD_MAX];
        char *fldptrto[PAS_FIELD_MAX];
        char *fldenum[PAS_FIELD_MAX];
        char *fldrec[PAS_FIELD_MAX];
        char *fldtypename[PAS_FIELD_MAX];
        int fldca[PAS_FIELD_MAX];
        int fldna[PAS_FIELD_MAX];
        long long fldna_lo[PAS_FIELD_MAX];
        long long fldna_hi[PAS_FIELD_MAX];
        long long fldca_lo[PAS_FIELD_MAX];
        long long fldca_hi[PAS_FIELD_MAX];
        int fldchar[PAS_FIELD_MAX];
        int fldfile[PAS_FIELD_MAX];
        long long fldov[PAS_FIELD_MAX];
        int nf;
        int packed;
        int align_mac68k;
        int pack_n;
    } pas_rectypes[PAS_REC_MAX];
    int pas_nrectype;
    struct pas_recvar_s {
        char *vname;
        char *fields[PAS_FIELD_MAX];
        int nf;
        int fldchar[PAS_FIELD_MAX];
        int packed;
        char *fldrec[PAS_FIELD_MAX];
        int fldna[PAS_FIELD_MAX];
        long long fldna_lo[PAS_FIELD_MAX];
        long long fldna_hi[PAS_FIELD_MAX];
        long long fldov[PAS_FIELD_MAX];
    } pas_recvars[PAS_REC_MAX];
    int pas_nrecvar;
    char *pas_pend_fields[PAS_FIELD_MAX];
    char *pas_pend_fldptrto[PAS_FIELD_MAX];
    char *pas_pend_fldenum[PAS_FIELD_MAX];
    char *pas_pend_fldrec[PAS_FIELD_MAX];
    char *pas_pend_fldtypename[PAS_FIELD_MAX];
    int pas_pend_fldca[PAS_FIELD_MAX];
    long long pas_pend_fldca_lo[PAS_FIELD_MAX];
    long long pas_pend_fldca_hi[PAS_FIELD_MAX];
    int pas_pend_fldchar[PAS_FIELD_MAX];
    int pas_pend_fldfile[PAS_FIELD_MAX];
    long long pas_pend_fldov[PAS_FIELD_MAX];
    int pas_pend_nf;
    char *pas_pend_ptrtarget;
    char *pas_pend_typename;
    int pas_pend_ischar;
    int pas_pend_isarr;
    int pas_pend_fldna[PAS_FIELD_MAX];
    long long pas_pend_fldna_lo[PAS_FIELD_MAX];
    long long pas_pend_fldna_hi[PAS_FIELD_MAX];
    struct { char *pname; char *rname; } pas_ptrtypes[PAS_REC_MAX];
    int pas_nptrtype;
    struct { char *vname; char *rname; } pas_arrptr[PAS_REC_MAX];
    int pas_narrptr;
    char *pas_pend_arr_ptrto;
    struct { char *vname; char *rname; } pas_ptrvars[PAS_REC_MAX];
    int pas_nptrvar;
    int pas_pvmarks[PAS_NEST_MAX_PV];
    int pas_npvmark;
    int pas_rvmarks[PAS_NEST_MAX_PV];
    int pas_nrvmark;
    struct { char *pname; char *vnames[16]; char *rnames[16]; int n; struct pas_recvar_s rvsave[16]; int rvn; void *sv[6]; int svn[6]; PNodeList *params; } pas_fwdpv[64];
    int pas_nfwdpv;
    struct { int lo, hi, n, first, last, nested; } pas_vcase_stk[32];
    int pas_vcase_depth;
    struct { const char *names[PAS_LOCAL_MAX]; int n; int decl_level; const char *func_name; } pas_lstk[PAS_NEST_MAX];
    struct { char *name; int depth; } pas_setvars[256];
    int pas_nsetvar;
    struct { char *name; long long hi; long long pack; } pas_settypes[64];
    int pas_nsettype;
    struct { char *name; int depth; } pas_charvars[256];
    int pas_ncharvar;
    struct { char *name; int depth; } pas_singlevars[256];
    int pas_nsinglevar;
    struct { char *name; int depth; } pas_pcharvars[256];
    int pas_npcharvar;
    struct { char *name; int depth; } pas_boolvars[512];
    int pas_nboolvar;
    struct { char *name; } pas_tfilevars[128];
    int pas_ntfilevar;
    struct { char *name; } pas_tfiletypes[64];
    int pas_ntfiletype;
    int pas_tfvmarks[PAS_NEST_MAX_PV];
    int pas_ntfvmark;
    struct { char *name; } pas_booltypes[64];
    int pas_nbooltype;
    struct { char *name; int depth; } pas_filevars[256];
    int pas_nfilevar;
    char *pas_hdrfiles[32];
    int pas_nhdrfile;
    struct { char *name; long long lo; int uid; int nostr; long long n; } pas_chararrs[256];
    int pas_nchararr;
    tree_t *pas_cafield_marks[2048];
    long long pas_cafield_lo[2048];
    long long pas_cafield_hi[2048];
    int pas_ncafield;
    tree_t *pas_nafield_marks[2048];
    long long pas_nafield_lo[2048];
    int pas_nnafield;
    tree_t *pas_cvfield_marks[2048];
    int pas_ncvfield;
    struct { char *name; long long lo; } pas_strarrs[128];
    int pas_nstrarr;
    struct {
        char *aname;
        char *rname;
        int nf;
        char *fields[32];
        char *fldenum[32];
        char *fldtypename[32];
        int fldchar[32];
        char *fldrec[32];
        int fldna[32];
        long long fldna_lo[32];
        long long fldna_hi[32];
        long long fldov[32];
    } pas_arrrecs[128];
    int pas_narrrec;
    char pas_case_tmp[8][24];
    int pas_case_depth;
    int pas_case_ctr;
    struct { tree_t *sel; const char *rtype; tree_t *orig; tree_t *pre; } with_stk[PAS_WITH_MAX];
    int with_depth;
    int pas_min_enum_stack_n;
    int pas_stk_enum[64];
    int pas_stk_set[64];
    int pas_stk_rec[64];
    int pas_stk_zb[64];
    int pkn;
    int fcn;
    int rdcn;
    int said;
    int wn;
    int fln;
    int pas_routine_alias_n;
} g_lower_pas_sem_t;
#endif
