#line 2 "raku.lex.c"

#line 4 "raku.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer raku_yy_create_buffer
#define yy_delete_buffer raku_yy_delete_buffer
#define yy_scan_buffer raku_yy_scan_buffer
#define yy_scan_string raku_yy_scan_string
#define yy_scan_bytes raku_yy_scan_bytes
#define yy_init_buffer raku_yy_init_buffer
#define yy_flush_buffer raku_yy_flush_buffer
#define yy_load_buffer_state raku_yy_load_buffer_state
#define yy_switch_to_buffer raku_yy_switch_to_buffer
#define yypush_buffer_state raku_yypush_buffer_state
#define yypop_buffer_state raku_yypop_buffer_state
#define yyensure_buffer_stack raku_yyensure_buffer_stack
#define yy_flex_debug raku_yy_flex_debug
#define yyin raku_yyin
#define yyleng raku_yyleng
#define yylex raku_yylex
#define yylineno raku_yylineno
#define yyout raku_yyout
#define yyrestart raku_yyrestart
#define yytext raku_yytext
#define yywrap raku_yywrap
#define yyalloc raku_yyalloc
#define yyrealloc raku_yyrealloc
#define yyfree raku_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define raku_yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer raku_yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define raku_yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer raku_yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define raku_yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer raku_yy_scan_buffer
#endif

#ifdef yy_scan_string
#define raku_yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string raku_yy_scan_string
#endif

#ifdef yy_scan_bytes
#define raku_yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes raku_yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define raku_yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer raku_yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define raku_yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer raku_yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define raku_yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state raku_yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define raku_yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer raku_yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define raku_yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state raku_yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define raku_yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state raku_yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define raku_yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack raku_yyensure_buffer_stack
#endif

#ifdef yylex
#define raku_yylex_ALREADY_DEFINED
#else
#define yylex raku_yylex
#endif

#ifdef yyrestart
#define raku_yyrestart_ALREADY_DEFINED
#else
#define yyrestart raku_yyrestart
#endif

#ifdef yylex_init
#define raku_yylex_init_ALREADY_DEFINED
#else
#define yylex_init raku_yylex_init
#endif

#ifdef yylex_init_extra
#define raku_yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra raku_yylex_init_extra
#endif

#ifdef yylex_destroy
#define raku_yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy raku_yylex_destroy
#endif

#ifdef yyget_debug
#define raku_yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug raku_yyget_debug
#endif

#ifdef yyset_debug
#define raku_yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug raku_yyset_debug
#endif

#ifdef yyget_extra
#define raku_yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra raku_yyget_extra
#endif

#ifdef yyset_extra
#define raku_yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra raku_yyset_extra
#endif

#ifdef yyget_in
#define raku_yyget_in_ALREADY_DEFINED
#else
#define yyget_in raku_yyget_in
#endif

#ifdef yyset_in
#define raku_yyset_in_ALREADY_DEFINED
#else
#define yyset_in raku_yyset_in
#endif

#ifdef yyget_out
#define raku_yyget_out_ALREADY_DEFINED
#else
#define yyget_out raku_yyget_out
#endif

#ifdef yyset_out
#define raku_yyset_out_ALREADY_DEFINED
#else
#define yyset_out raku_yyset_out
#endif

#ifdef yyget_leng
#define raku_yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng raku_yyget_leng
#endif

#ifdef yyget_text
#define raku_yyget_text_ALREADY_DEFINED
#else
#define yyget_text raku_yyget_text
#endif

#ifdef yyget_lineno
#define raku_yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno raku_yyget_lineno
#endif

#ifdef yyset_lineno
#define raku_yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno raku_yyset_lineno
#endif

#ifdef yywrap
#define raku_yywrap_ALREADY_DEFINED
#else
#define yywrap raku_yywrap
#endif

#ifdef yyalloc
#define raku_yyalloc_ALREADY_DEFINED
#else
#define yyalloc raku_yyalloc
#endif

#ifdef yyrealloc
#define raku_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc raku_yyrealloc
#endif

#ifdef yyfree
#define raku_yyfree_ALREADY_DEFINED
#else
#define yyfree raku_yyfree
#endif

#ifdef yytext
#define raku_yytext_ALREADY_DEFINED
#else
#define yytext raku_yytext
#endif

#ifdef yyleng
#define raku_yyleng_ALREADY_DEFINED
#else
#define yyleng raku_yyleng
#endif

#ifdef yyin
#define raku_yyin_ALREADY_DEFINED
#else
#define yyin raku_yyin
#endif

#ifdef yyout
#define raku_yyout_ALREADY_DEFINED
#else
#define yyout raku_yyout
#endif

#ifdef yy_flex_debug
#define raku_yy_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug raku_yy_flex_debug
#endif

#ifdef yylineno
#define raku_yylineno_ALREADY_DEFINED
#else
#define yylineno raku_yylineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define raku_yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 137
#define YY_END_OF_BUFFER 138
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[314] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  138,  136,    1,    2,   72,  104,
        3,  136,   68,   62,  112,   76,   77,   67,   65,   81,
       66,   83,  126,   87,  136,   80,   70,   73,   71,  136,
      103,  103,  103,  103,   78,   79,   52,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,   74,   61,   75,   69,  111,  110,  105,  111,
      117,  116,  113,  117,  130,  129,  127,  130,  121,  137,
      119,  121,  124,  122,  124,  135,  134,  135,  131,  132,
        1,   56,    3,    0,    0,    0,   92,    0,  100,   88,

        0,    0,  102,   59,   54,   53,   82,    0,   87,    0,
       63,   40,   41,   57,   55,   84,   58,    0,    0,  101,
      103,  103,  103,  103,  103,  103,  103,  103,  103,   47,
      103,  103,  103,  103,  103,  103,    7,    0,  103,  103,
      103,    4,   48,  103,  103,  103,  103,  118,  103,  103,
      103,  103,  103,  103,  103,  103,  103,   60,   64,  109,
      108,  106,  107,  114,  115,  128,  120,  122,  123,  133,
       95,    0,   94,    0,  100,   99,   98,  102,   51,   50,
       85,    0,   86,   97,   96,  101,  103,  103,  103,  103,
      103,  103,  103,   30,   49,  103,  103,   11,  103,  103,

      103,  103,   42,    0,   24,  103,  103,   43,  103,  103,
      103,  103,  103,  103,  103,    5,  103,  103,   15,  103,
      103,   27,  103,  103,  103,  103,   95,    0,   94,    0,
       93,   99,   98,    0,   97,   96,  103,  103,   45,  103,
      103,  103,  103,    8,  103,  103,  103,  103,  103,   25,
      125,  103,  103,  103,  103,  103,  103,  103,   32,   35,
       44,   26,   17,  103,  103,  103,   13,  103,    0,    0,
       85,   29,   46,   28,   31,  103,  103,    9,  103,  103,
       12,  103,  103,   38,    6,   39,   36,  103,  103,   34,
      103,   22,   10,    0,    0,    0,  103,   20,   19,   16,

      103,   37,   23,   18,   21,    0,   89,    0,   14,   33,
       91,   90,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   27,   28,   29,   30,   31,
       27,   32,   33,   27,   27,   27,   27,   34,   35,   27,
       27,   36,   37,   38,   39,   27,   27,   27,   27,   27,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   27,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   27,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    1,    1,    3,    1,    5,    1,
        1,    4,    1,    6,    1,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    1,
        1,    1,    1,    8,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[343] =
    {   0,
        0,    0,   70,   71,   74,   75,   76,   77,   78,   79,
       80,   83,   84,   85,  446,  447,  443,  447,  421,  447,
        0,   86,   85,  434,  447,  447,  447,  447,  447,  447,
      418,   83,  447,   74,   99,  447,  418,   86,  417,  110,
        0,  413,  393,  376,  447,  447,  447,   84,   82,   77,
      378,   88,  390,  384,  114,  384,  371,   87,  122,  103,
      374,  378,  447,  359,  447,  356,  447,  447,  447,  138,
      447,  447,  447,  132,  447,  447,  447,  409,  447,  447,
      447,  408,  447,  374,  406,  447,  447,    0,  447,  447,
      421,  447,    0,    0,  385,    0,  402,    0,    0,    0,

        0,    0,    0,  447,  447,  129,  447,  401,  151,  146,
      447,  447,  447,  447,  447,  447,  447,    0,    0,    0,
        0,  381,  363,  353,  353,  370,   97,  101,  352,    0,
      360,  351,  348,  345,  138,  347,    0,  357,  348,  343,
      350,    0,  338,  116,  125,  348,  347,  447,  333,  345,
      338,  352,  343,  342,  327,  122,  140,  447,  447,  447,
      447,  447,  447,  447,  447,  447,  447,  447,  447,  447,
        0,  356,    0,  369,    0,    0,    0,    0,  447,  447,
      172,  373,  372,    0,    0,    0,  362,  327,  339,  340,
      324,  340,  335,    0,    0,  141,  321,    0,  330,  332,

      324,  320,    0,  360,    0,  325,  313,    0,  318,  311,
      324,  323,  307,  321,  320,    0,  318,  304,    0,  317,
      316,    0,  315,  310,  305,  306,    0,  331,    0,  333,
      447,    0,    0,  189,    0,    0,  321,  300,    0,  293,
      275,  269,  266,    0,  271,  250,  252,  240,  237,    0,
      447,  234,  238,  224,  228,  218,  236,  210,    0,    0,
        0,    0,    0,  163,  157,  163,    0,  168,  174,  197,
      196,    0,    0,    0,    0,  159,  164,    0,  150,  150,
        0,  165,  158,    0,    0,    0,    0,  136,  141,    0,
      135,    0,    0,  160,  158,  136,   95,    0,    0,    0,

       96,    0,    0,    0,    0,   77,  447,   69,    0,    0,
      447,  447,  447,  221,  229,  237,  245,  253,  261,  269,
      275,  281,  287,  291,  299,  301,  303,   85,  307,  309,
      311,  315,  317,  319,  323,  327,  331,  335,  339,  343,
      347,  351
    } ;

static const flex_int16_t yy_def[343] =
    {   0,
      313,    1,  314,  314,  315,  315,  316,  316,  317,  317,
      318,  318,  319,  319,  313,  313,  313,  313,  313,  313,
      320,  321,  322,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  323,
      324,  324,  324,  324,  313,  313,  313,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  325,  313,  313,
      313,  313,  320,  326,  313,  327,  313,  328,  329,  329,

      330,  331,  332,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  333,  334,  335,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  313,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  313,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      336,  313,  337,  338,  329,  339,  340,  332,  313,  313,
      313,  313,  313,  341,  342,  335,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,

      324,  324,  324,  313,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  336,  313,  337,  338,
      313,  339,  340,  313,  341,  342,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      313,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  313,  313,
      313,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  313,  313,  313,  324,  324,  324,  324,

      324,  324,  324,  324,  324,  313,  313,  313,  324,  324,
      313,  313,    0,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313
    } ;

static const flex_int16_t yy_nxt[520] =
    {   0,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   41,   42,   41,   41,
       43,   41,   41,   41,   41,   41,   41,   44,   41,   45,
       16,   46,   47,   41,   41,   41,   48,   49,   50,   51,
       52,   53,   54,   41,   41,   55,   56,   41,   57,   41,
       58,   59,   60,   61,   41,   62,   41,   41,   63,   64,
       65,   66,   68,   68,   69,   69,   72,   72,   76,   76,
       80,   80,   80,   73,   73,   80,   87,   87,  101,   94,
      108,  174,  109,   77,   77,   81,   81,   84,   95,  106,

       84,  102,   96,  110,   97,  107,  312,   98,  115,  116,
       70,   70,  311,  118,   74,   74,   78,   78,   82,   82,
       85,  111,  110,   85,   88,   88,  119,  112,  125,  100,
      127,  129,  133,  138,  128,  145,  130,  113,  126,  148,
      134,  164,  160,  131,  146,  179,  192,  153,  135,  194,
      147,  193,   89,   89,   90,   90,  310,  309,  139,  182,
      154,  182,  140,  155,  183,  195,  149,  108,  209,  109,
      150,  180,  165,  210,  308,  211,  223,  141,  161,  151,
      110,  142,  201,  212,  224,  152,  202,  213,  225,  244,
      181,  307,  226,  245,  162,  306,  305,  304,  303,  110,

      163,  234,  270,  294,  270,  302,  295,  271,  296,  301,
      300,  299,  298,  297,  271,  271,  293,  292,  291,  290,
      234,   67,   67,   67,   67,   67,   67,   67,   67,   71,
       71,   71,   71,   71,   71,   71,   71,   75,   75,   75,
       75,   75,   75,   75,   75,   79,   79,   79,   79,   79,
       79,   79,   79,   83,   83,   83,   83,   83,   83,   83,
       83,   86,   86,   86,   86,   86,   86,   86,   86,   93,
      289,   93,   93,   93,   93,   93,   93,   99,   99,   99,
      288,   99,   99,  103,  287,  286,  285,  103,  103,  120,
      284,  283,  282,  120,  120,  121,  281,  121,  121,  170,

      280,  170,  170,  170,  170,  170,  170,  171,  171,  173,
      173,  175,  279,  175,  175,  176,  176,  177,  177,  178,
      278,  178,  178,  184,  184,  185,  185,  186,  277,  186,
      186,  227,  276,  227,  227,  229,  275,  229,  229,  230,
      230,  230,  230,  232,  274,  232,  232,  233,  273,  233,
      233,  235,  272,  235,  235,  236,  231,  236,  236,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  243,  242,  241,  240,  239,  238,  237,
      183,  183,  231,  228,  222,  221,  220,  219,  218,  217,

      216,  215,  214,  208,  207,  206,  205,  204,  203,  200,
      199,  198,  197,  196,  191,  190,  189,  188,  187,  181,
       97,  172,   91,  169,  168,  167,  166,  159,  158,  157,
      156,  144,  143,  137,  136,  132,  124,  123,  122,  117,
      114,  105,  104,   92,   91,  313,   15,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313
    } ;

static const flex_int16_t yy_chk[520] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    3,    4,    5,    6,    7,    8,
        9,   10,   11,    5,    6,   12,   13,   14,   23,   22,
       34,  328,   34,    7,    8,    9,   10,   11,   22,   32,

       12,   23,   22,   34,   22,   32,  308,   22,   38,   38,
        3,    4,  306,   40,    5,    6,    7,    8,    9,   10,
       11,   35,   34,   12,   13,   14,   40,   35,   48,   22,
       49,   50,   52,   55,   49,   58,   50,   35,   48,   59,
       52,   74,   70,   50,   58,  106,  127,   60,   52,  128,
       58,  127,   13,   14,   13,   14,  301,  297,   55,  110,
       60,  110,   55,   60,  110,  128,   59,  109,  144,  109,
       59,  106,   74,  144,  296,  145,  156,   55,   70,   59,
      109,   55,  135,  145,  156,   59,  135,  145,  157,  196,
      181,  295,  157,  196,   70,  294,  291,  289,  288,  109,

       70,  181,  234,  269,  234,  283,  269,  234,  269,  282,
      280,  279,  277,  276,  271,  270,  268,  266,  265,  264,
      181,  314,  314,  314,  314,  314,  314,  314,  314,  315,
      315,  315,  315,  315,  315,  315,  315,  316,  316,  316,
      316,  316,  316,  316,  316,  317,  317,  317,  317,  317,
      317,  317,  317,  318,  318,  318,  318,  318,  318,  318,
      318,  319,  319,  319,  319,  319,  319,  319,  319,  320,
      258,  320,  320,  320,  320,  320,  320,  321,  321,  321,
      257,  321,  321,  322,  256,  255,  254,  322,  322,  323,
      253,  252,  249,  323,  323,  324,  248,  324,  324,  325,

      247,  325,  325,  325,  325,  325,  325,  326,  326,  327,
      327,  329,  246,  329,  329,  330,  330,  331,  331,  332,
      245,  332,  332,  333,  333,  334,  334,  335,  243,  335,
      335,  336,  242,  336,  336,  337,  241,  337,  337,  338,
      338,  338,  338,  339,  240,  339,  339,  340,  238,  340,
      340,  341,  237,  341,  341,  342,  230,  342,  342,  228,
      226,  225,  224,  223,  221,  220,  218,  217,  215,  214,
      213,  212,  211,  210,  209,  207,  206,  204,  202,  201,
      200,  199,  197,  193,  192,  191,  190,  189,  188,  187,
      183,  182,  174,  172,  155,  154,  153,  152,  151,  150,

      149,  147,  146,  143,  141,  140,  139,  138,  136,  134,
      133,  132,  131,  129,  126,  125,  124,  123,  122,  108,
       97,   95,   91,   85,   84,   82,   78,   66,   64,   62,
       61,   57,   56,   54,   53,   51,   44,   43,   42,   39,
       37,   31,   24,   19,   17,   15,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[138] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "raku.l"
#line 2 "raku.l"
#include "raku.tab.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static char raku_strbuf[65536];
static int  raku_strpos;
static int raku_after_smatch  = 0;
static int raku_match_global   = 0;
static char *raku_subst_pat    = NULL;
static int raku_expect_rebody  = 0;
static int rebody_depth   = 0;
void raku_lex_error(const char *msg) {
    fprintf(stderr, "raku lex error line %d: %s\n", raku_yylineno, msg);
}
/*--------------------------------------------------------------------------------------------------------------------*/
int raku_get_lineno(void) { return raku_yylineno; }
#line 978 "raku.lex.c"
#define YY_NO_INPUT 1

#line 981 "raku.lex.c"

#define INITIAL 0
#define STR_DQ 1
#define STR_SQ 2
#define STR_RE 3
#define STR_SUBST_PAT 4
#define STR_SUBST_REPL 5
#define STR_REBODY 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 28 "raku.l"

#line 1204 "raku.lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 314 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 447 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "raku.l"
{ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 30 "raku.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "raku.l"
{ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "raku.l"
{ return KW_MY; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "raku.l"
{ return KW_SAY; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "raku.l"
{ return KW_PRINT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "raku.l"
{ return KW_IF; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "raku.l"
{ return KW_ELSE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "raku.l"
{ return KW_ELSIF; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "raku.l"
{ return KW_WHILE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "raku.l"
{ return KW_FOR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "raku.l"
{ return KW_GIVEN; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "raku.l"
{ return KW_WHEN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "raku.l"
{ return KW_DEFAULT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "raku.l"
{ return KW_SUB; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "raku.l"
{ return KW_GATHER; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "raku.l"
{ return KW_TAKE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "raku.l"
{ return KW_RETURN; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "raku.l"
{ return KW_EXISTS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "raku.l"
{ return KW_DELETE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "raku.l"
{ return KW_UNLESS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "raku.l"
{ return KW_UNTIL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "raku.l"
{ return KW_REPEAT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "raku.l"
{ return KW_MAP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "raku.l"
{ return KW_GREP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "raku.l"
{ return KW_SORT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "raku.l"
{ return KW_TRY; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "raku.l"
{ return KW_CATCH; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "raku.l"
{ return KW_CATCH; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "raku.l"
{ return KW_DIE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "raku.l"
{ return KW_CLASS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "raku.l"
{ return KW_ROLE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 61 "raku.l"
{ return KW_GRAMMAR; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 62 "raku.l"
{ raku_expect_rebody = 1; return KW_TOKEN; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "raku.l"
{ raku_expect_rebody = 1; return KW_RULE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "raku.l"
{ raku_expect_rebody = 1; return KW_REGEX; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "raku.l"
{ return KW_METHOD; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "raku.l"
{ return KW_MULTI; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "raku.l"
{ return KW_PROTO; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "raku.l"
{ return OP_COLON_D; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 "raku.l"
{ return OP_COLON_U; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 "raku.l"
{ return KW_HAS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 "raku.l"
{ return KW_NEW; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 72 "raku.l"
{ raku_yylval.sval = strdup("self"); return VAR_SCALAR; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 73 "raku.l"
{ raku_yylval.ival = 1; return LIT_INT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 74 "raku.l"
{ raku_yylval.ival = 0; return LIT_INT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 75 "raku.l"
{ return OP_SEQ; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 76 "raku.l"
{ return OP_SNE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 77 "raku.l"
{ return OP_DIV; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 78 "raku.l"
{ return OP_RANGE_EX; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 79 "raku.l"
{ return YADA; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 80 "raku.l"
{ return CARET; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 81 "raku.l"
{ return OP_RANGE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 82 "raku.l"
{ return OP_ARROW; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 83 "raku.l"
{ return OP_EQ; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "raku.l"
{ return OP_NE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 85 "raku.l"
{ return OP_LE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 86 "raku.l"
{ return OP_GE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 87 "raku.l"
{ return OP_AND; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 88 "raku.l"
{ return OP_OR; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 89 "raku.l"
{ return '|'; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 90 "raku.l"
{ return '&'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 91 "raku.l"
{ return OP_BIND; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 92 "raku.l"
{ raku_after_smatch = 1; return OP_SMATCH; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 93 "raku.l"
{ return '+'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 94 "raku.l"
{ return '-'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 95 "raku.l"
{ return '*'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 96 "raku.l"
{ return '%'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 97 "raku.l"
{ return '~'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 98 "raku.l"
{ return '<'; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 99 "raku.l"
{ return '>'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 100 "raku.l"
{ return '!'; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 101 "raku.l"
{ return '='; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 102 "raku.l"
{ if (raku_expect_rebody) { raku_expect_rebody = 0; raku_strpos = 0; rebody_depth = 1; BEGIN(STR_REBODY); } else { return '{'; } }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 103 "raku.l"
{ return '}'; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 104 "raku.l"
{ return '('; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 105 "raku.l"
{ return ')'; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 106 "raku.l"
{ return '['; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 107 "raku.l"
{ return ']'; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 108 "raku.l"
{ return ';'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 109 "raku.l"
{ return ','; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 110 "raku.l"
{ return OP_DOTEQ; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 111 "raku.l"
{ return '.'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 112 "raku.l"
{ return OP_FATARROW; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 113 "raku.l"
{ raku_yylval.dval = atof(yytext); return LIT_FLOAT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 114 "raku.l"
{ raku_yylval.dval = atof(yytext); return LIT_FLOAT; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 115 "raku.l"
{ raku_yylval.ival = atol(yytext); return LIT_INT; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 116 "raku.l"
{ raku_yylval.sval = strdup("$_"); return VAR_SCALAR; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 117 "raku.l"
{ raku_yylval.ival = 0; return VAR_FH; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 118 "raku.l"
{ raku_yylval.ival = 1; return VAR_FH; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 119 "raku.l"
{ raku_yylval.ival = 2; return VAR_FH; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 120 "raku.l"
{ raku_yylval.ival = atoi(yytext+1); return VAR_CAPTURE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 121 "raku.l"
{
    int len = strlen(yytext)-3;
    char *nm = malloc(len+1); memcpy(nm,yytext+2,len); nm[len]='\0';
    raku_yylval.sval = nm; return VAR_NAMED_CAPTURE; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 125 "raku.l"
{ raku_yylval.sval = strdup(yytext+2); return VAR_TWIGIL; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 126 "raku.l"
{ raku_yylval.sval = strdup(yytext+2); return VAR_TWIGIL; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 127 "raku.l"
{ raku_yylval.sval = strdup(yytext+2); return VAR_ARRAY_TWIGIL; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 128 "raku.l"
{ raku_yylval.sval = strdup(yytext+2); return VAR_ARRAY_TWIGIL; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 129 "raku.l"
{ raku_yylval.sval = strdup(yytext+2); return VAR_HASH_TWIGIL; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 130 "raku.l"
{ raku_yylval.sval = strdup(yytext+2); return VAR_HASH_TWIGIL; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 131 "raku.l"
{ raku_yylval.sval = strdup(yytext); return VAR_SCALAR; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 132 "raku.l"
{ raku_yylval.sval = strdup(yytext); return VAR_ARRAY; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 133 "raku.l"
{ raku_yylval.sval = strdup(yytext); return VAR_HASH; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 134 "raku.l"
{ raku_yylval.sval = strdup(yytext); return IDENT; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 135 "raku.l"
{ raku_strpos = 0; BEGIN(STR_DQ); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 136 "raku.l"
{
    raku_strbuf[raku_strpos] = '\0';
    raku_yylval.sval = strdup(raku_strbuf);
    BEGIN(INITIAL);
    if (strchr(raku_strbuf, '$') != NULL)
        return LIT_INTERP_STR;
    return LIT_STR;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 106:
YY_RULE_SETUP
#line 145 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 146 "raku.l"
{ raku_strbuf[raku_strpos++] = '\t'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 147 "raku.l"
{ raku_strbuf[raku_strpos++] = '\\'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 148 "raku.l"
{ raku_strbuf[raku_strpos++] = '"'; }
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 149 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 150 "raku.l"
{ raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 151 "raku.l"
{ raku_strpos = 0; BEGIN(STR_SQ); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 152 "raku.l"
{
    raku_strbuf[raku_strpos] = '\0';
    raku_yylval.sval = strdup(raku_strbuf);
    BEGIN(INITIAL);
    return LIT_STR;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 114:
YY_RULE_SETUP
#line 159 "raku.l"
{ raku_strbuf[raku_strpos++] = '\''; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 160 "raku.l"
{ raku_strbuf[raku_strpos++] = '\\'; }
	YY_BREAK
case 116:
/* rule 116 can match eol */
YY_RULE_SETUP
#line 161 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 162 "raku.l"
{ raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 163 "raku.l"
{ if (raku_after_smatch) { raku_after_smatch=0; raku_strpos=0; BEGIN(STR_SUBST_PAT); } else { yyless(1); return 's'; } }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 164 "raku.l"
{
    raku_strbuf[raku_strpos]='\0';
    raku_subst_pat = strdup(raku_strbuf);
    raku_strpos=0; BEGIN(STR_SUBST_REPL);
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 120:
YY_RULE_SETUP
#line 170 "raku.l"
{ raku_strbuf[raku_strpos++]='/'; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 171 "raku.l"
{ raku_strbuf[raku_strpos++]=yytext[0]; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 172 "raku.l"
{
    raku_strbuf[raku_strpos]='\0';
    int global = (yytext[1]=='g');
    size_t plen=strlen(raku_subst_pat), rlen=raku_strpos;
    char *tok = malloc(plen+rlen+4);
    memcpy(tok, raku_subst_pat, plen); tok[plen]='\x01';
    memcpy(tok+plen+1, raku_strbuf, rlen); tok[plen+1+rlen]='\x01';
    tok[plen+2+rlen] = global ? 'g' : '-'; tok[plen+3+rlen]='\0';
    free(raku_subst_pat); raku_subst_pat=NULL;
    raku_yylval.sval = tok;
    BEGIN(INITIAL); return LIT_SUBST;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 123:
YY_RULE_SETUP
#line 185 "raku.l"
{ raku_strbuf[raku_strpos++]='/'; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 186 "raku.l"
{ raku_strbuf[raku_strpos++]=yytext[0]; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 187 "raku.l"
{ if (raku_after_smatch) { raku_after_smatch=0; raku_strpos=0; BEGIN(STR_RE); raku_match_global=1; } else { yyless(3); return IDENT; } }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 188 "raku.l"
{ if (raku_after_smatch) { raku_after_smatch=0; raku_strpos=0; BEGIN(STR_RE); } else { return '/'; } }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 189 "raku.l"
{
    raku_strbuf[raku_strpos] = '\0';
    raku_yylval.sval = strdup(raku_strbuf);
    BEGIN(INITIAL);
    if (raku_match_global) { raku_match_global=0; return LIT_MATCH_GLOBAL; }
    return LIT_REGEX;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 128:
YY_RULE_SETUP
#line 197 "raku.l"
{ raku_strbuf[raku_strpos++] = '/'; }
	YY_BREAK
case 129:
/* rule 129 can match eol */
YY_RULE_SETUP
#line 198 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 199 "raku.l"
{ raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 200 "raku.l"
{ if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = '{'; rebody_depth++; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 201 "raku.l"
{
    rebody_depth--;
    if (rebody_depth == 0) {
        raku_strbuf[raku_strpos] = '\0';
        raku_yylval.sval = strdup(raku_strbuf);
        BEGIN(INITIAL);
        return LIT_REGEX;
    }
    if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = '}';
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 133:
YY_RULE_SETUP
#line 212 "raku.l"
{ if (raku_strpos < 65533) { raku_strbuf[raku_strpos++] = yytext[0]; raku_strbuf[raku_strpos++] = yytext[1]; } }
	YY_BREAK
case 134:
/* rule 134 can match eol */
YY_RULE_SETUP
#line 213 "raku.l"
{ if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 214 "raku.l"
{ if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 215 "raku.l"
{
    char buf[64];
    snprintf(buf, sizeof buf, "unexpected char '%c'", yytext[0]);
    raku_lex_error(buf);
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 137:
YY_RULE_SETUP
#line 221 "raku.l"
ECHO;
	YY_BREAK
#line 2017 "raku.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR_DQ):
case YY_STATE_EOF(STR_SQ):
case YY_STATE_EOF(STR_RE):
case YY_STATE_EOF(STR_SUBST_PAT):
case YY_STATE_EOF(STR_SUBST_REPL):
case YY_STATE_EOF(STR_REBODY):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 314 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 314 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 313);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 221 "raku.l"


