#line 2 "/tmp/rkregen/raku.lex.c"

#line 4 "/tmp/rkregen/raku.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer raku_yy_create_buffer
#define yy_delete_buffer raku_yy_delete_buffer
#define yy_scan_buffer raku_yy_scan_buffer
#define yy_scan_string raku_yy_scan_string
#define yy_scan_bytes raku_yy_scan_bytes
#define yy_init_buffer raku_yy_init_buffer
#define yy_flush_buffer raku_yy_flush_buffer
#define yy_load_buffer_state raku_yy_load_buffer_state
#define yy_switch_to_buffer raku_yy_switch_to_buffer
#define yypush_buffer_state raku_yypush_buffer_state
#define yypop_buffer_state raku_yypop_buffer_state
#define yyensure_buffer_stack raku_yyensure_buffer_stack
#define yy_flex_debug raku_yy_flex_debug
#define yyin raku_yyin
#define yyleng raku_yyleng
#define yylex raku_yylex
#define yylineno raku_yylineno
#define yyout raku_yyout
#define yyrestart raku_yyrestart
#define yytext raku_yytext
#define yywrap raku_yywrap
#define yyalloc raku_yyalloc
#define yyrealloc raku_yyrealloc
#define yyfree raku_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define raku_yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer raku_yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define raku_yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer raku_yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define raku_yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer raku_yy_scan_buffer
#endif

#ifdef yy_scan_string
#define raku_yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string raku_yy_scan_string
#endif

#ifdef yy_scan_bytes
#define raku_yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes raku_yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define raku_yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer raku_yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define raku_yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer raku_yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define raku_yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state raku_yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define raku_yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer raku_yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define raku_yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state raku_yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define raku_yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state raku_yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define raku_yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack raku_yyensure_buffer_stack
#endif

#ifdef yylex
#define raku_yylex_ALREADY_DEFINED
#else
#define yylex raku_yylex
#endif

#ifdef yyrestart
#define raku_yyrestart_ALREADY_DEFINED
#else
#define yyrestart raku_yyrestart
#endif

#ifdef yylex_init
#define raku_yylex_init_ALREADY_DEFINED
#else
#define yylex_init raku_yylex_init
#endif

#ifdef yylex_init_extra
#define raku_yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra raku_yylex_init_extra
#endif

#ifdef yylex_destroy
#define raku_yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy raku_yylex_destroy
#endif

#ifdef yyget_debug
#define raku_yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug raku_yyget_debug
#endif

#ifdef yyset_debug
#define raku_yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug raku_yyset_debug
#endif

#ifdef yyget_extra
#define raku_yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra raku_yyget_extra
#endif

#ifdef yyset_extra
#define raku_yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra raku_yyset_extra
#endif

#ifdef yyget_in
#define raku_yyget_in_ALREADY_DEFINED
#else
#define yyget_in raku_yyget_in
#endif

#ifdef yyset_in
#define raku_yyset_in_ALREADY_DEFINED
#else
#define yyset_in raku_yyset_in
#endif

#ifdef yyget_out
#define raku_yyget_out_ALREADY_DEFINED
#else
#define yyget_out raku_yyget_out
#endif

#ifdef yyset_out
#define raku_yyset_out_ALREADY_DEFINED
#else
#define yyset_out raku_yyset_out
#endif

#ifdef yyget_leng
#define raku_yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng raku_yyget_leng
#endif

#ifdef yyget_text
#define raku_yyget_text_ALREADY_DEFINED
#else
#define yyget_text raku_yyget_text
#endif

#ifdef yyget_lineno
#define raku_yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno raku_yyget_lineno
#endif

#ifdef yyset_lineno
#define raku_yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno raku_yyset_lineno
#endif

#ifdef yywrap
#define raku_yywrap_ALREADY_DEFINED
#else
#define yywrap raku_yywrap
#endif

#ifdef yyalloc
#define raku_yyalloc_ALREADY_DEFINED
#else
#define yyalloc raku_yyalloc
#endif

#ifdef yyrealloc
#define raku_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc raku_yyrealloc
#endif

#ifdef yyfree
#define raku_yyfree_ALREADY_DEFINED
#else
#define yyfree raku_yyfree
#endif

#ifdef yytext
#define raku_yytext_ALREADY_DEFINED
#else
#define yytext raku_yytext
#endif

#ifdef yyleng
#define raku_yyleng_ALREADY_DEFINED
#else
#define yyleng raku_yyleng
#endif

#ifdef yyin
#define raku_yyin_ALREADY_DEFINED
#else
#define yyin raku_yyin
#endif

#ifdef yyout
#define raku_yyout_ALREADY_DEFINED
#else
#define yyout raku_yyout
#endif

#ifdef yy_flex_debug
#define raku_yy_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug raku_yy_flex_debug
#endif

#ifdef yylineno
#define raku_yylineno_ALREADY_DEFINED
#else
#define yylineno raku_yylineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define raku_yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 164
#define YY_END_OF_BUFFER 165
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[442] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  165,  163,    1,    2,
       99,  131,    3,  163,   94,   88,  139,  103,  104,   93,
       91,  108,   92,  110,  153,  114,  163,  107,   97,  100,
       98,  163,  130,  130,  130,  130,  105,  106,   78,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  101,   87,  102,   95,  100,
      138,  137,  132,  138,  144,  143,  140,  144,  157,  156,
      154,  157,  148,  164,  146,  148,  151,  149,  151,  162,
      161,  162,  158,  159,   10,    9,   10,    1,   82,    3,

        0,    0,    0,  119,    0,  127,  115,    0,    0,  129,
       85,   80,   79,  109,    0,  114,    0,    0,   89,   64,
       65,    0,    0,   83,   81,  111,   84,    0,    0,  128,
        0,  130,  130,  130,  130,  130,  130,  130,  130,  130,
      130,   73,  130,  130,  130,  130,  130,  130,  130,   27,
      130,   16,    0,  130,  130,  130,   11,   74,  130,   14,
      130,  130,  130,  130,  130,  130,  130,  145,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,   86,
       90,    0,    0,    0,  136,  135,  133,  134,  141,  142,
      155,  147,  149,  150,  160,   10,    9,   10,   10,  122,

        0,  121,    0,  127,  126,  125,  129,   77,   76,  112,
        0,  113,   66,    0,  124,  123,  128,  130,  130,  130,
      130,  130,  130,  130,  130,  130,   50,   75,  130,  130,
      130,  130,   31,  130,  130,  130,  130,  130,   67,  130,
      130,    0,   44,  130,  130,   69,   15,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,   25,  130,
      130,  130,   35,  130,  130,  130,   47,  130,  130,   12,
      130,  130,    0,    6,    0,    0,   10,   10,  122,    0,
      121,    0,  120,  126,  125,    0,   66,    0,  124,  123,
      130,  130,  130,   71,  130,  130,  130,  130,   22,  130,

       28,  130,  130,  130,  130,  130,  130,   45,  130,  130,
       17,  152,  130,  130,   23,   13,  130,  130,  130,  130,
      130,  130,  130,   52,   55,   70,   20,   46,  130,   37,
       21,  130,  130,  130,   33,  130,    0,    0,   10,   10,
        0,    0,  112,    0,   96,   49,   72,   48,   51,  130,
      130,    0,   29,  130,   24,  130,   32,  130,  130,  130,
      130,   59,  130,  130,   26,   60,   56,  130,  130,    0,
      130,   54,  130,   42,   30,    0,    0,    5,   10,    8,
       10,    7,    0,    0,    0,  130,   40,  130,   39,   36,
      130,  130,    0,   57,  130,  130,   43,   38,  130,  130,

       41,    0,    0,  116,    0,   34,  130,   53,  130,    0,
      130,    0,  130,  130,    0,    4,  118,  117,  130,    0,
        0,    0,    0,    0,  130,  130,  130,    0,   68,   61,
        0,    0,   19,   58,  130,    0,   62,  130,   63,   18,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       29,   34,   35,   29,   29,   29,   29,   36,   37,   29,
       29,   38,   39,   40,   41,   29,   29,   29,   29,   29,
       42,   43,   44,   45,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   29,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   29,   71,   72,   73,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    2,    1,    1,
        1,    1,    1,    5,    2,    1,    6,    4,    2,    7,
        2,    1,    8,    9,   10,    2,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,    1,    1,    1,    1,   12,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[489] =
    {   0,
        0,  975,   72,   73,   74,   77,   78,   79,   80,   81,
       83,   84,   86,   87,  995,   88,  997, 1000,   90, 1000,
      972, 1000,    0,   90,   88,  985, 1000, 1000, 1000, 1000,
     1000, 1000,  969,   83, 1000,  113,  101, 1000,   94,  110,
      969,  123,  975,  120,   97,   88, 1000, 1000, 1000,  121,
      122,  123,  126,  132,  129,  102,  146,  130,   94,  154,
      138,  177,  155,  167,  145, 1000,  919, 1000,  916,  182,
     1000, 1000, 1000,  182, 1000, 1000, 1000,  180, 1000, 1000,
     1000,  970, 1000, 1000, 1000,  969, 1000,  934,  967, 1000,
     1000,    0, 1000, 1000,  982, 1000,  171,  201, 1000,    0,

        0,  945,    0,  963,    0,    0,    0,    0,    0,    0,
     1000, 1000,  182, 1000,  962,  218,  193,    0, 1000, 1000,
     1000,  979,  978,  977, 1000, 1000, 1000,    0,    0,    0,
        0,  961,  135,  152,  153,  212,  204,  215,  223,  222,
      218,  960,  225,  227,  228,  229,  231,  232,  236,  959,
      235,  237,  922,  238,  239,  240,  957,  241,  245,  956,
      242,  256,  243,  259,  267,  248,  251, 1000,  246,  254,
      247,  249,  244,  261,  268,  269,  258,  271,  296, 1000,
     1000,  969,  286,  318, 1000, 1000, 1000, 1000, 1000, 1000,
     1000, 1000, 1000, 1000, 1000,  968, 1000,  322,  323,    0,

      930,    0,  944,    0,    0,    0,    0, 1000, 1000,  309,
      948,  945,    0,  951,    0,    0,    0,  912,  310,  313,
      314,  317,  316,  321,  318,  319,  852,  851,  325,  328,
      326,  327,  850,  331,  333,  329,  332,  339,  845,  336,
      335,  842,  843,  338,  337,  839,  838,  340,  342,  341,
      344,  346,  345,  347,  356,  350,  357,  358,  837,  377,
      353,  354,  364,  380,  378,  382,  833,  386,  394,  831,
      395,  396,  840, 1000,  412,  414,  415,  417,    0,  808,
        0,  813, 1000,    0,    0,  406,    0,  422,    0,    0,
      820,  408,  410,  816,  415,  411,  413,  417,  815,  814,

      810,  418,  419,  422,  423,  424,  427,  809,  429,  426,
      808, 1000,  428,  434,  803,  802,  435,  438,  431,  439,
      433,  443,  440,  798,  797,  796,  792,  791,  441,  790,
      772,  442,  445,  447,  771,  446,  463,  784,  774,  773,
      436,  755,  747,  489, 1000,  749,  748,  721,  713,  455,
      459,  664,  711,  464,  706,  477,  705,  483,  481,  490,
      488,  704,  489,  491,  703,  702,  701,  496,  498,  651,
      499,  695,  502,  690,  686,  514,  699, 1000,  698, 1000,
      697, 1000,  661,  662,  653,  503,  676,  504,  673,  661,
      506,  507,  567,  571,  505,  508,  570,  566,  514,  509,

      565,  574,  538, 1000,  535,  555,  516,  553,  525,    0,
      518,  544,  517,  519,  556, 1000, 1000, 1000,  520,  539,
      533,  531,  531,    0,  526,  528,  529,  528, 1000, 1000,
        0,  527,  534,  532,  530,  140, 1000,  533, 1000,  139,
     1000,  591,  603,  615,  627,  639,  651,  663,  675,  684,
      693,  704,  713,  720,  724,  735,  747,  749,  751,  142,
      757,  759,  761,  767,  769,  771,  773,  779,  781,  793,
      799,  805,  811,  817,  823,  829,  840,  846,  852,  859,
      871,  883,  895,  907,  919,  931,  943,  955
    } ;

static const flex_int16_t yy_def[489] =
    {   0,
      441,    1,  442,  442,  443,  443,  444,  444,  445,  445,
      446,  446,  447,  447,  448,  448,  441,  441,  441,  441,
      441,  441,  449,  450,  451,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  452,  441,
      441,  453,  454,  454,  454,  454,  441,  441,  441,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  441,  441,  441,  441,  455,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  456,  441,  441,  457,  441,  457,  441,  441,  449,

      458,  441,  459,  441,  460,  461,  461,  462,  463,  464,
      441,  441,  441,  441,  441,  441,  441,  465,  441,  441,
      441,  452,  452,  452,  441,  441,  441,  466,  467,  468,
      469,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  441,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  441,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  441,
      441,  470,  470,  470,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  457,  441,  457,  457,  471,

      441,  472,  473,  461,  474,  475,  464,  441,  441,  441,
      441,  441,  476,  477,  478,  479,  468,  480,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  441,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  470,  441,  470,  470,  457,  457,  471,  441,
      472,  473,  441,  474,  475,  441,  476,  477,  478,  479,
      480,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  441,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  470,  481,  482,  483,
      441,  441,  441,  477,  441,  454,  454,  454,  454,  454,
      454,  469,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  469,
      454,  454,  454,  454,  454,  470,  481,  441,  482,  441,
      483,  441,  441,  441,  441,  454,  454,  480,  454,  454,
      454,  454,  441,  454,  454,  454,  454,  454,  480,  454,

      454,  484,  441,  441,  441,  454,  480,  454,  454,  485,
      454,  441,  480,  454,  484,  441,  441,  441,  480,  441,
      486,  485,  441,  487,  480,  454,  480,  486,  441,  441,
      488,  487,  480,  454,  480,  488,  441,  480,  441,  480,
        0,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441
    } ;

static const flex_int16_t yy_nxt[1075] =
    {   0,
       18,   19,   20,   19,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   18,   42,   43,   43,   44,
       43,   43,   45,   43,   43,   43,   43,   43,   43,   46,
       43,   47,   18,   48,   49,   43,   43,   43,   50,   51,
       52,   53,   54,   55,   56,   43,   43,   57,   58,   59,
       60,   43,   61,   62,   63,   64,   43,   65,   43,   43,
       66,   67,   68,   69,   72,   72,   76,   73,   73,   76,
       80,   80,   84,   84,   77,   84,   84,   77,   91,   91,
       96,   98,  108,   98,  101,  122,   81,   81,   85,   85,

      113,   88,   88,  102,  131,  109,  114,  103,  118,  104,
      131,   97,  105,  131,   74,   74,   78,  124,  131,   78,
       82,   82,   86,   86,  119,   89,   89,  128,   92,   92,
      115,  120,  116,  125,  126,  107,  131,  131,  131,  131,
      129,  121,  131,  134,  117,  131,  131,  133,  131,  160,
      135,  131,  203,  150,  131,  131,   93,   93,   94,   94,
      151,  131,  131,  117,  439,  152,  153,  136,  131,  131,
      131,  131,  138,  197,  219,  149,  139,  137,  146,  141,
      158,  140,  144,  131,  142,  145,  147,  185,  165,  159,
      189,  143,  154,  131,  148,  168,  155,  166,  179,  208,

      161,  174,   98,  167,   98,  125,  126,  211,  220,  211,
      162,  156,  212,  163,  175,  157,  164,  176,  221,  198,
      131,  199,  190,  169,  186,  177,  209,  170,  131,  183,
      178,  131,  171,  184,  131,  115,  172,  116,  131,  131,
      187,  131,  173,  131,  131,  131,  188,  131,  131,  117,
      223,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  224,  131,  117,  226,
      131,  225,  131,  227,  131,  131,  222,  131,  236,  231,
      229,  230,  237,  131,  131,  131,  240,  131,  274,  228,
      233,  263,  232,  234,  238,  241,  245,  235,  243,  239,

      247,  261,  249,  244,  257,  248,  250,  258,  246,  251,
      260,  262,  131,  252,  268,  259,  264,  265,  253,  254,
      274,  270,  269,  266,  197,  197,  131,  255,  210,  131,
      131,  256,  131,  131,  131,  131,  275,  131,  267,  292,
      286,  131,  131,  131,  131,  131,  271,  131,  131,  131,
      272,  131,  131,  131,  131,  131,  131,  131,  131,  286,
      131,  131,  131,  131,  294,  295,  131,  297,  298,  131,
      131,  299,  131,  131,  131,  300,  293,  276,  301,  296,
      131,  278,  302,  306,  305,  304,  307,  277,  309,  303,
      310,  313,  308,  131,  131,  318,  131,  321,  131,  311,

      316,  314,  131,  315,  319,  317,  322,  324,  325,  320,
      131,  131,  131,  327,  274,  323,  274,  197,  328,  197,
      342,  329,  342,  344,  131,  343,  131,  131,  326,  131,
      330,  131,  332,  131,  131,  131,  333,  331,  131,  131,
      131,  346,  131,  131,  131,  131,  345,  131,  334,  131,
      131,  131,  336,  335,  131,  131,  131,  131,  131,  131,
      347,  131,  131,  131,  337,  274,  340,  383,  348,  353,
      384,  131,  385,  356,  349,  131,  338,  355,  350,  339,
      131,  351,  357,  354,  358,  359,  363,  361,  362,  368,
      344,  371,  364,  131,  360,  365,  375,  131,  366,  131,

      372,  367,  369,  374,  131,  131,  131,  131,  373,  387,
      393,  386,  131,  345,  131,  131,  274,  376,  131,  131,
      131,  131,  131,  131,  131,  131,  420,  389,  412,  391,
      131,  392,  131,  131,  131,  131,  131,  394,  423,  390,
      420,  131,  131,  395,  131,  131,  131,  421,  131,  131,
      131,  437,  429,  431,  407,  430,  398,  429,  416,  396,
      397,  421,  414,  400,  413,  401,  424,  406,  408,  131,
      409,  131,  402,  411,  418,  417,  416,  434,  426,  419,
      425,  131,  131,  435,  427,  440,  131,  131,  438,  410,
      433,   71,   71,   71,   71,   71,   71,   71,   71,   71,

       71,   71,   71,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   95,   95,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,  100,  100,  131,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  106,  106,  131,
      106,  106,  131,  405,  106,  106,  110,  404,  403,  382,

      380,  378,  131,  110,  110,  123,  131,  123,  123,  123,
      123,  131,  123,  399,  123,  123,  130,  131,  131,  131,
      131,  131,  131,  130,  130,  132,  132,  131,  388,  131,
      132,  132,  182,  182,  182,  195,  195,  131,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  200,
      200,  202,  202,  204,  131,  131,  343,  204,  204,  205,
      205,  206,  206,  207,  343,  382,  380,  207,  207,  213,
      213,  215,  215,  216,  216,  217,  378,  131,  131,  217,
      217,  218,  218,  273,  273,  273,  273,  273,  273,  273,

      273,  273,  273,  273,  273,  279,  131,  131,  370,  279,
      279,  281,  131,  131,  131,  281,  281,  282,  131,  131,
      282,  282,  282,  284,  131,  131,  131,  284,  284,  285,
      352,  131,  131,  285,  285,  287,  131,  283,  341,  287,
      287,  288,  274,  288,  288,  288,  288,  131,  288,  131,
      288,  288,  289,  131,  131,  131,  289,  289,  290,  131,
      312,  131,  290,  290,  291,  291,  131,  131,  131,  291,
      291,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  415,  415,  415,
      415,  415,  415,  415,  415,  415,  415,  415,  415,  422,
      422,  422,  422,  422,  422,  422,  422,  422,  131,  422,
      422,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  428,  428,  432,  432,  432,  432,  432,  432,  432,
      432,  432,  214,  432,  432,  436,  436,  436,  436,  436,
      436,  436,  436,  436,  212,  436,  436,  212,  283,  280,
      197,  274,  131,  131,  242,  131,  131,  131,  214,  214,
      122,  210,  104,  201,  197,  194,  193,  192,  191,  181,
      180,  131,  127,  112,  111,   99,  441,   96,   70,   17,

      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441
    } ;

static const flex_int16_t yy_chk[1075] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,    3,    4,    6,
        7,    8,    9,   10,    5,   11,   12,    6,   13,   14,
       16,   19,   25,   19,   24,   39,    7,    8,    9,   10,

       34,   11,   12,   24,   46,   25,   34,   24,   37,   24,
       59,   16,   24,   45,    3,    4,    5,   39,   56,    6,
        7,    8,    9,   10,   37,   11,   12,   42,   13,   14,
       36,   37,   36,   40,   40,   24,   44,   50,   51,   52,
       42,   37,   53,   45,   36,   55,   58,   44,   54,   59,
       46,  133,  460,   56,   61,  440,   13,   14,   13,   14,
       56,   65,   57,   36,  436,   56,   57,   50,  134,  135,
       60,   63,   51,   97,  133,   55,   51,   50,   54,   52,
       58,   51,   53,   64,   52,   53,   54,   74,   61,   58,
       78,   52,   57,   62,   54,   62,   57,   61,   65,  113,

       60,   63,   98,   61,   98,   70,   70,  117,  134,  117,
       60,   57,  117,   60,   63,   57,   60,   63,  135,   97,
      137,   97,   78,   62,   74,   64,  113,   62,  136,   70,
       64,  138,   62,   70,  141,  116,   62,  116,  140,  139,
       74,  143,   62,  144,  145,  146,   74,  147,  148,  116,
      137,  151,  149,  152,  154,  155,  156,  158,  161,  163,
      173,  159,  169,  171,  166,  172,  138,  167,  116,  139,
      170,  138,  162,  139,  177,  164,  136,  174,  148,  143,
      140,  141,  148,  165,  175,  176,  151,  178,  183,  139,
      145,  173,  144,  146,  149,  152,  156,  147,  154,  149,

      159,  171,  162,  155,  166,  161,  163,  167,  158,  164,
      170,  172,  179,  164,  177,  169,  174,  175,  164,  165,
      184,  178,  177,  175,  198,  199,  219,  165,  210,  220,
      221,  165,  223,  222,  225,  226,  183,  224,  176,  219,
      210,  229,  231,  232,  230,  236,  179,  234,  237,  235,
      179,  241,  240,  245,  244,  238,  248,  250,  249,  210,
      251,  253,  252,  254,  221,  222,  256,  224,  225,  261,
      262,  226,  255,  257,  258,  229,  220,  184,  230,  223,
      263,  199,  230,  235,  234,  232,  236,  198,  238,  231,
      240,  244,  237,  260,  265,  251,  264,  254,  266,  241,

      249,  245,  268,  248,  252,  250,  255,  257,  258,  253,
      269,  271,  272,  261,  275,  256,  276,  277,  262,  278,
      286,  263,  286,  288,  292,  286,  293,  296,  260,  297,
      264,  295,  266,  298,  302,  303,  268,  265,  304,  305,
      306,  292,  310,  307,  313,  309,  288,  319,  269,  321,
      314,  317,  272,  271,  318,  320,  323,  329,  332,  322,
      293,  333,  336,  334,  275,  337,  278,  341,  295,  302,
      341,  350,  341,  305,  296,  351,  276,  304,  297,  277,
      354,  298,  306,  303,  307,  309,  317,  313,  314,  322,
      344,  329,  318,  356,  310,  319,  336,  359,  320,  358,

      332,  321,  323,  334,  361,  363,  360,  364,  333,  351,
      360,  350,  368,  344,  369,  371,  376,  337,  373,  386,
      388,  395,  391,  392,  396,  400,  409,  354,  396,  358,
      399,  359,  407,  413,  411,  414,  419,  361,  411,  356,
      420,  409,  425,  363,  426,  427,  435,  409,  434,  438,
      433,  432,  428,  423,  388,  422,  369,  421,  415,  364,
      368,  420,  400,  371,  399,  373,  412,  386,  391,  408,
      392,  406,  376,  395,  405,  403,  402,  426,  414,  407,
      413,  401,  398,  427,  419,  438,  397,  394,  435,  393,
      425,  442,  442,  442,  442,  442,  442,  442,  442,  442,

      442,  442,  442,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  444,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  447,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  447,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  449,  449,  390,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  450,  450,  389,
      450,  450,  387,  385,  450,  450,  451,  384,  383,  381,

      379,  377,  375,  451,  451,  452,  374,  452,  452,  452,
      452,  372,  452,  370,  452,  452,  453,  367,  366,  365,
      362,  357,  355,  453,  453,  454,  454,  353,  352,  349,
      454,  454,  455,  455,  455,  456,  456,  348,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  458,
      458,  459,  459,  461,  347,  346,  343,  461,  461,  462,
      462,  463,  463,  464,  342,  340,  339,  464,  464,  465,
      465,  466,  466,  467,  467,  468,  338,  335,  331,  468,
      468,  469,  469,  470,  470,  470,  470,  470,  470,  470,

      470,  470,  470,  470,  470,  471,  330,  328,  327,  471,
      471,  472,  326,  325,  324,  472,  472,  473,  316,  315,
      473,  473,  473,  474,  311,  308,  301,  474,  474,  475,
      300,  299,  294,  475,  475,  476,  291,  282,  280,  476,
      476,  477,  273,  477,  477,  477,  477,  270,  477,  267,
      477,  477,  478,  259,  247,  246,  478,  478,  479,  243,
      242,  239,  479,  479,  480,  480,  233,  228,  227,  480,
      480,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  483,  483,  483,  483,  483,

      483,  483,  483,  483,  483,  483,  483,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  218,  485,
      485,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  214,  487,  487,  488,  488,  488,  488,  488,
      488,  488,  488,  488,  212,  488,  488,  211,  203,  201,
      196,  182,  160,  157,  153,  150,  142,  132,  124,  123,
      122,  115,  104,  102,   95,   89,   88,   86,   82,   69,
       67,   43,   41,   33,   26,   21,   17,   15,    2,  441,

      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441,  441,  441,  441,  441,  441,  441,
      441,  441,  441,  441
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[165] =
    {   0,
0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
    0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "raku.l"
#line 2 "raku.l"
#include "raku.tab.h"
#include "rk_opname.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static char raku_strbuf[65536];
static int  raku_strpos;
static int raku_after_smatch  = 0;
static int raku_match_global   = 0;
static char *raku_subst_pat    = NULL;
static int raku_expect_rebody  = 0;
static int rebody_depth   = 0;
void raku_lex_error(const char *msg) {
    fprintf(stderr, "raku lex error line %d: %s\n", raku_yylineno, msg);
}
/*--------------------------------------------------------------------------------------------------------------------*/
int raku_get_lineno(void) { return raku_yylineno; }
#line 1147 "/tmp/rkregen/raku.lex.c"
#define YY_NO_INPUT 1

#line 1150 "/tmp/rkregen/raku.lex.c"

#define INITIAL 0
#define STR_DQ 1
#define STR_SQ 2
#define STR_RE 3
#define STR_SUBST_PAT 4
#define STR_SUBST_REPL 5
#define STR_REBODY 6
#define POD 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 30 "raku.l"

#line 1377 "/tmp/rkregen/raku.lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 442 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1000 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "raku.l"
{ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 32 "raku.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "raku.l"
{ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 34 "raku.l"
{ BEGIN(POD); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 35 "raku.l"
{ BEGIN(POD); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 36 "raku.l"
{ BEGIN(POD); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 37 "raku.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 38 "raku.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 39 "raku.l"
{ }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 40 "raku.l"
{ }
	YY_BREAK
case YY_STATE_EOF(POD):
#line 41 "raku.l"
{ BEGIN(INITIAL); yyterminate(); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "raku.l"
{ return KW_MY; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "raku.l"
{ return KW_USE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "raku.l"
{ return KW_SAY; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "raku.l"
{ return KW_PRINT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "raku.l"
{ return KW_IF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "raku.l"
{ return KW_ELSE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "raku.l"
{ return KW_ELSIF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "raku.l"
{ return KW_WHILE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "raku.l"
{ return KW_FOR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "raku.l"
{ return KW_GIVEN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "raku.l"
{ return KW_WHEN; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "raku.l"
{ return KW_DEFAULT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 66 "raku.l"
{ return KW_SUB; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 67 "raku.l"
{ return KW_GATHER; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 68 "raku.l"
{ return KW_TAKE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 69 "raku.l"
{ return KW_RETURN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 70 "raku.l"
{ return KW_EXISTS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 71 "raku.l"
{ return KW_DELETE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 72 "raku.l"
{ return KW_UNLESS; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 73 "raku.l"
{ return KW_UNTIL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 74 "raku.l"
{ return KW_REPEAT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 75 "raku.l"
{ return KW_MAP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 76 "raku.l"
{ return KW_GREP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 77 "raku.l"
{ return KW_SORT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 78 "raku.l"
{ return KW_TRY; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 79 "raku.l"
{ return KW_CATCH; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 80 "raku.l"
{ return KW_CATCH; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 81 "raku.l"
{ return KW_DIE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 82 "raku.l"
{ return KW_CLASS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 83 "raku.l"
{ return KW_ROLE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 84 "raku.l"
{ return KW_GRAMMAR; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 85 "raku.l"
{ raku_expect_rebody = 1; return KW_TOKEN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 86 "raku.l"
{ raku_expect_rebody = 1; return KW_RULE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 87 "raku.l"
{ raku_expect_rebody = 1; return KW_REGEX; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 88 "raku.l"
{ return KW_METHOD; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 89 "raku.l"
{ return KW_METHOD; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 90 "raku.l"
{ return KW_MULTI; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 91 "raku.l"
{ return KW_PROTO; }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 92 "raku.l"
{ char raw[64]; int rl=(int)yyleng-8; if(rl>63)rl=63; memcpy(raw,yytext+7,rl); raw[rl]=0; char cb[96]; rk_op_canon_base("infix",raw,cb,sizeof cb); raku_yylval.sval=strdup(cb); return OP_NAME; }
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 93 "raku.l"
{ char raw[64]; int rl=(int)yyleng-9; if(rl>63)rl=63; memcpy(raw,yytext+8,rl); raw[rl]=0; char cb[96]; rk_op_canon_base("prefix",raw,cb,sizeof cb); raku_yylval.sval=strdup(cb); return OP_NAME; }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 94 "raku.l"
{ char raw[64]; int rl=(int)yyleng-10; if(rl>63)rl=63; memcpy(raw,yytext+9,rl); raw[rl]=0; char cb[96]; rk_op_canon_base("postfix",raw,cb,sizeof cb); raku_yylval.sval=strdup(cb); return OP_NAME; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 95 "raku.l"
{ return OP_COLON_D; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 96 "raku.l"
{ return OP_COLON_U; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 97 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_SCALAR; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 98 "raku.l"
{ return KW_HAS; }
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 99 "raku.l"
{ const char *lt = strchr(yytext,'<'); const char *gt = strrchr(yytext,'>'); int n=(int)(gt-lt-1); if(n<0)n=0; char *w=(char*)malloc(n+1); memcpy(w,lt+1,n); w[n]=0; raku_yylval.sval=w; return KW_HANDLES; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 100 "raku.l"
{ return KW_NEW; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 101 "raku.l"
{ raku_yylval.sval = strdup("self"); return VAR_SCALAR; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 102 "raku.l"
{ raku_yylval.ival = 1; return LIT_INT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 103 "raku.l"
{ raku_yylval.ival = 0; return LIT_INT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 104 "raku.l"
{ return OP_SEQ; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 105 "raku.l"
{ return OP_SNE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 106 "raku.l"
{ return OP_DIV; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 107 "raku.l"
{ return OP_RANGE_EX; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 108 "raku.l"
{ return YADA; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 109 "raku.l"
{ return CARET; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 110 "raku.l"
{ return OP_RANGE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 111 "raku.l"
{ return OP_ARROW; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 112 "raku.l"
{ return OP_EQ; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 113 "raku.l"
{ return OP_NE; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 114 "raku.l"
{ return OP_LE; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 115 "raku.l"
{ return OP_GE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 116 "raku.l"
{ return OP_AND; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 117 "raku.l"
{ return OP_OR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 118 "raku.l"
{ return '|'; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 119 "raku.l"
{ return '&'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 120 "raku.l"
{ return OP_BIND; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 121 "raku.l"
{ raku_after_smatch = 1; return OP_SMATCH; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 122 "raku.l"
{ return '+'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 123 "raku.l"
{ return '-'; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 124 "raku.l"
{ return '*'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 125 "raku.l"
{ return '%'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 126 "raku.l"
{ return '~'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 127 "raku.l"
{
    int n=(int)yyleng-2; char *inner=(char*)malloc(n+1); memcpy(inner,yytext+1,n); inner[n]='\0';
    raku_yylval.sval=inner; return WORDLIST; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 130 "raku.l"
{ return '<'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 131 "raku.l"
{ return '>'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 132 "raku.l"
{ return '!'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 133 "raku.l"
{ return '='; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 134 "raku.l"
{ if (raku_expect_rebody) { raku_expect_rebody = 0; raku_strpos = 0; rebody_depth = 1; BEGIN(STR_REBODY); } else { return '{'; } }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 135 "raku.l"
{ return '}'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 136 "raku.l"
{ return '('; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 137 "raku.l"
{ return ')'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 138 "raku.l"
{ return '['; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 139 "raku.l"
{ return ']'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 140 "raku.l"
{ return ';'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 141 "raku.l"
{ return ','; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 142 "raku.l"
{ return OP_DOTEQ; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 143 "raku.l"
{ return '.'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 144 "raku.l"
{ return OP_FATARROW; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 145 "raku.l"
{ raku_yylval.dval = atof(yytext); return LIT_FLOAT; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 146 "raku.l"
{ raku_yylval.dval = atof(yytext); return LIT_FLOAT; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 147 "raku.l"
{ raku_yylval.ival = atol(yytext); return LIT_INT; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 148 "raku.l"
{ raku_yylval.sval = strdup("$_"); return VAR_SCALAR; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 149 "raku.l"
{ raku_yylval.ival = 0; return VAR_FH; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 150 "raku.l"
{ raku_yylval.ival = 1; return VAR_FH; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 151 "raku.l"
{ raku_yylval.ival = 2; return VAR_FH; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 152 "raku.l"
{ raku_yylval.ival = atoi(yytext+1); return VAR_CAPTURE; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 153 "raku.l"
{
    int len = strlen(yytext)-3;
    char *nm = malloc(len+1); memcpy(nm,yytext+2,len); nm[len]='\0';
    raku_yylval.sval = nm; return VAR_NAMED_CAPTURE; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 157 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_TWIGIL; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 158 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_TWIGIL; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 159 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_ARRAY_TWIGIL; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 160 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_ARRAY_TWIGIL; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 161 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_HASH_TWIGIL; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 162 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_HASH_TWIGIL; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 163 "raku.l"
{ raku_yylval.sval = strdup(yytext); return VAR_SCALAR; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 164 "raku.l"
{ raku_yylval.sval = strdup(yytext); return VAR_ARRAY; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 165 "raku.l"
{ raku_yylval.sval = strdup(yytext); return VAR_HASH; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 166 "raku.l"
{ raku_yylval.sval = strdup(yytext); return IDENT; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 167 "raku.l"
{ raku_strpos = 0; BEGIN(STR_DQ); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 168 "raku.l"
{
    raku_strbuf[raku_strpos] = '\0';
    raku_yylval.sval = strdup(raku_strbuf);
    BEGIN(INITIAL);
    if (strchr(raku_strbuf, '$') != NULL)
        return LIT_INTERP_STR;
    return LIT_STR;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 133:
YY_RULE_SETUP
#line 177 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 178 "raku.l"
{ raku_strbuf[raku_strpos++] = '\t'; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 179 "raku.l"
{ raku_strbuf[raku_strpos++] = '\\'; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 180 "raku.l"
{ raku_strbuf[raku_strpos++] = '"'; }
	YY_BREAK
case 137:
/* rule 137 can match eol */
YY_RULE_SETUP
#line 181 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 182 "raku.l"
{ raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 183 "raku.l"
{ raku_strpos = 0; BEGIN(STR_SQ); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 184 "raku.l"
{
    raku_strbuf[raku_strpos] = '\0';
    raku_yylval.sval = strdup(raku_strbuf);
    BEGIN(INITIAL);
    return LIT_STR;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 141:
YY_RULE_SETUP
#line 191 "raku.l"
{ raku_strbuf[raku_strpos++] = '\''; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 192 "raku.l"
{ raku_strbuf[raku_strpos++] = '\\'; }
	YY_BREAK
case 143:
/* rule 143 can match eol */
YY_RULE_SETUP
#line 193 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 194 "raku.l"
{ raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 195 "raku.l"
{ if (raku_after_smatch) { raku_after_smatch=0; raku_strpos=0; BEGIN(STR_SUBST_PAT); } else { yyless(1); return 's'; } }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 196 "raku.l"
{
    raku_strbuf[raku_strpos]='\0';
    raku_subst_pat = strdup(raku_strbuf);
    raku_strpos=0; BEGIN(STR_SUBST_REPL);
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 147:
YY_RULE_SETUP
#line 202 "raku.l"
{ raku_strbuf[raku_strpos++]='/'; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 203 "raku.l"
{ raku_strbuf[raku_strpos++]=yytext[0]; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 204 "raku.l"
{
    raku_strbuf[raku_strpos]='\0';
    int global = (yytext[1]=='g');
    size_t plen=strlen(raku_subst_pat), rlen=raku_strpos;
    char *tok = malloc(plen+rlen+4);
    memcpy(tok, raku_subst_pat, plen); tok[plen]='\x01';
    memcpy(tok+plen+1, raku_strbuf, rlen); tok[plen+1+rlen]='\x01';
    tok[plen+2+rlen] = global ? 'g' : '-'; tok[plen+3+rlen]='\0';
    free(raku_subst_pat); raku_subst_pat=NULL;
    raku_yylval.sval = tok;
    BEGIN(INITIAL); return LIT_SUBST;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 150:
YY_RULE_SETUP
#line 217 "raku.l"
{ raku_strbuf[raku_strpos++]='/'; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 218 "raku.l"
{ raku_strbuf[raku_strpos++]=yytext[0]; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 219 "raku.l"
{ if (raku_after_smatch) { raku_after_smatch=0; raku_strpos=0; BEGIN(STR_RE); raku_match_global=1; } else { yyless(3); return IDENT; } }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 220 "raku.l"
{ if (raku_after_smatch) { raku_after_smatch=0; raku_strpos=0; BEGIN(STR_RE); } else { return '/'; } }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 221 "raku.l"
{
    raku_strbuf[raku_strpos] = '\0';
    raku_yylval.sval = strdup(raku_strbuf);
    BEGIN(INITIAL);
    if (raku_match_global) { raku_match_global=0; return LIT_MATCH_GLOBAL; }
    return LIT_REGEX;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 155:
YY_RULE_SETUP
#line 229 "raku.l"
{ raku_strbuf[raku_strpos++] = '/'; }
	YY_BREAK
case 156:
/* rule 156 can match eol */
YY_RULE_SETUP
#line 230 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 231 "raku.l"
{ raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 232 "raku.l"
{ if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = '{'; rebody_depth++; }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 233 "raku.l"
{
    rebody_depth--;
    if (rebody_depth == 0) {
        raku_strbuf[raku_strpos] = '\0';
        raku_yylval.sval = strdup(raku_strbuf);
        BEGIN(INITIAL);
        return LIT_REGEX;
    }
    if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = '}';
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 160:
YY_RULE_SETUP
#line 244 "raku.l"
{ if (raku_strpos < 65533) { raku_strbuf[raku_strpos++] = yytext[0]; raku_strbuf[raku_strpos++] = yytext[1]; } }
	YY_BREAK
case 161:
/* rule 161 can match eol */
YY_RULE_SETUP
#line 245 "raku.l"
{ if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 246 "raku.l"
{ if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 247 "raku.l"
{
    char buf[64];
    snprintf(buf, sizeof buf, "unexpected char '%c'", yytext[0]);
    raku_lex_error(buf);
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 164:
YY_RULE_SETUP
#line 253 "raku.l"
ECHO;
	YY_BREAK
#line 2342 "/tmp/rkregen/raku.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR_DQ):
case YY_STATE_EOF(STR_SQ):
case YY_STATE_EOF(STR_RE):
case YY_STATE_EOF(STR_SUBST_PAT):
case YY_STATE_EOF(STR_SUBST_REPL):
case YY_STATE_EOF(STR_REBODY):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 442 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 442 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 441);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 253 "raku.l"


