#line 2 "raku.lex.c"

#line 4 "raku.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer raku_yy_create_buffer
#define yy_delete_buffer raku_yy_delete_buffer
#define yy_scan_buffer raku_yy_scan_buffer
#define yy_scan_string raku_yy_scan_string
#define yy_scan_bytes raku_yy_scan_bytes
#define yy_init_buffer raku_yy_init_buffer
#define yy_flush_buffer raku_yy_flush_buffer
#define yy_load_buffer_state raku_yy_load_buffer_state
#define yy_switch_to_buffer raku_yy_switch_to_buffer
#define yypush_buffer_state raku_yypush_buffer_state
#define yypop_buffer_state raku_yypop_buffer_state
#define yyensure_buffer_stack raku_yyensure_buffer_stack
#define yy_flex_debug raku_yy_flex_debug
#define yyin raku_yyin
#define yyleng raku_yyleng
#define yylex raku_yylex
#define yylineno raku_yylineno
#define yyout raku_yyout
#define yyrestart raku_yyrestart
#define yytext raku_yytext
#define yywrap raku_yywrap
#define yyalloc raku_yyalloc
#define yyrealloc raku_yyrealloc
#define yyfree raku_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define raku_yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer raku_yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define raku_yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer raku_yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define raku_yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer raku_yy_scan_buffer
#endif

#ifdef yy_scan_string
#define raku_yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string raku_yy_scan_string
#endif

#ifdef yy_scan_bytes
#define raku_yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes raku_yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define raku_yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer raku_yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define raku_yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer raku_yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define raku_yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state raku_yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define raku_yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer raku_yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define raku_yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state raku_yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define raku_yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state raku_yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define raku_yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack raku_yyensure_buffer_stack
#endif

#ifdef yylex
#define raku_yylex_ALREADY_DEFINED
#else
#define yylex raku_yylex
#endif

#ifdef yyrestart
#define raku_yyrestart_ALREADY_DEFINED
#else
#define yyrestart raku_yyrestart
#endif

#ifdef yylex_init
#define raku_yylex_init_ALREADY_DEFINED
#else
#define yylex_init raku_yylex_init
#endif

#ifdef yylex_init_extra
#define raku_yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra raku_yylex_init_extra
#endif

#ifdef yylex_destroy
#define raku_yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy raku_yylex_destroy
#endif

#ifdef yyget_debug
#define raku_yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug raku_yyget_debug
#endif

#ifdef yyset_debug
#define raku_yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug raku_yyset_debug
#endif

#ifdef yyget_extra
#define raku_yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra raku_yyget_extra
#endif

#ifdef yyset_extra
#define raku_yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra raku_yyset_extra
#endif

#ifdef yyget_in
#define raku_yyget_in_ALREADY_DEFINED
#else
#define yyget_in raku_yyget_in
#endif

#ifdef yyset_in
#define raku_yyset_in_ALREADY_DEFINED
#else
#define yyset_in raku_yyset_in
#endif

#ifdef yyget_out
#define raku_yyget_out_ALREADY_DEFINED
#else
#define yyget_out raku_yyget_out
#endif

#ifdef yyset_out
#define raku_yyset_out_ALREADY_DEFINED
#else
#define yyset_out raku_yyset_out
#endif

#ifdef yyget_leng
#define raku_yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng raku_yyget_leng
#endif

#ifdef yyget_text
#define raku_yyget_text_ALREADY_DEFINED
#else
#define yyget_text raku_yyget_text
#endif

#ifdef yyget_lineno
#define raku_yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno raku_yyget_lineno
#endif

#ifdef yyset_lineno
#define raku_yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno raku_yyset_lineno
#endif

#ifdef yywrap
#define raku_yywrap_ALREADY_DEFINED
#else
#define yywrap raku_yywrap
#endif

#ifdef yyalloc
#define raku_yyalloc_ALREADY_DEFINED
#else
#define yyalloc raku_yyalloc
#endif

#ifdef yyrealloc
#define raku_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc raku_yyrealloc
#endif

#ifdef yyfree
#define raku_yyfree_ALREADY_DEFINED
#else
#define yyfree raku_yyfree
#endif

#ifdef yytext
#define raku_yytext_ALREADY_DEFINED
#else
#define yytext raku_yytext
#endif

#ifdef yyleng
#define raku_yyleng_ALREADY_DEFINED
#else
#define yyleng raku_yyleng
#endif

#ifdef yyin
#define raku_yyin_ALREADY_DEFINED
#else
#define yyin raku_yyin
#endif

#ifdef yyout
#define raku_yyout_ALREADY_DEFINED
#else
#define yyout raku_yyout
#endif

#ifdef yy_flex_debug
#define raku_yy_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug raku_yy_flex_debug
#endif

#ifdef yylineno
#define raku_yylineno_ALREADY_DEFINED
#else
#define yylineno raku_yylineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define raku_yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 179
#define YY_END_OF_BUFFER 180
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[472] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  180,  178,    1,    2,
        1,  114,  146,    3,  178,  109,   95,  154,  118,  119,
      108,  106,  123,  107,  125,  168,  129,  178,  122,  112,
      115,  113,  178,  178,  145,  145,  145,  145,  120,  121,
       83,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  116,   94,  117,
      110,  115,  153,  152,  147,  153,  159,  158,  155,  159,
      172,  171,  169,  172,  163,  179,  161,  163,  166,  164,
      166,  177,  176,  177,  173,  174,   10,    9,   10,    1,

        1,    0,   93,   87,    3,    0,    0,    0,  134,    0,
      142,  130,    0,    0,  144,   90,  102,   98,  100,   99,
      101,   85,   84,  124,  105,  103,    0,  129,    0,    0,
       96,   67,   68,    0,    0,   88,   86,  126,   89,   92,
        0,    0,  143,    0,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,   76,  145,  145,  145,  145,
      145,  145,  145,   27,  145,   16,    0,  145,  145,  145,
       11,   77,  145,   14,  145,  145,  145,  145,  145,  145,
      145,  160,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,   91,  104,   97,    0,    0,    0,

      151,  150,  148,  149,  156,  157,  170,  162,  164,  165,
      175,   10,    9,   10,   10,   79,    0,  137,    0,  136,
        0,  142,  141,  140,  144,   82,   81,  127,    0,  128,
       69,    0,  139,  138,  143,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,   53,   80,  145,  145,  145,
      145,   31,  145,  145,  145,  145,  145,   70,  145,  145,
        0,   47,  145,  145,   72,   15,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,   25,  145,  145,
      145,   37,  145,  145,  145,   50,  145,  145,   12,  145,
      145,  145,    0,    6,    0,    0,   10,   10,   78,  137,

        0,  136,    0,  135,  141,  140,    0,   69,    0,  139,
      138,  145,  145,  145,   74,  145,  145,  145,  145,  145,
       22,  145,   28,  145,  145,  145,  145,  145,  145,   48,
      145,  145,   17,  167,  145,  145,   23,   13,  145,  145,
      145,  145,  145,  145,  145,   55,   58,   73,   20,   49,
      145,   40,   21,  145,  145,  145,   35,  145,   34,    0,
        0,   10,   10,    0,    0,  127,    0,  111,   52,   75,
       51,   54,  145,  145,  145,    0,   29,  145,   24,  145,
       32,  145,  145,  145,  145,   62,  145,  145,   26,   63,
       59,  145,  145,    0,  145,   57,  145,   45,   30,  145,

        0,    0,    5,   10,    8,   10,    7,    0,    0,    0,
      145,  145,   43,  145,   42,   39,  145,  145,    0,   60,
      145,  145,   46,   41,  145,  145,   44,  145,    0,    0,
      131,    0,  145,   36,  145,   56,  145,    0,  145,    0,
      145,  145,   33,    0,    4,  133,  132,   38,  145,    0,
        0,    0,    0,    0,  145,  145,  145,    0,   71,   64,
        0,    0,   19,   61,  145,    0,   65,  145,   66,   18,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       29,   34,   35,   29,   29,   29,   29,   36,   37,   29,
       29,   38,   39,   40,   41,   29,   29,   29,   29,   29,
       42,   43,   44,   45,   46,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   29,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   29,   71,   72,   73,   74,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    2,    1,    1,
        1,    1,    1,    5,    2,    1,    6,    4,    2,    7,
        2,    1,    8,    9,   10,    2,    1,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,    1,    1,    1,    1,   12,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   13,   11,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[521] =
    {   0,
        0, 1082,   72,   73,   74,   77,   78,   79,   80,   81,
       83,   84,   86,   87, 1102,   88, 1104, 1107,   92, 1107,
       91,   87, 1107,    0,  120,   96, 1093, 1107, 1107, 1107,
     1078,   89, 1107,  111,  113,   86,  121,  124, 1107,  140,
       82, 1077, 1074,  128, 1082,   91,  127,  128, 1107, 1107,
     1107,  130,  133,  132,  135,  150,  134,  151,  161,  156,
      146,  162,  163,  179,  187,  169,  145, 1107, 1026, 1107,
      132,  196, 1107, 1107, 1107,  211, 1107, 1107, 1107,  200,
     1107, 1107, 1107, 1078, 1107, 1107, 1107, 1077, 1107, 1042,
     1075, 1107, 1107,    0, 1107, 1107, 1090, 1107,  215,  167,

      181, 1023, 1107, 1107,    0,    0, 1052,    0, 1070,    0,
        0,    0,    0,    0,    0, 1107, 1107, 1107, 1107, 1107,
     1107, 1107,  206, 1107, 1107, 1107, 1069,  220,  238,    0,
     1107, 1107, 1107, 1086, 1085, 1084, 1107, 1107, 1107, 1107,
        0,    0,    0,    0, 1068,  220,  215,  224,  229,  232,
      225,  239,  242,  240,  244, 1067,  245,  246,  248,  250,
      251,  256,  257, 1066,  252,  258, 1029,  261,  260,  263,
     1064,  264,  268, 1063,  265,  266,  269,  275,  278,  270,
      271, 1107,  280,  281,  285,  284,  288,  289,  302,  293,
      297,  306,  317,  320, 1107, 1107, 1107, 1076,  338,  115,

     1107, 1107, 1107, 1107, 1107, 1107, 1107, 1107, 1107, 1107,
     1107, 1072, 1107,  339,  341, 1107,    0,    0, 1022,    0,
     1011,    0,    0,    0,    0, 1107, 1107,  328,  951,  950,
        0,  967,    0,    0,    0,  946,  329,  332,  336,  334,
      338,  339,  344,  347,  348,  945,  944,  353,  356,  349,
      350,  939,  352,  357,  354,  358,  360,  938,  359,  361,
      935,  932,  363,  364,  930,  925,  367,  365,  369,  371,
      373,  375,  376,  377,  378,  382,  398,  920,  399,  380,
      401,  403,  404,  405,  408,  919,  413,  418,  918,  419,
      420,  421,  927, 1107,  436,  439,  440,  442, 1107,    0,

      898,    0,  903, 1107,    0,    0,  433,    0,  444,    0,
        0,  906,  437,  430,  905,  439,  435,  441,  443,  445,
      904,  898,  897,  446,  450,  440,  453,  455,  459,  892,
      451,  457,  891, 1107,  462,  463,  890,  885,  467,  465,
      466,  468,  469,  474,  470,  884,  883,  878,  877,  852,
      473,  851,  850,  471,  477,  478,  836,  483,  480,  498,
      849,  848,  837,  507,  819,  818,  511, 1107,  818,  809,
      808,  804,  490,  486,  494,  755,  774,  495,  770,  499,
      763,  508,  506,  529,  510,  762,  512,  515,  761,  755,
      754,  530,  531,  707,  532,  752,  534,  751,  750,  535,

      551,  759, 1107,  757, 1107,  752, 1107,  712,  713,  707,
      541,  539,  730,  548,  729,  728,  544,  547,  717,  722,
      546,  549,  719,  706,  551,  552,  605,  554,  615,  579,
     1107,  576,  555,  597,  557,  595,  571,    0,  558,  586,
      559,  564,  591,  602, 1107, 1107, 1107,  579,  560,  580,
      567,  566,  564,    0,  561,  563,  572,  560, 1107, 1107,
        0,  558,  159,  153,  569,  129, 1107,  576, 1107,   92,
     1107,  629,  642,  655,  668,  681,  694,  707,  720,  730,
      740,  752,  762,  770,  775,  788,  801,  814,  817,  820,
      823,  830,  833,  836,  843,  846,  849,  852,  859,  862,

      875,  888,  892,  899,  906,  913,  920,  927,  939,  946,
      953,  961,  974,  987, 1000, 1013, 1026, 1039, 1052, 1065
    } ;

static const flex_int16_t yy_def[521] =
    {   0,
      471,    1,  472,  472,  473,  473,  474,  474,  475,  475,
      476,  476,  477,  477,  478,  478,  471,  471,  471,  471,
      471,  471,  471,  479,  480,  481,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  482,
      471,  471,  471,  483,  484,  484,  484,  484,  471,  471,
      471,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  471,  471,  471,
      471,  485,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  486,  471,  471,  487,  471,  487,  471,

      471,  488,  471,  471,  479,  489,  471,  490,  471,  491,
      492,  492,  493,  494,  495,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  496,
      471,  471,  471,  482,  482,  482,  471,  471,  471,  471,
      497,  498,  499,  500,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  471,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  471,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  471,  471,  471,  501,  501,  501,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  487,  471,  487,  487,  471,  502,  503,  471,  504,
      505,  492,  506,  507,  495,  471,  471,  471,  471,  471,
      508,  509,  510,  511,  499,  512,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      471,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  501,  471,  501,  501,  487,  487,  471,  503,

      471,  504,  505,  471,  506,  507,  471,  508,  509,  510,
      511,  512,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  471,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  501,
      513,  514,  515,  471,  471,  471,  509,  471,  484,  484,
      484,  484,  484,  484,  484,  500,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  500,  484,  484,  484,  484,  484,  484,

      501,  513,  471,  514,  471,  515,  471,  471,  471,  471,
      484,  484,  484,  512,  484,  484,  484,  484,  471,  484,
      484,  484,  484,  484,  512,  484,  484,  484,  516,  471,
      471,  471,  484,  484,  512,  484,  484,  517,  484,  471,
      512,  484,  484,  516,  471,  471,  471,  484,  512,  471,
      518,  517,  471,  519,  512,  484,  512,  518,  471,  471,
      520,  519,  512,  484,  512,  520,  471,  512,  471,  512,
        0,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471
    } ;

static const flex_int16_t yy_nxt[1182] =
    {   0,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   45,   46,
       45,   45,   47,   45,   45,   45,   45,   45,   45,   48,
       45,   49,   18,   50,   51,   45,   45,   45,   52,   53,
       54,   55,   56,   57,   58,   45,   45,   59,   60,   61,
       62,   45,   63,   64,   65,   66,   45,   67,   45,   45,
       68,   69,   70,   71,   74,   74,   78,   75,   75,   78,
       82,   82,   86,   86,   79,   86,   86,   79,   93,   93,
       98,  103,  101,  100,  101,  101,   83,   83,   87,   87,

      113,   90,   90,  118,  125,  137,  138,  144,  144,  126,
      104,   99,  119,  114,   76,   76,   80,  294,  146,   80,
       84,   84,   88,   88,  106,   91,   91,  120,   94,   94,
      123,  130,  141,  107,  121,  122,  124,  108,  127,  109,
      128,  134,  110,  144,  144,  142,  144,  131,  144,  144,
      144,  144,  129,  469,  132,  196,   95,   95,   96,   96,
      102,  144,  144,  136,  133,  112,  144,  144,  100,  144,
      101,  129,  144,  147,  296,  144,  149,  144,  144,  144,
      163,  167,  101,  152,  101,  144,  150,  153,  155,  151,
      148,  158,  154,  156,  159,  144,  160,  182,  193,  194,

      157,  174,  164,  144,  161,  197,  172,  168,  175,  165,
      205,  169,  162,  179,  166,  173,  201,  213,  176,  137,
      138,  177,  180,  226,  178,  183,  170,  191,  181,  184,
      171,  144,  192,  188,  185,  102,  144,  127,  186,  128,
      144,  144,  206,  199,  187,  144,  189,  200,  144,  190,
      227,  129,  229,  202,  229,  144,  144,  230,  144,  237,
      144,  144,  144,  214,  144,  215,  144,  144,  144,  203,
      129,  238,  144,  144,  144,  204,  144,  144,  241,  144,
      144,  144,  144,  242,  144,  144,  144,  144,  245,  239,
      243,  144,  246,  240,  144,  244,  144,  144,  248,  250,

      144,  144,  255,  259,  144,  144,  256,  249,  247,  144,
      252,  251,  268,  144,  253,  257,  260,  254,  144,  264,
      258,  262,  144,  266,  263,  270,  276,  277,  267,  271,
      273,  265,  269,  144,  272,  282,  144,  279,  274,  280,
      294,  213,  275,  213,  283,  144,  281,  228,  144,  278,
      144,  284,  144,  287,  144,  144,  289,  285,  313,  307,
      144,  288,  286,  144,  144,  144,  144,  290,  144,  144,
      144,  291,  144,  144,  144,  144,  144,  144,  307,  144,
      144,  144,  316,  144,  292,  144,  315,  144,  295,  144,
      319,  144,  144,  144,  144,  314,  144,  320,  144,  298,

      321,  317,  318,  322,  297,  327,  323,  328,  326,  331,
      324,  329,  325,  332,  144,  144,  335,  144,  330,  144,
      144,  144,  340,  338,  144,  333,  343,  344,  336,  144,
      337,  341,  346,  339,  144,  144,  144,  144,  294,  342,
      349,  294,  213,  345,  213,  367,  144,  365,  347,  365,
      348,  144,  366,  144,  352,  144,  144,  144,  354,  144,
      351,  144,  144,  355,  353,  350,  144,  144,  368,  144,
      369,  144,  356,  144,  359,  144,  358,  357,  144,  144,
      370,  144,  144,  144,  144,  144,  144,  144,  360,  144,
      144,  363,  371,  144,  144,  379,  144,  377,  372,  144,

      294,  361,  144,  380,  362,  373,  144,  383,  374,  375,
      144,  144,  367,  381,  378,  144,  382,  386,  387,  388,
      392,  385,  144,  395,  144,  384,  144,  390,  144,  396,
      389,  144,  393,  399,  398,  368,  411,  391,  408,  400,
      397,  409,  412,  410,  413,  144,  144,  144,  144,  419,
      144,  144,  401,  294,  417,  144,  418,  144,  415,  420,
      144,  416,  144,  144,  144,  144,  421,  144,  144,  440,
      144,  144,  450,  144,  144,  144,  144,  144,  453,  144,
      144,  450,  467,  422,  459,  144,  461,  144,  144,  424,
      460,  459,  144,  451,  423,  144,  426,  427,  435,  433,

      428,  441,  451,  434,  445,  442,  436,  144,  454,  429,
      437,  144,  464,  144,  439,  447,  446,  445,  443,  448,
      449,  144,  455,  456,  457,  463,  465,  468,  470,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   92,   92,   92,   92,   92,   92,

       92,   92,   92,   92,   92,   92,   92,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
      105,  105,  144,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  111,  111,  144,  111,  111,  144,  438,
      111,  111,  111,  115,  144,  144,  144,  432,  431,  430,
      115,  115,  115,  135,  407,  135,  135,  135,  135,  405,
      135,  403,  135,  135,  135,  143,  144,  144,  144,  425,
      144,  144,  143,  143,  143,  145,  145,  144,  144,  144,
      145,  145,  145,  198,  198,  198,  144,  198,  211,  211,
      144,  211,  211,  211,  211,  211,  211,  211,  211,  211,

      211,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  216,  216,  216,  216,  216,  414,
      144,  216,  216,  216,  144,  144,  216,  218,  218,  218,
      220,  220,  220,  221,  144,  221,  222,  366,  366,  407,
      222,  222,  222,  223,  223,  223,  224,  224,  224,  225,
      405,  403,  144,  225,  225,  225,  231,  231,  231,  233,
      233,  233,  234,  234,  234,  235,  144,  144,  144,  235,
      235,  235,  236,  236,  236,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  299,  299,
      299,  299,  299,  394,  144,  299,  299,  299,  300,  144,

      144,  144,  300,  300,  300,  302,  144,  144,  144,  302,
      302,  302,  303,  144,  376,  303,  303,  303,  303,  305,
      144,  144,  144,  305,  305,  305,  306,  304,  364,  294,
      306,  306,  306,  308,  144,  144,  144,  308,  308,  308,
      309,  144,  309,  309,  309,  309,  144,  309,  144,  309,
      309,  309,  310,  334,  144,  144,  310,  310,  310,  311,
      144,  144,  144,  311,  311,  311,  312,  312,  232,  230,
      230,  312,  312,  312,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  404,  404,  404,
      404,  404,  404,  404,  404,  404,  404,  404,  404,  404,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  444,  444,  444,  444,  444,  444,  444,
      444,  444,  444,  444,  444,  444,  452,  452,  452,  452,
      452,  452,  452,  452,  452,  304,  452,  452,  452,  458,
      458,  458,  458,  458,  458,  458,  458,  458,  458,  458,
      458,  458,  462,  462,  462,  462,  462,  462,  462,  462,
      462,  301,  462,  462,  462,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  213,  466,  466,  466,  294,  144,
      144,  261,  144,  144,  144,  232,  232,  134,  228,  109,
      219,  217,  213,  210,  209,  208,  207,  195,  144,  140,

      139,  117,  116,  471,   98,   72,   17,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471
    } ;

static const flex_int16_t yy_chk[1182] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,    3,    4,    6,
        7,    8,    9,   10,    5,   11,   12,    6,   13,   14,
       16,   22,   21,   19,   21,   19,    7,    8,    9,   10,

       26,   11,   12,   32,   36,   41,   41,   46,  470,   36,
       22,   16,   32,   26,    3,    4,    5,  200,   46,    6,
        7,    8,    9,   10,   25,   11,   12,   34,   13,   14,
       35,   38,   44,   25,   34,   34,   35,   25,   37,   25,
       37,   40,   25,   47,   48,   44,   52,   38,   54,   53,
       57,   55,   37,  466,   38,   71,   13,   14,   13,   14,
       19,   67,   61,   40,   38,   25,   56,   58,  100,  464,
      100,   37,   60,   47,  200,  463,   52,   59,   62,   63,
       57,   59,  101,   53,  101,   66,   52,   53,   54,   52,
       48,   55,   53,   54,   55,   64,   56,   64,   67,   67,

       54,   61,   58,   65,   56,   71,   60,   59,   62,   58,
       80,   59,   56,   63,   58,   60,   76,   99,   62,   72,
       72,   62,   63,  123,   62,   64,   59,   66,   63,   64,
       59,  147,   66,   65,   64,  100,  146,  128,   64,  128,
      148,  151,   80,   72,   64,  149,   65,   72,  150,   65,
      123,  128,  129,   76,  129,  152,  154,  129,  153,  146,
      155,  157,  158,   99,  159,   99,  160,  161,  165,   76,
      128,  147,  162,  163,  166,   76,  169,  168,  150,  170,
      172,  175,  176,  151,  173,  177,  180,  181,  153,  148,
      152,  178,  153,  149,  179,  152,  183,  184,  154,  157,

      186,  185,  162,  165,  187,  188,  162,  155,  153,  190,
      159,  158,  176,  191,  160,  163,  166,  161,  189,  170,
      163,  168,  192,  173,  169,  178,  180,  181,  175,  178,
      179,  172,  177,  193,  178,  187,  194,  184,  179,  185,
      199,  214,  179,  215,  188,  237,  186,  228,  238,  183,
      240,  189,  239,  191,  241,  242,  192,  189,  237,  228,
      243,  191,  190,  244,  245,  250,  251,  193,  253,  248,
      255,  193,  249,  254,  256,  259,  257,  260,  228,  263,
      264,  268,  240,  267,  194,  269,  239,  270,  199,  271,
      243,  272,  273,  274,  275,  238,  280,  244,  276,  215,

      245,  241,  242,  248,  214,  253,  249,  254,  251,  257,
      249,  255,  250,  259,  277,  279,  263,  281,  256,  282,
      283,  284,  270,  268,  285,  260,  273,  274,  264,  287,
      267,  271,  276,  269,  288,  290,  291,  292,  295,  272,
      280,  296,  297,  275,  298,  309,  314,  307,  277,  307,
      279,  317,  307,  313,  283,  316,  326,  318,  285,  319,
      282,  320,  324,  287,  284,  281,  325,  331,  309,  327,
      313,  328,  288,  332,  292,  329,  291,  290,  335,  336,
      314,  340,  341,  339,  342,  343,  345,  354,  295,  351,
      344,  298,  316,  355,  356,  326,  359,  324,  317,  358,

      360,  296,  374,  327,  297,  318,  373,  331,  319,  320,
      375,  378,  367,  328,  325,  380,  329,  336,  339,  340,
      344,  335,  383,  351,  382,  332,  385,  342,  387,  354,
      341,  388,  345,  358,  356,  367,  373,  343,  364,  359,
      355,  364,  374,  364,  375,  384,  392,  393,  395,  384,
      397,  400,  360,  401,  382,  412,  383,  411,  378,  385,
      417,  380,  421,  418,  414,  422,  387,  425,  426,  422,
      428,  433,  437,  435,  439,  441,  449,  455,  439,  456,
      442,  450,  462,  388,  458,  465,  453,  437,  457,  393,
      452,  451,  468,  437,  392,  448,  395,  397,  414,  411,

      400,  425,  450,  412,  444,  426,  417,  443,  440,  401,
      418,  436,  456,  434,  421,  432,  430,  429,  428,  433,
      435,  427,  441,  442,  449,  455,  457,  465,  468,  472,
      472,  472,  472,  472,  472,  472,  472,  472,  472,  472,
      472,  472,  473,  473,  473,  473,  473,  473,  473,  473,
      473,  473,  473,  473,  473,  474,  474,  474,  474,  474,
      474,  474,  474,  474,  474,  474,  474,  474,  475,  475,
      475,  475,  475,  475,  475,  475,  475,  475,  475,  475,
      475,  476,  476,  476,  476,  476,  476,  476,  476,  476,
      476,  476,  476,  476,  477,  477,  477,  477,  477,  477,

      477,  477,  477,  477,  477,  477,  477,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      479,  479,  424,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  480,  480,  423,  480,  480,  420,  419,
      480,  480,  480,  481,  416,  415,  413,  410,  409,  408,
      481,  481,  481,  482,  406,  482,  482,  482,  482,  404,
      482,  402,  482,  482,  482,  483,  399,  398,  396,  394,
      391,  390,  483,  483,  483,  484,  484,  389,  386,  381,
      484,  484,  484,  485,  485,  485,  379,  485,  486,  486,
      377,  486,  486,  486,  486,  486,  486,  486,  486,  486,

      486,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  487,  487,  487,  488,  488,  488,  488,  488,  376,
      372,  488,  488,  488,  371,  370,  488,  489,  489,  489,
      490,  490,  490,  491,  369,  491,  492,  366,  365,  363,
      492,  492,  492,  493,  493,  493,  494,  494,  494,  495,
      362,  361,  357,  495,  495,  495,  496,  496,  496,  497,
      497,  497,  498,  498,  498,  499,  353,  352,  350,  499,
      499,  499,  500,  500,  500,  501,  501,  501,  501,  501,
      501,  501,  501,  501,  501,  501,  501,  501,  502,  502,
      502,  502,  502,  349,  348,  502,  502,  502,  503,  347,

      346,  338,  503,  503,  503,  504,  337,  333,  330,  504,
      504,  504,  505,  323,  322,  505,  505,  505,  505,  506,
      321,  315,  312,  506,  506,  506,  507,  303,  301,  293,
      507,  507,  507,  508,  289,  286,  278,  508,  508,  508,
      509,  266,  509,  509,  509,  509,  265,  509,  262,  509,
      509,  509,  510,  261,  258,  252,  510,  510,  510,  511,
      247,  246,  236,  511,  511,  511,  512,  512,  232,  230,
      229,  512,  512,  512,  513,  513,  513,  513,  513,  513,
      513,  513,  513,  513,  513,  513,  513,  514,  514,  514,
      514,  514,  514,  514,  514,  514,  514,  514,  514,  514,

      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  516,  516,  516,  516,  516,  516,  516,
      516,  516,  516,  516,  516,  516,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  221,  517,  517,  517,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  519,  519,  519,  519,  519,  519,  519,  519,
      519,  219,  519,  519,  519,  520,  520,  520,  520,  520,
      520,  520,  520,  520,  212,  520,  520,  520,  198,  174,
      171,  167,  164,  156,  145,  136,  135,  134,  127,  109,
      107,  102,   97,   91,   90,   88,   84,   69,   45,   43,

       42,   31,   27,   17,   15,    2,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[180] =
    {   0,
0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "raku.l"
#line 2 "raku.l"
#include "raku.tab.h"
#include "rk_opname.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static char raku_strbuf[65536];
static int  raku_strpos;
static int raku_after_smatch  = 0;
static int raku_match_global   = 0;
static char *raku_subst_pat    = NULL;
static int raku_expect_rebody  = 0;
static int rebody_depth   = 0;
void raku_lex_error(const char *msg) {
    fprintf(stderr, "raku lex error line %d: %s\n", raku_yylineno, msg);
}
/*--------------------------------------------------------------------------------------------------------------------*/
int raku_get_lineno(void) { return raku_yylineno; }
#line 1183 "raku.lex.c"
#define YY_NO_INPUT 1

#line 1186 "raku.lex.c"

#define INITIAL 0
#define STR_DQ 1
#define STR_SQ 2
#define STR_RE 3
#define STR_SUBST_PAT 4
#define STR_SUBST_REPL 5
#define STR_REBODY 6
#define POD 7

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 30 "raku.l"

#line 1413 "raku.lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 472 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1107 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "raku.l"
{ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 32 "raku.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "raku.l"
{ }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 34 "raku.l"
{ BEGIN(POD); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 35 "raku.l"
{ BEGIN(POD); }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 36 "raku.l"
{ BEGIN(POD); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 37 "raku.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 38 "raku.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 39 "raku.l"
{ }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 40 "raku.l"
{ }
	YY_BREAK
case YY_STATE_EOF(POD):
#line 41 "raku.l"
{ BEGIN(INITIAL); yyterminate(); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "raku.l"
{ return KW_MY; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "raku.l"
{ return KW_USE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "raku.l"
{ raku_yylval.sval = strdup(yytext); return TESTOP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "raku.l"
{ return KW_SAY; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "raku.l"
{ return KW_PRINT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "raku.l"
{ return KW_IF; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "raku.l"
{ return KW_ELSE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "raku.l"
{ return KW_ELSIF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "raku.l"
{ return KW_WHILE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "raku.l"
{ return KW_FOR; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "raku.l"
{ return KW_GIVEN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "raku.l"
{ return KW_WITHOUT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "raku.l"
{ return KW_WITH; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 66 "raku.l"
{ return KW_WHEN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 67 "raku.l"
{ return KW_DEFAULT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 68 "raku.l"
{ return KW_SUB; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 69 "raku.l"
{ return KW_CONSTANT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 70 "raku.l"
{ return KW_GATHER; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 71 "raku.l"
{ return KW_TAKE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 72 "raku.l"
{ return KW_RETURN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 73 "raku.l"
{ return KW_EXISTS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 74 "raku.l"
{ return KW_DELETE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 75 "raku.l"
{ return KW_UNLESS; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 76 "raku.l"
{ return KW_UNTIL; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 77 "raku.l"
{ return KW_REPEAT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 78 "raku.l"
{ return KW_MAP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 79 "raku.l"
{ return KW_GREP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 80 "raku.l"
{ return KW_SORT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 81 "raku.l"
{ return KW_TRY; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 82 "raku.l"
{ return KW_CATCH; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 83 "raku.l"
{ return KW_CATCH; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 84 "raku.l"
{ return KW_DIE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 85 "raku.l"
{ return KW_CLASS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 86 "raku.l"
{ return KW_ROLE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 87 "raku.l"
{ return KW_GRAMMAR; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 88 "raku.l"
{ raku_expect_rebody = 1; return KW_TOKEN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 89 "raku.l"
{ raku_expect_rebody = 1; return KW_RULE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 90 "raku.l"
{ raku_expect_rebody = 1; return KW_REGEX; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 91 "raku.l"
{ return KW_METHOD; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 92 "raku.l"
{ return KW_METHOD; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 93 "raku.l"
{ return KW_MULTI; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 94 "raku.l"
{ return KW_PROTO; }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 95 "raku.l"
{ char raw[64]; int rl=(int)yyleng-8; if(rl>63)rl=63; memcpy(raw,yytext+7,rl); raw[rl]=0; char cb[96]; rk_op_canon_base("infix",raw,cb,sizeof cb); raku_yylval.sval=strdup(cb); return OP_NAME; }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 96 "raku.l"
{ char raw[64]; int rl=(int)yyleng-9; if(rl>63)rl=63; memcpy(raw,yytext+8,rl); raw[rl]=0; char cb[96]; rk_op_canon_base("prefix",raw,cb,sizeof cb); raku_yylval.sval=strdup(cb); return OP_NAME; }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 97 "raku.l"
{ char raw[64]; int rl=(int)yyleng-10; if(rl>63)rl=63; memcpy(raw,yytext+9,rl); raw[rl]=0; char cb[96]; rk_op_canon_base("postfix",raw,cb,sizeof cb); raku_yylval.sval=strdup(cb); return OP_NAME; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 98 "raku.l"
{ return OP_COLON_D; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 99 "raku.l"
{ return OP_COLON_U; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 100 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_SCALAR; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 101 "raku.l"
{ return KW_HAS; }
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 102 "raku.l"
{ const char *lt = strchr(yytext,'<'); const char *gt = strrchr(yytext,'>'); int n=(int)(gt-lt-1); if(n<0)n=0; char *w=(char*)malloc(n+1); memcpy(w,lt+1,n); w[n]=0; raku_yylval.sval=w; return KW_HANDLES; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 103 "raku.l"
{ return KW_NEW; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 104 "raku.l"
{ raku_yylval.sval = strdup("self"); return VAR_SCALAR; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 105 "raku.l"
{ raku_yylval.ival = 1; return LIT_INT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 106 "raku.l"
{ raku_yylval.ival = 0; return LIT_INT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 107 "raku.l"
{ return OP_SEQ; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 108 "raku.l"
{ return OP_SNE; }
	YY_BREAK
case 78:
/* rule 78 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 109 "raku.l"
{ return OP_REP_XX; }
	YY_BREAK
case 79:
/* rule 79 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 110 "raku.l"
{ return OP_REP_X; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 111 "raku.l"
{ return OP_DIV; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 112 "raku.l"
{ return OP_RANGE_EX; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 113 "raku.l"
{ return YADA; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 114 "raku.l"
{ return CARET; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 115 "raku.l"
{ return OP_RANGE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 116 "raku.l"
{ return OP_ARROW; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 117 "raku.l"
{ return OP_EQ; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 118 "raku.l"
{ return OP_NE; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 119 "raku.l"
{ return OP_LE; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 120 "raku.l"
{ return OP_GE; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 121 "raku.l"
{ return OP_AND; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 122 "raku.l"
{ return OP_OR; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 123 "raku.l"
{ return OP_TERNARY1; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 124 "raku.l"
{ return OP_TERNARY2; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 125 "raku.l"
{ return '|'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 126 "raku.l"
{ return '&'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 127 "raku.l"
{ return OP_BIND; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 128 "raku.l"
{ raku_after_smatch = 1; return OP_SMATCH; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 129 "raku.l"
{ return OP_INC; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 130 "raku.l"
{ return OP_DEC; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 131 "raku.l"
{ return OP_ADD_EQ; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 132 "raku.l"
{ return OP_SUB_EQ; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 133 "raku.l"
{ return OP_MUL_EQ; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 134 "raku.l"
{ return OP_DIV_EQ; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 135 "raku.l"
{ return OP_CAT_EQ; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 136 "raku.l"
{ return OP_DOR; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 137 "raku.l"
{ return '+'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 138 "raku.l"
{ return '-'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 139 "raku.l"
{ return '*'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 140 "raku.l"
{ return '%'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 141 "raku.l"
{ return '~'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 142 "raku.l"
{
    int n=(int)yyleng-2; char *inner=(char*)malloc(n+1); memcpy(inner,yytext+1,n); inner[n]='\0';
    raku_yylval.sval=inner; return WORDLIST; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 145 "raku.l"
{ return '<'; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 146 "raku.l"
{ return '>'; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 147 "raku.l"
{ return '!'; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 148 "raku.l"
{ return '='; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 149 "raku.l"
{ if (raku_expect_rebody) { raku_expect_rebody = 0; raku_strpos = 0; rebody_depth = 1; BEGIN(STR_REBODY); } else { return '{'; } }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 150 "raku.l"
{ return '}'; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 151 "raku.l"
{ return '('; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 152 "raku.l"
{ return ')'; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 153 "raku.l"
{ return '['; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 154 "raku.l"
{ return ']'; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 155 "raku.l"
{ return ';'; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 156 "raku.l"
{ return ','; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 157 "raku.l"
{ return OP_DOTEQ; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 158 "raku.l"
{ return '.'; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 159 "raku.l"
{ return OP_FATARROW; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 160 "raku.l"
{ raku_yylval.dval = atof(yytext); return LIT_FLOAT; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 161 "raku.l"
{ raku_yylval.dval = atof(yytext); return LIT_FLOAT; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 162 "raku.l"
{ raku_yylval.ival = atol(yytext); return LIT_INT; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 163 "raku.l"
{ raku_yylval.sval = strdup("$_"); return VAR_SCALAR; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 164 "raku.l"
{ raku_yylval.ival = 0; return VAR_FH; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 165 "raku.l"
{ raku_yylval.ival = 1; return VAR_FH; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 166 "raku.l"
{ raku_yylval.ival = 2; return VAR_FH; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 167 "raku.l"
{ raku_yylval.ival = atoi(yytext+1); return VAR_CAPTURE; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 168 "raku.l"
{
    int len = strlen(yytext)-3;
    char *nm = malloc(len+1); memcpy(nm,yytext+2,len); nm[len]='\0';
    raku_yylval.sval = nm; return VAR_NAMED_CAPTURE; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 172 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_TWIGIL; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 173 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_TWIGIL; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 174 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_ARRAY_TWIGIL; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 175 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_ARRAY_TWIGIL; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 176 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_HASH_TWIGIL; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 177 "raku.l"
{ raku_yylval.sval = strdup(yytext+1); return VAR_HASH_TWIGIL; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 178 "raku.l"
{ raku_yylval.sval = strdup(yytext); return VAR_SCALAR; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 179 "raku.l"
{ raku_yylval.sval = strdup(yytext); return VAR_ARRAY; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 180 "raku.l"
{ raku_yylval.sval = strdup(yytext); return VAR_HASH; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 181 "raku.l"
{ raku_yylval.sval = strdup(yytext); return IDENT; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 182 "raku.l"
{ raku_strpos = 0; BEGIN(STR_DQ); }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 183 "raku.l"
{
    raku_strbuf[raku_strpos] = '\0';
    raku_yylval.sval = strdup(raku_strbuf);
    BEGIN(INITIAL);
    if (strchr(raku_strbuf, '$') != NULL)
        return LIT_INTERP_STR;
    return LIT_STR;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 148:
YY_RULE_SETUP
#line 192 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 193 "raku.l"
{ raku_strbuf[raku_strpos++] = '\t'; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 194 "raku.l"
{ raku_strbuf[raku_strpos++] = '\\'; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 195 "raku.l"
{ raku_strbuf[raku_strpos++] = '"'; }
	YY_BREAK
case 152:
/* rule 152 can match eol */
YY_RULE_SETUP
#line 196 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 197 "raku.l"
{ raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 198 "raku.l"
{ raku_strpos = 0; BEGIN(STR_SQ); }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 199 "raku.l"
{
    raku_strbuf[raku_strpos] = '\0';
    raku_yylval.sval = strdup(raku_strbuf);
    BEGIN(INITIAL);
    return LIT_STR;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 156:
YY_RULE_SETUP
#line 206 "raku.l"
{ raku_strbuf[raku_strpos++] = '\''; }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 207 "raku.l"
{ raku_strbuf[raku_strpos++] = '\\'; }
	YY_BREAK
case 158:
/* rule 158 can match eol */
YY_RULE_SETUP
#line 208 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 209 "raku.l"
{ raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 210 "raku.l"
{ if (raku_after_smatch) { raku_after_smatch=0; raku_strpos=0; BEGIN(STR_SUBST_PAT); } else { yyless(1); return 's'; } }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 211 "raku.l"
{
    raku_strbuf[raku_strpos]='\0';
    raku_subst_pat = strdup(raku_strbuf);
    raku_strpos=0; BEGIN(STR_SUBST_REPL);
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 162:
YY_RULE_SETUP
#line 217 "raku.l"
{ raku_strbuf[raku_strpos++]='/'; }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 218 "raku.l"
{ raku_strbuf[raku_strpos++]=yytext[0]; }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 219 "raku.l"
{
    raku_strbuf[raku_strpos]='\0';
    int global = (yytext[1]=='g');
    size_t plen=strlen(raku_subst_pat), rlen=raku_strpos;
    char *tok = malloc(plen+rlen+4);
    memcpy(tok, raku_subst_pat, plen); tok[plen]='\x01';
    memcpy(tok+plen+1, raku_strbuf, rlen); tok[plen+1+rlen]='\x01';
    tok[plen+2+rlen] = global ? 'g' : '-'; tok[plen+3+rlen]='\0';
    free(raku_subst_pat); raku_subst_pat=NULL;
    raku_yylval.sval = tok;
    BEGIN(INITIAL); return LIT_SUBST;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 165:
YY_RULE_SETUP
#line 232 "raku.l"
{ raku_strbuf[raku_strpos++]='/'; }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 233 "raku.l"
{ raku_strbuf[raku_strpos++]=yytext[0]; }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 234 "raku.l"
{ if (raku_after_smatch) { raku_after_smatch=0; raku_strpos=0; BEGIN(STR_RE); raku_match_global=1; } else { yyless(3); return IDENT; } }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 235 "raku.l"
{ if (raku_after_smatch) { raku_after_smatch=0; raku_strpos=0; BEGIN(STR_RE); } else { return '/'; } }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 236 "raku.l"
{
    raku_strbuf[raku_strpos] = '\0';
    raku_yylval.sval = strdup(raku_strbuf);
    BEGIN(INITIAL);
    if (raku_match_global) { raku_match_global=0; return LIT_MATCH_GLOBAL; }
    return LIT_REGEX;
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 170:
YY_RULE_SETUP
#line 244 "raku.l"
{ raku_strbuf[raku_strpos++] = '/'; }
	YY_BREAK
case 171:
/* rule 171 can match eol */
YY_RULE_SETUP
#line 245 "raku.l"
{ raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 246 "raku.l"
{ raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 247 "raku.l"
{ if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = '{'; rebody_depth++; }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 248 "raku.l"
{
    rebody_depth--;
    if (rebody_depth == 0) {
        raku_strbuf[raku_strpos] = '\0';
        raku_yylval.sval = strdup(raku_strbuf);
        BEGIN(INITIAL);
        return LIT_REGEX;
    }
    if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = '}';
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 175:
YY_RULE_SETUP
#line 259 "raku.l"
{ if (raku_strpos < 65533) { raku_strbuf[raku_strpos++] = yytext[0]; raku_strbuf[raku_strpos++] = yytext[1]; } }
	YY_BREAK
case 176:
/* rule 176 can match eol */
YY_RULE_SETUP
#line 260 "raku.l"
{ if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = '\n'; }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 261 "raku.l"
{ if (raku_strpos < 65534) raku_strbuf[raku_strpos++] = yytext[0]; }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 262 "raku.l"
{
    char buf[64];
    snprintf(buf, sizeof buf, "unexpected char '%c'", yytext[0]);
    raku_lex_error(buf);
}
	YY_BREAK
/*--------------------------------------------------------------------------------------------------------------------*/
case 179:
YY_RULE_SETUP
#line 268 "raku.l"
ECHO;
	YY_BREAK
#line 2463 "raku.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR_DQ):
case YY_STATE_EOF(STR_SQ):
case YY_STATE_EOF(STR_RE):
case YY_STATE_EOF(STR_SUBST_PAT):
case YY_STATE_EOF(STR_SUBST_REPL):
case YY_STATE_EOF(STR_REBODY):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 472 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 472 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 471);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 268 "raku.l"


