#include "zeta_depth.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/*====================================================================================================================================================================================================*/
/* ZETA-DEPTH (ZDP) IMPLEMENTATION.  DEFAULT-INERT BY CONSTRUCTION: nothing in this file runs unless SCRIP_ZDP is set in the environment, and no other translation unit calls into it on the default    */
/* arm, so the shipped build is byte-identical with this file linked in.  s133 built the lattice and reported a NEGATIVE first result -- resume_skew fired on all four witnesses, red AND green, on     */
/* IR_STATEMENT_BEGIN and never once on IR_MATCH_DEFER -- and named three defects of its own as the cause: (i) omega written into the beta cell unconditionally, (ii) gamma->beta encoded as a live     */
/* class, (iii) the operand-carried (entry_j, resume_j) pairs never walked at all.  THIS IS THAT REBUILD.  All three are fixed by MIRRORING the emitter own resolution rather than re-deriving it, and  */
/* the transfer function now reads zw_carve_k -- THE ONE CARVE AUTHORITY -- instead of re-spelling the carve out of zw_node_k.  THE FALSIFIABLE CLAIM IS UNCHANGED: does the TOP set separate the       */
/* minted reds from the minted greens, and does it land on exactly Lon five taxonomy sources?  A rebuilt instrument that still fails to separate is a REFUTATION and must be reported as one.           */
/*====================================================================================================================================================================================================*/
extern long zw_node_k(const IR_t * nd);
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
extern long zw_carve_k(const IR_t * nd);
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
extern int  zls_result_live(const IR_t * nd);
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
#define ZDP_CAP 8192
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static const IR_t * zdp_key[ZDP_CAP]; static int zdp_ina[ZDP_CAP]; static int zdp_inb[ZDP_CAP]; static int zdp_ret[ZDP_CAP]; static int zdp_wy[ZDP_CAP]; static int zdp_src[ZDP_CAP]; static int zdp_used = 0; static int zdp_valid = 0;
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_mode(void) { static int m = -1; if (m < 0) { const char * e = getenv("SCRIP_ZDP"); m = (e && *e && *e != '0') ? atoi(e) : 0; } return m; }   /* 0 = inert (default, shipped build) | 1 = analyze + per-graph census to stderr | 2 = census + per-node detail | 3 = + port census.  Read ONCE; no other gate exists and no template consults this pass yet -- consumers arrive in a later rung under their own killswitch, per the migration law. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static unsigned zdp_h(const IR_t * p) { unsigned long long v = (unsigned long long)(size_t)p; v ^= v >> 33; v *= 0xff51afd7ed558ccdULL; v ^= v >> 33; return (unsigned)(v & (ZDP_CAP - 1)); }   /* open-addressed pointer hash: the pass is per-graph and read-mostly, so a linear probe over a power-of-two table beats threading an index field through IR_t -- and the PEERS RULE forbids adding fields to IR_t regardless. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_slot(const IR_t * nd, int create) { if (!nd) return -1; unsigned i = zdp_h(nd); for (int probe = 0; probe < ZDP_CAP; probe++) { unsigned j = (i + (unsigned)probe) & (ZDP_CAP - 1); if (zdp_key[j] == nd) return (int)j; if (!zdp_key[j]) { if (!create) return -1; zdp_key[j] = nd; zdp_ina[j] = ZDP_BOT; zdp_inb[j] = ZDP_BOT; zdp_ret[j] = ZDP_BOT; zdp_wy[j] = ZDP_UNREACHED; zdp_src[j] = 0; zdp_used++; return (int)j; } } return -1; }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_meet(int a, int b) { if (a == ZDP_BOT) return b; if (b == ZDP_BOT) return a; if (a == ZDP_TOP || b == ZDP_TOP) return ZDP_TOP; return (a == b) ? a : ZDP_TOP; }   /* THE MEET.  Height-2 lattice (BOT < n < TOP) so every point descends at most twice and the worklist fixpoint is O(E) -- Kildall on the constant-propagation lattice, the same shape a JVM verifier and WASM validation use for exactly this question.  n meet m = TOP for n != m IS case (a) and case (b) simultaneously; nothing distinguishes them and nothing needs to. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_carve_dynamic(const IR_t * nd) { if (!nd) return 0; switch (nd->op) { case IR_STATEMENT: case IR_BOUND: case IR_UNMARK: return 1; default: return 0; } }   /* THE THIRD SOURCE OF TOP, AND IT IS NOT A THIRD CASE: a SINGLE box whose own carve is not a compile-time constant (op_stmt_dyn class -- emit.h:624 already models it correctly and cures it correctly with a depth-immune base, which is the existing proof the approach works).  Lon two cases are both about an unknown COUNT of boxes; this is a known count of ONE box at an unknown SIZE.  Same TOP, same cure. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static long zdp_carve(const IR_t * nd) { return nd ? zw_carve_k(nd) : 0L; }   /* THE ONE CARVE AUTHORITY, READ NOT RE-DERIVED.  s133 spelled this as `zls_result_live(nd) ? zw_node_k(nd) : 0`, which is a SECOND OPINION about a number zw_carve_k already owns: it misses the _spine exclusion (BINOP/ASSIGN/LIT-family/VAR/CMP_TEST/COERCE_NUMERIC carve ZERO on the rsp FORTH spine), the fc_geom fixed-cell exclusion, the grammar-box exclusion and the ZC_PORT_FORTH regime gate -- so it credited a carve to every node the allocator never charges.  A lattice whose transfer function disagrees with the allocator measures a machine that does not exist. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_out_gamma(const IR_t * nd, int in) { if (in == ZDP_TOP) return ZDP_TOP; if (zdp_carve_dynamic(nd)) return ZDP_TOP; return zls_result_live(nd) ? in + (int)zdp_carve(nd) : in; }   /* SUCCESS EXIT: under CARVE-ERAD a box allocates at alpha and releases at gamma/omega, EXCEPT a spine producer holding its cell live for a downstream consumer (RESULT-IS-THE-CELL).  zls_result_live is that flag; the bytes come from zw_carve_k so allocator and lattice cannot hold two opinions about one carve. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_out_omega(const IR_t * nd, int in) { if (in == ZDP_TOP) return ZDP_TOP; if (zdp_carve_dynamic(nd)) return ZDP_TOP; return in; }   /* FAILURE EXIT: the cell is dead on the fail edge, so the box releases what it carved and omega leaves the frontier where alpha found it.  THIS IS THE MODEL OF THE INTENDED PROTOCOL, NOT A MEASUREMENT OF THE MACHINE -- a box that fails to release on omega diverges from this and that divergence IS the bug class. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_disagree(int a, int b) { return (a != ZDP_BOT && b != ZDP_BOT && a != ZDP_TOP && b != ZDP_TOP && a != b); }   /* GENUINE DISAGREEMENT vs INHERITED TOP.  TOP is ABSORBING, so one unsound point floods every node downstream and a raw TOP COUNT measures TAINT, not defects.  A node is a SOURCE iff its own meet put two DISTINCT FINITE depths together (or its carve is dynamic); everything else merely inherited.  The source set is the answer; the taint set is only its shadow. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static void zdp_push(const IR_t ** wl, int * wn, const IR_t * nd) { if (*wn < ZDP_CAP) wl[(*wn)++] = nd; }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static void zdp_edge(int t, int val, int is_beta, const IR_t ** wl, int * wn, const IR_t * succ) { if (t < 0) return; int * cell = is_beta ? &zdp_inb[t] : &zdp_ina[t]; if (zdp_disagree(*cell, val)) zdp_src[t] = 1; int nv = zdp_meet(*cell, val); if (nv != *cell) { *cell = nv; zdp_push(wl, wn, succ); } }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_tag(const char * sz) { if (sz[0] == (char)0xce && (unsigned char)sz[1] == 0xb2) return 1; if (sz[0] == (char)0xcf && (unsigned char)sz[1] == 0x83) return 2; if (sz[0] == (char)0xcf && (unsigned char)sz[1] == 0x86) return 3; return 0; }   /* THE ENTRY-PORT TAG carried on the edge itself: 0=alpha (untagged default) 1=beta (0xce 0xb2).  0xcf83 / 0xcf86 are NOT PORTS -- they are the n-ary ALT/ARBNO INTERNAL GLUE defines (na_s / na_f, emit.cpp:1391-1394), and FOUR PORT NAMES ONLY (s133) forbids ever presenting them as a fifth or sixth port.  They are recognised here solely so a RETURN edge can be routed to the return-depth check instead of being mistaken for a fresh alpha entry.  Mirrors emit.cpp:2999-3001 exactly; if those move this must move with them. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static const IR_t * zdp_chase(const IR_t * t, int * tag) { int g = 0; while (t && t->op == IR_GOTO && g++ < 128) { int nt = zdp_tag(t->γ.sz); if (nt && !*tag) *tag = nt; t = t->γ.node; } return t; }   /* GOTO-CHASE, mirroring emit.cpp:3002-3003: an edge through a folded unconditional goto carries its port tag on the CHASED node, so a raw ->node read gets both the wrong target and the wrong port.  The optimizer GOTO-chase folds these to bare edges, so this is the common path, not a corner -- and s133 walk did not do it at all. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_beta_is_stmt_land(const IR_t * tgt) { return tgt && tgt->op == IR_STATEMENT_BEGIN; }   /* MIRROR of emit.cpp:2104, not a second opinion: a beta-edge into IR_STATEMENT_BEGIN is a PURE LANDING PAD (by the UNWIND LAW every box already freed its own K rolling home, so rsp is at claim base on arrival), while a beta-edge anywhere else is an in-match scanner RETRY back-edge.  s133 conflated the two by writing every omega into the beta cell unconditionally -- which is exactly why its skew fired on IR_STATEMENT_BEGIN in all four witnesses and never once on IR_MATCH_DEFER. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_land_value(const IR_t * tgt, int v) { (void)tgt; return v; }   /* ⛔ THE LANDING RESET IS GONE (Lon in-chat s134: "Both STATEMENT_BEGIN and MATCH_BEGIN must be guaranteed MEET points").  This function briefly forced incoming edges at statement landings to 0 on the strength of the UNWIND LAW, which collapsed top_join 9->1 and made the tier split look sane.  IT WAS THE SAME KLUDGE AS THE MATCH_BEGIN WHACK AND IT HID THE SAME CLASS OF DEFECT: if a guaranteed meet point does not meet, the guarantee is being violated somewhere upstream and the instrument job is to SAY SO, not to restore the invariant by fiat.  The identity kept as a named seam so no seat re-introduces the reset by accident. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_has_pairs(const IR_t * nd) { if (!nd || nd->n_operands <= 0) return 0; switch (nd->op) { case IR_MATCH_ALTERNATE: case IR_MATCH_ARBNO: case IR_MATCH_FENCE1: case IR_SCAN_SEQUENCE: case IR_SCAN_ALTERNATE: case IR_DISJUNCTION: return 1; default: return 0; } }   /* THE SECOND BETA-TARGETING CLASS, INVISIBLE TO ANY GAMMA/OMEGA WALK (s133 named it and could not walk it).  Op set copied from emit.cpp:3082 -- the exact guard routing a node into flat_drive_match_alt -- so the traversal walks an edge iff the emitter drives one.  It contains Lon sources (3) ARBNO, (4) FENCE1 and (5) ALTERNATE by construction, which is why a walk missing it could not possibly validate his taxonomy. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_pairs_n(const IR_t * nd) { int N = (nd->op == IR_MATCH_ARBNO) ? 1 : (nd->op == IR_DISJUNCTION) ? (int)IR_LIT(nd).ival : nd->n_operands / 2; if (N < 0) N = 0; if (2 * N > nd->n_operands) N = nd->n_operands / 2; return N; }   /* MIRROR of emit.cpp:1392: ARBNO carries one (entry,resume) pair plus geometry/seal markers, DISJUNCTION rides N on ival because its operands are (entry,resume)xN THEN resultxN, everything else is n_operands/2.  Clamped so a malformed node cannot walk past its own operand array. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_inside_of(const IR_t * nd, int in) { if (in == ZDP_TOP) return ZDP_TOP; if (in == ZDP_BOT) return ZDP_BOT; if (zdp_carve_dynamic(nd)) return ZDP_TOP; return in + (int)zdp_carve(nd); }   /* THE DEPTH THE ARMS RUN AT.  A dispatcher carves its own choice record at its alpha and THEN hands control to an arm, so the arm entry (and the arm resume) sees in + carve -- never the dispatcher own arrival depth.  This is the value that rides the operand edges. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_analyze(IR_graph_t * g) {
    if (!g || !g->entry || g->n <= 0) return 0;
    memset(zdp_key, 0, sizeof(zdp_key)); zdp_used = 0; zdp_valid = 0;
    for (int i = 0; i < g->n; i++) (void)zdp_slot(g->all[i], 1);
    int es = zdp_slot(g->entry, 1); if (es < 0) return 0;
    zdp_ina[es] = 0;
    const IR_t * wl[ZDP_CAP]; int wn = 0; zdp_push(wl, &wn, g->entry); int guard = 0;
    while (wn > 0 && guard++ < ZDP_CAP * 16) {
        const IR_t * nd = wl[--wn]; int s = zdp_slot(nd, 0); if (s < 0) continue;
        int gtag = zdp_tag(nd->γ.sz); const IR_t * gtgt = zdp_chase(nd->γ.node, &gtag);
        int otag = zdp_tag(nd->ω.sz); const IR_t * otgt = zdp_chase(nd->ω.node, &otag);
        int omega_is_retry = (otag == 1) && !zdp_beta_is_stmt_land(otgt);   /* MIRROR emit.cpp:3004 -- "read it, never mint a second opinion" (s133 cursor, and this is the line it meant).  omega->beta is an in-match retry back-edge; omega into a STATEMENT_BEGIN landing pad is an alpha entry at statement granularity, and writing THAT into the beta cell is what made every witness report RESUME-SKEW. */
        int ports[2]; ports[0] = zdp_ina[s]; ports[1] = zdp_inb[s];
        for (int pi = 0; pi < 2; pi++) {
            int in = ports[pi]; if (in == ZDP_BOT) continue;
            if (gtgt) {
                int gv = zdp_out_gamma(nd, in);
                if (gtag == 2 || gtag == 3) { int t = zdp_slot(gtgt, 1); if (t >= 0) { if (zdp_disagree(zdp_ret[t], gv)) zdp_src[t] = 1; int nv = zdp_meet(zdp_ret[t], gv); if (nv != zdp_ret[t]) { zdp_ret[t] = nv; zdp_push(wl, &wn, gtgt); } } }   /* SIGMA/PHI RETURN.  This edge RETURNS INTO the enclosing box internal dispatch; it is NOT a port and must never be presented as one.  Its depth is accumulated as that box RETURN depth and checked against the depth the box dispatched its arms at -- a disagreement there IS Lon source (5), an ALTERNATE whose accumulated carve past its own gamma depends on WHICH ARM RAN.  Propagating it into the target alpha instead would manufacture a join the machine does not have, which is the shape of s133 defect (ii). */
                else zdp_edge(zdp_slot(gtgt, 1), zdp_land_value(gtgt, gv), 0, wl, &wn, gtgt);   /* GAMMA LANDS ALPHA.  Measured law (s133, 16,082 edges): gamma->beta cross-box is not rare but STRUCTURALLY IMPOSSIBLE -- the target alpha never ran, so no cell exists for beta to read.  Encoding it as a live class was s133 own defect (ii). */
            }
            if (otgt) zdp_edge(zdp_slot(otgt, 1), zdp_land_value(otgt, zdp_out_omega(nd, in)), omega_is_retry, wl, &wn, otgt);   /* MATCH_BEGIN.beta IS A MEET AND MUST STAY ONE (Lon in-chat s134): it is THE TOTAL UNWOUND SPOT, so by the UNWIND LAW every incoming omega has already released and they MUST all arrive at one frontier.  A disagreement there is NOT noise to be reset away -- it is the instrument reporting that some box on that path did not free what it carved, which is precisely the bug class zdp_out_gamma own comment names.  This seat briefly overwrote the source frontier with the target standing base, which collapsed 793 corpus-wide skews to zero and HID every one of them; the kludge is removed and the disagreeing sources are censused instead (zdp_unwind_census). */
        }
        if (zdp_has_pairs(nd)) {
            int in = (zdp_ina[s] != ZDP_BOT) ? zdp_ina[s] : zdp_inb[s];
            if (in != ZDP_BOT) {
                int inside = zdp_inside_of(nd, in); int N = zdp_pairs_n(nd);
                for (int j = 0; j < N; j++) {
                    const IR_t * e = nd->operands[2 * j]; const IR_t * r = nd->operands[2 * j + 1];
                    if (e && e->op != IR_FAIL && e != nd) zdp_edge(zdp_slot(e, 1), inside, 0, wl, &wn, e);   /* operands[2j] = entry_j, the arm ALPHA (emit.cpp:1397 routes it to lbls[k]). */
                    if (r && r->op != IR_FAIL && r != nd) zdp_edge(zdp_slot(r, 1), inside, 1, wl, &wn, r);   /* operands[2j+1] = resume_j, the arm OWN inner resume, routed to betas[k] (emit.cpp:1398) -- a genuine BETA entry, and the one every gamma/omega census is structurally blind to.  s133 defect (iii): never walked, which is why ~45% of nodes in every witness came back UNREACHED. */
                }
            }
        }
    }
    for (int i = 0; i < g->n; i++) {
        int s = zdp_slot(g->all[i], 0); if (s < 0) continue; const IR_t * nd = g->all[i];
        int inside = zdp_inside_of(nd, zdp_ina[s]);
        if (zdp_ina[s] == ZDP_BOT && zdp_inb[s] == ZDP_BOT) zdp_wy[s] = ZDP_UNREACHED;
        else if (zdp_carve_dynamic(nd)) zdp_wy[s] = ZDP_DYN;
        else if (zdp_ret[s] != ZDP_BOT && inside != ZDP_BOT && inside != ZDP_TOP && zdp_ret[s] != inside) zdp_wy[s] = ZDP_ALTRET;
        else if (zdp_inb[s] != ZDP_BOT && zdp_ina[s] != ZDP_BOT && zdp_inb[s] != zdp_ina[s]) zdp_wy[s] = ZDP_RESUME;
        else if (zdp_src[s]) zdp_wy[s] = ZDP_JOIN;
        else zdp_wy[s] = ZDP_OK;
    }
    zdp_valid = 1; return 1;
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_alpha(const IR_t * nd) { int s = zdp_valid ? zdp_slot(nd, 0) : -1; return (s < 0) ? ZDP_TOP : zdp_ina[s]; }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_beta(const IR_t * nd) { int s = zdp_valid ? zdp_slot(nd, 0) : -1; return (s < 0) ? ZDP_TOP : zdp_inb[s]; }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_inside(const IR_t * nd) { int a = zdp_alpha(nd); return zdp_inside_of(nd, a); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_known_alpha(const IR_t * nd) { int d = zdp_alpha(nd); return (d != ZDP_TOP && d != ZDP_BOT); }   /* THE PREDICATE x86_rsp_slide_known() (x86_asm.h:582) WAS HARDWIRED TO RETURN 1 FOR.  With it computable, x86_frame_off -1 unknown-depth branch stops being dead code -- but NOTHING CONSULTS THIS YET and that is deliberate: the consumer side needs the RBP registry shaped to hold whatever TOP classifies, and s131b measured what happens when it is not (trueinline_grn regressed on a one-constant re-base). */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_known_beta(const IR_t * nd) { int d = zdp_beta(nd); return (d != ZDP_TOP && d != ZDP_BOT); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_resume_sound(const IR_t * nd) { int a = zdp_alpha(nd); int b = zdp_beta(nd); if (b == ZDP_BOT) return 1; if (a == ZDP_TOP || b == ZDP_TOP) return 0; return a == b; }   /* THE BETA VERDICT THAT DID NOT EXIST.  s132: "the beta side has no verdict at all -- nothing at a beta port ever asks", which is why IR_MATCH_DEFER beta is a bare `jmp qword ptr [rsp]` three lines from IR_MATCH_ALTERNATE `mov rax,[rsp+8]`.  A bare-rsp resume read is sound IFF the frontier at resume equals the frontier at fresh entry; the fan-in meet answers exactly that, and it is the SAME lattice queried at the other port.  ONE analysis, TWO call sites -- not a taxonomy, and not a op-filter anybody has to maintain. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_why(const IR_t * nd) { int s = zdp_valid ? zdp_slot(nd, 0) : -1; return (s < 0) ? ZDP_UNREACHED : zdp_wy[s]; }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_match_lifetime(const IR_t * nd) { if (!nd) return 0; switch (nd->op) { case IR_MATCH_ASSIGN_SAVE: case IR_MATCH_ASSIGN_COND: case IR_MATCH_ASSIGN_IMM: case IR_MATCH_BEGIN: return 1; default: return 0; } }   /* THE LIFETIME HALF, DELIBERATELY SEPARATE FROM THE DEPTH HALF.  The depth lattice answers RSP-or-RBP; it CANNOT answer WHICH RBP tier, because STANDING vs ACTIVATION is a question about how long a cell lives, not about whether its address is computable.  A capture SAVE..COND/IMM span and the root MATCH_BEGIN carry cells whose live range is THE WHOLE MATCH (CAS mark at [rbp-8], outer sigma/delta/Delta, retry cursor, every registered slot at frame_slot_scan offset -(64+16*idx)); everything else on RBP is per-activation and dies with its frame.  STATED AS A FIRST CUT: this is a structural class test and the authority it must be reconciled against is frame_need_of (emit.cpp:749) with capture_frame_slot/arbno_frame_slot -- that reconciliation is the NEXT rung and is NOT claimed here. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_tier(const IR_t * nd) { if (zdp_match_lifetime(nd)) return ZDP_TIER_STANDING; if (!zdp_known_alpha(nd)) return ZDP_TIER_ACTIVATION; if (!zdp_resume_sound(nd)) return ZDP_TIER_ACTIVATION; return ZDP_TIER_SPINE; }   /* THE UNIFIED ZETA TIER VERDICT -- ONE TRAVERSAL, THREE TIERS, AND REFUSAL IS THE SAFETY PROPERTY.  SPINE(rsp) requires BOTH halves of Lon s132 model to hold: the alpha depth is a compile-time constant (his case (a) clear) AND the beta port resumes at the frontier alpha arrived on (his case (b) clear).  Either one unknown and the pass REFUSES the spine and homes the cell on a base that does not move -- structurally, once, instead of the per-rung hand judgement (leaf_frame_member, blob_choice_rbp_scan, the s128 five-term gate, the s130 eight-byte window law, the s131 BAL refuse) that each got its own corner right and the next corner wrong.  A cell whose live range is the whole match takes STANDING ahead of both tests because its LIFETIME, not its addressability, is what disqualifies the spine. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static const char * zdp_wname(int w) { switch (w) { case ZDP_OK: return "OK"; case ZDP_UNREACHED: return "UNREACHED"; case ZDP_JOIN: return "TOP-JOIN"; case ZDP_DYN: return "TOP-DYN"; case ZDP_RESUME: return "RESUME-SKEW"; case ZDP_ALTRET: return "ALT-RETURN"; default: return "?"; } }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_teardown_owner(const IR_t * nd) { if (!nd) return 0; switch (nd->op) { case IR_MATCH_BEGIN: case IR_MATCH_DEFER: case IR_MATCH_ARBNO: return 1; default: return 0; } }   /* THE TOTAL-TEARDOWN SET (Lon in-chat s134: "a check for each BETA where there is a total tear down for that activation... the difference between RSP measured at alpha and measured at beta is ZERO").  These are the boxes that ESTABLISH an activation and therefore fully discard it: MATCH_BEGIN whacks the STANDING frame (mov rsp,rbp; pop rbp), MATCH_DEFER self-pops its ACTIVATION frame at omega, and an ARBNO site discards suspended iterations at any exit (FRAME LAW s75).  Scoping the check to THIS SET is the correction to this seat first bomb, which fired at every beta and therefore could not tell a violated guarantee from an ordinary imprecision.  Where teardown is total the equation is EXACT and a mismatch is a defect, full stop. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_guaranteed_meet(const IR_t * nd) { if (!nd) return 0; switch (nd->op) { case IR_MATCH_BEGIN: case IR_STATEMENT_BEGIN: case IR_STATEMENT_END: return 1; default: return 0; } }   /* THE GUARANTEED MEET POINTS (Lon in-chat s134: "Both STATEMENT_BEGIN and MATCH_BEGIN must be guaranteed MEET points").  A statement landing is at claim base by the UNWIND LAW (emit.cpp:2104 own words) and MATCH_BEGIN.beta is the TOTAL UNWOUND SPOT, so at these three ops every incoming edge MUST carry one frontier.  They are the places where the invariant is strong enough that a violation is a BUG REPORT rather than an imprecision, which is exactly what makes them worth bombing. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void zdp_bomb_census(IR_graph_t * g, const char * tag) {
    if (!g) return; static int bm = -1; if (bm < 0) { const char * e = getenv("SCRIP_ZDP_BOMB"); bm = (e && *e && *e != '0') ? 1 : 0; } if (!bm) return;
    for (int i = 0; i < g->n; i++) { const IR_t * nd = g->all[i]; int td = zdp_teardown_owner(nd); if (!zdp_guaranteed_meet(nd) && !td) continue; int s = zdp_slot(nd, 0); if (s < 0) continue;
        if (zdp_ina[s] == ZDP_BOT && zdp_inb[s] == ZDP_BOT) continue;
        if (td && zdp_inb[s] != ZDP_BOT) { int a = zdp_ina[s], b = zdp_inb[s]; if (a == ZDP_TOP || b == ZDP_TOP || a != b) { fprintf(stderr, "[ZDPBOMB] %s op=%s TEARDOWN-SKEW\n", tag ? tag : "graph", bb_op_name(nd->op)); continue; } }   /* LON EQUATION, STATIC HALF: at a total-teardown owner the frontier at beta MUST equal the frontier at alpha, so alpha != beta (or either unknown) is the violation.  The RUNTIME half -- store rsp at alpha in a depth-immune home and cmp it at beta -- is the stronger instrument and is spelled out as the next rung; this static form is what could be closed at this seat budget and it costs no codegen risk. */
        const char * why = zdp_src[s] ? "SOURCE-DISAGREE" : (zdp_inb[s] != ZDP_BOT && zdp_ina[s] != ZDP_BOT && zdp_ina[s] != ZDP_TOP && zdp_inb[s] != ZDP_TOP && zdp_ina[s] != zdp_inb[s]) ? "ALPHA-NE-BETA" : (const char *)0;   /* ⛔ THE BOMB FIRES ON SOURCES, NEVER ON TAINT.  The first cut of this bomb tested for TOP and reported 13,801 hits over 552 of 654 programs -- and that number is WORTHLESS, for the reason zdp_disagree own comment already gives: TOP is ABSORBING, so one unsound point floods every node downstream and a raw TOP count measures the shadow, not the defect.  zdp_src[] is set only where a node OWN meet put two DISTINCT FINITE depths together.  That is a bug report; inherited TOP is not. */
        if (!why) continue;
        fprintf(stderr, "[ZDPBOMB] %s op=%s %s\n", tag ? tag : "graph", bb_op_name(nd->op), why);   /* ⛔ A GUARANTEED MEET POINT DID NOT MEET.  This is not an imprecision of the lattice: at these three ops the incoming frontier is fixed by the UNWIND LAW, so a TOP here says a box upstream did not release what it carved.  COMPILE-TIME bomb by choice -- it costs no codegen risk and no byte-identity exposure, and it fires on every program in one sweep.  The RUNTIME bomb (cmp rsp against the standing base at the landing, rt_bomb + ud2 through the existing bomb_text/bomb_bytes both-medium pair) is the stronger instrument and is the named next rung; it is a codegen change and needs its own killswitch, gate and regens. */
    }
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void zdp_unwind_census(IR_graph_t * g) {
    if (!g) return;
    for (int i = 0; i < g->n; i++) { const IR_t * b = g->all[i]; if (!b || b->op != IR_MATCH_BEGIN) continue; int bs = zdp_slot(b, 0); if (bs < 0) continue;
        int base = zdp_ina[bs]; int inside = zdp_inside_of(b, base);
        for (int j = 0; j < g->n; j++) { const IR_t * nd = g->all[j]; if (!nd) continue; int s = zdp_slot(nd, 0); if (s < 0) continue;
            int otag = zdp_tag(nd->ω.sz); const IR_t * otgt = zdp_chase(nd->ω.node, &otag); if (otgt != b) continue; if (otag != 1 || zdp_beta_is_stmt_land(otgt)) continue;
            int in = (zdp_ina[s] != ZDP_BOT) ? zdp_ina[s] : zdp_inb[s]; if (in == ZDP_BOT) continue; int v = zdp_out_omega(nd, in);
            if (v == base || v == inside) continue;
            fprintf(stderr, "[ZDPUNW] src=%s arrives=%s base=%s inside=%s carve=%ld\n", bb_op_name(nd->op), (v == ZDP_TOP) ? "TOP" : "off-base", (base == ZDP_TOP) ? "TOP" : "int", (inside == ZDP_TOP) ? "TOP" : "int", zdp_carve(nd));   /* EVERY ROW IS A BOX THAT REACHED THE TOTAL UNWOUND SPOT WITHOUT HAVING UNWOUND.  Under the UNWIND LAW this list must be EMPTY; each row names a box whose omega path did not restore the frontier it found, which is a release defect at that box, not an addressing defect at the landing. */
        } }
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void zdp_report(IR_graph_t * g, const char * tag) {
    if (!zdp_mode() || !g) return; if (!zdp_analyze(g)) return;
    int ok = 0, un = 0, tj = 0, td = 0, rs = 0, ar = 0, sp = 0, ac = 0, st = 0;
    for (int i = 0; i < g->n; i++) { int w = zdp_why(g->all[i]);
        switch (w) { case ZDP_OK: ok++; break; case ZDP_UNREACHED: un++; break; case ZDP_JOIN: tj++; break; case ZDP_DYN: td++; break; case ZDP_RESUME: rs++; break; case ZDP_ALTRET: ar++; break; default: break; }
        if (w == ZDP_UNREACHED) continue;
        switch (zdp_tier(g->all[i])) { case ZDP_TIER_SPINE: sp++; break; case ZDP_TIER_ACTIVATION: ac++; break; case ZDP_TIER_STANDING: st++; break; default: break; } }
    fprintf(stderr, "[ZDP] %s n=%d ok=%d top_join=%d top_dyn=%d resume_skew=%d alt_return=%d unreached=%d | TIER spine=%d activation=%d standing=%d\n", tag ? tag : "graph", g->n, ok, tj, td, rs, ar, un, sp, ac, st);
    zdp_bomb_census(g, tag);
    if (zdp_mode() < 2) return;
    zdp_unwind_census(g);
    { static const char * tn[3] = { "SPINE", "ACTIVATION", "STANDING" };
      for (int i = 0; i < g->n; i++) { int w = zdp_why(g->all[i]); if (w == ZDP_OK || w == ZDP_UNREACHED) continue; int a = zdp_alpha(g->all[i]); int b = zdp_beta(g->all[i]);
        fprintf(stderr, "[ZDP]   node#%d op=%s %s tier=%s alpha=%s beta=%s\n", i, bb_op_name(g->all[i]->op), zdp_wname(w), tn[zdp_tier(g->all[i])], (a == ZDP_TOP) ? "TOP" : (a == ZDP_BOT) ? "BOT" : "int", (b == ZDP_TOP) ? "TOP" : (b == ZDP_BOT) ? "BOT" : "int"); } }
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void zdp_port_census(IR_graph_t * g) { if (zdp_mode() < 3 || !g) return; for (int i = 0; i < g->n; i++) { const IR_t * nd = g->all[i]; if (!nd) continue; int gt = zdp_tag(nd->γ.sz); const IR_t * gtgt = zdp_chase(nd->γ.node, &gt); int ot = zdp_tag(nd->ω.sz); const IR_t * otgt = zdp_chase(nd->ω.node, &ot);
        if (gtgt) fprintf(stderr, "[ZDPORT] src=%s port=gamma lands=%s tgt=%s self=%d\n", bb_op_name(nd->op), (gt == 1) ? "beta" : (gt == 2 || gt == 3) ? "returns-into" : "alpha", bb_op_name(gtgt->op), (nd == gtgt));   /* FOUR PORT NAMES ONLY: a glue-tagged edge is reported as "returns-into <box>", NEVER as a fifth port row.  s133 shipped a seven-row grid with sigma and phi as port rows and Lon rejected it on sight -- arithmetically correct, architecturally false, and it buried the one fact that mattered. */
        if (otgt) fprintf(stderr, "[ZDPORT] src=%s port=omega lands=%s tgt=%s\n", bb_op_name(nd->op), ((ot == 1) && !zdp_beta_is_stmt_land(otgt)) ? "beta" : "alpha", bb_op_name(otgt->op));
        if (zdp_has_pairs(nd)) { int N = zdp_pairs_n(nd); for (int j = 0; j < N; j++) { const IR_t * e = nd->operands[2 * j]; const IR_t * r = nd->operands[2 * j + 1];
            if (e && e->op != IR_FAIL && e != nd) fprintf(stderr, "[ZDPORT] src=%s port=operand lands=alpha tgt=%s\n", bb_op_name(nd->op), bb_op_name(e->op));
            if (r && r->op != IR_FAIL && r != nd) fprintf(stderr, "[ZDPORT] src=%s port=operand lands=beta tgt=%s\n", bb_op_name(nd->op), bb_op_name(r->op)); } } } }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
/* ⭐⭐⭐⭐⭐ ζ-ONE U-1 — THE UNIFIED ZETA ZONE PLAN (Lon in-chat s136: "Complete the unified zeta offset calculation graph traversals and the template code that uses that data.  Finish the work to
 * properly calculate and use offset from RSP and RBP based on standing, activation frames, and spine cells.")
 * ONE TRAVERSAL, ONE VERDICT PER NODE, consumed by ONE accessor.  Before this, the tree had FIVE unrelated spellings of "where does this node's storage live" -- zone_ref (2 callers, leaf cell only),
 * x86_zop/FRQ/FR (1151 callers, rsp-only, trusting x86_rsp_slide_known()'s hardwired 1), and 59 direct RDQ("rbp",..) sites in the seven ζ-family templates -- so the PLANNER's opinion and the
 * TEMPLATE's opinion about one operand could differ with nothing to detect it.  That is the class the s136 every-port probe could NOT see: it checks the BASE (rsp vs its lattice depth) and never the
 * DISPLACEMENT, and an operand banked at one offset and read at another is sound in rsp at both ends.
 * THE THREE ZETAS ARE THE THREE ANSWERS (Lon's register ruling s81): ζ-STANDING -> rbp, the match-lifetime root; ζ-ACTIVATION-FRAME -> rbp, per *P defer / per re-entrant site; ζ-SPINE -> rsp,
 * compile-time-constant FORTH/LIFO.  zdp_tier() already computes exactly this verdict and had no consumer; the registry (frame_slot_scan family) already owns the rbp offsets and had four separate
 * consumers.  This joins them: TIER from the lattice, OFFSET from the registry, and the templates stop deciding either. */
static int  zzone_tier[ZDP_CAP]; static int zzone_off[ZDP_CAP]; static int zzone_valid = 0;
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zzone_plan(IR_graph_t * g) {
    if (!g || g->n <= 0) return 0;
    zzone_valid = 0;
    for (int i = 0; i < g->n; i++) {
        const IR_t * nd = g->all[i]; int s = zdp_slot(nd, 0); if (s < 0) continue;
        zzone_off[s] = -1;                    /* ⛔⭐⭐⭐ THE PLANNER DOES NOT CALL THE REGISTRY, AND THAT IS THE WHOLE FINDING OF THIS RUNG (s136, MEASURED).  The first cut asked capture/arbno/fence/leaf_frame_slot for every node and moved 81 of 656 programs -- and the diff was NOT an offset: it was a LABEL COUNTER (`.Lbynamefnzd4` -> `.Lbynamefnzd3`).  THE REGISTRY FUNCTIONS HAVE EMIT-TIME SIDE EFFECTS, so merely OBSERVING the plan perturbed the compiler.  That is the s132 monitor lesson wearing a new costume: a verdict on a DIFFERENT program.  The offset therefore stays where it already was -- the CUSTOMER'S OWN STAGED FIELD, passed into ZREF by the call site that knows which customer it is -- and the planner supplies only the TIER, which zdp_tier computes purely from the lattice and touches nothing. */
        zzone_tier[s] = zdp_tier(nd);         /* PURE: reads zdp_ina/zdp_inb, allocates nothing, numbers nothing.  ⛔ AND THE REGISTRY KEY IS (NODE, CUSTOMER), NOT NODE -- one node can host a leaf cell AND a capture save, each with its own slot, so a node-keyed offset plan is not merely side-effecting, it is the wrong shape.  A future seat giving the planner offset authority must key it the same way the registry does. */
    }
    zzone_valid = 1; return 1;
}
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zzone_tier_of(const IR_t * nd) { int s = zzone_valid ? zdp_slot(nd, 0) : -1; return (s < 0) ? ZDP_TIER_SPINE : zzone_tier[s]; }   /* SPINE is the SAFE DEFAULT for an unplanned node: it is what every template did before this rung, so an unplanned node is byte-identical to the legacy path rather than silently re-based onto an rbp that may not exist. */
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zzone_off_of(const IR_t * nd) { int s = zzone_valid ? zdp_slot(nd, 0) : -1; return (s < 0) ? -1 : zzone_off[s]; }   /* -1 = NO RBP HOME (the accessor then addresses the spine), matching the -1 refuse the four registry functions already speak.  ONE sentinel, five producers, one consumer. */
