#include "zeta_depth.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/*===================================================================================================================================================================================================*/
/* ZETA-DEPTH (ZDP) IMPLEMENTATION.  DEFAULT-INERT BY CONSTRUCTION: nothing in this file runs unless SCRIP_ZDP is set in the environment, and no other translation unit calls into it on the default    */
/* arm, so the shipped build is byte-identical with this file linked in.  That is deliberate and it is the migration law (RULES.md): the FIRST cut of a redesign lands as an INSTRUMENT, not a behavior */
/* change, because s127's wide cut and s130's one-constant re-base were both retracted same-session and both were caught ONLY by the full battery.  This rung measures whether the predicate agrees     */
/* with the already-minted corpses (probe/deferclob, probe/clobarm, probe/leafsib) before one byte of codegen moves.  If the TOP set separates the reds from the greens the theory is confirmed and      */
/* every rung after it is mechanical; if it does not, we learn that in one session instead of six.  THAT SEPARATION IS THE FALSIFIABLE CLAIM AND IT IS THE ONLY THING THIS RUNG ASSERTS.                 */
/*===================================================================================================================================================================================================*/
extern long zw_node_k(const IR_t * nd);
extern int  zls_result_live(const IR_t * nd);
#define ZDP_CAP 8192
static const IR_t * zdp_key[ZDP_CAP]; static int zdp_ina[ZDP_CAP]; static int zdp_inb[ZDP_CAP]; static int zdp_wy[ZDP_CAP]; static int zdp_src[ZDP_CAP]; static int zdp_used = 0; static int zdp_valid = 0;
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_mode(void) { static int m = -1; if (m < 0) { const char * e = getenv("SCRIP_ZDP"); m = (e && *e && *e != '0') ? atoi(e) : 0; } return m; }   /* 0 = inert (default, shipped build) | 1 = analyze + per-graph census to stderr | 2 = census + per-node TOP detail.  Read ONCE; no other gate exists and no template consults this pass yet -- consumers arrive in a later rung under their own killswitch, per the migration law. */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static unsigned zdp_h(const IR_t * p) { unsigned long long v = (unsigned long long)(size_t)p; v ^= v >> 33; v *= 0xff51afd7ed558ccdULL; v ^= v >> 33; return (unsigned)(v & (ZDP_CAP - 1)); }   /* open-addressed pointer hash: the pass is per-graph and read-mostly, so a linear probe over a power-of-two table beats threading an index field through IR_t -- and the PEERS RULE forbids adding fields to IR_t regardless. */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_slot(const IR_t * nd, int create) { if (!nd) return -1; unsigned i = zdp_h(nd); for (int probe = 0; probe < ZDP_CAP; probe++) { unsigned j = (i + (unsigned)probe) & (ZDP_CAP - 1); if (zdp_key[j] == nd) return (int)j; if (!zdp_key[j]) { if (!create) return -1; zdp_key[j] = nd; zdp_ina[j] = ZDP_BOT; zdp_inb[j] = ZDP_BOT; zdp_wy[j] = ZDP_UNREACHED; zdp_src[j] = 0; zdp_used++; return (int)j; } } return -1; }
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_meet(int a, int b) { if (a == ZDP_BOT) return b; if (b == ZDP_BOT) return a; if (a == ZDP_TOP || b == ZDP_TOP) return ZDP_TOP; return (a == b) ? a : ZDP_TOP; }   /* THE MEET.  Height-2 lattice (BOT < n < TOP) so every point descends at most twice and the worklist fixpoint is O(E) -- this is Kildall's algorithm on the constant-propagation lattice, the same shape a JVM verifier and WASM validation use for exactly this question.  n meet m = TOP for n != m IS case (a) and case (b) simultaneously; nothing distinguishes them and nothing needs to. */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_carve_dynamic(const IR_t * nd) { if (!nd) return 0; switch (nd->op) { case IR_STATEMENT: case IR_BOUND: case IR_UNMARK: return 1; default: return 0; } }   /* THE THIRD SOURCE OF TOP, AND IT IS NOT A THIRD CASE: a SINGLE box whose own carve is not a compile-time constant (op_stmt_dyn's class -- emit.h:624 already models it correctly and cures it correctly with a depth-immune base, which is the existing proof the approach works).  Lon's two cases are both about an unknown COUNT of boxes; this is a known count of ONE box at an unknown SIZE.  Same TOP, same cure, so the model survives -- but a transfer function that could only return integers would silently miss it, which is why carve() must be able to say "dynamic" rather than just a number. */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_out_gamma(const IR_t * nd, int in) { if (in == ZDP_TOP) return ZDP_TOP; if (zdp_carve_dynamic(nd)) return ZDP_TOP; long k = zls_result_live(nd) ? zw_node_k(nd) : 0L; return in + (int)k; }   /* SUCCESS EXIT: under CARVE-ERAD a box allocates at alpha and releases at gamma/omega, EXCEPT a spine producer holding its cell live for a downstream consumer (RESULT-IS-THE-CELL).  zls_result_live is that flag and zw_node_k is THE ONE K AUTHORITY, so this transfer function invents no new arithmetic and cannot hold a second opinion about a size the allocator already spent. */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_out_omega(const IR_t * nd, int in) { if (in == ZDP_TOP) return ZDP_TOP; if (zdp_carve_dynamic(nd)) return ZDP_TOP; return in; }   /* FAILURE EXIT: the cell is dead on the fail edge, so the box releases what it carved and omega leaves the frontier where alpha found it.  ⛔ THIS IS THE MODEL OF THE INTENDED PROTOCOL, NOT A MEASUREMENT OF THE MACHINE -- a box that fails to release on omega diverges from this and that divergence IS the bug class.  Stated plainly so no later seat reads a green census as proof the emitted code balances. */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_disagree(int a, int b) { return (a != ZDP_BOT && b != ZDP_BOT && a != ZDP_TOP && b != ZDP_TOP && a != b); }   /* GENUINE DISAGREEMENT vs INHERITED TOP.  TOP is ABSORBING, so one unsound point floods every node downstream and a raw TOP COUNT measures TAINT, not defects -- the first cut of this pass reported ok=0 top_join=90 on a graph with a handful of real seams, which is true and useless.  A node is a SOURCE iff its own meet put two DISTINCT FINITE depths together (or its carve is dynamic); everything else merely inherited.  The source set is the answer; the taint set is only its shadow. */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static void zdp_push(const IR_t ** wl, int * wn, const IR_t * nd) { if (*wn < ZDP_CAP) wl[(*wn)++] = nd; }
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static void zdp_edge(int t, int val, int is_beta, const IR_t ** wl, int * wn, const IR_t * succ) { if (t < 0) return; int * cell = is_beta ? &zdp_inb[t] : &zdp_ina[t]; if (zdp_disagree(*cell, val)) zdp_src[t] = 1; int nv = zdp_meet(*cell, val); if (nv != *cell) { *cell = nv; zdp_push(wl, wn, succ); } }
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_analyze(IR_graph_t * g) { if (!g || !g->entry || g->n <= 0) return 0; memset(zdp_key, 0, sizeof(zdp_key)); zdp_used = 0; zdp_valid = 0; for (int i = 0; i < g->n; i++) (void)zdp_slot(g->all[i], 1); int es = zdp_slot(g->entry, 1); if (es < 0) return 0; zdp_ina[es] = 0; const IR_t * wl[ZDP_CAP]; int wn = 0; zdp_push(wl, &wn, g->entry); int guard = 0; while (wn > 0 && guard++ < ZDP_CAP * 16) { const IR_t * nd = wl[--wn]; int s = zdp_slot(nd, 0); if (s < 0) continue; const IR_t * sg = nd->γ.node; const IR_t * so = nd->ω.node; int ports[2]; ports[0] = zdp_ina[s]; ports[1] = zdp_inb[s]; for (int pi = 0; pi < 2; pi++) { int in = ports[pi]; if (in == ZDP_BOT) continue; if (sg) zdp_edge(zdp_slot(sg, 1), zdp_out_gamma(nd, in), 0, wl, &wn, sg); if (so) zdp_edge(zdp_slot(so, 1), zdp_out_omega(nd, in), 1, wl, &wn, so); } } for (int i = 0; i < g->n; i++) { int s = zdp_slot(g->all[i], 0); if (s < 0) continue; if (zdp_ina[s] == ZDP_BOT && zdp_inb[s] == ZDP_BOT) zdp_wy[s] = ZDP_UNREACHED; else if (zdp_carve_dynamic(g->all[i])) zdp_wy[s] = ZDP_DYN; else if (zdp_inb[s] != ZDP_BOT && zdp_ina[s] != ZDP_BOT && zdp_inb[s] != zdp_ina[s]) zdp_wy[s] = ZDP_RESUME; else if (zdp_src[s]) zdp_wy[s] = ZDP_JOIN; else zdp_wy[s] = ZDP_OK; } zdp_valid = 1; return 1; }
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_alpha(const IR_t * nd) { int s = zdp_valid ? zdp_slot(nd, 0) : -1; return (s < 0) ? ZDP_TOP : zdp_ina[s]; }
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_beta(const IR_t * nd) { int s = zdp_valid ? zdp_slot(nd, 0) : -1; return (s < 0) ? ZDP_TOP : zdp_inb[s]; }
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_known_alpha(const IR_t * nd) { int d = zdp_alpha(nd); return (d != ZDP_TOP && d != ZDP_BOT); }   /* ⭐ THE PREDICATE x86_rsp_slide_known() WAS HARDWIRED TO RETURN 1 FOR (x86_asm.h:582).  With it computable, x86_frame_off's -1 unknown-depth branch stops being dead code -- but NOTHING CONSULTS THIS YET and that is deliberate: the consumer side needs the RBP registry shaped to hold whatever TOP classifies, and s131b measured what happens when it is not (trueinline_grn regressed on a one-constant re-base). */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_known_beta(const IR_t * nd) { int d = zdp_beta(nd); return (d != ZDP_TOP && d != ZDP_BOT); }
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_resume_sound(const IR_t * nd) { int a = zdp_alpha(nd); int b = zdp_beta(nd); if (b == ZDP_BOT) return 1; if (a == ZDP_TOP || b == ZDP_TOP) return 0; return a == b; }   /* ⭐⭐⭐ THE BETA VERDICT THAT DID NOT EXIST.  s132: "the beta side has no verdict at all -- nothing at a beta port ever asks", which is why IR_MATCH_DEFER's beta is a bare `jmp qword ptr [rsp]` three lines from IR_MATCH_ALTERNATE's `mov rax,[rsp+8]`.  A bare-rsp resume read is sound IFF the frontier at resume equals the frontier at fresh entry; the omega fan-in meet answers exactly that and it is the SAME lattice queried at the other port.  ONE analysis, TWO call sites -- not a taxonomy, and not a whitelist anybody has to maintain. */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
int zdp_why(const IR_t * nd) { int s = zdp_valid ? zdp_slot(nd, 0) : -1; return (s < 0) ? ZDP_UNREACHED : zdp_wy[s]; }
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static const char * zdp_wname(int w) { switch (w) { case ZDP_OK: return "OK"; case ZDP_UNREACHED: return "UNREACHED"; case ZDP_JOIN: return "TOP-JOIN"; case ZDP_DYN: return "TOP-DYN"; case ZDP_RESUME: return "RESUME-SKEW"; default: return "?"; } }
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void zdp_report(IR_graph_t * g, const char * tag) { if (!zdp_mode() || !g) return; if (!zdp_analyze(g)) return; int ok = 0, un = 0, tj = 0, td = 0, rs = 0; for (int i = 0; i < g->n; i++) { switch (zdp_why(g->all[i])) { case ZDP_OK: ok++; break; case ZDP_UNREACHED: un++; break; case ZDP_JOIN: tj++; break; case ZDP_DYN: td++; break; case ZDP_RESUME: rs++; break; default: break; } } fprintf(stderr, "[ZDP] %s n=%d ok=%d top_join=%d top_dyn=%d resume_skew=%d unreached=%d\n", tag ? tag : "graph", g->n, ok, tj, td, rs, un); if (zdp_mode() < 2) return; for (int i = 0; i < g->n; i++) { int w = zdp_why(g->all[i]); if (w == ZDP_OK || w == ZDP_UNREACHED) continue; int a = zdp_alpha(g->all[i]); int b = zdp_beta(g->all[i]); fprintf(stderr, "[ZDP]   node#%d op=%d %s alpha=%s beta=%s\n", i, (int)g->all[i]->op, zdp_wname(w), (a == ZDP_TOP) ? "TOP" : (a == ZDP_BOT) ? "BOT" : "int", (b == ZDP_TOP) ? "TOP" : (b == ZDP_BOT) ? "BOT" : "int"); }
}
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static int zdp_tag(const char * sz) { if (sz[0] == (char)0xce && (unsigned char)sz[1] == 0xb2) return 1; if (sz[0] == (char)0xcf && (unsigned char)sz[1] == 0x83) return 2; if (sz[0] == (char)0xcf && (unsigned char)sz[1] == 0x86) return 3; return 0; }   /* THE FOUR ENTRY-PORT TAGS carried on the edge itself: 0=alpha (untagged default) 1=beta (0xce 0xb2) 2=sigma (0xcf 0x83, inside-success na_s glue) 3=phi (0xcf 0x86, inside-fail na_f glue).  Spelled here to MIRROR emit.cpp:2102/2999/3000 exactly -- if those move this must move with them; it is a reader of that authority, not a second opinion. */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
static const IR_t * zdp_chase(const IR_t * t, int * tag) { int g = 0; while (t && t->op == IR_GOTO && g++ < 128) { int nt = zdp_tag(t->γ.sz); if (nt && !*tag) *tag = nt; t = t->γ.node; } return t; }   /* GOTO-CHASE, mirroring emit.cpp:3002-3003: an edge through a folded unconditional goto carries its port tag on the CHASED node, so a raw ->node read gets both the wrong target and the wrong port.  The optimizer's GOTO-chase folds these to bare edges, so this is the common path, not a corner. */
/*---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void zdp_port_census(IR_graph_t * g) { if (zdp_mode() < 3 || !g) return; static const char * tn[4] = { "alpha", "beta", "sigma", "phi" }; for (int i = 0; i < g->n; i++) { const IR_t * nd = g->all[i]; if (!nd) continue; int gt = zdp_tag(nd->γ.sz); const IR_t * gtgt = zdp_chase(nd->γ.node, &gt); int ot = zdp_tag(nd->ω.sz); const IR_t * otgt = zdp_chase(nd->ω.node, &ot); if (gtgt) { int si = -1, ti = -1; for (int q = 0; q < g->n; q++) { if (g->all[q] == nd) si = q; if (g->all[q] == gtgt) ti = q; } fprintf(stderr, "[ZDPORT] src=%d port=gamma tag=%s tgt=%d | srcidx=%d tgtidx=%d self=%d rawsz=%02x%02x chased=%d\n", (int)nd->op, tn[gt], (int)gtgt->op, si, ti, (nd == gtgt), (unsigned char)nd->γ.sz[0], (unsigned char)nd->γ.sz[1], (nd->γ.node != gtgt)); } if (otgt) fprintf(stderr, "[ZDPORT] src=%d port=omega tag=%s tgt=%d\n", (int)nd->op, tn[ot], (int)otgt->op); } }
