#!/usr/bin/env python3
"""audit_fixed_caps_census.py [--tsv OUT] [--top N] [--dir src]

Census of FIXED-SIZE storage in the SCRIP compiler and runtime (Lon 2026-09-23, in-chat to the ceo: "we must still handle
almost everything without a FIXED LIMIT ... Scan the SCRIP for all fixed arrays, fixed buffers, etc.").  It reads every
.c/.cpp/.h under --dir, skips generated flex/bison output, and lists (1) every array declaration with a constant bound --
literal or UPPER_CASE macro -- with its scope (file/static, struct field, local, parameter), the bound resolved through the
tree's #defines where it can be, and whether the bound's macro is ever compared against in the same file (a loud guard) or
never (a silent overrun); (2) every #define whose name ends in MAX/CAP/LIMIT/SIZE/DEPTH/ENTRIES/SLOTS/COUNT/LEN with a
numeric value and its use count.  It is a census, not a verdict: the classification (bounded by the machine vs a
population cap a program can outgrow) is the reader's, written beside each row in the design page.
"""
import os
import re
import sys
from collections import Counter, defaultdict

CAP_NAME = re.compile(r"_(MAX|CAP|LIMIT|SIZE|DEPTH|ENTRIES|SLOTS|COUNT|LEN|BUCKETS|N)\b|^(MAX|N)[A-Z_]*$")
DEFINE = re.compile(r"^\s*#\s*define\s+([A-Z][A-Z0-9_]*)\s+\(?\s*([0-9]+|0x[0-9a-fA-F]+|[A-Z][A-Z0-9_]*(?:\s*[*+]\s*[0-9A-Z_]+)*)\s*\)?\s*$")
ARRAY = re.compile(r"(?P<pre>(?:^|[;{,(]|\)\s*)\s*(?:static\s+|const\s+|volatile\s+|unsigned\s+|signed\s+|struct\s+|enum\s+|extern\s+)*(?:[A-Za-z_][A-Za-z0-9_:<>]*\s*[*&\s]+))(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\[\s*(?P<bound>[A-Z0-9_][A-Za-z0-9_+*\- ]*?)\s*\](?P<dims>(?:\s*\[[^\]]*\])*)\s*(?P<post>[;=,)]|\[)")
# ⭐ A TABLE NAMED AFTER A CLOSING BRACE (coo 2026-09-23, the cfo's finding on this row): `static struct { fields } name[CAP];` -- one
# line or several -- names its array after the `}`, where ARRAY needs a type word before the name, so the census never saw it. In
# lower_snobol4.c alone that hid five population caps (g_sno_exprs[SNO_EXPR_MAX] FATAL past 4096, g_sno_pats[SNO_PAT_MAX] FATAL past
# 256, g_sno_fz, g_sno_seal, scd[64]) that the design page's own section 6 names. CLOSE reads that form; its scope is the scope the
# struct OPENED in, and a typedef'd struct is a type, not storage, so it is skipped.
CLOSE = re.compile(r"\}\s*(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\[\s*(?P<bound>[A-Z0-9_][A-Za-z0-9_+*\- ]*?)\s*\](?P<dims>(?:\s*\[[^\]]*\])*)\s*(?P<post>[;=,])")
BOUND_RE = r"[0-9]+|0x[0-9a-fA-F]+|[A-Z][A-Z0-9_]*(?:\s*[*+]\s*[A-Z0-9_]+)*"
GENERATED = re.compile(r"(A Bison parser|generated by flex|#define FLEX_SCANNER|yy_create_buffer|YYBISON)")
SKIP_NAMES = {"sizeof", "return", "case", "goto", "else", "typedef"}


def load(path):
    try:
        return open(path, encoding="utf-8", errors="replace").read()
    except OSError:
        return ""


def resolve(bound, defines, depth=0):
    b = bound.strip()
    if re.fullmatch(r"[0-9]+", b):
        return int(b)
    if re.fullmatch(r"0x[0-9a-fA-F]+", b):
        return int(b, 16)
    if depth > 6:
        return None
    m = re.fullmatch(r"([A-Z][A-Z0-9_]*)\s*([*+])\s*([A-Z0-9_]+)", b)
    if m:
        a, op, c = resolve(m.group(1), defines, depth + 1), m.group(2), resolve(m.group(3), defines, depth + 1)
        if a is None or c is None:
            return None
        return a * c if op == "*" else a + c
    if b in defines:
        return resolve(defines[b], defines, depth + 1)
    return None


def selftest():
    """Planted fixtures, every form the census must count or refuse to count, graded by NAME. rc 0 / 1."""
    import tempfile
    d = tempfile.mkdtemp(prefix="caps_census_selftest.")
    try:
        open(os.path.join(d, "a.c"), "w").write(
            "#define T1_MAX 16\n#define T2_MAX 32\n#define T5_MAX 8\n#define T6_MAX 4\n"
            "static struct { int a; char *b; } t1_oneline[T1_MAX];\n"
            "static struct {\n    int a;\n    int b;\n} t2_multiline[T2_MAX];\n"
            "typedef struct { int a; } t3_is_a_type[4];\n"
            "extern int t4_extern[T5_MAX];\n"
            "int t5_plain[T5_MAX];\n"
            "void f(void) {\n    extern int t4_extern[T5_MAX];\n    static struct { int q; } t6_local_static[T6_MAX];\n    (void)t6_local_static;\n}\n")
        out = os.path.join(d, "c.tsv")
        import io, contextlib
        with contextlib.redirect_stdout(io.StringIO()):
            main(["x", "--dir", d, "--tsv", out])
        got = {}
        for ln in open(out).read().split("\n")[1:]:
            if ln:
                f = ln.split("\t")
                got.setdefault(f[3], []).append(f[2])
        want = {"t1_oneline": ["file"], "t2_multiline": ["file"], "t5_plain": ["file"], "t6_local_static": ["static"]}
        ok = True
        for n, sc in want.items():
            if got.get(n) != sc:
                print("SELFTEST FAIL: %s counted as %r, want %r" % (n, got.get(n), sc)); ok = False
            else:
                print("SELFTEST: %s counted once, scope %s" % (n, sc[0]))
        for n in ("t3_is_a_type", "t4_extern"):
            if n in got:
                print("SELFTEST FAIL: %s was counted %r -- a typedef and an extern are not storage" % (n, got[n])); ok = False
            else:
                print("SELFTEST: %s not counted (not storage)" % n)
        print("SELFTEST %s" % ("PASS" if ok else "FAIL"))
        return 0 if ok else 1
    finally:
        import shutil
        shutil.rmtree(d, ignore_errors=True)


def main(argv):
    if "--selftest" in argv:
        return selftest()
    root = "src"
    out = None
    top = 40
    if "--dir" in argv:
        root = argv[argv.index("--dir") + 1]
    if "--tsv" in argv:
        out = argv[argv.index("--tsv") + 1]
    if "--top" in argv:
        top = int(argv[argv.index("--top") + 1])
    files = []
    for d, _, fs in os.walk(root):
        for f in fs:
            if f.endswith((".c", ".cpp", ".h")):
                files.append(os.path.join(d, f))
    files.sort()
    texts = {}
    defines = {}
    define_sites = {}
    for p in files:
        t = load(p)
        if GENERATED.search(t[:4000]):
            continue
        texts[p] = t
        for i, l in enumerate(t.split("\n"), 1):
            m = DEFINE.match(l)
            if m and m.group(1) not in defines:
                defines[m.group(1)] = m.group(2)
                define_sites[m.group(1)] = "%s:%d" % (p, i)
    rows = []
    for p, t in texts.items():
        lines = t.split("\n")
        depth = 0
        struct_depth = None
        struct_open = ""
        for i, l in enumerate(lines, 1):
            s = l
            line_depth = depth
            if re.search(r"\b(typedef\s+)?(struct|union)\b[^;(]*\{", s) and struct_depth is None:
                struct_depth = depth
                struct_open = s
            for m in CLOSE.finditer(s):
                name, bound = m.group("name"), m.group("bound").strip()
                if name in SKIP_NAMES or not re.fullmatch(BOUND_RE, bound):
                    continue
                upto = s[:m.start() + 1]
                level = line_depth + upto.count("{") - upto.count("}")
                opener = upto[:upto.rfind("{")] if "{" in upto else struct_open
                if re.search(r"\btypedef\b", opener) or not re.search(r"\b(struct|union)\b", opener):
                    continue
                if level <= 0:
                    scope = "file"
                elif struct_depth is not None and level == struct_depth + 1:
                    scope = "field"
                else:
                    scope = "static" if re.search(r"\bstatic\b", opener) else "local"
                size = resolve(bound, defines)
                macro = bound if re.fullmatch(r"[A-Z][A-Z0-9_]*", bound) else ""
                guarded = ""
                if macro:
                    guarded = "guarded" if re.search(r"[<>=!]=?\s*\(?\s*" + re.escape(macro) + r"\b|\b" + re.escape(macro) + r"\s*\)?\s*[<>=!]=?", t) else "UNGUARDED"
                rows.append((p, i, scope, name, bound, size if size is not None else "", m.group("dims").replace(" ", ""), guarded))
            for m in ARRAY.finditer(s):
                name = m.group("name")
                pre = m.group("pre")
                if name in SKIP_NAMES or re.search(r"\b(return|case|sizeof|if|while|for)\b", pre):
                    continue
                # ⛔ AN extern IS A RE-DECLARATION, NOT STORAGE (coo 2026-09-23): counting it made one array two tables -- hq_snobol4's
                # 2b89a5ef2 added a file-scope `extern jmp_buf g_core_errjmp_stk[64];` in core.c beside the definition 900 lines
                # down, and the ratchet read "a new fixed limit landed" (361 -> 362) where the same storage was declared twice.
                if re.search(r"\bextern\b", pre):
                    continue
                if re.search(r"\b(if|while|for|switch|return)\s*\($", pre.strip() + "("):
                    continue
                bound = m.group("bound").strip()
                if not re.fullmatch(r"[0-9]+|0x[0-9a-fA-F]+|[A-Z][A-Z0-9_]*(?:\s*[*+]\s*[A-Z0-9_]+)*", bound):
                    continue
                if depth == 0:
                    scope = "file"
                elif struct_depth is not None and depth == struct_depth + 1:
                    scope = "field"
                elif m.group("post") == ")" or (pre.strip().endswith(",") or pre.strip().endswith("(")) and depth == 0:
                    scope = "param"
                else:
                    scope = "local"
                if scope == "file" and (m.group("post") == ")" or pre.strip().endswith("(") or pre.strip().endswith(",")):
                    scope = "param"
                if "static" in pre:
                    scope = "static" if scope == "local" else scope
                size = resolve(bound, defines)
                macro = bound if re.fullmatch(r"[A-Z][A-Z0-9_]*", bound) else ""
                guarded = ""
                if macro:
                    guarded = "guarded" if re.search(r"[<>=!]=?\s*\(?\s*" + re.escape(macro) + r"\b|\b" + re.escape(macro) + r"\s*\)?\s*[<>=!]=?", t) else "UNGUARDED"
                rows.append((p, i, scope, name, bound, size if size is not None else "", m.group("dims").replace(" ", ""), guarded))
            opens = s.count("{")
            closes = s.count("}")
            depth += opens - closes
            if struct_depth is not None and depth <= struct_depth:
                struct_depth = None
            if depth < 0:
                depth = 0
    if out:
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write("file\tline\tscope\tname\tbound\tsize\tdims\tguard\n")
            for r in rows:
                f.write("\t".join(str(x) for x in r) + "\n")
    by_dir = defaultdict(Counter)
    for r in rows:
        by_dir[os.path.dirname(r[0])][r[2]] += 1
    print("FIXED-CAPS CENSUS: %d array declarations with a constant bound in %d files (%d generated files skipped)" % (len(rows), len(texts), len(files) - len(texts)))
    print("%-34s %5s %5s %5s %5s %5s" % ("directory", "file", "field", "local", "param", "all"))
    for d in sorted(by_dir):
        c = by_dir[d]
        print("%-34s %5d %5d %5d %5d %5d" % (d, c["file"] + c["static"], c["field"], c["local"], c["param"], sum(c.values())))
    macros = Counter(r[4] for r in rows if re.fullmatch(r"[A-Z][A-Z0-9_]*", r[4]))
    print("\nBOUND MACROS (%d distinct), by declarations using them:" % len(macros))
    for mname, n in macros.most_common(top):
        print("  %-40s uses=%-3d value=%-10s defined %s" % (mname, n, resolve(mname, defines) if resolve(mname, defines) is not None else defines.get(mname, "?"), define_sites.get(mname, "?")))
    ung = [r for r in rows if r[7] == "UNGUARDED" and r[2] in ("file", "static", "field")]
    print("\nFILE-SCOPE OR FIELD ARRAYS WHOSE BOUND MACRO IS NEVER COMPARED IN ITS FILE (silent overrun candidates): %d" % len(ung))
    for r in sorted(ung, key=lambda r: -(r[5] or 0))[:top]:
        print("  %s:%d %s %s[%s] size=%s" % r[:6])
    lits = [r for r in rows if re.fullmatch(r"[0-9]+", r[4]) and r[2] in ("file", "static", "field") and int(r[4]) >= 8]
    print("\nFILE-SCOPE OR FIELD ARRAYS WITH A BARE LITERAL BOUND >= 8: %d" % len(lits))
    for r in sorted(lits, key=lambda r: -int(r[4]))[:top]:
        print("  %s:%d %s %s[%s]" % r[:5])
    caps = [(k, v, define_sites[k]) for k, v in defines.items() if CAP_NAME.search(k) and resolve(k, defines) is not None]
    print("\nCAP-SHAPED #defines with a numeric value: %d (top by value)" % len(caps))
    alltext = "\n".join(texts.values())
    for k, v, site in sorted(caps, key=lambda kv: -(resolve(kv[0], defines) or 0))[:top]:
        print("  %-40s = %-10s uses=%-4d %s" % (k, resolve(k, defines), len(re.findall(r"\b" + re.escape(k) + r"\b", alltext)) - 1, site))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
