#!/usr/bin/env python3
"""audit_fixed_caps_census.py [--tsv OUT] [--top N] [--dir src]

Census of FIXED-SIZE storage in the SCRIP compiler and runtime (Lon 2026-09-23, in-chat to the ceo: "we must still handle
almost everything without a FIXED LIMIT ... Scan the SCRIP for all fixed arrays, fixed buffers, etc.").  It reads every
.c/.cpp/.h under --dir, skips generated flex/bison output, and lists (1) every array declaration with a constant bound --
literal or UPPER_CASE macro -- with its scope (file/static, struct field, local, parameter), the bound resolved through the
tree's #defines where it can be, and whether the bound's macro is ever compared against in the same file (a loud guard) or
never (a silent overrun); (2) every #define whose name ends in MAX/CAP/LIMIT/SIZE/DEPTH/ENTRIES/SLOTS/COUNT/LEN with a
numeric value and its use count.  It is a census, not a verdict: the classification (bounded by the machine vs a
population cap a program can outgrow) is the reader's, written beside each row in the design page.
"""
import os
import re
import sys
from collections import Counter, defaultdict

CAP_NAME = re.compile(r"_(MAX|CAP|LIMIT|SIZE|DEPTH|ENTRIES|SLOTS|COUNT|LEN|BUCKETS|N)\b|^(MAX|N)[A-Z_]*$")
DEFINE = re.compile(r"^\s*#\s*define\s+([A-Z][A-Z0-9_]*)\s+\(?\s*([0-9]+|0x[0-9a-fA-F]+|[A-Z][A-Z0-9_]*(?:\s*[*+]\s*[0-9A-Z_]+)*)\s*\)?\s*$")
ARRAY = re.compile(r"(?P<pre>(?:^|[;{,(]|\)\s*)\s*(?:static\s+|const\s+|volatile\s+|unsigned\s+|signed\s+|struct\s+|enum\s+|extern\s+)*(?:[A-Za-z_][A-Za-z0-9_:<>]*\s*[*&\s]+))(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\[\s*(?P<bound>[A-Z0-9_][A-Za-z0-9_+*\- ]*?)\s*\](?P<dims>(?:\s*\[[^\]]*\])*)\s*(?P<post>[;=,)]|\[)")
GENERATED = re.compile(r"(A Bison parser|generated by flex|#define FLEX_SCANNER|yy_create_buffer|YYBISON)")
SKIP_NAMES = {"sizeof", "return", "case", "goto", "else", "typedef"}


def load(path):
    try:
        return open(path, encoding="utf-8", errors="replace").read()
    except OSError:
        return ""


def resolve(bound, defines, depth=0):
    b = bound.strip()
    if re.fullmatch(r"[0-9]+", b):
        return int(b)
    if re.fullmatch(r"0x[0-9a-fA-F]+", b):
        return int(b, 16)
    if depth > 6:
        return None
    m = re.fullmatch(r"([A-Z][A-Z0-9_]*)\s*([*+])\s*([A-Z0-9_]+)", b)
    if m:
        a, op, c = resolve(m.group(1), defines, depth + 1), m.group(2), resolve(m.group(3), defines, depth + 1)
        if a is None or c is None:
            return None
        return a * c if op == "*" else a + c
    if b in defines:
        return resolve(defines[b], defines, depth + 1)
    return None


def main(argv):
    root = "src"
    out = None
    top = 40
    if "--dir" in argv:
        root = argv[argv.index("--dir") + 1]
    if "--tsv" in argv:
        out = argv[argv.index("--tsv") + 1]
    if "--top" in argv:
        top = int(argv[argv.index("--top") + 1])
    files = []
    for d, _, fs in os.walk(root):
        for f in fs:
            if f.endswith((".c", ".cpp", ".h")):
                files.append(os.path.join(d, f))
    files.sort()
    texts = {}
    defines = {}
    define_sites = {}
    for p in files:
        t = load(p)
        if GENERATED.search(t[:4000]):
            continue
        texts[p] = t
        for i, l in enumerate(t.split("\n"), 1):
            m = DEFINE.match(l)
            if m and m.group(1) not in defines:
                defines[m.group(1)] = m.group(2)
                define_sites[m.group(1)] = "%s:%d" % (p, i)
    rows = []
    for p, t in texts.items():
        lines = t.split("\n")
        depth = 0
        struct_depth = None
        for i, l in enumerate(lines, 1):
            s = l
            if re.search(r"\b(typedef\s+)?(struct|union)\b[^;(]*\{", s) and struct_depth is None:
                struct_depth = depth
            for m in ARRAY.finditer(s):
                name = m.group("name")
                pre = m.group("pre")
                if name in SKIP_NAMES or re.search(r"\b(return|case|sizeof|if|while|for)\b", pre):
                    continue
                if re.search(r"\b(if|while|for|switch|return)\s*\($", pre.strip() + "("):
                    continue
                bound = m.group("bound").strip()
                if not re.fullmatch(r"[0-9]+|0x[0-9a-fA-F]+|[A-Z][A-Z0-9_]*(?:\s*[*+]\s*[A-Z0-9_]+)*", bound):
                    continue
                if depth == 0:
                    scope = "file"
                elif struct_depth is not None and depth == struct_depth + 1:
                    scope = "field"
                elif m.group("post") == ")" or (pre.strip().endswith(",") or pre.strip().endswith("(")) and depth == 0:
                    scope = "param"
                else:
                    scope = "local"
                if scope == "file" and (m.group("post") == ")" or pre.strip().endswith("(") or pre.strip().endswith(",")):
                    scope = "param"
                if "static" in pre:
                    scope = "static" if scope == "local" else scope
                size = resolve(bound, defines)
                macro = bound if re.fullmatch(r"[A-Z][A-Z0-9_]*", bound) else ""
                guarded = ""
                if macro:
                    guarded = "guarded" if re.search(r"[<>=!]=?\s*\(?\s*" + re.escape(macro) + r"\b|\b" + re.escape(macro) + r"\s*\)?\s*[<>=!]=?", t) else "UNGUARDED"
                rows.append((p, i, scope, name, bound, size if size is not None else "", m.group("dims").replace(" ", ""), guarded))
            opens = s.count("{")
            closes = s.count("}")
            depth += opens - closes
            if struct_depth is not None and depth <= struct_depth:
                struct_depth = None
            if depth < 0:
                depth = 0
    if out:
        with open(out, "w", encoding="utf-8", newline="\n") as f:
            f.write("file\tline\tscope\tname\tbound\tsize\tdims\tguard\n")
            for r in rows:
                f.write("\t".join(str(x) for x in r) + "\n")
    by_dir = defaultdict(Counter)
    for r in rows:
        by_dir[os.path.dirname(r[0])][r[2]] += 1
    print("FIXED-CAPS CENSUS: %d array declarations with a constant bound in %d files (%d generated files skipped)" % (len(rows), len(texts), len(files) - len(texts)))
    print("%-34s %5s %5s %5s %5s %5s" % ("directory", "file", "field", "local", "param", "all"))
    for d in sorted(by_dir):
        c = by_dir[d]
        print("%-34s %5d %5d %5d %5d %5d" % (d, c["file"] + c["static"], c["field"], c["local"], c["param"], sum(c.values())))
    macros = Counter(r[4] for r in rows if re.fullmatch(r"[A-Z][A-Z0-9_]*", r[4]))
    print("\nBOUND MACROS (%d distinct), by declarations using them:" % len(macros))
    for mname, n in macros.most_common(top):
        print("  %-40s uses=%-3d value=%-10s defined %s" % (mname, n, resolve(mname, defines) if resolve(mname, defines) is not None else defines.get(mname, "?"), define_sites.get(mname, "?")))
    ung = [r for r in rows if r[7] == "UNGUARDED" and r[2] in ("file", "static", "field")]
    print("\nFILE-SCOPE OR FIELD ARRAYS WHOSE BOUND MACRO IS NEVER COMPARED IN ITS FILE (silent overrun candidates): %d" % len(ung))
    for r in sorted(ung, key=lambda r: -(r[5] or 0))[:top]:
        print("  %s:%d %s %s[%s] size=%s" % r[:6])
    lits = [r for r in rows if re.fullmatch(r"[0-9]+", r[4]) and r[2] in ("file", "static", "field") and int(r[4]) >= 8]
    print("\nFILE-SCOPE OR FIELD ARRAYS WITH A BARE LITERAL BOUND >= 8: %d" % len(lits))
    for r in sorted(lits, key=lambda r: -int(r[4]))[:top]:
        print("  %s:%d %s %s[%s]" % r[:5])
    caps = [(k, v, define_sites[k]) for k, v in defines.items() if CAP_NAME.search(k) and resolve(k, defines) is not None]
    print("\nCAP-SHAPED #defines with a numeric value: %d (top by value)" % len(caps))
    alltext = "\n".join(texts.values())
    for k, v, site in sorted(caps, key=lambda kv: -(resolve(kv[0], defines) or 0))[:top]:
        print("  %-40s = %-10s uses=%-4d %s" % (k, resolve(k, defines), len(re.findall(r"\b" + re.escape(k) + r"\b", alltext)) - 1, site))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
