#!/usr/bin/env python3
"""audit_delimited_aggregates_census.py [--dir src] [--tsv OUT] [--baseline FILE] [--non-members FILE] [--top N] [--selftest]

Census of DELIMITER-JOINED AGGREGATES (RULES.md FACT RULE NO DELIMITER-JOINED AGGREGATES; Lon 2026-09-28 08:5x CDT, in-chat to
hq_pascal, verbatim: "What are seperator bytes? Are you storing data as tag delimited strings? Where are you doing that crazy
thing?" · "Do not store records like that." · "Get rid of ALL delimited based processing like the one I just discovered."; ceo
CEO-1349, the cfo's row).  It reads every .c/.cpp/.h/.y/.l under --dir, skips generated flex/bison output, and lists every SITE
where a value is joined by, split on, or tagged with a SEPARATOR BYTE: a control-byte literal ('\\x01', "\\001", '\\x05', '\\x1f',
'\\x04' and the rest of \\x01..\\x07 and \\x1c..\\x1f, in char or string form) or a macro that names one (SOH), used on a line
that is not a whole-byte table (eight or more distinct byte escapes on one line is a table, not a separator) and not the macro's
own #define (printed as the separator's DEFINITION beside its file).  Each site carries its file, line, enclosing function and
CARRIER -- PASCAL (records and arrays: __pas_*, arr_get/arr_set_pure, pascal.y init literals, norm_charseq in lower_common.c, a
shared node), RAKU (arrays, lists, hashes: the __rk_* and generic builtins, rt_str_method, out_write_str, rt_make_flat_agg,
lower_raku.c, rk_tree.c), REGISTRY_KEY (src/runtime/aggregates.c's \\001-prefixed type-tagged registry keys: a MEMBER since
CEO-1350, the cfo's view adopted by the ceo) or OTHER (anything else found: a member until its owner names it) -- and the
NON-MEMBERS are carried from a declaration file with their reasons, counted separately and printed every run, never silently
exempt: x86_asm.h's \\x01 port mark in the TEXT medium (emitter bookkeeping) and the whole-byte tables.  It is a census, not a
verdict: --baseline FILE compares the member count PER CARRIER against a baseline that may only fall (above: a separator-joined
value landed; below: lower the baseline in the same landing) and exits 1 above it.  The TSV columns are file line function
carrier kind text.  --selftest builds a scratch tree with every declared form and refuses the census that miscounts one.
"""
import os
import re
import sys
import tempfile
from collections import Counter, defaultdict

EXTS = (".c", ".cpp", ".h", ".y", ".l")
GENERATED = re.compile(r"(A Bison parser|generated by flex|#define FLEX_SCANNER|yy_create_buffer|YYBISON)")
# a control byte spelled as a char or string literal: \x01..\x07, \x1c..\x1f, in hex or octal
BYTE = re.compile(r"""(?:'\\(?:x0[1-7]|x1[c-f]|00[1-7]|03[4-7])'|"[^"\n]*?\\(?:x0[1-7]|x1[c-f]|00[1-7]|03[4-7])[^"\n]*?")""")
DEFINE_SEP = re.compile(r"^\s*#\s*define\s+([A-Z][A-Z0-9_]*)\s+(?:'\\(?:x0[1-7]|x1[c-f]|00[1-7]|03[4-7])'|\"\\(?:x0[1-7]|x1[c-f]|00[1-7]|03[4-7])\")")
ANCHOR = re.compile(r'strcmp\s*\(\s*fn\s*,\s*"([^"]+)"\s*\)')
ESCAPES = re.compile(r"\\(?:x[0-9a-fA-F]{2}|[0-7]{3})")
STRLIT = re.compile(r'"(?:[^"\\\n]|\\.)*"')
FN = re.compile(r"^(?:[A-Za-z_][A-Za-z0-9_]*[ \t*]+)+\**([A-Za-z_][A-Za-z0-9_]*)\s*\(")
PASCAL_FN = re.compile(r"^(?:__pas_|pas_|arr_get\b|arr_set_pure\b|norm_charseq\b)")
RAKU_FN = re.compile(r"^(?:__rk_|rk_|rt_str_method\b|out_write_str\b|rt_make_flat_agg\b|hash_get\b|push_pure\b|unshift_pure\b|array_sort\b|array_reverse\b|re_match_global\b|arr_init\b|arr_last\b|arr_tail\b)")
PASCAL_FILE = re.compile(r"(?:^|/)(?:parsers/pascal/|lower/lower_pascal\.c|lower/lower_common\.c)")
RAKU_FILE = re.compile(r"(?:^|/)(?:parsers/raku/|lower/lower_raku\.c)")
REGISTRY_FILE = re.compile(r"(?:^|/)runtime/aggregates\.c$")
CARRIERS = ("PASCAL", "RAKU", "REGISTRY_KEY", "OTHER")


def files_under(d):
    out = []
    for root, _, names in os.walk(d):
        for n in sorted(names):
            if n.endswith(EXTS):
                out.append(os.path.join(root, n))
    return sorted(out)


def load(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def blank_comments(t):
    t = re.sub(r"/\*.*?\*/", lambda m: re.sub(r"[^\n]", " ", m.group(0)), t, flags=re.S)
    return re.sub(r"//[^\n]*", "", t)


def enclosing(lines):
    fn = "-"
    out = []
    for l in lines:
        m = FN.match(l)
        if m and not l.startswith((" ", "\t")) and m.group(1) not in ("if", "for", "while", "switch", "return", "sizeof", "_Static_assert", "static_assert"):
            fn = m.group(1)
        out.append(fn)
    return out


RAKU_GENERIC = re.compile(r"^(?:hash_|push|unshift|pop|shift|array_|arr_|re_|head|tail|last|lines|reverse|unique|join|split|keys|values|kv|pairs|elems|sort|map|grep|first|flat|list|slice|junction|any|all|one|none|min|max|sum|comb|words|append|prepend|splice|rotate|pick|roll|classify|categorize|antipairs|invert|zip|cross|roundrobin|reduce|produce|squish|repeated|combinations|permutations|range|seq|iter)")
def carrier_of(rel, fn, anchor):
    if REGISTRY_FILE.search(rel):
        return "REGISTRY_KEY"
    a = anchor or ""
    if PASCAL_FILE.search(rel) or PASCAL_FN.match(fn) or a.startswith("__pas_"):
        return "PASCAL"
    if RAKU_FILE.search(rel) or RAKU_FN.match(fn) or a.startswith(("__rk_", "rk_", "rkb_", "meth_")) or fn.startswith(("junction", "hash_find", "script_hash", "script_try_hash", "rt_make_nested_agg")) or (fn == "script_try_call_builtin_by_name" and RAKU_GENERIC.match(a)):
        return "RAKU"
    return "OTHER"


def load_non_members(path):
    rows = []
    if not path or not os.path.isfile(path):
        return rows
    for ln in load(path).split("\n"):
        if not ln.strip() or ln.startswith("#"):
            continue
        parts = ln.split("\t")
        if len(parts) < 3:
            continue
        rows.append((parts[0].strip(), parts[1].strip(), parts[2].strip()))
    return rows


def census(d, non_members):
    files = files_under(d)
    sites, defs, tables, exempt, stale = [], [], [], [], []
    seen_nm = set()
    texts = {}
    for path in files:
        raw = load(path)
        if GENERATED.search(raw[:4000]):
            continue
        rel = os.path.relpath(path, d)
        texts[rel] = blank_comments(raw)
        for i, l in enumerate(texts[rel].split("\n"), 1):
            m = DEFINE_SEP.match(l)
            if m:
                defs.append((rel, i, m.group(1), l.strip()))
    names = sorted(set(d_[2] for d_ in defs))
    macro_re = re.compile(r"\b(?:" + "|".join(re.escape(n) for n in names) + r")\b") if names else None
    for rel in sorted(texts):
        lines = texts[rel].split("\n")
        fns = enclosing(lines)
        anchor = ""
        for i, l in enumerate(lines, 1):
            am = ANCHOR.search(l)
            if am:
                anchor = am.group(1)
            if re.match(r"^\s*#\s*(?:define|undef)\b", l):
                continue
            hits = BYTE.findall(l)
            macro = bool(macro_re) and macro_re.search(re.sub(STRLIT, '""', l)) is not None
            if not hits and not macro:
                continue
            if len(set(ESCAPES.findall(l))) >= 8:
                tables.append((rel, i, fns[i - 1], "a whole-byte table (%d distinct byte escapes on one line), not a separator" % len(set(ESCAPES.findall(l))), l.strip()))
                continue
            nm = None
            for (f, pat, why) in non_members:
                if rel.endswith(f) and re.search(pat, l):
                    nm = (f, pat, why)
                    break
            if nm:
                seen_nm.add(nm)
                exempt.append((rel, i, fns[i - 1], nm[2], l.strip()))
                continue
            kind = "macro" if (macro and not hits) else ("literal" if not macro else "macro+literal")
            sites.append((rel, i, fns[i - 1], carrier_of(rel, fns[i - 1], anchor), kind, l.strip(), anchor))
    for nm in non_members:
        if nm not in seen_nm:
            stale.append(nm)
    return sites, defs, tables, exempt, stale


def read_baseline(path):
    b = {}
    for ln in load(path).split("\n"):
        if not ln.strip() or ln.startswith("#"):
            continue
        k, v = ln.split("\t")[:2]
        b[k.strip()] = int(v)
    return b


def report(d, sites, defs, tables, exempt, stale, top, baseline):
    by_c = Counter(s[3] for s in sites)
    by_file = Counter(s[0] for s in sites)
    print("DELIMITED-AGGREGATE CENSUS (RULES.md NO DELIMITER-JOINED AGGREGATES, CEO-1349): %d member site(s) in %d file(s) under %s; %d non-member site(s) carried with reasons; %d whole-byte table line(s) skipped by rule; %d separator definition(s)"
          % (len(sites), len(by_file), d, len(exempt), len(tables), len(defs)))
    print("%-14s %6s   %s" % ("carrier", "sites", "files"))
    for c in CARRIERS:
        fs = sorted(set(s[0] for s in sites if s[3] == c))
        print("%-14s %6d   %s" % (c, by_c.get(c, 0), " ".join(fs)))
    print("\nBY FILE:")
    for f, n in by_file.most_common():
        print("  %5d %s" % (n, f))
    for (rel, i, name, l) in defs:
        print("\nSEPARATOR DEFINITION: %s:%d %s -- %s" % (rel, i, name, l[:120]))
    print("\nMEMBER SITES (first %d per carrier; --tsv for all):" % top)
    for c in CARRIERS:
        sel = [s for s in sites if s[3] == c]
        for s in sel[:top]:
            print("  %-12s %s:%d %s%s  %s" % (c, s[0], s[1], s[2], (" [" + s[6] + "]") if s[6] else "", s[5][:100]))
        if len(sel) > top:
            print("  %-12s ... %d more" % (c, len(sel) - top))
    print("\nNON-MEMBERS, CARRIED WITH THEIR REASONS (counted separately, never silently exempt; Lon may overrule):")
    for (rel, i, fn, why, l) in exempt:
        print("  %s:%d %s -- %s  |  %s" % (rel, i, fn, why, l[:90]))
    for (rel, i, fn, why, l) in tables:
        print("  %s:%d %s -- %s" % (rel, i, fn, why))
    rc = 0
    for (f, pat, why) in stale:
        print("  STALE NON-MEMBER DECLARATION: %s /%s/ -- no line under %s matches it any more; retire the row" % (f, pat, f))
        rc = 1
    if baseline is not None:
        print("\nRATCHET against the baseline (member sites per carrier; the count may only fall):")
        for c in CARRIERS:
            have, want = by_c.get(c, 0), baseline.get(c)
            if want is None:
                print("  %-14s %4d  (no baseline row)" % (c, have)); continue
            if have > want:
                print("  %-14s %4d > baseline %d  RED: a separator-joined value landed (make it typed storage, or declare a non-member with its reason)" % (c, have, want)); rc = 1
            elif have < want:
                print("  %-14s %4d < baseline %d  LOWER THE BASELINE to %d in this landing (the ratchet keeps the fall)" % (c, have, want, have)); rc = 1
            else:
                print("  %-14s %4d = baseline" % (c, have))
    return rc


def selftest():
    d = tempfile.mkdtemp(prefix="delim_census_selftest.")
    src = os.path.join(d, "src"); os.makedirs(os.path.join(src, "runtime")); os.makedirs(os.path.join(src, "parsers", "pascal")); os.makedirs(os.path.join(src, "templates", "x86"))
    with open(os.path.join(src, "runtime", "by_name_dispatch.c"), "w") as f:
        f.write("#define SOH '\\x01'\n"
                "static int __rk_count(const char *s) {\n    int c = 1; for (const char *p = s; *p; p++) if (*p == SOH) c++;\n    return c;\n}\n"
                "static char *__pas_join(char *buf, const char *a, const char *b) {\n    size_t n = strlen(a); memcpy(buf, a, n); buf[n] = SOH; strcpy(buf + n + 1, b); return buf;\n}\n"
                "static const char *other_split(const char *s) { return strchr(s, '\\x05'); }\n"
                "#define MON_US \"\\x1f\"\n"
                "static int script_try_call_builtin_by_name(const char *fn, const char *s) {\n    if (!strcmp(fn, \"hash_get\")) { return strchr(s, SOH) != 0; }\n    if (!strcmp(fn, \"__pas_ca_encode\")) { return s[0] == SOH; }\n    if (!strcmp(fn, \"mystery\")) { return strchr(s, MON_US) != 0; }\n    return 0;\n}\n"
                "/* a comment with SOH and '\\x01' in it must not count */\n"
                "static const char *name_only(void) { return \"HANGUL SYLLABLE SOH\"; }\n"
                "static const char tab[] = \"\\000\\000\" \"\\001\\000\" \"\\002\\000\" \"\\003\\000\" \"\\004\\000\" \"\\005\\000\" \"\\006\\000\" \"\\007\\000\" \"\\010\\000\";\n")
    with open(os.path.join(src, "runtime", "aggregates.c"), "w") as f:
        f.write("static const char *agg_key(int v, char *buf) { snprintf(buf, 32, \"\\001i%d\", v); return buf; }\n")
    with open(os.path.join(src, "parsers", "pascal", "pascal.y"), "w") as f:
        f.write("static void init_lit(char *buf, long n) { for (long k = 0; k < n; k++) { if (k) buf[k] = '\\001'; } }\n")
    with open(os.path.join(src, "templates", "x86", "x86_asm.h"), "w") as f:
        f.write("#define X86_IS_PORTMARK(s_, i_) ((s_)[i_] == '\\x01')\nstatic int is_mark(const char *s) { return X86_IS_PORTMARK(s, 0) || s[0] == '\\x01'; }\n")
    with open(os.path.join(src, "parsers", "pascal", "pascal.tab.c"), "w") as f:
        f.write("/* A Bison parser, made by GNU Bison */\nstatic char sep = '\\001';\n")
    nm = [("templates/x86/x86_asm.h", r"X86_IS_PORTMARK", "the port mark of the TEXT medium: emitter bookkeeping, never a stored value"),
          ("runtime/gone.c", r"never", "a declaration whose site is gone")]
    sites, defs, tables, exempt, stale = census(src, nm)
    want = {("by_name_dispatch.c", 3, "__rk_count", "RAKU", "macro", ""), ("by_name_dispatch.c", 7, "__pas_join", "PASCAL", "macro", ""),
            ("by_name_dispatch.c", 9, "other_split", "OTHER", "literal", ""), ("aggregates.c", 1, "agg_key", "REGISTRY_KEY", "literal", ""),
            ("pascal.y", 1, "init_lit", "PASCAL", "literal", ""),
            ("by_name_dispatch.c", 12, "script_try_call_builtin_by_name", "RAKU", "macro", "hash_get"),
            ("by_name_dispatch.c", 13, "script_try_call_builtin_by_name", "PASCAL", "macro", "__pas_ca_encode"),
            ("by_name_dispatch.c", 14, "script_try_call_builtin_by_name", "OTHER", "macro", "mystery")}
    got = {(os.path.basename(s[0]), s[1], s[2], s[3], s[4], s[6]) for s in sites}
    bad = 0
    if got != want:
        print("SELFTEST FAIL: member sites read %s, want %s" % (sorted(got), sorted(want))); bad = 1
    if sorted(d_[2] for d_ in defs) != ["MON_US", "SOH"]:
        print("SELFTEST FAIL: separator definitions read %s, want ['MON_US', 'SOH']" % [d_[2] for d_ in defs]); bad = 1
    if len(tables) != 1 or "tab" not in tables[0][4]:
        print("SELFTEST FAIL: whole-byte tables read %s, want the one table line" % (tables,)); bad = 1
    if len(exempt) != 1 or "PORTMARK" not in exempt[0][4]:
        print("SELFTEST FAIL: non-members read %s, want the port mark" % (exempt,)); bad = 1
    if len(stale) != 1 or stale[0][0] != "runtime/gone.c":
        print("SELFTEST FAIL: stale declarations read %s, want the gone.c row" % (stale,)); bad = 1
    print("SELFTEST %s: 8 member sites by carrier, kind and builtin anchor (RAKU macro, PASCAL macro, OTHER literal, REGISTRY_KEY literal, PASCAL literal, and inside the by-name dispatcher hash_get RAKU, __pas_ca_encode PASCAL, mystery OTHER through a string-valued macro), the two definitions, the comment, the name string, the byte table, the generated file and the port mark each refused or set aside by name, the stale declaration named" % ("FAIL" if bad else "PASS"))
    return bad


def main(argv):
    if "--selftest" in argv:
        return selftest()
    d = "src"; tsv = None; base = None; nmf = None; top = 12
    for i, a in enumerate(argv):
        if a == "--dir": d = argv[i + 1]
        if a == "--tsv": tsv = argv[i + 1]
        if a == "--baseline": base = argv[i + 1]
        if a == "--non-members": nmf = argv[i + 1]
        if a == "--top": top = int(argv[i + 1])
    if nmf is None:
        cand = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures", "delimited", "NON_MEMBERS.tsv")
        nmf = cand if os.path.isfile(cand) else None
    sites, defs, tables, exempt, stale = census(d, load_non_members(nmf))
    if tsv:
        with open(tsv, "w") as f:
            f.write("file\tline\tfunction\tcarrier\tkind\ttext\tanchor\n")
            for s in sites:
                f.write("%s\t%d\t%s\t%s\t%s\t%s\t%s\n" % s)
    baseline = read_baseline(base) if base else None
    return report(d, sites, defs, tables, exempt, stale, top, baseline)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
