#!/usr/bin/env bash
echo "RETIRED (BM-ONE, s153): harness.inc is the ONE authority; benchmark bodies are hand-editable files. This stamped-file generator no longer matches the artifacts. Kept one session for reference -- delete next."; exit 1
# gen_timed_bench_snobol4.sh -- emit the TIME-BASED SNOBOL4 benchmark family.
#
# THE INVERSION (Lon, 2026-08-19): the legacy family in corpus/benchmarks/snobol4/
# is an ITERATION-BASED MEASUREMENT OF TIME -- it fixes the loop count and prints
# the elapsed ms.  That shape has three measured defects:
#   (a) RESOLUTION -- TIME() is integer milliseconds (manual p.244), so arith_loop
#       at 1,000,000 iterations reads "10" on scrip: one significant digit, and a
#       10% regression is invisible.
#   (b) UNBOUNDED WALL TIME -- a slow engine takes arbitrarily longer on a fixed
#       iteration count; the suite has no time budget.
#   (c) DEAD REFS -- the programs print a nondeterministic ms delta while every
#       sibling .ref holds a deterministic result, so no .ref can ever match.
# This family inverts it: FIX THE TIME, COUNT THE ITERATIONS.  The measurement is
# a throughput (iters/ms) that is directly comparable across engines, the wall
# cost of the suite is BUDGET x programs by construction, and a deterministic
# check phase runs first so the .ref stays a live correctness oracle.
#
# ONE AUTHORITY: the harness shape lives here and nowhere else.  The emitted .sno
# files are self-contained (house rule, corpus/benchmarks/snobol4/README.md) but
# are GENERATED -- edit this script, never the output.
#
# Harness shape, per program:
#   phase 1  CHECK      fixed, small iteration count -> deterministic OUTPUT (ref-diffable)
#   phase 2  CALIBRATE  double the batch K until ONE batch spans FLOOR ms
#   phase 3  MEASURE    run batches until TIME() passes the deadline; count iterations
# Phase 2 is itself time-based: the batch size is derived from a TIME floor, not
# guessed as an iteration count.  It is load-bearing -- measured on scrip, a batch
# of 4096 under-reports throughput by 13% because the per-batch clock read is not
# yet amortized.  Rate is reported against ACTUAL elapsed, so deadline overshoot
# (up to one batch) does not bias it.
set -u
OUT="${1:-/home/claude/corpus/benchmarks/snobol4/timed}"
BUDGET="${BUDGET:-500}"     # ms of the measured phase; verified budget-independent 250..2000
FLOOR="${FLOOR:-20}"        # ms a calibrated batch must span; verified rate-flat 2..80
mkdir -p "$OUT"
# ---------------------------------------------------------------------------
# emit <name> <bottleneck> <checkn> <checkexpr> <fixedK> <<'EOF' ... sections
#   sections are:  @INIT (once)  @RESET (per phase)  @BODY (one iteration)
#   a label inside a section is written  @NAME  and is expanded per phase, since
#   the body is emitted three times and SNOBOL4 labels must be unique.
# ---------------------------------------------------------------------------
emit() {
  local name="$1" bottle="$2" checkn="$3" checkexpr="$4" fixedk="$5"
  local src; src="$(cat)"
  local init reset body
  init=$(awk '/^%%INIT/{f=1;next}/^%%RESET|^%%BODY/{f=0}f' <<<"$src")
  reset=$(awk '/^%%RESET/{f=1;next}/^%%INIT|^%%BODY/{f=0}f' <<<"$src")
  body=$(awk '/^%%BODY/{f=1;next}/^%%INIT|^%%RESET/{f=0}f' <<<"$src")
  ph() { sed "s/@/$1/g" <<<"$2"; }   # expand label prefix for this phase
  {
    echo "* $name -- TIME-BASED: fixed ms budget, count iterations"
    echo "* bottleneck: $bottle"
    echo "* GENERATED by scripts/gen_timed_bench_snobol4.sh -- edit the generator, not this file."
    echo "* phase 1 = deterministic check (ref-diffable) | phase 2 = calibrate batch | phase 3 = measure"
    echo "        &TRIM = 1"
    echo "        &ANCHOR = 0"
    echo "        &STLIMIT = -1"
    echo "        ZBUD = $BUDGET"
    echo "        ZFLR = $FLOOR"
    [ -n "$init" ] && ph "" "$init"
    echo "* ---- phase 1 -- CHECK: fixed count, deterministic output"
    [ -n "$reset" ] && ph A "$reset"
    echo "        ZI = 1"
    ph A "$body"
    echo "        ZI = LT(ZI, $checkn) ZI + 1                      :S(ABODY)"
    echo "        OUTPUT = \"check: \" $checkexpr"
    echo "* ---- phase 2 -- CALIBRATE: grow the batch until it spans ZFLR ms"
    if [ "$fixedk" = "-" ]; then
      echo "        ZK = 1"
      echo "ZCAL    ZT = TIME()"
      [ -n "$reset" ] && ph B "$reset"
      echo "        ZI = 1"
      ph B "$body"
      echo "        ZI = LT(ZI, ZK) ZI + 1                          :S(BBODY)"
      echo "        ZE = TIME() - ZT"
      echo "        ZK = LT(ZE, ZFLR) ZK * 2                        :S(ZCAL)"
    else
      echo "        ZK = $fixedk"
      echo "* batch PINNED: this kernel's cost per iteration is not steady-state,"
      echo "* so the batch size is part of the workload and must not float."
    fi
    echo "* ---- phase 3 -- MEASURE: batches until the deadline; count iterations"
    echo "        ZT = TIME()"
    echo "        ZD = ZT + ZBUD"
    echo "        ZN = 0"
    echo "ZB      ZI = 1"
    [ -n "$reset" ] && ph C "$reset"
    ph C "$body"
    echo "        ZI = LT(ZI, ZK) ZI + 1                          :S(CBODY)"
    echo "        ZN = ZN + ZK"
    echo "        LT(TIME(), ZD)                                  :S(ZB)"
    echo "        ZE = TIME() - ZT"
    echo "        OUTPUT = \"iters: \" ZN"
    echo "        OUTPUT = \"ms: \" ZE"
    echo "END"
  } > "$OUT/$name.sno"
  echo "  emitted $name.sno"
}
# ===========================================================================
echo "generating TIME-based benchmarks into $OUT (budget=${BUDGET}ms floor=${FLOOR}ms)"
# --- arithmetic / loop dispatch -------------------------------------------
emit arith_loop_t "counter increment; loop dispatch" 1000 "A" - <<'EOF'
%%RESET
        A = 0
%%BODY
@BODY   A = A + 1
EOF
emit var_access_t "identifier lookup; 5 live vars" 1000 "E" - <<'EOF'
%%RESET
        A = 1
        B = 2
        C = 0
        D = 0
        E = 0
%%BODY
@BODY   A = A + 1
        B = B + 2
        C = A + B
        D = C + A
        E = D + B
EOF
emit op_dispatch_t "arithmetic operator dispatch" 1000 "N" - <<'EOF'
%%RESET
        N = 1
%%BODY
@BODY   N = N + 3
        N = N - 1
        N = N * 2
        N = GE(N, 1000000) N / 1000
EOF
# --- strings ---------------------------------------------------------------
emit string_manip_t "REPLACE/SIZE throughput" 1000 "NS" - <<'EOF'
%%BODY
@BODY   S = 'The quick brown fox jumps over the lazy dog'
        S = REPLACE(S, 'aeiou', '*****')
        NS = SIZE(S)
EOF
emit string_concat_t "string growth; cost rises with length" 1000 "SIZE(S)" 20000 <<'EOF'
%%RESET
        S = ''
%%BODY
@BODY   S = S 'x'
EOF
# --- patterns --------------------------------------------------------------
emit pattern_bt_t "alternation backtracking + SPAN capture" 1000 "W" - <<'EOF'
%%INIT
        PAT = ('aaa' | 'bbb' | 'ccc' | 'ddd') SPAN('abcd') . W
        SUB = 'xxxxxxxxxxbbbccccddddaaaaxxxxxxxxxxbbbccccddddaaaa'
%%BODY
@BODY   SUB ? PAT
EOF
emit string_pattern_t "BREAK-driven field split" 1000 "F3" - <<'EOF'
%%INIT
        REC = 'alpha,beta,gamma,delta,epsilon'
        PAT = BREAK(',') . F1 ',' BREAK(',') . F2 ',' BREAK(',') . F3
%%BODY
@BODY   REC ? PAT
EOF
# --- functions / recursion -------------------------------------------------
emit func_call_t "call/return overhead; trivial body" 1000 "R" - <<'EOF'
%%INIT
        DEFINE('INC(N)')                                :(@INCE)
@INC    INC = N + 1                                     :(RETURN)
@INCE
%%RESET
        R = 0
%%BODY
@BODY   R = INC(R)
EOF
emit fibonacci_t "deep recursion; FIB(16) per iteration" 3 "R" - <<'EOF'
%%INIT
        DEFINE('FIB(N)')                                :(@FIBE)
@FIB    FIB = LT(N, 2) N                                :S(RETURN)
        FIB = FIB(N - 1) + FIB(N - 2)                   :(RETURN)
@FIBE
%%BODY
@BODY   R = FIB(16)
EOF
# --- aggregates ------------------------------------------------------------
emit table_access_t "TABLE fill + sum, 500 entries" 20 "SUM" - <<'EOF'
%%BODY
@BODY   T = TABLE(512)
        I = 1
@FILL   T[I] = I * 2
        I = LT(I, 500) I + 1                            :S(@FILL)
        SUM = 0
        I = 1
@READ   SUM = SUM + T[I]
        I = LT(I, 500) I + 1                            :S(@READ)
EOF
emit array_sum_t "ARRAY fill + sum, 500 entries" 20 "SUM" - <<'EOF'
%%BODY
@BODY   V = ARRAY(500)
        I = 1
@FILL   V[I] = I * 2
        I = LT(I, 500) I + 1                            :S(@FILL)
        SUM = 0
        I = 1
@READ   SUM = SUM + V[I]
        I = LT(I, 500) I + 1                            :S(@READ)
EOF
# --- dynamic evaluation ----------------------------------------------------
emit eval_fixed_t "EVAL() of a fixed expression" 1000 "R" - <<'EOF'
%%INIT
        X = 10
%%BODY
@BODY   R = EVAL('X + 1')
EOF
echo "done."
