#!/usr/bin/env bash
# test_gate_gc_the_blob_frame_interior_is_a_static_layout.sh -- the R-4(b) SNOBOL4 stored-pattern blob frame
# (emit.cpp, "R-4(b) BLOB ACTIVATION FRAME") carries ONE compiler-generated static layout of its interior.
# Row gc-the-blob-frame-interior-takes-one-static-layout-and-its-cross-frame-dependency-is-named (cto, 2026-09-19);
# ARCH-GC-COMPILE-TIME-FRAME-MAPS.md section 6.2e; Lon CEO-905 ("static layouts which have been generated by the
# compiler"). It retires the 6.2b exclusion (a blob frame presented no map cell; arm 6 of the safe-point gate held the
# count at 4) and unblocked rt_cas_live_span (conservative total 24 -> 21).
#
# WHAT IS HELD. The blob prologue is push rbp; mov rbp,rsp; sub rsp,bfb+16(+pad); the extra 16 at the BOTTOM of the
# carve is the frame's DT_MAP cell { slen = bfb+16, p = &map }, stored on the line after the carve (the safe-point
# gate's arm 6 reads exactly that line), then [rbp-bfb, rbp) is zeroed so a collection before a box wrote its slot
# reads a null. The map carries GC_FRAME_MAP_BLOB, header_bytes = 24 (saved rbp, gamma, omega above rbp) and, after
# its four quads, n then n entries `off | kind<<32 | size<<40` (gc_frame_map.h GC_LAY_*), generated by the SAME
# frame_slot_scan walk that hands the boxes their slots (single producer, emit.cpp blob_layout_build): gamma/omega
# CODE, [rbp-24] the DTP pointer PTR_GC (the one heap pointer in the head), [rbp-32] r12 RAW (into the rt_cas island,
# a non-moving slab), ARBNO/FENCE1 saved-rsp RAW, ASSIGN_SAVE cursor RAW, ALTERNATE's 32-byte choice record (RAW,
# CODE, CODE, RAW), a scratch-cell leaf (SPAN/BREAK/BREAKX/TAB/RTAB/REM/ARB/BAL) two slots: its pointer slot {PTR_GC,
# RAW} -- the deferred-string form SPAN(*C)/ANY(*C)/NOTANY(*C)/BREAK(*C) keeps the string pointer rt_pat_prim_str
# returned THERE (moved in this landing from the cnt/cursor word it shared before, so no word is sometimes an int and
# sometimes a pointer) -- and its cnt/cursor slot RAW; any other xop result cell DESCR. THE INVARIANT IS COVERAGE: the
# generator sorts the entries and ABORTS unless they tile [rbp-bfb, rbp+24) exactly. The collector (gc_heap.c
# gc_zeta_frame -> gc_blob_layout_visit) trusts the cell only after the map is REGISTERED (an address comparison,
# never a dereference of a stack word), visits DESCR by tag and PTR_GC by rt_gc_visit_raw, skips RAW/CODE, and resumes
# the walk at rbp+24: the interior is never word-swept again.
#
# ARMS. (1) every blob prologue in the witness set names its map on the line after the carve (cell-less blobs = 0,
# population printed). (2) the two media's INSTALLED tables agree entry for entry on [GC-MAPTAB-LAYOUT]
# (SCRIP_GC_MAPS_DUMP=1, read back through rt_gc_frame_maps_dump, not the emitter's intent). (3) the coverage plant
# SCRIP_GC_BLOB_LAYOUT_PLANT=1 (drops the last entry) ABORTS the emitter in both media, rc 134. (4) the witness
# scripts/gc_witnesses/hb_blob_span_defer.sno (SPAN(*C) . X inside a stored pattern, C a heap string) matches its
# oracle-cut ref at SCRIP_GC_STRESS=1,3,5 in BOTH modes, and the kind plant SCRIP_GC_BLOB_LAYOUT_PLANT=2 (every
# DESCR/PTR_GC entry retagged RAW) is COUNTED by the reporter: raw_in_heap goes 0 -> >0 on the frame that holds the
# pointer, in both media. ⛔ MEASURED AND RECORDED, not hidden: (a) SCRIP_GC_STRESS arms on ALLOCATION, not on the
# poll, and rt_pat_prim_str allocates nothing, so a witness without an allocation inside the frame never collects
# there in mode 4 (7 collections, frames=0 at every one) -- *ALLOC() is in the witness for that reason; (b) an
# output-level fail-once for the pointer slot did NOT reproduce: SCRIP_ZETA_TELEM shows moved=0B at the collections
# that see the frame, nothing dies in the witness so nothing slides, and a stale pointer reads the right bytes; the
# word the planted column counts is [rbp-24], the DTP (HB_DTP, a moving type), while the leaf's string word resolved
# to a NON-moving block in this witness. The reporter's column is the discriminator this gate holds. (5) the reporter
# prints the frame under SCRIP_GC_MAPS=1 with raw_in_heap=0 unplanted.
"$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/util_require_fresh.sh" --gate "$(basename "${BASH_SOURCE[0]}" .sh)" || exit $?
set -uo pipefail
G="$(basename "${BASH_SOURCE[0]}" .sh)"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; ROOT="$(cd "$HERE/.." && pwd)"
S4E="${S4E_HOME:-$(cd "$ROOT/.." && pwd)}"
SCRIP="${SCRIP_BIN:-$ROOT/scrip}"; [ -x "$SCRIP" ] || { echo "⛔ GATE REFUSE(2) [$G]: no scrip at $SCRIP"; exit 2; }
export SNO_LIB="${SNO_LIB:-$S4E/corpus/include}"
T=$(mktemp -d) || exit 2; trap 'rm -rf "$T"' EXIT
RC=0
W1="$ROOT/scripts/gc_witnesses/hb_blob_span_defer.sno"; R1="$ROOT/scripts/gc_witnesses/hb_blob_span_defer.ref"
W2="$ROOT/scripts/fixtures/gc_roots_witness.sno"; W3="$ROOT/scripts/gc_witnesses/hb_dtp.sno"
for f in "$W1" "$R1" "$W2" "$W3"; do [ -f "$f" ] || { echo "⛔ GATE REFUSE(2) [$G]: missing $f"; exit 2; }; done
printf "        P = (SPAN('a') | LEN(1)) . X ARBNO('b') FENCE(LEN(1)) BREAK('c') . Y\n        Q = ARB . W *Z . V\n        Z = 'abc'\n        'aabbxc' P  :F(NO)\n        OUTPUT = X '-' Y\n        'zzabczz' Q :F(NO)\n        OUTPUT = W '-' V  :(END)\nNO      OUTPUT = 'NO'\nEND\n" > "$T/w4.sno"
m4build() { "$SCRIP" --compile "$1" > "$2.s" 2>/dev/null && gcc "$2.s" -o "$2" -L"$ROOT/out" -lscrip_rt -lm -lpthread -Wl,-rpath,"$ROOT/out" 2>/dev/null; }
echo "  HOLDS: the R-4(b) blob frame's interior is ONE compiler-generated static layout sealed after its map (ARCH-GC 6.2e): the cell on the line after the carve, both media's tables agree, coverage is enforced by an emitter abort, the pointer slot survives forced collection in both modes and the kind plant is counted by the reporter"
blobcnt() { awk '{ if (want) { n++; if ($0 !~ /\.Lgcmap_/) c++; want = 0 } if (p2 && $1=="sub" && $2=="rsp,") want = 1; p2 = (p1 && $1=="mov" && $2=="rbp," && $3=="rsp"); p1 = ($1=="push" && $2=="rbp"); } END{print n+0, c+0}' "$1"; }
tot=0; bad=0
for w in "$W1" "$W2" "$W3" "$T/w4.sno"; do
    "$SCRIP" --compile "$w" > "$T/a.s" 2>/dev/null || { echo "  arm 1 FAIL ($(basename "$w") does not compile)"; RC=1; continue; }
    read -r n c <<< "$(blobcnt "$T/a.s")"; tot=$((tot + n)); bad=$((bad + c))
done
if [ "$tot" -gt 0 ] && [ "$bad" = 0 ]; then echo "  arm 1 PASS: $tot blob prologue(s) over 4 witnesses, every one stores its .Lgcmap_ cell on the line after the carve (cell-less = 0)"
else echo "  arm 1 FAIL: $tot blob prologue(s), $bad without a map cell on the line after the carve"; RC=1; fi
m4build "$W2" "$T/fx" && m4build "$W1" "$T/hb" && m4build "$T/w4.sno" "$T/w4" || { echo "  arm 2 FAIL (a mode-4 witness did not build)"; RC=1; }
a2=0
for pair in "$W2:$T/fx" "$W1:$T/hb" "$T/w4.sno:$T/w4"; do
    src="${pair%%:*}"; bin="${pair##*:}"
    SCRIP_GC_MAPS_DUMP=1 "$SCRIP" "$src" 2>&1 >/dev/null </dev/null | grep '^\[GC-MAPTAB-LAYOUT\]' | sort > "$T/l3.txt"
    SCRIP_GC_MAPS_DUMP=1 "$bin" 2>&1 >/dev/null </dev/null | grep '^\[GC-MAPTAB-LAYOUT\]' | sort > "$T/l4.txt"
    if [ -s "$T/l3.txt" ] && cmp -s "$T/l3.txt" "$T/l4.txt"; then a2=$((a2 + $(wc -l < "$T/l3.txt"))); else echo "  arm 2 FAIL ($(basename "$src"): mode 3 and mode 4 layouts differ or are absent: $(wc -l < "$T/l3.txt") vs $(wc -l < "$T/l4.txt") lines)"; diff "$T/l3.txt" "$T/l4.txt" | head -4; RC=1; fi
done
[ "$a2" -gt 0 ] && echo "  arm 2 PASS: $a2 blob layout(s) read back through rt_gc_frame_maps_dump agree entry for entry in both media (offset:kind:size)"
SCRIP_GC_BLOB_LAYOUT_PLANT=1 "$SCRIP" "$W3" >/dev/null 2>"$T/p3.err" </dev/null; p3=$?
SCRIP_GC_BLOB_LAYOUT_PLANT=1 "$SCRIP" --compile "$W3" >/dev/null 2>"$T/p4.err" </dev/null; p4=$?
if [ "$p3" = 134 ] && [ "$p4" = 134 ] && grep -q 'does not tile' "$T/p3.err" && grep -q 'does not tile' "$T/p4.err"; then echo "  arm 3 PASS: the coverage plant (one entry dropped) aborts the emitter in both media (rc 134, 'does not tile')"
else echo "  arm 3 FAIL: coverage plant not caught (rc $p3 / $p4)"; RC=1; fi
ref="$(cat "$R1")"; a4=""; a4bad=0
for st in 1 3 5; do
    o3="$(SCRIP_GC_STRESS=$st timeout 60 "$SCRIP" "$W1" 2>/dev/null </dev/null)"; o4="$(SCRIP_GC_STRESS=$st timeout 60 "$T/hb" 2>/dev/null </dev/null)"
    if [ "$o3" = "$ref" ] && [ "$o4" = "$ref" ]; then a4="$a4 stress=$st:ok"; else a4="$a4 stress=$st:m3=[$o3]m4=[$o4]"; a4bad=1; fi
done
if [ "$a4bad" = 0 ]; then echo "  arm 4a PASS: hb_blob_span_defer matches its oracle ref '$ref' at SCRIP_GC_STRESS=1,3,5 in both modes --$a4"
else echo "  arm 4a FAIL: the pointer slot did not survive forced collection --$a4"; RC=1; fi
rih() { grep '^\[GC-BLOB\] frames=[1-9]' | sed -n 's/.*raw_in_heap=\([0-9]*\).*/\1/p' | sort -n | tail -1; }
u3=$(SCRIP_GC_MAPS=1 SCRIP_GC_STRESS=1 "$SCRIP" "$W1" 2>&1 >/dev/null </dev/null | rih); k3=$(SCRIP_GC_BLOB_LAYOUT_PLANT=2 SCRIP_GC_MAPS=1 SCRIP_GC_STRESS=1 "$SCRIP" "$W1" 2>&1 >/dev/null </dev/null | rih)
SCRIP_GC_BLOB_LAYOUT_PLANT=2 "$SCRIP" --compile "$W1" > "$T/hbp.s" 2>/dev/null && gcc "$T/hbp.s" -o "$T/hbp" -L"$ROOT/out" -lscrip_rt -lm -lpthread -Wl,-rpath,"$ROOT/out" 2>/dev/null
u4=$(SCRIP_GC_MAPS=1 SCRIP_GC_STRESS=1 "$T/hb" 2>&1 >/dev/null </dev/null | rih); k4=$(SCRIP_GC_MAPS=1 SCRIP_GC_STRESS=1 "$T/hbp" 2>&1 >/dev/null </dev/null | rih)
if [ "${u3:-x}" = 0 ] && [ "${u4:-x}" = 0 ] && [ "${k3:-0}" -gt 0 ] && [ "${k4:-0}" -gt 0 ]; then echo "  arm 4b PASS: the kind plant (heap-pointer words retagged RAW) is counted by the reporter -- raw_in_heap unplanted m3=$u3 m4=$u4, planted m3=$k3 m4=$k4 (the layout lie the column exists to see)"
else echo "  arm 4b FAIL: raw_in_heap unplanted m3=${u3:-none} m4=${u4:-none}, planted m3=${k3:-none} m4=${k4:-none} -- the reporter does not see the kind plant"; RC=1; fi
line=$(SCRIP_GC_MAPS=1 SCRIP_GC_STRESS=1 "$SCRIP" "$W1" 2>&1 >/dev/null </dev/null | grep '^\[GC-BLOB\] frames=[1-9]' | head -1)
if [ -n "$line" ] && echo "$line" | grep -q 'ptr_gc=[1-9]' && echo "$line" | grep -q 'raw_in_heap=0'; then echo "  arm 5 PASS: the reporter prints the blob frame it visited: $line"
else echo "  arm 5 FAIL: reporter line '$line'"; RC=1; fi
if [ "$RC" = 0 ]; then echo "GATE PASS(0) [$G]: the blob frame interior is a static layout in both media, coverage is enforced, the pointer slot survives forced collection, and the kind plant is counted (examined 6 arms, two with planted violations)"
else echo "GATE FAIL(1) [$G]: the blob static layout does not hold (examined 6 arms)"; fi
echo "    tree: SCRIP=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null)$(git -C "$ROOT" diff --quiet 2>/dev/null || echo -DIRTY)  measured $(date -u +%Y-%m-%dT%H:%MZ)"
exit $RC
