#!/usr/bin/env bash
# test_gate_raku_an_unknown_method_throws_x_method_notfound_dot_question_calls_it_maybe_can_finds_methods_and_attributes_and_fallback_catches_the_rest_agree_with_rakudo.sh -- A METHOD THE INVOCANT DOES NOT HAVE IS AN X::Method::NotFound, `.?name` ANSWERS Nil, `.can(name)` SEES METHODS AND PUBLIC ATTRIBUTES UP THE MRO, `method FALLBACK` RECEIVES THE REST
# (row raku-every-suite-to-100-under-nonet-ceo-1266; found by probing what a runtime error does: 447 Roast files use throws-like, 269 dies-ok, 386 lives-ok, and the sampled files that stop early all stopped at a method call that neither died nor threw).
#
# THE DEFECT, measured against Rakudo: (1) `"abc".zzzmeth`, `42.zzzmeth`, `[1,2,3].zzzmeth`, `{a=>1}.zzzmeth` made the STATEMENT QUIETLY FAIL (meth_call's tail answered FAILDESCR), so `try { "abc".zzzmeth; CATCH { default { say .^name } } }` printed nothing and `throws-like {...}, X::Method::NotFound` could never hold; on a user object `Dog.new.zzzmeth` ABORTED THE PROGRAM ("procedure 'Dog__zzzmeth' has no stackless slab"), uncatchable; (2) `.?name` (call it if there is such a method) was parsed as a plain call, so it failed the same way; (3) `.can("m")` on a user object aborted ("procedure 'A__can' has no stackless slab"); (4) `method FALLBACK($name, *@args)` was never consulted.
# THE CURE: (by_name_dispatch.c rk_method_missing) both tails of meth_call throw X::Method::NotFound with Rakudo's message "No such method 'zzzmeth' for invocant of type 'Dog'" and its attributes method, typename and invocant (the class is registered with those four fields), so `try`, CATCH, dies-ok and throws-like see a typed exception; the type name is the user class, or Str / Int / Num / Array / Hash / List / Bool for a built-in invocant; (rk_tree.c method_call) `.?name` is passed as "?name" and meth_call strips it and answers Nil when there is no such method; `.can(name)` on an object or a class walks the MRO and answers a list with one entry per class that has the method or a public attribute of that name; a class's FALLBACK method is called with the name and the arguments before anything is thrown.
# A REAL RAKUDO METHOD THAT SCRIP HAS NOT IMPLEMENTED YET (`.permutations`, `.Rat`, `.WHICH` on a built-in invocant) STAYS A QUIET FAIL, exactly as before: src/runtime/rk_rakudo_method_names.inc, GENERATED by scripts/util_gen_rakudo_method_names.py from the oracle's own `.^methods(:all)` of the core types (824 names), separates a method that does not exist from one that merely is not written here, so no file that passes today stops passing (the first cut threw for every unimplemented method and lost 5 of 19 passing sampled files, four of them on `.permutations`).
# ALSO (found by the sample): a method a program AUGMENTS onto a built-in class (`augment class Int { method double { self * 2 } }; say 5.double`; S02-types/lists.t's `augment class List`) is called on a built-in invocant (Int, Str, List, Array, Bool and Cool / Any / Mu); it used to fail quietly.
# NOT HERE (own rows, measured): `.can` and `.^can` / `.^methods` on a BUILT-IN invocant (`"abc".can("uc")`), `.+name` / `.*name`, `Foo.nextwith`-style callsame forms, the Method object `.can` should return (this returns the name), the "Did you mean" suggestion Rakudo appends to the message for a near-miss name, an unimplemented real method still failing quietly (a gap to fill, not report).
# THE WITNESS (52 lines of output cut by the INSTALLED Rakudo 2022.12), graded in m3 (--run) and m4 (--compile + link), then under SCRIP_GC_STRESS 1 3 5 in both modes.
# FAILED ONCE, measured on the sitting's control build cfcfaf46d (nothing landed since touches method dispatch): the program ABORTS at its first user-object call (rc 1, "procedure 'Dog__zzzmeth' has no stackless slab") and prints none of its 52 lines.
#
# EXIT: 0 every witness matches in both modes; 1 a mismatch or a crash on a witness; 2 REFUSED (stale binary, no gcc).
# Usage: bash scripts/test_gate_raku_an_unknown_method_throws_x_method_notfound_dot_question_calls_it_maybe_can_finds_methods_and_attributes_and_fallback_catches_the_rest_agree_with_rakudo.sh   (~10s, no oracle at run time, no network)
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
cd "$ROOT"
. "$HERE/lib_gate.sh"
GATE_NAME="raku_an_unknown_method_throws_x_method_notfound_dot_question_calls_it_maybe_can_finds_methods_and_attributes_and_fallback_catches_the_rest_agree_with_rakudo"
gate_parse_args "$@"
gate_require_fresh "$ROOT" src "$ROOT/scrip" "$ROOT/out/libscrip_rt.so"
command -v gcc >/dev/null 2>&1 || { echo "⛔ REFUSE(rc=2) [$GATE_NAME]: gcc not found -- mode 4 cannot be linked, so half the population is unmeasured"; exit 2; }
W="$(mktemp -d)"; trap 'rm -rf "$W"' EXIT
cat > "$W/w.raku" <<'EOF'
class Animal {
    method speak { "..." }
    method name { "animal" }
}
class Dog is Animal {
    method speak { "woof" }
}
sub probe(&code) { try { code(); CATCH { default { say .^name, " | ", .message; say .method if .can("method"); } } } }
probe({ "abc".zzzmeth });
probe({ 42.zzzmeth });
probe({ [1, 2, 3].zzzmeth });
probe({ {a => 1}.zzzmeth });
probe({ (1, 2).zzzmeth });
probe({ 3.5e0.zzzmeth });
probe({ True.zzzmeth });
probe({ Dog.new.zzzmeth });
probe({ Dog.zzzmeth });
probe({ Int.zzzmeth });
say "abc".?zzzmeth.defined;
say 42.?zzzmeth.defined;
say Dog.new.?zzzmeth.defined;
say Dog.new.?speak;
say "abc".?uc;
say [1, 2, 3].?elems;
say Dog.new.can("speak").elems;
say Dog.new.can("name").elems;
say Dog.new.can("zzzmeth").elems;
say Dog.can("speak").so;
say Dog.new.can("zzzmeth").so;
say Dog.new.isa(Animal);
say Dog.new.isa(Str);
say Dog.new.does(Animal);
try { Dog.new.zzzmeth; CATCH { when X::Method::NotFound { say "typed catch: ", .method } } }
my $r = try { Dog.new.zzzmeth };
say $r.defined;
say (try { "x".zzzmeth }).defined;
say "still running";
class Chatty {
    method FALLBACK($name, *@args) { "fallback($name)" }
    method real { "real" }
}
say Chatty.new.real;
say Chatty.new.anything;
say Chatty.new.other(1, 2);
class Plain {
    has $.x = 5;
    method m { 1 }
}
my $p = Plain.new;
say $p.x;
say $p.?nothing.defined;
say $p.x.?nothing.defined;
say $p.can("x").so;
say $p.can("m").so;
say $p.can("nothing").so;
use MONKEY-TYPING;
augment class Int { method double { self * 2 } }
say 5.double;
augment class Str { method shout { self.uc ~ "!" } }
say "abc".shout;
augment class List { method rt_x { 62836 } }
say <1 2 3>.rt_x;
say (1,2,3).rt_x;
augment class Array { method amax { self.max } }
my @a = 3,1,2;
say @a.amax;
EOF
cat > "$W/w.ref" <<'EOF'
X::Method::NotFound | No such method 'zzzmeth' for invocant of type 'Str'
zzzmeth
X::Method::NotFound | No such method 'zzzmeth' for invocant of type 'Int'
zzzmeth
X::Method::NotFound | No such method 'zzzmeth' for invocant of type 'Array'
zzzmeth
X::Method::NotFound | No such method 'zzzmeth' for invocant of type 'Hash'
zzzmeth
X::Method::NotFound | No such method 'zzzmeth' for invocant of type 'List'
zzzmeth
X::Method::NotFound | No such method 'zzzmeth' for invocant of type 'Num'
zzzmeth
X::Method::NotFound | No such method 'zzzmeth' for invocant of type 'Bool'
zzzmeth
X::Method::NotFound | No such method 'zzzmeth' for invocant of type 'Dog'
zzzmeth
X::Method::NotFound | No such method 'zzzmeth' for invocant of type 'Dog'
zzzmeth
X::Method::NotFound | No such method 'zzzmeth' for invocant of type 'Int'
zzzmeth
False
False
False
woof
ABC
3
2
1
0
True
False
True
False
True
typed catch: zzzmeth
False
False
still running
real
fallback(anything)
fallback(other)
5
False
False
True
True
False
10
ABC!
62836
62836
3
EOF
fails=0; GATE_EXAMINED=0
ck() {
    local w="$1" m="$2" out rc
    GATE_EXAMINED=$((GATE_EXAMINED + 1))
    if [ "$m" = m3 ]; then out="$(env ${ST:+SCRIP_GC_STRESS=$ST} timeout 120 "$ROOT/scrip" --run "$W/$w.raku" 2>/dev/null </dev/null)"; rc=$?
    else
        if ! timeout 60 "$ROOT/scrip" --compile -o "$W/$w.s" "$W/$w.raku" </dev/null >"$W/$w.cerr" 2>&1 \
           || ! gcc -o "$W/$w.bin" "$W/$w.s" -L"$ROOT/out" -lscrip_rt -Wl,-rpath,"$ROOT/out" -lm -lpthread >>"$W/$w.cerr" 2>&1; then
            printf '  FAIL %-7s %s: did not build (%s)\n' "$w" "$m" "$(head -1 "$W/$w.cerr" | cut -c1-110)"; fails=$((fails + 1)); return; fi
        out="$(env ${ST:+SCRIP_GC_STRESS=$ST} timeout 120 "$W/$w.bin" 2>/dev/null </dev/null)"; rc=$?
    fi
    if [ "$rc" -ge 124 ]; then printf '  FAIL %-7s %s: died rc=%s\n' "$w" "$m" "$rc"; fails=$((fails + 1)); return; fi
        if [ "$out" = "$(cat "$W/$w.ref")" ]; then printf '  ok   %-7s %s%s\n' "$w" "$m" "${ST:+ stress=$ST}"
    else printf '  FAIL %-7s %s: got [%s] want [%s]\n' "$w" "$m" "$(printf '%s' "$out" | tr '\n' ' ' | cut -c1-110)" "$(tr '\n' ' ' < "$W/$w.ref" | cut -c1-110)"; fails=$((fails + 1)); fi
}
ST=""; for w in w; do for m in m3 m4; do ck "$w" "$m"; done; done
for ST in 1 3 5; do for w in w; do for m in m3 m4; do ck "$w" "$m"; done; done; done
gate_verdict "$fails" "witness-mode pair(s) wrong: a method-protocol result (X::Method::NotFound, .?name, .can, FALLBACK) that disagrees with Rakudo"
