#!/usr/bin/env bash
# test_emit_diff_invariant_check.sh — ⛔ REFUSES rc=2. LON ABOLISHED ITS SUBJECT, AND IT KEPT GRADING ANYWAY.
# Row dead-suite-path-consumer-sweep (hq_C 2026-09-04). M-G-INV-EMIT fossil: it diffed each test source's
# co-located generated artifacts (`foo.s` `foo.j` `foo.il`) against fresh compiler output, over
# `$CORPUS/crosscheck` (SNOBOL4) and the icon/prolog/rebus test trees, across cells snobol4_x86 · snobol4_jvm
# · snobol4_net · snobol4_js · snobol4_wasm · icon_* · prolog_* · rebus_*.
#
# ⛔ EVERY ONE OF ITS FOUR PREMISES IS GONE. Measured 2026-09-04 on SCRIP cb60deb7f:
#   1. THE ARTIFACTS: Lon ruled 2026-08-24 s269, verbatim in substance — "We will abandon the idea of having
#      artifacts for tests... we want artifacts for benchmarks and demos." `.s` exists ONLY beside benchmarks
#      and demos (RULES.md item 4). A test-tree artifact is not a golden this may diff against.
#   2. THE FLAG: it invokes `-x86`, removed from the driver ("scrip: cannot open '-x86'").
#   3. THE PATH: `$CORPUS/crosscheck` was folded into the master suites (corpus d5513783 / da098747).
#   4. THE BACKENDS: jvm/net/js/wasm are all refused by the driver ("[SMX] --target=X removed"); x86 is the
#      only live one, and the `.j`/`.il` files this diffed have a census of ZERO in the corpus.
#
# ⛔⭐ AND IT WAS STILL PRINTING A VERDICT: run unmodified today it reported "0 pass / 8 fail" rc=1 — eight
# REAL-LOOKING FAILs, all backend `-x86`, over eight leftover `.s` files under corpus/tests/scrip_test/prolog/
# that the artifact policy says should not be there at all. A reader chasing those eight would have gone
# hunting for a codegen regression that does not exist. ⭐ THE SHAPE: when a grader's SUBJECT is abolished but
# its INPUTS are merely mostly-deleted, it does not go quiet — it grades the residue and reports it in the
# vocabulary of a live defect. rc=1 says "the compiler is wrong"; the truth was "this question was retired."
# That is why this refuses rc=2 (RULES.md § an instrument that cannot measure REFUSES, never skip-as-success).
#
# ⭐ THE LIVE EQUIVALENT, if you came here looking for emission stability: the mode-4 `.s` beside every
# benchmark and demo, regenerated by `util_regen_benchmark_s_artifacts.sh` · `util_regen_demo_s_artifacts.sh`
# · `util_regen_prolog_bench_s_artifacts.sh` (and, for corpus/benchmarks/icon/, `update_icon_bench_asm.sh`),
# each of which rewrites only on a real emitter change, so `git diff` in corpus IS the emission diff.
echo "⛔ REFUSE(2): the emit-diff invariant cannot measure — test-tree .s/.j/.il artifacts were abolished by Lon 2026-08-24 s269 (artifacts beside benchmarks and demos ONLY), the '-x86' flag is removed from the driver, \$CORPUS/crosscheck was folded into the master suites, and every non-x86 backend it graded is driver-refused. It was reporting 0 pass / 8 fail rc=1 over leftover artifacts: a retired question wearing the vocabulary of a live defect. Emission stability now lives in the benchmark/demo .s regen chain." >&2
exit 2
