#!/usr/bin/env bash
export S4E_ONE_RUNNER_FIXTURE="gate arm ${0##*/}: the harness's run, extension-ref and extension-check verbs over a scratch suite outside corpus/, not a board (CEO-547)"
# test_gate_extension_refs_are_marked_graded_and_never_recut.sh -- THE EXTENSION REF (Lon 2026-10-02 15:5x CDT, in-chat to the coo,
# verbatim: "So mark it passing. We need a concept now of extensions which will NOT have their REF generated by oracle. But generated
# by us here." · "In this case use CSNOBOL4 to gen the ORD tests. Mark the test as not generated by the SPITBOL oracle."). A test of an
# extension the suite's one oracle lacks (ORD: sbl -bf ERROR 022) takes its ref from a NAMED other oracle, is marked in a ledger beside
# the data (ALL.extensions.tsv beside a rung suite, EXTENSIONS.tsv beside a package) and stays in the denominator. WHAT THIS GATE HOLDS,
# over a scratch two-entry rung suite and a scratch one-program package outside corpus/ (CEO-547), through corpus_suite_harness.py:
# (1) extension-ref without --apply writes nothing; with --apply it cuts the ORD entry's ref from csnobol4 (65) and writes a ledger row
#     whose sha is the ref's; it REFUSES rc=2 on the entry the suite's own oracle answers identically (no extension needed);
# (2) run grades the ORD entry against that ref -- PASS in m3, IN the denominator -- and prints EXTENSION_REF_COUNT 1 with its row;
# (3) FAIL-ONCE, the same entry declared OUTSIDE instead (the pre-cure shape) leaves the graded denominator, so arm 2 reds on it;
# (4) run REFUSES rc=2 on a ref edited after its row was cut (a stale sha), on a name both in the ledger and the outside list, and on
#     a ref_oracle accessor the harness does not know;
# (5) extension-check passes a package ledger, and REFUSES rc=2 on a stale sha and on a program also named in EXCLUDED.tsv;
# (6) capture-oracle-refs REFUSES rc=2 to overwrite a package program the ledger names.
# rc 2 when sbl, csnobol4 or the binary is missing.
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; ROOT="$(cd "$HERE/.." && pwd)"; cd "$ROOT" || { echo "⛔ REFUSE(2): cannot cd to SCRIP root" >&2; exit 2; }
. "$HERE/lib_gate.sh" 2>/dev/null || { echo "⛔ REFUSE(2): no lib_gate.sh" >&2; exit 2; }
. "$HERE/lib_oracle_flags.sh" 2>/dev/null || { echo "⛔ REFUSE(2): no lib_oracle_flags.sh" >&2; exit 2; }
GATE_NAME=extension_refs_are_marked_graded_and_never_recut; gate_parse_args "$@" 2>/dev/null || true
H="$HERE/corpus_suite_harness.py"
[ -x "$ROOT/scrip" ] || { echo "⛔ GATE REFUSE(2) [$GATE_NAME]: no ./scrip -- run make"; exit 2; }
gate_require_fresh "$ROOT" src "$ROOT/scrip" "$ROOT/out/libscrip_rt.so" || exit 2
sbl_correctness_bin >/dev/null 2>&1 || { echo "⛔ GATE REFUSE(2) [$GATE_NAME]: no SPITBOL oracle"; exit 2; }
csnobol4_bin >/dev/null 2>&1 || { echo "⛔ GATE REFUSE(2) [$GATE_NAME]: no csnobol4 -- the extension oracle this gate cuts with"; exit 2; }
export S4E_PROGRESS_OFF=1 S4E_SEAT="${S4E_SEAT:-coo}"
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT
banner() { local t=" $1 $2"; printf '*%s%s\n' "$(printf '%*s' $((79 - ${#t})) '' | tr ' ' -)" "$t"; }
suite() {  # <dir> <ord ref line> -- a two-entry rung suite: ord_entry (ORD, which sbl lacks) and plain_entry
    mkdir -p "$1"
    { banner 1 ord_entry; printf "\tOUTPUT = ORD('A')\nEND\n"; banner 2 plain_entry; printf "\tOUTPUT = 'hi'\nEND\n"; } > "$1/ALL.sno"
    { banner 1 ord_entry; printf '%s\n' "$2"; banner 2 plain_entry; printf 'hi\n'; } > "$1/ALL.ref"
}
red=0; n=0
arm() { n=$((n+1)); if [ "$2" = "$3" ]; then echo "  ok   $n $1: $2"; else echo "  FAIL $n $1: got '$2' want '$3'"; red=$((red+1)); fi; }
ruling="gate fixture: Lon 2026-10-02, use CSNOBOL4 to gen the ORD tests"
xref() { python3 "$H" extension-ref "$@" --oracle csnobol4_bin --feature ORD --ruling "$ruling" > "$T/xref.out" 2>&1; echo $?; }
run() { python3 "$H" run "$1/ALL.sno" "$1/ALL.ref" --modes m3 > "$T/run.out" 2>&1; echo $?; }
field() { grep -oE "(^| )$1=[0-9]+" "$T/run.out" | tail -1 | sed 's/^ //'; }
graded() { echo "$(field m3_pass) $(field m3_fail)"; }

# (1) the writer
S="$T/rungs"; suite "$S" "ord_unimplemented.sno(7) : ERROR 022 -- undefined function called"
before="$(md5sum < "$S/ALL.ref")"
arm "extension-ref dry run" "$(xref "$S/ALL.sno" ord_entry) $( [ "$(md5sum < "$S/ALL.ref")" = "$before" ] && [ ! -e "$S/ALL.extensions.tsv" ] && echo unchanged || echo written)" "0 unchanged"
arm "extension-ref --apply" "$(xref "$S/ALL.sno" ord_entry --apply) $(awk '/ord_entry$/{getline; print; exit}' "$S/ALL.ref") $(grep -c $'^ord_entry\tcsnobol4_bin\tORD\t' "$S/ALL.extensions.tsv" 2>/dev/null)" "0 65 1"
arm "extension-ref refuses where the suite's oracle agrees" "$(xref "$S/ALL.sno" plain_entry --apply)" "2"

# (2) graded, in the denominator, printed
rc=$(run "$S")
[ "$rc" = 2 ] && { echo "⛔ GATE REFUSE(2) [$GATE_NAME]: the harness refused the clean fixture:"; tail -5 "$T/run.out"; exit 2; }
arm "run grades the extension entry" "rc=$rc $(graded)" "rc=0 m3_pass=2 m3_fail=0"
arm "run prints the mark" "$(grep -c '^EXTENSION_REF ord_entry ref_oracle=csnobol4_bin feature=ORD' "$T/run.out") $(grep -oE '^EXTENSION_REF_COUNT [0-9]+' "$T/run.out")" "1 EXTENSION_REF_COUNT 1"
arm "the board line carries extension=" "$(grep '^SUITE_BOARD ' "$T/run.out" | grep -oE '(^| )extension=[0-9]+' | sed 's/^ //')" "extension=1"

# (3) fail-once: the pre-cure shape, the entry OUTSIDE and no ledger, grades one entry, not two
P="$T/pre"; suite "$P" "65"; printf 'ord_entry\tORACLE_REFUSES\tsbl -bf ERROR 022\n' > "$P/ALL.outside.tsv"
run "$P" >/dev/null
arm "fail-once: OUTSIDE leaves the graded denominator" "$(graded) $(grep '^SUITE_BOARD ' "$T/run.out" | grep -oE '(^| )extension=[0-9]+' | sed 's/^ //')" "m3_pass=1 m3_fail=0 extension=0"

# (4) the refusals
X="$T/stale"; cp -r "$S" "$X"; sed -i 's/^65$/66/' "$X/ALL.ref"
arm "run refuses a stale sha" "$(run "$X") $(grep -c 'no longer hashes' "$T/run.out")" "2 1"
X="$T/both"; cp -r "$S" "$X"; printf 'ord_entry\tORACLE_REFUSES\tsbl -bf ERROR 022\n' > "$X/ALL.outside.tsv"
arm "run refuses ledger and outside both" "$(run "$X") $(grep -c 'also stand in the outside list' "$T/run.out")" "2 1"
X="$T/acc"; cp -r "$S" "$X"; sed -i 's/\tcsnobol4_bin\t/\tsnobol4_on_path\t/' "$X/ALL.extensions.tsv"
arm "run refuses an unknown accessor" "$(run "$X") $(grep -c 'not one of' "$T/run.out")" "2 1"

# (5) a package ledger
K="$T/pkg"; mkdir -p "$K"; printf "\tOUTPUT = ORD('A')\nEND\n" > "$K/ord.sno"; printf 'stale\n' > "$K/ord.ref"
arm "extension-ref --apply on a package program" "$(xref "$K" ord.sno --apply) $(cat "$K/ord.ref")" "0 65"
python3 "$H" extension-check "$K" > "$T/chk.out" 2>&1; arm "extension-check passes" "$? $(grep -oE '^EXTENSION_REF_COUNT [0-9]+' "$T/chk.out")" "0 EXTENSION_REF_COUNT 1"
X="$T/pkg2"; cp -r "$K" "$X"; printf '66\n' > "$X/ord.ref"
python3 "$H" extension-check "$X" >/dev/null 2>&1; arm "extension-check refuses a stale sha" "$?" "2"
X="$T/pkg3"; cp -r "$K" "$X"; printf 'ord.sno\tNOT_SPITBOL_DIALECT\tORD\n' > "$X/EXCLUDED.tsv"
python3 "$H" extension-check "$X" >/dev/null 2>&1; arm "extension-check refuses a program also EXCLUDED" "$?" "2"

# (6) the oracle's capture never overwrites it
python3 "$H" capture-oracle-refs "$K" --force > "$T/cap.out" 2>&1; arm "capture-oracle-refs refuses an extension program" "$? $(grep -c 'carries an EXTENSION REF' "$T/cap.out") $(cat "$K/ord.ref")" "2 1 65"

echo "population: $n arm(s) over a 2-entry rung suite and a 1-program package, mode m3, oracles sbl -bf (the suite's) and csnobol4 (the extension's)"
if [ "$red" -eq 0 ]; then echo "GATE OK [$GATE_NAME]: an extension ref is cut by its named oracle, marked, graded in the denominator, printed, and never re-cut"; gate_stamp 2>/dev/null; exit 0; fi
echo "⛔ GATE FAIL [$GATE_NAME]: $red of $n arm(s) red"; gate_stamp 2>/dev/null; exit 1
