#!/usr/bin/env python3
"""util_icon_bench_wrap.py -- GENERATE the three-angle wrapper around one pristine Icon benchmark kernel.

THE ONE AUTHORITY for the wrapped form (RULES.md THE KERNEL CONVENTION, CEO-567; CEO-1221, Lon 2026-09-23: "The source of
the benchmark is the apple-core of the test, the wrapper code can be added to do both the test and the measurements."). The
kernel file is never edited: this reads it, renames its `procedure main` to `bench_kernel__`, and appends a generated `main`
that runs it
    BENCH_MODE=iter  BENCH_N=<n>          exactly n times                       (angle 2, fixed iterations)
    BENCH_MODE=time  BENCH_BUDGET_MS=<ms> until the budget is spent, at least once (angle 1, fixed time)
and writes ONE line to &errout: `BENCH iters=<k> work_ms=<ms>` -- the WORK half of the two-number basis, measured inside the
process with the compile phase and startup outside it, on stderr so stdout stays byte-comparable to the .ref. The harness runs
the result under tools/bench_rusage (angle 3) and checks stdout == k copies of the .ref: the loop itself is part of the test.

Each iteration resets what a whole-program run would have fresh: &random to its value at entry (a kernel that shuffles stays
deterministic) and &input rewound with seek(&input, 1) (a kernel that reads stdin reads it all again; stdin is a file). What it
cannot reset -- a global, a static, an `initial` clause that already ran -- the harness's loop test detects (two iterations do
not print two refs) and it then iterates whole processes instead, and says so.

usage: util_icon_bench_wrap.py KERNEL.icn > WRAPPED.icn        exit 2 when the kernel has no single `procedure main`
"""
import re
import sys

WRAPPER = '''
# ---- GENERATED by scripts/util_icon_bench_wrap.py -- the three-angle wrapper; never committed beside the kernel ----
procedure main(args)
   local mode, n, bud, r0, t0, k;
   mode := getenv("BENCH_MODE") | "iter";
   n := integer(getenv("BENCH_N")) | 1;
   bud := integer(getenv("BENCH_BUDGET_MS")) | 1000;
   r0 := &random;
   k := 0;
   t0 := &time;
   repeat {
      if mode == "iter" then { if k >= n then break }
      else { if k > 0 & &time - t0 >= bud then break };
      &random := r0;
      seek(&input, 1);
      bench_kernel__(copy(args));
      k +:= 1
   };
   write(&errout, "BENCH iters=", k, " work_ms=", &time - t0)
end
'''


def main(argv):
    if len(argv) != 2:
        sys.stderr.write("usage: util_icon_bench_wrap.py KERNEL.icn\n")
        return 2
    src = open(argv[1], encoding="latin-1").read()
    pat = re.compile(r'^(\s*)procedure(\s+)main(\s*)\(', re.M)
    hits = pat.findall(src)
    if len(hits) != 1:
        sys.stderr.write("REFUSE(2): %s has %d `procedure main`, a kernel has exactly one\n" % (argv[1], len(hits)))
        return 2
    if re.search(r'\bbench_kernel__\b', src):
        sys.stderr.write("REFUSE(2): %s already names bench_kernel__ -- is it a generated file?\n" % argv[1])
        return 2
    out = pat.sub(lambda m: m.group(1) + "procedure" + m.group(2) + "bench_kernel__" + m.group(3) + "(", src, count=1)
    sys.stdout.write(out.rstrip("\n") + "\n" + WRAPPER)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
