#!/usr/bin/env bash
# util_rtx_symbol_inventory.sh — regenerate the RTX replacement inventory MECHANICALLY.
#
# Sweeps every committed SNOBOL4 .s artifact for call/jmp targets, subtracts the
# program-local label classes the emitter mints (proc_/xchain/snoch/xcat/alt/dol/
# smatch/xscan/xgvarg/fn_/P_/L_/Ln_/s_/g_/a_/arb/ucall/flat_/main_ + bare registers),
# and prints what remains: the runtime symbols the blob actually calls.
#
# WHY MECHANICAL: the hand-written table in .github/ARCH-SNOBOL4-RTX.md section 5
# is a snapshot and WILL rot as the emitter changes. This script is the ground truth.
# Run it at the start of any RTX rung and diff against the doc.
#
# Usage: bash scripts/util_rtx_symbol_inventory.sh [corpus_root]   (default /home/claude/corpus)
#
# ⛔ LIVE ARTIFACTS ONLY (corrected RTX-2, s163). The sweep MUST NOT count files the current
# compiler did not produce. Three classes pollute the naive `find *.s`:
#   (a) *.byrd-reference.s  — hand-written nasm-syntax references (`[rel x]`, `qword [x]`)
#   (b) f13_eval_code.s     — same vintage; header `; generated by scrip-cc -asm`, a tool that
#                             no longer exists
#   (c) bb_macros.s / sm_macros.s — macro libraries, not program output
# Counting them invented an entire PHANTOM FAMILY: blk_alloc/blk_free showed 15/30 static sites
# and got written into ARCH-SNOBOL4-RTX.md section 5 as the ALLOC family, when the live compiler
# emits ZERO calls to either and their C has sat in archive/backend/ (unbuilt) for eras. RTX-2
# was aimed at dead symbols because of this. The live marker is the FIRST LINE: GNU as Intel
# syntax, `.intel_syntax noprefix` (Lon ruling s162, ARCH section 1). Filter on it, not on names.
# This is the same class of error as the s26 F12/F13 stale-artifact lesson in RULES.md step 4:
# when you need to know what the compiler emits, the COMPILER is the oracle, never an artifact.
S4E="${S4E_HOME:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"   # D-17 PORTABLE-HOME: the sibling root (all repos + oracles are siblings under ONE root; /home/claude2-style seat roots work with zero env; S4E_HOME overrides)
set -uo pipefail
CORPUS="${1:-$S4E/corpus}"
[ -d "$CORPUS" ] || { echo "FAIL: corpus not found at $CORPUS"; exit 1; }
mapfile -t ALL < <(find "$CORPUS" -path '*snobol4*' -name '*.s' 2>/dev/null)
FILES=()
for f in "${ALL[@]}"; do head -1 "$f" 2>/dev/null | grep -q '\.intel_syntax' && FILES+=("$f"); done
[ "${#FILES[@]}" -gt 0 ] || { echo "FAIL: no LIVE SNOBOL4 .s artifacts under $CORPUS"; exit 1; }
LOCAL='^(proc_|n[0-9]+_|snoch|xcat|alt[0-9]|dol[0-9]|smatch|xscan|xgvarg|xcap|fn_|P_|L_|Ln_|s_|g_|m_|a_|arb[0-9]|ucall|flat_|main_|vowelinstem|stemmer|cons_|cvc_|doublec_|record_register|execute_code_dyn|comm_stno|qword|r[0-9a-z]{1,3}$|scan_retry)'
printf '# RTX symbol inventory — generated %s from %d LIVE .s artifacts (of %d found) under %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "${#FILES[@]}" "${#ALL[@]}" "$CORPUS"
printf '# count symbol   (count = static call/jmp sites across all artifacts, NOT dynamic weight)\n'
grep -ohE '(call|jmp)[[:space:]]+[A-Za-z_][^[:space:],;()#]*' "${FILES[@]}" 2>/dev/null \
  | awk '{print $2}' | sed -e 's/[@]PLT$//' | grep -vE "$LOCAL" | sort | uniq -c | sort -rn
