/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
#ifndef ZETA_CHOICES_H
#define ZETA_CHOICES_H
#define ZC_ZBLOCK_KB 64
#define ZC_COL_MALLOC 0
#define ZC_COL_ARENA  1
#define ZC_COL_GC     2
#define ZC_COLLECTION ZC_COL_MALLOC
#define ZC_SELFLOAD_OFF        0
#define ZC_SELFLOAD_PLANE_CELL 1
#define ZC_SELFLOAD_ASSERT     2
#define ZC_SELFLOAD_STATIC     3
#define ZC_SELFLOAD_ALLOC      4
#define ZC_SELFLOAD ZC_SELFLOAD_OFF
#define ZC_PORT_PLAIN        0
#define ZC_PORT_INSTRUMENTED 1
#define ZC_PORT_ALLOC        2
#define ZC_PORT_INLINE       3
#define ZC_PORT_CSTACK       4
#define ZC_PORT_OWNED        5
#define ZC_PORT_FORTH        6
#define ZC_PORT_HEAP         7
#define ZC_COEXPR_STACK_GCHEAP 1
#define ZC_PORT ZC_PORT_FORTH
#define ZC_STORAGE_FRAME_R12  0
#define ZC_STORAGE_FRAME_RSP  1
#define ZC_STORAGE_CELL_STACK 2
#define ZC_STORAGE_CELL_HEAP  3
#define ZC_STORAGE ZC_STORAGE_CELL_STACK
#define ZC_INIT_ZERO  0
#define ZC_INIT_NONE  1
#define ZC_INIT_CLONE 2
#define ZC_INIT ZC_INIT_ZERO
#define ZC_POISON_OFF  0
#define ZC_POISON_FILL 1
#define ZC_POISON ZC_POISON_FILL
#define ZC_TELEM_OFF 0
#define ZC_TELEM_ON  1
#define ZC_TELEMETRY ZC_TELEM_ON
#define ZC_OVF_BOMB  0
#define ZC_OVF_GUARD 1
#define ZC_OVERFLOW ZC_OVF_BOMB
#define ZC_ARENA_MB 1024
#define ZC_ZLS2_MB 512
#define ZC_FRAME_ISLE 0
#define ZC_FRAME_DEAD5 1
#define ZC_FRAME_RSP 2
#define ZC_FRAME ZC_FRAME_RSP
#define ZC_ZETA_ZLS  0
#define ZC_ZETA_ZLS2 1
#define ZC_ZETA_ZH   2
#define ZC_ZETA ZC_ZETA_ZLS2
#define ZC_HEAP_SCRIP 1
#define ZC_HEAP_STRINGS ZC_HEAP_SCRIP
#define ZC_HEAP_MB 512
#define ZC_WSI_MB 1024
#define ZC_PROMOTE_GATE 0
#define ZC_PROMOTE_ON   1
#define ZC_PROMOTE ZC_PROMOTE_GATE
#define ZLS2_BUMP    1
#define ZLS2_RESTORE 2
#define ZLS2_RELEASE 4
#define ZC_CSET_CHAIN_MAX 3
#define ZC_SPAN_GUTS_INLINE 0
#define ZC_SPAN_GUTS_CALL   1
#define ZC_SPAN_GUTS ZC_SPAN_GUTS_INLINE
#define ZC_LIT_GUTS_UNROLL 0
#define ZC_LIT_GUTS_INLINE 1
#define ZC_LIT_GUTS_CALL   2
#define ZC_LIT_GUTS_RANGE  3
#define ZC_LIT_GUTS ZC_LIT_GUTS_UNROLL
#endif
