/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
#pragma once
typedef enum {
    XA_MACRO_LIBRARY,
    XA_MACRO_LIBRARY_OPEN,
    XA_MACRO_LIBRARY_CLOSE,
    XA_BB_MACRO_LIBRARY,
    XA_EXEC_STMT_BLOB,
    XA_FILE_HEADER,
    XA_FILE_FOOTER,
    XA_RODATA_STRTAB,
    XA_PREDICATE_REGISTRY,
    XA_BB_PTR_SLOT,
    XA_ENTRY_DISPATCH,
    XA_FLAT_EPILOGUE,
    XA_FLAT_DATA_SECTION,
    XA_PATTERN_BLOBS,
    XA_PROLOGUE,
    XA_EPILOGUE,
    XA_WASM_MAIN_WRAPPER,
    XA_WASM_MAIN_OPEN,
    XA_WASM_MAIN_CLOSE,
    XA_JS_LABEL_REGISTER,
    XA_EXPRESSION_REGISTRY,
    XA_KIDS_RODATA,
    XA_SUB_BUILDER,
    XA_BUILDER,
    XA_REGISTRY_TABLE,
    XA_STRTAB_RODATA,
    XA_CSETTAB_RODATA,
    XA_CAP_FIXUP,
    XA_OP_COUNT
} XA_op_t;
